Nilorea Library: examples/ex_network.h File Reference
ex_network.h File Reference
Nilorea Library n_network api test.
#include <getopt.h>
#include <sys/time.h>
#include <sys/types.h>
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include <sys/wait.h>
#include "nilorea/n_network.h"
#include "nilorea/n_network_msg.h"
#include "nilorea/n_thread_pool.h"
Macros
#define NETMSG_DATA 1
type of data message
Functions
int get_net_datas (N_STR *str, N_STR **hostname, N_STR **data)
decode data we got from network
void * manage_client (void *ptr)
recv/send datas if any for the client
int send_net_datas (NETWORK *netw, N_STR *data)
send data to specified network
Detailed Description
Nilorea Library n_network api test.
Author
Castagnier Mickael
Version
1.0
Date
26/05/2015
Definition in file ex_network.h.
Macro Definition Documentation
NETMSG_DATA
#define NETMSG_DATA 1
type of data message
Definition at line 9 of file ex_network.h.
Function Documentation
get_net_datas()
int get_net_datas (N_STR * str, N_STR ** hostname, N_STR ** data)
decode data we got from network
Parameters
str the string to decode
hostname decoded hostname
data decoded data
Returns
TRUE or FALSE
Examples
ex_network.c.
Definition at line 80 of file ex_network.h.
References __n_assert, delete_msg(), get_int_from_msg(), get_nstr_from_msg(), LOG_DEBUG, LOG_ERR, make_msg_from_str(), n_log, and NETMSG_DATA.
Referenced by manage_client().
manage_client()
void * manage_client (void * ptr)
recv/send datas if any for the client
Parameters
ptr pointer to the client structure to manage
Returns
NULL
Examples
ex_network.c.
Definition at line 115 of file ex_network.h.
References N_STR::data, free_nstr, get_net_datas(), N_SOCKET::ip, NETWORK::link, LOG_ERR, LOG_NOTICE, n_log, NETMSG_DATA, netw_close(), netw_get_msg(), netw_get_state(), netw_msg_get_type(), netw_start_thr_engine(), send_net_datas(), N_SOCKET::sock, and u_sleep().
send_net_datas()
int send_net_datas (NETWORK * netw, N_STR * data)
send data to specified network
Parameters
netw the target network
data the data to send
Returns
TRUE or FALSE
Examples
ex_network.c.
Definition at line 31 of file ex_network.h.
References __n_assert, add_int_to_msg(), add_nstrdup_to_msg(), add_nstrptr_to_msg(), create_msg(), N_STR::data, delete_msg(), free_nstr, N_STR::length, LOG_DEBUG, LOG_ERR, make_str_from_msg(), n_log, NETMSG_DATA, netw_add_msg(), new_nstr(), and N_STR::written.
Referenced by manage_client().