Nilorea Library: examples/ex_file.c File Reference
ex_file.c File Reference
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include "nilorea/n_files.h"
#include "nilorea/n_log.h"
#include "nilorea/n_str.h"
#include <sys/wait.h>
Functions
void inlined_func (void)
int main (int argc, char **argv)
void process_args (int argc, char **argv)
void usage (void)
Function Documentation
inlined_func()
void inlined_func (void)
Definition at line 98 of file ex_file.c.
References LOG_DEBUG, and n_log.
main()
int main (int argc, char ** argv)
Definition at line 102 of file ex_file.c.
References __n_assert, _nstr, _nstrp, _str, Alloca, char_to_nstr(), checkerror, endif, file_exist(), N_FILE_INFO::filetime, Free, free_nstr, FreeNoLog, get_error, get_prog_dir(), get_prog_name(), iffalse, ifnull, iftrue, ifzero, init_error_check, inlined_func(), list_destroy(), list_foreach, LOG_DEBUG, LOG_ERR, LOG_INFO, Malloc, n_abort(), n_daemonize(), N_HIDE_STR(), n_log, n_popen(), n_scan_dir(), N_FILE_INFO::name, LIST::nb_items, new_generic_list(), next_even, next_odd, process_args(), Realloc, Reallocz, and system_nb().
process_args()
void process_args (int argc, char ** argv)
Definition at line 47 of file ex_file.c.
References getoptret, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, LOG_NULL, set_log_level(), and usage().
usage()
void usage (void)
Definition at line 40 of file ex_file.c.