Nilorea Library: examples/ex_nstr.c File Reference
ex_nstr.c File Reference
#include "nilorea/n_str.h"
#include "nilorea/n_log.h"
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 30 of file ex_nstr.c.
References _nstr, char_to_nstr(), N_STR::data, empty_nstr(), file_to_nstr(), Free, free_nstr, free_split_result(), join(), N_STR::length, list_destroy(), LOG_DEBUG, LOG_ERR, LOG_INFO, n_log, n_str_url_encode(), LIST::nb_items, new_generic_list(), new_nstr(), nstr_to_file(), nstrcat, nstrdup(), nstrprintf, nstrprintf_cat, resize_nstr(), scan_dir(), set_log_level(), skipu(), skipw(), split(), split_count(), str_replace(), str_sanitize(), str_to_int(), str_to_long(), str_to_long_long(), strlo(), strup(), trim(), trim_nocopy(), wildmat(), wildmatcase(), write_and_fit(), write_and_fit_ex(), and N_STR::written.