Nilorea Library: examples/ex_base64.c File Reference
ex_base64.c File Reference
#include "nilorea/n_log.h"
#include "nilorea/n_list.h"
#include "nilorea/n_str.h"
#include "nilorea/n_base64.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 32 of file ex_base64.c.
References _nstr, char_to_nstr(), N_STR::data, file_to_nstr(), free_nstr, N_STR::length, LOG_DEBUG, LOG_INFO, LOG_NOTICE, n_base64_decode(), n_base64_encode(), n_isalpha(), n_islower(), n_isupper(), n_log, n_tolower(), n_toupper(), nstr_to_file(), nstrprintf, set_log_level(), and N_STR::written.