Nilorea Library: examples/ex_crypto.c File Reference
ex_crypto.c File Reference
#include "nilorea/n_log.h"
#include "nilorea/n_list.h"
#include "nilorea/n_str.h"
#include "nilorea/n_base64.h"
#include "nilorea/n_crypto.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 33 of file ex_crypto.c.
References _nstr, char_to_nstr(), free_nstr, getoptret, key, N_STR::length, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, LOG_NULL, n_base64_decode(), n_base64_encode(), n_log, n_vigenere_decode(), n_vigenere_decode_file(), n_vigenere_decode_file_qa(), n_vigenere_decode_qa(), n_vigenere_encode(), n_vigenere_encode_file(), n_vigenere_encode_qa(), n_vigenere_get_answer(), n_vigenere_get_question(), n_vigenere_get_rootkey(), n_vigenere_quick_decode(), n_vigenere_quick_encode(), nstrprintf, set_log_level(), usage(), and N_STR::written.