Nilorea Library: examples/ex_network_ws.c File Reference
ex_network_ws.c File Reference
#include "nilorea/n_str.h"
#include "nilorea/n_log.h"
#include "nilorea/n_network.h"
#include <getopt.h>
#include <string.h>
Functions
int main (int argc, char *argv[])
void usage (void)
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 40 of file ex_network_ws.c.
References N_STR::data, free_nstr, getoptret, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, LOG_NULL, n_log, n_ws_conn_free(), n_ws_connect(), N_WS_OP_TEXT, n_ws_recv(), n_ws_send(), N_WS_MESSAGE::opcode, N_WS_MESSAGE::payload, set_log_level(), and usage().
usage()
void usage (void)
Definition at line 34 of file ex_network_ws.c.