Nilorea Library: examples/ex_log.c File Reference
ex_log.c File Reference
#include "nilorea/n_log.h"
#include "nilorea/n_nodup_log.h"
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 30 of file ex_log.c.
References close_nodup_log(), close_safe_logging(), close_sysjrnl(), dump_nodup_log(), get_log_file(), get_log_level(), init_nodup_log(), LOG_ALERT, LOG_CRIT, LOG_DEBUG, LOG_EMERG, LOG_ERR, log_file, LOG_INFO, LOG_NOTICE, LOG_NULL, LOG_WARNING, n_log, n_nodup_log, n_nodup_log_indexed, open_safe_logging(), open_sysjrnl(), set_log_file(), set_log_level(), and write_safe_log().