Nilorea Library: examples/ex_exceptions.c File Reference
ex_exceptions.c File Reference
#include "nilorea/n_log.h"
#include "nilorea/n_exceptions.h"
Functions
int all_exception (int boolean)
int array_exception (int boolean)
int divzero_exception (int boolean)
int main (void)
int overflow_exception (int boolean)
int parsing_exception (int boolean)
Function Documentation
all_exception()
int all_exception (int boolean)
Examples
ex_exceptions.c.
Definition at line 70 of file ex_exceptions.c.
References LOG_NOTICE, n_log, PARSING_EXCEPTION, and Throw.
Referenced by main().
array_exception()
int array_exception (int boolean)
Examples
ex_exceptions.c.
Definition at line 30 of file ex_exceptions.c.
References ARRAY_EXCEPTION, LOG_NOTICE, n_log, and Throw.
Referenced by main().
divzero_exception()
int divzero_exception (int boolean)
Examples
ex_exceptions.c.
Definition at line 40 of file ex_exceptions.c.
References DIVZERO_EXCEPTION, LOG_NOTICE, n_log, and Throw.
Referenced by main().
main()
int main (void)
Examples
ex_accept_pool_client.c, ex_accept_pool_server.c, ex_base64.c, ex_clock_sync.c, ex_common.c, ex_configfile.c, ex_crypto.c, ex_exceptions.c, ex_file.c, ex_fluid.c, ex_gui.c, ex_gui_dictionary.c, ex_gui_isometric.c, ex_gui_network.c, ex_gui_particles.c, ex_hash.c, ex_iso_astar.c, ex_kafka.c, ex_list.c, ex_log.c, ex_monolith.c, ex_network.c, ex_network_ssl.c, ex_network_ssl_hardened.c, ex_nstr.c, ex_pcre.c, ex_signals.c, ex_stack.c, ex_threads.c, ex_trajectory.c, ex_trees.c, and ex_zlib.c.
Definition at line 80 of file ex_exceptions.c.
References all_exception(), array_exception(), ARRAY_EXCEPTION, Catch, CatchAll, divzero_exception(), DIVZERO_EXCEPTION, EndTry, GENERAL_EXCEPTION, LOG_DEBUG, LOG_INFO, LOG_NOTICE, LOG_STDERR, n_log, overflow_exception(), OVERFLOW_EXCEPTION, parsing_exception(), PARSING_EXCEPTION, set_log_level(), Throw, and Try.
overflow_exception()
int overflow_exception (int boolean)
Examples
ex_exceptions.c.
Definition at line 50 of file ex_exceptions.c.
References LOG_NOTICE, n_log, OVERFLOW_EXCEPTION, and Throw.
Referenced by main().
parsing_exception()
int parsing_exception (int boolean)
Examples
ex_exceptions.c.
Definition at line 60 of file ex_exceptions.c.
References LOG_NOTICE, n_log, PARSING_EXCEPTION, and Throw.
Referenced by main().