Nilorea Library: examples/ex_avro.c File Reference
ex_avro.c File Reference
Avro encoding/decoding example: JSON <-> Avro conversion.
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_str.h"
#include "nilorea/n_avro.h"
#include <stdio.h>
#include <string.h>
Functions
int main (int argc, char *argv[])
Detailed Description
Avro encoding/decoding example: JSON <-> Avro conversion.
Author
Castagnier Mickael
Version
1.0
Date
11/03/2026
Definition in file ex_avro.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 35 of file ex_avro.c.
References avro_file_to_json(), avro_json_to_file(), avro_nstr_avro_to_json(), avro_nstr_json_to_avro(), avro_schema_free(), avro_schema_parse_nstr(), avro_schema_to_json(), char_to_nstr(), N_STR::data, file_to_nstr(), Free, free_nstr, LOG_DEBUG, LOG_ERR, LOG_INFO, n_log, nstr_to_file(), set_log_level(), and N_STR::written.