Nilorea Library: examples/ex_stack.c File Reference
ex_stack.c File Reference
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_str.h"
#include "nilorea/n_stack.h"
Functions
int main (int argc, char **argv)
void process_args (int argc, char **argv)
void usage (void)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 95 of file ex_stack.c.
References delete_stack(), LOG_ERR, LOG_INFO, n_log, new_stack(), process_args(), set_log_level(), stack_is_empty(), stack_is_full(), STACK_IS_UNDEFINED, STACK_ITEM_BOOL, STACK_ITEM_CHAR, STACK_ITEM_DOUBLE, STACK_ITEM_FLOAT, STACK_ITEM_INT32, STACK_ITEM_INT8, STACK_ITEM_OK, STACK_ITEM_PTR, STACK_ITEM_UINT32, STACK_ITEM_UINT8, stack_peek(), stack_pop_b(), stack_pop_c(), stack_pop_d(), stack_pop_f(), stack_pop_i32(), stack_pop_i8(), stack_pop_p(), stack_pop_ui32(), stack_pop_ui8(), stack_push, STACK::tail, and STACK_ITEM::v_type.
process_args()
void process_args (int argc, char ** argv)
Definition at line 44 of file ex_stack.c.
References getoptret, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, LOG_NULL, set_log_level(), and usage().
usage()
void usage (void)
Definition at line 37 of file ex_stack.c.