Nilorea Library: examples/ex_gui_kvtable.c File Reference
ex_gui_kvtable.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_gui.h"
Macros
#define ALLEGRO_UNSTABLE 1
Functions
static void expect_close (const char *label, float got, float want, float tol)
static void expect_true (const char *label, int cond)
int main (int argc, char **argv)
static int process_args (int argc, char **argv)
Variables
static int failures = 0
static int log_level = 3
Macro Definition Documentation
ALLEGRO_UNSTABLE
#define ALLEGRO_UNSTABLE 1
Definition at line 37 of file ex_gui_kvtable.c.
Function Documentation
expect_close()
static void expect_close (const char * label, float got, float want, float tol) static
Examples
ex_gui_kvtable.c.
Definition at line 77 of file ex_gui_kvtable.c.
References failures, LOG_ERR, LOG_INFO, and n_log.
Referenced by main().
expect_true()
static void expect_true (const char * label, int cond) static
Examples
ex_gui_kvtable.c.
Definition at line 89 of file ex_gui_kvtable.c.
References failures, LOG_ERR, LOG_INFO, and n_log.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 98 of file ex_gui_kvtable.c.
References N_GUI_KV_ROW::active, N_GUI_KVTABLE::btn_add, expect_close(), expect_true(), failures, gui, N_GUI_WIDGET::h, N_GUI_KV_ROW::key_id, N_GUI_KVTABLE::lbl_key, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, n_gui_add_window(), n_gui_destroy_ctx(), n_gui_get_widget(), n_gui_kvtable_add_row(), n_gui_kvtable_create(), n_gui_kvtable_free(), n_gui_kvtable_relayout(), n_gui_kvtable_remove_row(), n_gui_new_ctx(), N_GUI_RESIZE_ADAPTIVE, n_gui_set_display_size(), n_gui_set_resize_mode(), N_GUI_WIN_RESIZE_SCALE, n_gui_window_set_resize_policy(), n_log, N_GUI_KVTABLE::nb_rows, process_args(), N_GUI_KVTABLE::rows, set_log_level(), and N_GUI_WIDGET::y.
process_args()
static int process_args (int argc, char ** argv) static
Definition at line 50 of file ex_gui_kvtable.c.
References LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, and LOG_NULL.
Variable Documentation
failures
int failures = 0 static
Examples
ex_gui_kvtable.c.
Definition at line 75 of file ex_gui_kvtable.c.
Referenced by expect_close(), expect_true(), and main().
log_level
int log_level = 3 static
Definition at line 48 of file ex_gui_kvtable.c.