Nilorea Library: examples/ex_zlib.c File Reference
ex_zlib.c File Reference
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_str.h"
#include "nilorea/n_zlib.h"
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 32 of file ex_zlib.c.
References __n_assert, char_to_nstr(), CompressData(), N_STR::data, Free, free_nstr, GetMaxCompressedLen(), N_STR::length, LOG_DEBUG, LOG_ERR, LOG_INFO, LOG_NOTICE, Malloc, n_log, set_log_level(), UncompressData(), unzip_nstr(), N_STR::written, and zip_nstr().