Nilorea Library: examples/ex_gui_particles.c File Reference
ex_gui_particles.c File Reference
#include "nilorea/n_common.h"
#include "nilorea/n_particles.h"
#include "nilorea/n_anim.h"
#include "nilorea/n_gui.h"
#include <allegro5/allegro_ttf.h>
Macros
#define ALLEGRO_UNSTABLE 1
#define HEIGHT 480
#define WIDTH 640
Functions
int main (int argc, char *argv[])
Variables
LIST * active_object = NULL
ALLEGRO_DISPLAY * display = NULL
int DONE = 0
static double fps_accum = 0.0
static double fps_display = 0.0
ALLEGRO_TIMER * fps_timer = NULL
static int frame_count = 0
int getoptret = 0
static int lbl_fps_info = -1
static int lbl_mouse_pos = -1
static int lbl_particle_count = -1
static int lbl_particle_max = -1
static int lbl_spawn_info = -1
int log_level = 3
ALLEGRO_TIMER * logic_timer = NULL
PARTICLE_SYSTEM * particle_system_effects = NULL
ALLEGRO_BITMAP * scr_buf = NULL
static int total_spawned = 0
Macro Definition Documentation
ALLEGRO_UNSTABLE
#define ALLEGRO_UNSTABLE 1
Definition at line 30 of file ex_gui_particles.c.
HEIGHT
#define HEIGHT 480
Definition at line 28 of file ex_gui_particles.c.
WIDTH
#define WIDTH 640
Definition at line 27 of file ex_gui_particles.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 64 of file ex_gui_particles.c.
References __attribute__(), PHYSICS::acceleration, active_object, add_particle(), display, DONE, draw_particle(), fps_accum, fps_display, fps_timer, frame_count, free_nstr, getoptret, gui, HEIGHT, init_particle_system(), key, lbl_fps_info, lbl_mouse_pos, lbl_particle_count, lbl_particle_max, lbl_spawn_info, PARTICLE_SYSTEM::list, list_destroy(), LOG_DEBUG, LOG_ERR, log_file, LOG_INFO, log_level, LOG_NOTICE, logic_timer, manage_particle(), MAX_LIST_ITEMS, n_abort(), n_gui_add_label(), n_gui_add_window(), N_GUI_ALIGN_LEFT, n_gui_destroy_ctx(), n_gui_draw(), n_gui_label_set_text(), n_gui_new_ctx(), n_gui_process_event(), n_gui_set_display_size(), n_gui_set_virtual_size(), n_gui_wants_mouse(), n_log, LIST::nb_items, LIST::nb_max_items, new_generic_list(), nstrprintf, PHYSICS::orientation, particle_system_effects, PIXEL_PART, PHYSICS::position, scr_buf, set_log_file(), set_log_level(), PHYSICS::speed, PHYSICS::sz, total_spawned, VECTOR3D_SET, and WIDTH.
Variable Documentation
active_object
LIST* active_object = NULL
Examples
ex_gui_particles.c.
Definition at line 48 of file ex_gui_particles.c.
Referenced by main().
display
ALLEGRO_DISPLAY* display = NULL
Definition at line 38 of file ex_gui_particles.c.
DONE
int DONE = 0
Definition at line 40 of file ex_gui_particles.c.
fps_accum
double fps_accum = 0.0 static
Examples
ex_gui_particles.c.
Definition at line 62 of file ex_gui_particles.c.
Referenced by main().
fps_display
double fps_display = 0.0 static
Examples
ex_gui_particles.c.
Definition at line 61 of file ex_gui_particles.c.
Referenced by main().
fps_timer
ALLEGRO_TIMER* fps_timer = NULL
Definition at line 46 of file ex_gui_particles.c.
frame_count
int frame_count = 0 static
Examples
ex_gui_particles.c.
Definition at line 60 of file ex_gui_particles.c.
Referenced by main().
getoptret
int getoptret = 0
Definition at line 41 of file ex_gui_particles.c.
lbl_fps_info
int lbl_fps_info = -1 static
Examples
ex_gui_particles.c.
Definition at line 56 of file ex_gui_particles.c.
Referenced by main().
lbl_mouse_pos
int lbl_mouse_pos = -1 static
Examples
ex_gui_particles.c.
Definition at line 54 of file ex_gui_particles.c.
Referenced by main().
lbl_particle_count
int lbl_particle_count = -1 static
Examples
ex_gui_particles.c.
Definition at line 52 of file ex_gui_particles.c.
Referenced by main().
lbl_particle_max
int lbl_particle_max = -1 static
Examples
ex_gui_particles.c.
Definition at line 53 of file ex_gui_particles.c.
Referenced by main().
lbl_spawn_info
int lbl_spawn_info = -1 static
Examples
ex_gui_particles.c.
Definition at line 55 of file ex_gui_particles.c.
Referenced by main().
log_level
int log_level = 3
Definition at line 42 of file ex_gui_particles.c.
logic_timer
ALLEGRO_TIMER* logic_timer = NULL
Definition at line 47 of file ex_gui_particles.c.
particle_system_effects
PARTICLE_SYSTEM* particle_system_effects = NULL
Examples
ex_gui_particles.c.
Definition at line 49 of file ex_gui_particles.c.
Referenced by main().
scr_buf
ALLEGRO_BITMAP* scr_buf = NULL
Examples
ex_gui_particles.c.
Definition at line 44 of file ex_gui_particles.c.
Referenced by main().
total_spawned
int total_spawned = 0 static
Examples
ex_gui_particles.c.
Definition at line 59 of file ex_gui_particles.c.
Referenced by main().