Nilorea Library: examples/ex_list.c File Reference
ex_list.c File Reference
#include "nilorea/n_log.h"
#include "nilorea/n_list.h"
#include "nilorea/n_str.h"
Macros
#define LIST_LIMIT 10
#define NB_TEST_ELEM 15
Functions
int main (void)
int nstrcmp (const void *a, const void *b)
void print_list_info (LIST *list)
Macro Definition Documentation
LIST_LIMIT
#define LIST_LIMIT 10
Examples
ex_list.c.
Definition at line 31 of file ex_list.c.
NB_TEST_ELEM
#define NB_TEST_ELEM 15
Examples
ex_list.c.
Definition at line 32 of file ex_list.c.
Function Documentation
main()
int main (void)
Definition at line 51 of file ex_list.c.
References __n_assert, _nstr, N_STR::data, LIST_NODE::destroy_func, Free, free_nstr, free_nstr_ptr(), list_destroy(), list_empty(), list_foreach, LIST_LIMIT, list_node_pop(), list_node_push(), list_node_shift(), list_node_unshift(), list_pop, list_push(), list_push_sorted(), list_search(), list_shift, list_unshift(), list_unshift_sorted(), LOG_DEBUG, LOG_ERR, LOG_INFO, LOG_NOTICE, n_log, LIST::nb_items, LIST::nb_max_items, NB_TEST_ELEM, new_generic_list(), new_list_node(), nstrcmp(), nstrprintf, print_list_info(), LIST_NODE::ptr, remove_list_node, set_log_level(), LIST::start, and UNLIMITED_LIST_ITEMS.
nstrcmp()
int nstrcmp (const void * a, const void * b)
Examples
ex_list.c.
Definition at line 39 of file ex_list.c.
References N_STR::data.
Referenced by main().
print_list_info()
void print_list_info (LIST * list)
Examples
ex_list.c.
Definition at line 34 of file ex_list.c.
References __n_assert, LOG_NOTICE, n_log, LIST::nb_items, and LIST::nb_max_items.
Referenced by main().