Nilorea Library: examples/ex_hash.c File Reference
ex_hash.c File Reference
#include "nilorea/n_str.h"
#include "nilorea/n_log.h"
#include "nilorea/n_list.h"
#include "nilorea/n_hash.h"
Data Structures
struct DATA
string and int holder
Macros
#define NB_HASH_ELEMENTS 24
Functions
void destroy_data (void *ptr)
destroy a DATA struct
int main (void)
Data Structure Documentation
DATA
struct DATA
string and int holder
Examples
ex_hash.c.
Definition at line 35 of file ex_hash.c.
Data Fields
N_STR * rnd_str string holder
int value int value
Macro Definition Documentation
NB_HASH_ELEMENTS
#define NB_HASH_ELEMENTS 24
Examples
ex_hash.c.
Definition at line 32 of file ex_hash.c.
Function Documentation
destroy_data()
void destroy_data (void * ptr)
destroy a DATA struct
Parameters
ptr A pointer to a DATA struct
Examples
ex_hash.c.
Definition at line 46 of file ex_hash.c.
References Free, free_nstr, and DATA::rnd_str.
Referenced by main().
main()
int main (void)
Definition at line 52 of file ex_hash.c.
References _nstr, _str, destroy_data(), destroy_ht(), empty_ht(), Free, free_nstr_ptr(), HASH_INT_TYPE, ht_duplicate(), HT_FOREACH, HT_FOREACH_R, ht_get_completion_list(), ht_get_double(), ht_get_int(), ht_get_optimal_size(), ht_get_ptr(), ht_get_string(), ht_get_table_collision_percentage(), ht_optimize(), ht_put_double(), ht_put_int(), ht_put_ptr(), ht_put_string(), ht_remove(), ht_resize(), ht_search(), HASH_NODE::key, list_destroy(), list_foreach, list_push(), LOG_DEBUG, LOG_ERR, LOG_INFO, Malloc, n_log, NB_HASH_ELEMENTS, new_generic_list(), new_ht(), new_ht_trie(), nstrprintf, DATA::rnd_str, set_log_level(), HASH_TABLE::size, and DATA::value.