Nilorea Library: examples/ex_pcre.c File Reference
ex_pcre.c File Reference
#include "nilorea/n_log.h"
#include "nilorea/n_pcre.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 30 of file ex_pcre.c.
References N_PCRE::captured, LOG_DEBUG, LOG_ERR, LOG_INFO, LOG_STDERR, N_PCRE::match_list, n_log, npcre_clean_match(), npcre_delete(), npcre_match_capture(), npcre_new(), and set_log_level().