Nilorea Library: examples/ex_network_proxy.c File Reference
ex_network_proxy.c File Reference
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_network.h"
#include <stdio.h>
#include <string.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 34 of file ex_network_proxy.c.
References N_PROXY_CFG::host, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, n_log, n_proxy_cfg_free(), n_proxy_cfg_parse(), N_PROXY_CFG::password, N_PROXY_CFG::port, N_PROXY_CFG::scheme, set_log_level(), and N_PROXY_CFG::username.