Nilorea Library: examples/ex_common.c File Reference
ex_common.c File Reference
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_str.h"
#include <sys/wait.h>
Functions
void inlined_func (void)
int main (int argc, char **argv)
void process_args (int argc, char **argv)
void usage (void)
Function Documentation
inlined_func()
void inlined_func (void)
Examples
ex_common.c, and ex_file.c.
Definition at line 98 of file ex_common.c.
References LOG_DEBUG, and n_log.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 102 of file ex_common.c.
References __n_assert, _nstr, _nstrp, _str, Alloca, char_to_nstr(), checkerror, endif, file_exist(), Free, free_nstr, FreeNoLog, get_computer_name(), get_error, get_prog_dir(), get_prog_name(), iffalse, ifnull, iftrue, ifzero, init_error_check, inlined_func(), LOG_DEBUG, log_environment(), LOG_ERR, LOG_INFO, Malloc, n_get_file_extension(), N_HIDE_STR(), n_log, n_popen(), next_even, next_odd, process_args(), Realloc, Reallocz, sigchld_handler_installer(), and system_nb().
process_args()
void process_args (int argc, char ** argv)
Examples
ex_common.c, ex_file.c, ex_network.c, ex_network_ssl.c, ex_network_ssl_hardened.c, ex_stack.c, ex_threads.c, and ex_trees.c.
Definition at line 47 of file ex_common.c.
References getoptret, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, LOG_NULL, set_log_level(), and usage().
Referenced by main(), and main().
usage()
void usage (void)
Definition at line 40 of file ex_common.c.