Nilorea Library: examples/ex_fluid_config.c File Reference
ex_fluid_config.c File Reference
#include "ex_fluid_config.h"
#include "nilorea/n_str.h"
#include "nilorea/n_fluids.h"
#include "nilorea/n_config_file.h"
Functions
int load_app_state (char *state_filename, int *WIDTH, int *HEIGHT, bool *fullscreen, char **bgmusic, double *drawFPS, double *logicFPS, N_FLUID *fluid, int *threaded)
Load application state from a config file.
Function Documentation
load_app_state()
int load_app_state (char * state_filename, int * WIDTH, int * HEIGHT, bool * fullscreen, char ** bgmusic, double * drawFPS, double * logicFPS, N_FLUID * fluid, int * threaded)
Load application state from a config file.
Parameters
state_filename path to the config file
WIDTH pointer to store display width
HEIGHT pointer to store display height
fullscreen pointer to store fullscreen flag
bgmusic pointer to store background music path
drawFPS pointer to store drawing framerate
logicFPS pointer to store logic framerate
fluid pointer to a N_FLUID to populate
threaded pointer to store threaded processing flag
Returns
TRUE on success, FALSE on error
Examples
ex_fluid.c, ex_fluid_config.c, and ex_fluid_config.h.
Definition at line 45 of file ex_fluid_config.c.
References __n_assert, N_FLUID::cScale, N_FLUID::density, destroy_config_file(), N_FLUID::fluid_production_percentage, get_config_section_value(), get_nb_config_file_sections(), N_FLUID::gravity, load_config_file(), LOG_ERR, LOG_INFO, n_log, N_FLUID::numIters, and N_FLUID::overRelaxation.
Referenced by main().