Nilorea Library: examples/ex_trees.c File Reference
ex_trees.c File Reference
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_str.h"
#include "nilorea/n_trees.h"
#include <sys/wait.h>
Functions
int main (int argc, char **argv)
void process_args (int argc, char **argv)
void usage (void)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 99 of file ex_trees.c.
References __n_assert, COORD_INT, create_node(), create_octree(), create_octree_node(), create_quadtree(), TREE_NODE::data, QUADTREE_NODE::data_ptr, Free, free_octree(), free_octree_node(), free_quadtree(), COORD_VALUE::i, insert(), insert_octree(), NODE_DATA_TYPES::ival, LOG_INFO, LOG_NOTICE, n_log, TREE::nb_nodes, new_tree(), OCTREE_NODE::point, QUADTREE::print, process_args(), TREE::root, QUADTREE::root, search(), tree_create_node(), tree_delete_node(), tree_destroy(), tree_insert_child(), NODE_DATA::type, NODE_DATA::value, POINT3D::x, QUADTREE_NODE::x, POINT3D::y, QUADTREE_NODE::y, and POINT3D::z.
process_args()
void process_args (int argc, char ** argv)
Definition at line 48 of file ex_trees.c.
References getoptret, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, LOG_NULL, set_log_level(), and usage().
usage()
void usage (void)
Definition at line 41 of file ex_trees.c.