Nilorea Library: CYPHERS: VIGENERE (encode / decode) a (N_STR / file) with a root key or a combination of a question and an answer
CYPHERS: VIGENERE (encode / decode) a (N_STR / file) with a root key or a combination of a question and an answer
Macros
#define n_mathmod(__a, __b) ((__a % __b + __b) % __b)
The % operator returns a result that adopts the sign of the dividend, a true mathematical modulus adopts the sign of the divisor.
Functions
N_STR * n_vigenere_decode (N_STR *string, N_STR *key)
decode a N_STR using vigenere cipher with the given key
int n_vigenere_decode_file (N_STR *in, N_STR *out, N_STR *rootkey)
decode a file using vigenere cipher with a root key
int n_vigenere_decode_file_qa (N_STR *in, N_STR *out, N_STR *question, N_STR *answer)
decode a file using vigenere cipher with a question and answer pair
N_STR * n_vigenere_decode_qa (N_STR *input_data, N_STR *question, N_STR *answer)
decode a N_STR using vigenere cipher with a question and answer pair
N_STR * n_vigenere_encode (N_STR *string, N_STR *key)
encode a N_STR using vigenere cipher with the given key
int n_vigenere_encode_file (N_STR *in, N_STR *out, N_STR *rootkey)
encode a file using vigenere cipher with a root key
int n_vigenere_encode_file_qa (N_STR *in, N_STR *out, N_STR *question, N_STR *answer)
encode a file using vigenere cipher with a question and answer pair
N_STR * n_vigenere_encode_qa (N_STR *input_data, N_STR *question, N_STR *answer)
encode a N_STR using vigenere cipher with a question and answer pair
N_STR * n_vigenere_get_answer (N_STR *root_key, N_STR *question)
compute the answer from a root key and a question
N_STR * n_vigenere_get_question (size_t question_size)
generate a random question of given size
N_STR * n_vigenere_get_rootkey (size_t rootkey_size)
generate a random root key of given size
N_STR * n_vigenere_quick_decode (N_STR *encoded_question)
quick decode a N_STR using an auto-generated key
N_STR * n_vigenere_quick_encode (N_STR *decoded_question)
quick encode a N_STR using an auto-generated key
Detailed Description
Macro Definition Documentation
n_mathmod
#define n_mathmod (__a, __b) ((__a % __b + __b) % __b)
The % operator returns a result that adopts the sign of the dividend, a true mathematical modulus adopts the sign of the divisor.
This method implements a mathematical modulus
Definition at line 44 of file n_crypto.h.
Function Documentation
n_vigenere_decode()
N_STR * n_vigenere_decode (N_STR * string, N_STR * key)
decode a N_STR using vigenere cipher with the given key
decode a N_STR using vigenere cipher with the given key
Parameters
string source to decode
key key to use for the encoding/decoding
Returns
a N_STR *decoded
Definition at line 454 of file n_crypto.c.
References key, and n_vigenere_cypher().
Referenced by main(), and n_vigenere_quick_decode().
n_vigenere_decode_file()
int n_vigenere_decode_file (N_STR * in, N_STR * out, N_STR * key)
decode a file using vigenere cipher with a root key
decode a file using vigenere cipher with a root key
Parameters
in input path and filename
out output path and filename
key key to use
Returns
TRUE or FALSE
Definition at line 660 of file n_crypto.c.
References __n_assert, _nstr, file_to_nstr(), free_nstr, key, LOG_ERR, n_base64_decode(), n_log, n_vigenere_decode_in_place(), and nstr_to_file().
Referenced by main().
n_vigenere_decode_file_qa()
int n_vigenere_decode_file_qa (N_STR * in, N_STR * out, N_STR * question, N_STR * answer)
decode a file using vigenere cipher with a question and answer pair
decode a file using vigenere cipher with a question and answer pair
Parameters
in input path and filename
out output path and filename
question question key to use
answer answer key to use
Returns
TRUE or FALSE
Definition at line 788 of file n_crypto.c.
References __n_assert, _nstr, file_to_nstr(), free_nstr, LOG_ERR, n_log, n_vigenere_decode_qa(), and nstr_to_file().
Referenced by main().
n_vigenere_decode_qa()
N_STR * n_vigenere_decode_qa (N_STR * input_data, N_STR * question, N_STR * answer)
decode a N_STR using vigenere cipher with a question and answer pair
decode a N_STR using vigenere cipher with a question and answer pair
Parameters
input_data input path and filename
question question key to use
answer answer key to use
Returns
a N_STR *decoded string or NULL
Definition at line 745 of file n_crypto.c.
References __n_assert, N_STR::data, free_nstr, N_STR::length, LOG_DEBUG, LOG_ERR, n_base64_decode(), n_log, n_vigenere_decode_in_place(), n_vigenere_encode(), n_vigenere_quick_decode(), and N_STR::written.
Referenced by main(), and n_vigenere_decode_file_qa().
n_vigenere_encode()
N_STR * n_vigenere_encode (N_STR * string, N_STR * key)
encode a N_STR using vigenere cipher with the given key
encode a N_STR using vigenere cipher with the given key
Parameters
string source to encode
key key to use for the encoding/decoding
Returns
a N_STR *encoded
Definition at line 444 of file n_crypto.c.
References key, and n_vigenere_cypher().
Referenced by main(), and n_vigenere_decode_qa().
n_vigenere_encode_file()
int n_vigenere_encode_file (N_STR * in, N_STR * out, N_STR * key)
encode a file using vigenere cipher with a root key
encode a file using vigenere cipher with a root key
Parameters
in input path and filename
out output path and filename
key key to use
Returns
TRUE or FALSE
Definition at line 616 of file n_crypto.c.
References __n_assert, _nstr, file_to_nstr(), free_nstr, key, LOG_ERR, n_base64_encode(), n_log, n_vigenere_encode_in_place(), and nstr_to_file().
Referenced by main().
n_vigenere_encode_file_qa()
int n_vigenere_encode_file_qa (N_STR * in, N_STR * out, N_STR * question, N_STR * answer)
encode a file using vigenere cipher with a question and answer pair
encode a file using vigenere cipher with a question and answer pair
Parameters
in input path and filename
out output path and filename
question question key to use
answer answer key to use
Returns
TRUE or FALSE
Definition at line 817 of file n_crypto.c.
References __n_assert, _nstr, file_to_nstr(), free_nstr, LOG_ERR, n_log, n_vigenere_encode_qa(), and nstr_to_file().
n_vigenere_encode_qa()
N_STR * n_vigenere_encode_qa (N_STR * input_data, N_STR * question, N_STR * answer)
encode a N_STR using vigenere cipher with a question and answer pair
encode a N_STR using vigenere cipher with a question and answer pair
Parameters
input_data input path and filename
question question key to use
answer answer key to use
Returns
a N_STR *encoded string or NULL
Definition at line 703 of file n_crypto.c.
References __n_assert, free_nstr, LOG_ERR, n_base64_encode(), n_log, n_vigenere_decode_in_place(), n_vigenere_encode_in_place(), and n_vigenere_quick_decode().
Referenced by main(), and n_vigenere_encode_file_qa().
n_vigenere_get_answer()
N_STR * n_vigenere_get_answer (N_STR * root_key, N_STR * question)
compute the answer from a root key and a question
compute the answer from a root key and a question
Parameters
root_key the key used to do the inital encoding
question question generated from hardware
Returns
a N_STR *answer_key string
Definition at line 576 of file n_crypto.c.
References __n_assert, N_STR::data, free_nstr, N_STR::length, LOG_ERR, n_log, n_vigenere_quick_decode(), new_nstr(), and N_STR::written.
Referenced by main().
n_vigenere_get_question()
N_STR * n_vigenere_get_question (size_t question_size)
generate a random question of given size
generate a random question of given size
Parameters
question_size size of the needed question. Must be a multiple of 2
Returns
a N_STR *question string
Definition at line 515 of file n_crypto.c.
References _nstr, N_STR::data, free_nstr, LOG_ERR, n_base64_encode(), n_get_cpu_id(), n_get_current_dir_hd_serial(), n_log, n_vigenere_quick_encode(), new_nstr(), nstrprintf_cat, and N_STR::written.
Referenced by main().
n_vigenere_get_rootkey()
N_STR * n_vigenere_get_rootkey (size_t rootkey_size)
generate a random root key of given size
generate a random root key of given size
Parameters
rootkey_size size of the needed rootkey. Must be a multiple of 2
Returns
a N_STR *rootkey string
Definition at line 68 of file n_crypto.c.
References N_STR::data, LOG_ERR, n_log, new_nstr(), and N_STR::written.
Referenced by main().
n_vigenere_quick_decode()
N_STR * n_vigenere_quick_decode (N_STR * encoded_data)
quick decode a N_STR using an auto-generated key
quick decode a N_STR using an auto-generated key
Parameters
encoded_data the data to decode
Returns
a N_STR *decoded_data
Definition at line 498 of file n_crypto.c.
References __internal_root_key, char_to_nstr(), free_nstr, n_base64_decode(), and n_vigenere_decode().
Referenced by main(), n_vigenere_decode_qa(), n_vigenere_encode_qa(), and n_vigenere_get_answer().
n_vigenere_quick_encode()
N_STR * n_vigenere_quick_encode (N_STR * decoded_data)
quick encode a N_STR using an auto-generated key
quick encode a N_STR using an auto-generated key
Parameters
decoded_data the data to encode
Returns
a N_STR *encoded_data
Definition at line 483 of file n_crypto.c.
References __internal_root_key, char_to_nstr(), free_nstr, n_base64_encode(), and n_vigenere_encode_in_place().
Referenced by main(), and n_vigenere_get_question().