Nilorea Library: CYPHERS: BASE64 (encode / decode) (from / to) a N_STR *string
CYPHERS: BASE64 (encode / decode) (from / to) a N_STR *string
Functions
N_STR * n_base64_decode (N_STR *bufcoded)
decode a base64 encoded N_STR
N_STR * n_base64_encode (N_STR *string)
encode a N_STR to base64
bool n_isalpha (char c)
check if a character is alphabetic
bool n_islower (char c)
check if a character is lowercase
bool n_isupper (char c)
check if a character is uppercase
char n_tolower (char c)
convert a character to lowercase
char n_toupper (char c)
convert a character to uppercase
Detailed Description
Function Documentation
n_base64_decode()
N_STR * n_base64_decode (N_STR * bufcoded)
decode a base64 encoded N_STR
decode a base64 encoded N_STR
Parameters
bufcoded the N_STR *string to decode
Returns
a new base64 N_STR *decoded string or NULL
Definition at line 187 of file n_base64.c.
References __n_assert, N_STR::data, LOG_ERR, n_log, new_nstr(), pr2six, and N_STR::written.
Referenced by main(), n_vigenere_decode_file(), n_vigenere_decode_qa(), and n_vigenere_quick_decode().
n_base64_encode()
N_STR * n_base64_encode (N_STR * input)
encode a N_STR to base64
encode a N_STR to base64
Parameters
input the N_STR *string to encode
Returns
a new base64 N_STR *encoded string or NULL
Definition at line 269 of file n_base64.c.
References __n_assert, basis_64, N_STR::data, free_nstr, LOG_ERR, n_base64_encode_len(), n_log, new_nstr(), and N_STR::written.
Referenced by main(), n_vigenere_encode_file(), n_vigenere_encode_qa(), n_vigenere_get_question(), and n_vigenere_quick_encode().
n_isalpha()
bool n_isalpha (char c)
check if a character is alphabetic
check if a character is alphabetic
Parameters
c character to look up
Returns
TRUE or FALSE
Definition at line 122 of file n_base64.c.
References ascii_lower_case_lookup_table, and ascii_upper_case_lookup_table.
Referenced by main().
n_islower()
bool n_islower (char c)
check if a character is lowercase
check if a character is lowercase
Parameters
c character to look up
Returns
TRUE or FALSE
Definition at line 113 of file n_base64.c.
References ascii_lower_case_lookup_table.
Referenced by main(), and n_vigenere_cypher_thread().
n_isupper()
bool n_isupper (char c)
check if a character is uppercase
check if a character is uppercase
Parameters
c character to look up
Returns
TRUE or FALSE
Definition at line 104 of file n_base64.c.
References ascii_upper_case_lookup_table.
Referenced by main(), and n_vigenere_cypher_thread().
n_tolower()
char n_tolower (char c)
convert a character to lowercase
convert a character to lowercase
Parameters
c character to convert
Returns
lowercased char c
Definition at line 142 of file n_base64.c.
References ascii_upper_case_lookup_table.
Referenced by main(), and n_vigenere_cypher_thread().
n_toupper()
char n_toupper (char c)
convert a character to uppercase
convert a character to uppercase
Parameters
c character to convert
Returns
uppercased char c
Definition at line 131 of file n_base64.c.
References ascii_lower_case_lookup_table.
Referenced by main(), and n_vigenere_cypher_thread().