Nilorea Library: DEAD_RECKONING: latency hiding with extrapolation and convergence blending
DEAD_RECKONING: latency hiding with extrapolation and convergence blending
Data Structures
struct DR_ENTITY
Dead reckoned entity with extrapolation and convergence state.
struct DR_STATE
A snapshot of entity kinematic state at a point in time.
struct DR_VEC3
3D vector used for position, velocity, and acceleration
Enumerations
enum DR_ALGO { DR_ALGO_STATIC = 0 , DR_ALGO_VEL = 1 , DR_ALGO_VEL_ACC = 2 }
Dead reckoning extrapolation algorithm.
enum DR_BLEND { DR_BLEND_SNAP = 0 , DR_BLEND_PVB = 1 , DR_BLEND_CUBIC = 2 }
Dead reckoning convergence/blending mode.
Functions
bool dr_entity_check_threshold (const DR_ENTITY *entity, const DR_VEC3 *true_pos, const DR_VEC3 *true_vel, const DR_VEC3 *true_acc, double time)
check if the owner's true state has diverged beyond the threshold
void dr_entity_compute (DR_ENTITY *entity, double time, DR_VEC3 *out_pos)
compute the dead reckoned display position at a given time
DR_ENTITY * dr_entity_create (DR_ALGO algo, DR_BLEND blend_mode, double pos_threshold, double blend_time)
create a new dead reckoning entity
void dr_entity_destroy (DR_ENTITY **entity_ptr)
destroy a dead reckoning entity and free its memory
DR_VEC3 dr_entity_extrapolate (const DR_ENTITY *entity, const DR_STATE *state, double dt)
extrapolate a kinematic state forward by dt seconds
void dr_entity_receive_state (DR_ENTITY *entity, const DR_VEC3 *pos, const DR_VEC3 *vel, const DR_VEC3 *acc, double time)
receive a new authoritative state update from the network
void dr_entity_set_algo (DR_ENTITY *entity, DR_ALGO algo)
set the extrapolation algorithm
void dr_entity_set_blend_mode (DR_ENTITY *entity, DR_BLEND blend_mode)
set the convergence blending mode
void dr_entity_set_blend_time (DR_ENTITY *entity, double blend_time)
set the convergence blend duration
void dr_entity_set_position (DR_ENTITY *entity, const DR_VEC3 *pos, const DR_VEC3 *vel, const DR_VEC3 *acc, double time)
force-set entity position without blending
void dr_entity_set_threshold (DR_ENTITY *entity, double threshold)
set the position error threshold
static DR_VEC3 dr_vec3 (double x, double y, double z)
Create a DR_VEC3 from components.
static DR_VEC3 dr_vec3_add (DR_VEC3 a, DR_VEC3 b)
Vector addition: a + b.
static double dr_vec3_distance (DR_VEC3 a, DR_VEC3 b)
Distance between two points.
static double dr_vec3_length (DR_VEC3 v)
Length of vector.
static double dr_vec3_length_sq (DR_VEC3 v)
Squared length of vector.
static DR_VEC3 dr_vec3_lerp (DR_VEC3 a, DR_VEC3 b, double t)
Linear interpolation: a + (b - a) * t.
static DR_VEC3 dr_vec3_scale (DR_VEC3 v, double s)
Scalar multiplication: v * s.
static DR_VEC3 dr_vec3_sub (DR_VEC3 a, DR_VEC3 b)
Vector subtraction: a - b.
static DR_VEC3 dr_vec3_zero (void)
Zero vector.
Detailed Description
Data Structure Documentation
DR_ENTITY
struct DR_ENTITY
Dead reckoned entity with extrapolation and convergence state.
Tracks the last known authoritative state, the previous predicted state at the moment a new update arrived, and all parameters needed for extrapolation and convergence blending.
Examples
ex_gui_isometric.c, and ex_iso_astar.c.
Definition at line 149 of file n_dead_reckoning.h.
Data Fields
DR_ALGO algo Extrapolation algorithm.
DR_VEC3 bezier_p0 Start point (previous predicted position)
DR_VEC3 bezier_p1 Control point 1.
DR_VEC3 bezier_p2 Control point 2.
DR_VEC3 bezier_p3 End point (extrapolated last_known at blend_time)
DR_BLEND blend_mode Convergence blending mode.
double blend_start Timestamp when blending started.
double blend_time Duration of convergence blend in seconds.
bool blending True if currently blending toward last_known.
DR_VEC3 display_pos Current blended/rendered position.
DR_VEC3 display_vel Current blended/rendered velocity.
DR_STATE last_known Most recent authoritative state (P0', V0', A0')
double pos_threshold Position error threshold for sending updates (distance)
DR_STATE prev_predicted Where we THOUGHT entity was when update arrived (P0, V0)
int update_count Number of state updates received.
DR_STATE
struct DR_STATE
A snapshot of entity kinematic state at a point in time.
Definition at line 134 of file n_dead_reckoning.h.
Data Fields
DR_VEC3 acc Acceleration.
DR_VEC3 pos Position.
double time Timestamp (seconds) when this state was captured.
DR_VEC3 vel Velocity.
DR_VEC3
struct DR_VEC3
3D vector used for position, velocity, and acceleration
Examples
ex_gui_isometric.c, and ex_iso_astar.c.
Definition at line 101 of file n_dead_reckoning.h.
Data Fields
double x X component.
double y Y component.
double z Z component.
Enumeration Type Documentation
DR_ALGO
enum DR_ALGO
Dead reckoning extrapolation algorithm.
Determines how the entity position is predicted forward in time from the last known kinematic state.
Enumerator
DR_ALGO_STATIC
No extrapolation; entity stays at last position.
DR_ALGO_VEL
Velocity only: P(t) = P0 + V0*t.
DR_ALGO_VEL_ACC
Velocity + acceleration: P(t) = P0 + V0*t + 0.5*A0*t^2.
Definition at line 114 of file n_dead_reckoning.h.
DR_BLEND
enum DR_BLEND
Dead reckoning convergence/blending mode.
Determines how the entity transitions from its predicted position to the newly received authoritative position.
Enumerator
DR_BLEND_SNAP
Snap instantly to new state (no smoothing)
DR_BLEND_PVB
Projective Velocity Blending (recommended)
DR_BLEND_CUBIC
Cubic Bezier spline convergence.
Definition at line 123 of file n_dead_reckoning.h.
Function Documentation
dr_entity_check_threshold()
bool dr_entity_check_threshold (const DR_ENTITY * entity, const DR_VEC3 * true_pos, const DR_VEC3 * true_vel, const DR_VEC3 * true_acc, double time)
check if the owner's true state has diverged beyond the threshold
check if the owner's true state has diverged beyond the threshold
The owner entity runs the same extrapolation algorithm as remotes. If the error exceeds the threshold, a new state update should be sent.
Parameters
entity the entity
true_pos the owner's true position
true_vel the owner's true velocity (unused, reserved for velocity threshold)
true_acc the owner's true acceleration (unused, reserved)
time current time
Returns
true if threshold exceeded (send update), false if prediction is acceptable
Definition at line 315 of file n_dead_reckoning.c.
References __n_assert, dr_entity_extrapolate(), dr_vec3_distance(), DR_ENTITY::last_known, DR_ENTITY::pos_threshold, and DR_STATE::time.
Referenced by demo_dead_reckoning(), and main().
dr_entity_compute()
void dr_entity_compute (DR_ENTITY * entity, double time, DR_VEC3 * out_pos)
compute the dead reckoned display position at a given time
compute the dead reckoned display position at a given time
If the entity is currently blending (after receiving a new state update), this returns a convergence-blended position. Otherwise, it returns the pure extrapolated position from the last known state.
Parameters
entity the entity
time current time
out_pos output: the blended display position
Definition at line 236 of file n_dead_reckoning.c.
References __n_assert, DR_ENTITY::bezier_p0, DR_ENTITY::bezier_p1, DR_ENTITY::bezier_p2, DR_ENTITY::bezier_p3, DR_ENTITY::blend_mode, DR_ENTITY::blend_start, DR_ENTITY::blend_time, DR_ENTITY::blending, cubic_bezier(), DR_ENTITY::display_pos, DR_BLEND_CUBIC, DR_BLEND_PVB, DR_BLEND_SNAP, dr_entity_extrapolate(), dr_vec3_lerp(), DR_ENTITY::last_known, DR_ENTITY::prev_predicted, and DR_STATE::time.
Referenced by demo_dead_reckoning(), and main().
dr_entity_create()
DR_ENTITY * dr_entity_create (DR_ALGO algo, DR_BLEND blend_mode, double pos_threshold, double blend_time)
create a new dead reckoning entity
create a new dead reckoning entity
Parameters
algo extrapolation algorithm (DR_ALGO_STATIC, DR_ALGO_VEL, DR_ALGO_VEL_ACC)
blend_mode convergence mode (DR_BLEND_SNAP, DR_BLEND_PVB, DR_BLEND_CUBIC)
pos_threshold distance threshold for triggering network updates
blend_time convergence blend duration in seconds
Returns
newly allocated entity, or NULL on failure
Definition at line 83 of file n_dead_reckoning.c.
References __n_assert, DR_STATE::acc, DR_ENTITY::algo, DR_ENTITY::bezier_p0, DR_ENTITY::bezier_p1, DR_ENTITY::bezier_p2, DR_ENTITY::bezier_p3, DR_ENTITY::blend_mode, DR_ENTITY::blend_start, DR_ENTITY::blend_time, DR_ENTITY::blending, DR_ENTITY::display_pos, DR_ENTITY::display_vel, dr_vec3_zero(), DR_ENTITY::last_known, Malloc, DR_STATE::pos, DR_ENTITY::pos_threshold, DR_ENTITY::prev_predicted, DR_STATE::time, DR_ENTITY::update_count, and DR_STATE::vel.
Referenced by demo_dead_reckoning(), and main().
dr_entity_destroy()
void dr_entity_destroy (DR_ENTITY ** entity_ptr)
destroy a dead reckoning entity and free its memory
destroy a dead reckoning entity and free its memory
Parameters
entity_ptr pointer to the entity pointer
Definition at line 122 of file n_dead_reckoning.c.
References __n_assert, and Free.
Referenced by demo_dead_reckoning(), and main().
dr_entity_extrapolate()
DR_VEC3 dr_entity_extrapolate (const DR_ENTITY * entity, const DR_STATE * state, double dt)
extrapolate a kinematic state forward by dt seconds
extrapolate a kinematic state forward by dt seconds
Uses the entity's configured algorithm (static, velocity, or velocity+acceleration).
Parameters
entity the entity (used for algorithm selection)
state the state to extrapolate from
dt time delta in seconds (can be negative for backward extrapolation)
Returns
the extrapolated position
Definition at line 135 of file n_dead_reckoning.c.
References DR_STATE::acc, DR_ENTITY::algo, DR_ALGO_STATIC, DR_ALGO_VEL, DR_ALGO_VEL_ACC, dr_vec3_add(), dr_vec3_scale(), DR_STATE::pos, and DR_STATE::vel.
Referenced by dr_entity_check_threshold(), dr_entity_compute(), and dr_entity_receive_state().
dr_entity_receive_state()
void dr_entity_receive_state (DR_ENTITY * entity, const DR_VEC3 * pos, const DR_VEC3 * vel, const DR_VEC3 * acc, double time)
receive a new authoritative state update from the network
receive a new authoritative state update from the network
This is called when a new state packet arrives from the network (or when the owner determines a new update is needed). It records the current predicted position as prev_predicted so the convergence algorithm can smoothly blend from there to the new state's extrapolation.
Parameters
entity the entity
pos new authoritative position (required)
vel new authoritative velocity (NULL treated as zero)
acc new authoritative acceleration (NULL treated as zero)
time timestamp of the update
Definition at line 168 of file n_dead_reckoning.c.
References __n_assert, DR_STATE::acc, DR_ENTITY::algo, DR_ENTITY::bezier_p0, DR_ENTITY::bezier_p1, DR_ENTITY::bezier_p2, DR_ENTITY::bezier_p3, DR_ENTITY::blend_mode, DR_ENTITY::blend_start, DR_ENTITY::blend_time, DR_ENTITY::blending, DR_ALGO_VEL_ACC, DR_BLEND_CUBIC, DR_BLEND_SNAP, dr_entity_extrapolate(), dr_vec3_add(), dr_vec3_scale(), dr_vec3_sub(), dr_vec3_zero(), DR_ENTITY::last_known, DR_STATE::pos, DR_ENTITY::prev_predicted, DR_STATE::time, DR_ENTITY::update_count, and DR_STATE::vel.
Referenced by demo_dead_reckoning(), and main().
dr_entity_set_algo()
void dr_entity_set_algo (DR_ENTITY * entity, DR_ALGO algo)
set the extrapolation algorithm
set the extrapolation algorithm
Parameters
entity the entity
algo new algorithm
Definition at line 338 of file n_dead_reckoning.c.
References __n_assert, and DR_ENTITY::algo.
Referenced by main().
dr_entity_set_blend_mode()
void dr_entity_set_blend_mode (DR_ENTITY * entity, DR_BLEND blend_mode)
set the convergence blending mode
set the convergence blending mode
Parameters
entity the entity
blend_mode new blending mode
Definition at line 348 of file n_dead_reckoning.c.
References __n_assert, and DR_ENTITY::blend_mode.
Referenced by main().
dr_entity_set_blend_time()
void dr_entity_set_blend_time (DR_ENTITY * entity, double blend_time)
set the convergence blend duration
set the convergence blend duration
Parameters
entity the entity
blend_time new blend time in seconds
Definition at line 368 of file n_dead_reckoning.c.
References __n_assert, and DR_ENTITY::blend_time.
Referenced by main().
dr_entity_set_position()
void dr_entity_set_position (DR_ENTITY * entity, const DR_VEC3 * pos, const DR_VEC3 * vel, const DR_VEC3 * acc, double time)
force-set entity position without blending
force-set entity position without blending
Used for teleportation or initial placement.
Parameters
entity the entity
pos position (required)
vel velocity (NULL treated as zero)
acc acceleration (NULL treated as zero)
time timestamp
Definition at line 382 of file n_dead_reckoning.c.
References __n_assert, DR_STATE::acc, DR_ENTITY::blending, DR_ENTITY::display_pos, dr_vec3_zero(), DR_ENTITY::last_known, DR_STATE::pos, DR_ENTITY::prev_predicted, DR_STATE::time, DR_ENTITY::update_count, and DR_STATE::vel.
Referenced by demo_dead_reckoning(), main(), and on_ghost_toggle().
dr_entity_set_threshold()
void dr_entity_set_threshold (DR_ENTITY * entity, double threshold)
set the position error threshold
set the position error threshold
Parameters
entity the entity
threshold new threshold value (distance units)
Definition at line 358 of file n_dead_reckoning.c.
References __n_assert, and DR_ENTITY::pos_threshold.
Referenced by main().
dr_vec3()
static DR_VEC3 dr_vec3 (double x, double y, double z) inline static
Create a DR_VEC3 from components.
Examples
ex_gui_isometric.c, and ex_iso_astar.c.
Definition at line 185 of file n_dead_reckoning.h.
Referenced by demo_dead_reckoning(), main(), and on_ghost_toggle().
dr_vec3_add()
static DR_VEC3 dr_vec3_add (DR_VEC3 a, DR_VEC3 b) inline static
Vector addition: a + b.
Definition at line 197 of file n_dead_reckoning.h.
References DR_VEC3::x, DR_VEC3::y, and DR_VEC3::z.
Referenced by dr_entity_extrapolate(), and dr_entity_receive_state().
dr_vec3_distance()
static double dr_vec3_distance (DR_VEC3 a, DR_VEC3 b) inline static
Distance between two points.
Definition at line 234 of file n_dead_reckoning.h.
References dr_vec3_length(), and dr_vec3_sub().
Referenced by dr_entity_check_threshold().
dr_vec3_length()
static double dr_vec3_length (DR_VEC3 v) inline static
Length of vector.
Definition at line 229 of file n_dead_reckoning.h.
References dr_vec3_length_sq().
Referenced by dr_vec3_distance().
dr_vec3_length_sq()
static double dr_vec3_length_sq (DR_VEC3 v) inline static
Squared length of vector.
Definition at line 224 of file n_dead_reckoning.h.
References DR_VEC3::x, DR_VEC3::y, and DR_VEC3::z.
Referenced by dr_vec3_length().
dr_vec3_lerp()
static DR_VEC3 dr_vec3_lerp (DR_VEC3 a, DR_VEC3 b, double t) inline static
Linear interpolation: a + (b - a) * t.
Definition at line 215 of file n_dead_reckoning.h.
References DR_VEC3::x, DR_VEC3::y, and DR_VEC3::z.
Referenced by dr_entity_compute().
dr_vec3_scale()
static DR_VEC3 dr_vec3_scale (DR_VEC3 v, double s) inline static
Scalar multiplication: v * s.
Definition at line 209 of file n_dead_reckoning.h.
References DR_VEC3::x, DR_VEC3::y, and DR_VEC3::z.
Referenced by dr_entity_extrapolate(), and dr_entity_receive_state().
dr_vec3_sub()
static DR_VEC3 dr_vec3_sub (DR_VEC3 a, DR_VEC3 b) inline static
Vector subtraction: a - b.
Definition at line 203 of file n_dead_reckoning.h.
References DR_VEC3::x, DR_VEC3::y, and DR_VEC3::z.
Referenced by dr_entity_receive_state(), and dr_vec3_distance().
dr_vec3_zero()
static DR_VEC3 dr_vec3_zero (void) inline static
Zero vector.
Examples
ex_iso_astar.c.
Definition at line 191 of file n_dead_reckoning.h.
Referenced by demo_dead_reckoning(), dr_entity_create(), dr_entity_receive_state(), and dr_entity_set_position().