Nilorea Library: GRAPHICS: isometric engine, maps, tiles, ...
GRAPHICS: isometric engine, maps, tiles, ...
Data Structures
struct CELL
Cell of a MAP.
struct ISO_DRAW_ENTRY
Draw order entry for segment-sorted rendering.
struct ISO_MAP
Height-aware isometric map with terrain and height layers.
struct ISO_PROJECTION
Axonometric projection parameters.
struct ISO_TILE_SEGMENT
Single vertical segment of a tile: solid matter from bottom to top.
struct ISO_TILE_SEGMENTS
Per-tile height segments.
struct ISO_VISIBLE_EDGES
Per-tile edge visibility flags for height border rendering.
struct MAP
MAP with objects, tiles, skins (legacy structure)
struct N_ISO_CAMERA
2D isometric camera for viewport management.
struct N_ISO_OBJECT
Drawable object for depth-sorted isometric rendering.
Macros
#define BLCK 3
FLAG of a stopping tile.
#define ISO_CORNER_NE (1 << 1)
Corner bitmask: northeast diagonal has higher terrain.
#define ISO_CORNER_NW (1 << 0)
Corner bitmask: northwest diagonal has higher terrain.
#define ISO_CORNER_SE (1 << 2)
Corner bitmask: southeast diagonal has higher terrain.
#define ISO_CORNER_SW (1 << 3)
Corner bitmask: southwest diagonal has higher terrain.
#define ISO_EDGE_E (1 << 2)
Edge bitmask: east neighbor has higher terrain.
#define ISO_EDGE_N (1 << 1)
Edge bitmask: north neighbor has higher terrain.
#define ISO_EDGE_S (1 << 3)
Edge bitmask: south neighbor has higher terrain.
#define ISO_EDGE_W (1 << 0)
Edge bitmask: west neighbor has higher terrain.
#define ISO_MAX_SEGMENTS_PER_TILE 2
Max height segments per tile (ground + one elevated structure).
#define ISO_NUM_CORNER_MASKS 16
Number of possible corner mask combinations (2^4 = 16)
#define ISO_NUM_EDGE_MASKS 16
Number of possible edge mask combinations (2^4 = 16)
#define ISO_NUM_MASKS (ISO_NUM_EDGE_MASKS + ISO_NUM_CORNER_MASKS)
Total number of transition masks (edge + corner)
#define ISO_NUM_PROJECTIONS 4
Number of built-in projection presets.
#define ISO_PROJ_CLASSIC 0
Projection ID: classic 2:1 isometric (~26.565 degree angle)
#define ISO_PROJ_ISOMETRIC 1
Projection ID: true isometric (30 degree angle)
#define ISO_PROJ_MILITARY 2
Projection ID: military/planometric (45 degree angle)
#define ISO_PROJ_STAGGERED 3
Projection ID: flatter dimetric (~18.43 degree angle)
#define ISO_PROJ_STEEP ISO_PROJ_ISOMETRIC
Legacy alias: ISO_PROJ_STEEP maps to ISO_PROJ_ISOMETRIC.
#define ISO_PROJ_WIDE ISO_PROJ_STAGGERED
Legacy alias: ISO_PROJ_WIDE maps to ISO_PROJ_STAGGERED.
#define N_ABILITY 3
FLAG of ability type.
#define N_MUSIC 4
FLAG of music type.
#define N_OBJECT 5
FLAG of object type.
#define N_TILE 2
FLAG of tile type.
#define SWIM 2
FLAG of a swimmable tile.
#define WALK 1
FLAG of a walkable tile.
Typedefs
typedef void(* N_ISO_OBJECT_DRAW_FN) (float screen_x, float screen_y, float zoom, float alpha, void *user_data)
Object draw callback.
Functions
int camera_to_map (MAP **map, int tx, int ty, int x, int y)
Center Map on given map coordinate, with x & y offset.
int camera_to_scr (MAP **map, int x, int y)
Center Map on given screen coordinate.
int create_empty_map (MAP **map, char *name, int XSIZE, int YSIZE, int TILEW, int TILEH, int nbmaxobjects, int nbmaxgroup, int nbmaxanims, int nbtiles, int nbanims)
Create an empty map.
int draw_map (MAP *map, ALLEGRO_BITMAP *bmp, int destx, int desty, int mode)
Draw the map using its coordinate on the specified bitmap.
int free_map (MAP **map)
Free the map.
int get_value (MAP *map, int type, int x, int y)
Get the tilenumber of a cell.
void iso_corner_to_screen (const ISO_MAP *map, int cx, int cy, float fh, float cam_x, float cam_y, float zoom, float *sx, float *sy)
Project a tile corner to screen coordinates (canonical formula).
float iso_diamond_dist (int px, int py, int tile_w, int tile_h)
distance from pixel to diamond edge (0 at edge, 1 at center)
void iso_generate_transition_masks (ALLEGRO_BITMAP **masks, int tile_w, int tile_h)
Generate the 32 procedural transition alpha masks (16 edge + 16 corner).
void iso_generate_transition_tiles (ALLEGRO_BITMAP ***tiles, ALLEGRO_BITMAP **masks, ALLEGRO_BITMAP **tile_bitmaps, int num_terrains, int tile_w, int tile_h)
Pre-composite transition tiles (terrain texture * alpha mask).
int iso_is_in_diamond (int px, int py, int tile_w, int tile_h)
test if pixel (px,py) is inside the isometric diamond of size tile_w x tile_h
int iso_map_build_draw_order (const ISO_MAP *map, ISO_DRAW_ENTRY *out, int max_entries)
Build the draw order for segment-sorted rendering.
void iso_map_calc_transitions (const ISO_MAP *map, int mx, int my, int *edge_bits, int *corner_bits)
compute terrain transition bitmasks for a cell (Article 934)
void iso_map_calc_transitions_full (const ISO_MAP *map, int mx, int my, int *edge_bits, int *corner_bits)
compute per-terrain transition bitmasks with height filtering (Article 934).
void iso_map_corner_heights (const ISO_MAP *map, int mx, int my, float *h_n, float *h_e, float *h_s, float *h_w)
compute average corner heights for smooth rendering (Article 2026)
void iso_map_draw (const ISO_MAP *map, ALLEGRO_BITMAP **tile_bitmaps, ALLEGRO_BITMAP ***transition_tiles, int num_masks, ALLEGRO_BITMAP **overlay_bitmaps, int num_overlay_tiles, float cam_px, float cam_py, float zoom, int screen_w, int screen_h, int player_mode, N_ISO_OBJECT *objects, int num_objects)
Draw the full ISO_MAP with height, transitions, overlays, cliff walls, hover, and grid.
void iso_map_free (ISO_MAP **map)
free an ISO_MAP and set the pointer to NULL
int iso_map_get_ability (const ISO_MAP *map, int mx, int my)
get ability for a cell (bounds-checked)
int iso_map_get_height (const ISO_MAP *map, int mx, int my)
get height for a cell (bounds-checked, clamped)
const ISO_TILE_SEGMENTS * iso_map_get_segments (const ISO_MAP *map, int mx, int my)
get per-tile segments.
int iso_map_get_terrain (const ISO_MAP *map, int mx, int my)
get terrain type for a cell (bounds-checked)
ISO_VISIBLE_EDGES iso_map_get_visible_edges (const ISO_MAP *map, int mx, int my)
Compute which diamond edges of tile (mx, my) need a height border.
ISO_VISIBLE_EDGES iso_map_get_visible_edges_segment (const ISO_MAP *map, int mx, int my, int seg_idx)
Compute per-segment edge visibility for height border rendering.
float iso_map_interpolate_height (const ISO_MAP *map, float fx, float fy)
bilinear height interpolation at fractional map coordinates
void iso_map_lerp_projection (ISO_MAP *map, float dt)
smoothly interpolate current projection angle toward target (call every frame)
ISO_MAP * iso_map_load (const char *filename)
load ISO_MAP from binary file
ISO_MAP * iso_map_new (int width, int height, int num_terrains, int max_height)
create a new height-aware ISO_MAP with given dimensions
void iso_map_randomize (ISO_MAP *map)
randomize terrain and height for testing/demo purposes
int iso_map_save (const ISO_MAP *map, const char *filename)
save ISO_MAP to binary file (chunk-based format)
void iso_map_set_ability (ISO_MAP *map, int mx, int my, int ab)
set ability for a cell (bounds-checked)
void iso_map_set_height (ISO_MAP *map, int mx, int my, int h)
set height for a cell (bounds-checked, clamped)
void iso_map_set_projection (ISO_MAP *map, int preset, float tile_width)
set projection preset and snap to it immediately
void iso_map_set_projection_custom (ISO_MAP *map, float half_w, float half_h, float tile_lift)
set custom projection parameters directly
void iso_map_set_projection_target (ISO_MAP *map, int preset)
set target projection preset for smooth interpolation via iso_map_lerp_projection
int iso_map_set_segments (ISO_MAP *map, int mx, int my, const ISO_TILE_SEGMENT *segs, int count)
set per-tile segments on an ISO_MAP.
void iso_map_set_terrain (ISO_MAP *map, int mx, int my, int terrain)
set terrain type for a cell (bounds-checked)
int iso_map_should_transition (const ISO_MAP *map, int mx1, int my1, int mx2, int my2)
check if terrain blending should occur between two adjacent cells
int iso_map_should_transition_smooth (const ISO_MAP *map, int mx1, int my1, int mx2, int my2)
check if terrain transition should render between two cells (height-aware)
void iso_map_smooth_corner_heights (const ISO_MAP *map, int mx, int my, float *h_n, float *h_e, float *h_s, float *h_w)
compute smooth corner heights with slope clamping (for rendering)
void iso_map_to_screen (const ISO_MAP *map, int mx, int my, int h, float *screen_x, float *screen_y)
convert map tile coordinates to screen pixel coordinates
void iso_map_to_screen_f (const ISO_MAP *map, float fmx, float fmy, float h, float *screen_x, float *screen_y)
convert map tile coordinates to screen pixel coordinates (float version)
void iso_mask_tile_to_diamond (ALLEGRO_BITMAP *bmp, int tile_w, int tile_h)
Mask a tile bitmap to the isometric diamond shape.
const char * iso_projection_name (int preset)
get the display name for a projection preset
void iso_screen_to_map (const ISO_MAP *map, float screen_x, float screen_y, int *mx, int *my)
convert screen pixel coordinates to map tile coordinates (flat, no height)
void iso_screen_to_map_height (const ISO_MAP *map, float screen_x, float screen_y, int tile_w, int tile_h, int *mx, int *my)
height-aware screen-to-map conversion with diamond hit testing.
void iso_screen_to_map_height_f (const ISO_MAP *map, float screen_x, float screen_y, int tile_w, int tile_h, int *mx, int *my, float *out_fx, float *out_fy)
height-aware screen-to-map conversion returning fractional tile coordinates.
int load_map (MAP **map, char *filename)
Load the map.
void n_iso_camera_center_on (N_ISO_CAMERA *cam, float world_x, float world_y, int screen_w, int screen_h)
Center the camera so that a world point is at screen center.
void n_iso_camera_follow (N_ISO_CAMERA *cam, float target_x, float target_y, int screen_w, int screen_h, float smoothing, float dt)
Smoothly follow a world-space target (camera lerp).
void n_iso_camera_free (N_ISO_CAMERA **cam)
Free a camera and set the pointer to NULL.
N_ISO_CAMERA * n_iso_camera_new (float zoom_min, float zoom_max)
Create a new camera with the given zoom limits.
void n_iso_camera_screen_to_world (const N_ISO_CAMERA *cam, float sx, float sy, float *wx, float *wy)
Convert screen pixel coordinates to world coordinates.
void n_iso_camera_scroll (N_ISO_CAMERA *cam, float dx, float dy)
Scroll the camera by (dx, dy) world units.
void n_iso_camera_world_to_screen (const N_ISO_CAMERA *cam, float wx, float wy, float *sx, float *sy)
Convert world coordinates to screen pixel coordinates.
void n_iso_camera_zoom (N_ISO_CAMERA *cam, float dz, float mouse_x, float mouse_y)
Zoom the camera toward a screen-space point (e.g.
int save_map (MAP *map, char *filename)
Save the map.
int ScreenToMap (int mx, int my, int *Tilex, int *Tiley, ALLEGRO_BITMAP *mousemap)
Convert screen coordinate to map coordinate.
int set_value (MAP *map, int type, int x, int y, int value)
Set the tilenumber of a cell.
Detailed Description
Data Structure Documentation
CELL
struct CELL
Cell of a MAP.
Definition at line 586 of file n_iso_engine.h.
Data Fields
int ability ability of the tile (walking, swimming, blocking, killing ?)
int music ident of the music on the tile
int objectnumber ident of the object in the MAP->object library
int tilenumber ident of the tile in the MAP->tile library
ISO_DRAW_ENTRY
struct ISO_DRAW_ENTRY
Draw order entry for segment-sorted rendering.
Produced by iso_map_build_draw_order().
Definition at line 148 of file n_iso_engine.h.
Data Fields
int bottom segment bottom height (primary sort key)
int mx
int my tile coordinates
int seg_idx segment index within tile (0..count-1)
int top segment top height
int underside 1 if underside face should be drawn
ISO_MAP
struct ISO_MAP
Height-aware isometric map with terrain and height layers.
Extends the legacy MAP concept with per-cell height values, configurable projection, and terrain transition support.
Examples
ex_gui_isometric.c, and ex_iso_astar.c.
Definition at line 188 of file n_iso_engine.h.
Data Fields
int * ability walkability per cell [height * width] (WALK/SWIM/BLCK)
float ambient_b
float ambient_g
float ambient_r Global ambient color (day/night + dark place tinting).
Applied as additional multiply on top of height tinting. Default: (1.0, 1.0, 1.0) = no change. Set by client lighting system each frame.
float * dynamic_light_map Per-tile dynamic light accumulation buffer.
Caller fills this before iso_map_draw() with additive light contributions. Array of [width * height * 3] floats (r, g, b per tile). NULL = no dynamic lighting. Caller-owned.
int height map height in tiles (Y axis)
float height_tint_intensity 0.0 = no tint, 0.3 = subtle, 1.0 = full range.
Higher segments are brighter, lower are darker. Applied as a multiply tint on tile top faces and walls.
int * heightmap height value per cell [height * width], 0..max_height
int hover_mx hovered tile X (-1 = none)
int hover_my hovered tile Y (-1 = none)
int max_height maximum allowed height value
int * neighbor_heights_east Heights from east neighbor chunk's west edge [height], NULL = boundary.
int * neighbor_heights_north Heights from north neighbor chunk's south edge [width], NULL = boundary.
int * neighbor_heights_south Heights from south neighbor chunk's north edge [width], NULL = boundary.
int * neighbor_heights_west Heights from west neighbor chunk's east edge [height], NULL = boundary.
int num_terrains number of terrain types used
int * overlay overlay tile index per cell [height * width], 0 = none.
NULL = no overlays
ISO_PROJECTION proj current projection parameters
ISO_TILE_SEGMENTS * segments Per-cell height segments.
NULL = use heightmap as single segment. When non-NULL, heightmap[] is derived (top of highest segment).
int show_grid 1 = draw grid overlay
int smooth_height 0 = CUT mode (cliff walls), 1 = SMOOTH mode (per-corner slopes)
int smooth_slope_max max height diff rendered as slope (default 1)
int * terrain terrain type per cell [height * width], indices 0..num_terrains-1
int width map width in tiles (X axis)
ISO_PROJECTION
struct ISO_PROJECTION
Axonometric projection parameters.
Controls how map coordinates are projected to screen coordinates. The half-widths define the diamond shape of each tile.
Definition at line 159 of file n_iso_engine.h.
Data Fields
float angle_deg current projection angle in degrees
float half_h half-height of a tile in pixels (vertical extent)
float half_w half-width of a tile in pixels (horizontal extent)
float lerp_speed interpolation speed factor (default 3.0)
float target_angle target angle for smooth interpolation (degrees)
float tile_lift vertical pixel offset per height unit
ISO_TILE_SEGMENT
struct ISO_TILE_SEGMENT
Single vertical segment of a tile: solid matter from bottom to top.
Definition at line 132 of file n_iso_engine.h.
Data Fields
int bottom lower height bound (inclusive), must be < top
int lower_tile terrain index for wall/side faces (-1 = use tile's terrain layer)
int top upper height bound, must be > bottom
int upper_tile terrain index for top face (-1 = use tile's terrain layer)
ISO_TILE_SEGMENTS
struct ISO_TILE_SEGMENTS
Per-tile height segments.
A normal solid tile is [{0, h}]. A bridge tile might be [{0,1},{3,4}]. A flat tile has count=0.
Definition at line 141 of file n_iso_engine.h.
Data Fields
int count 0..ISO_MAX_SEGMENTS_PER_TILE
ISO_TILE_SEGMENT segs[2]
ISO_VISIBLE_EDGES
struct ISO_VISIBLE_EDGES
Per-tile edge visibility flags for height border rendering.
Definition at line 367 of file n_iso_engine.h.
Data Fields
int draw_ne 1 if NE edge (N→E, top-right) should be drawn
int draw_nw 1 if NW edge (N→W, top-left) should be drawn
int draw_se 1 if SE edge (E→S, bottom-right) should be drawn
int draw_sw 1 if SW edge (S→W, bottom-left) should be drawn
int draw_underside 1 if floating segment underside border should be drawn
int neighbor_top_ne top height of NE neighbor (0 if absent/boundary)
int neighbor_top_nw top height of NW neighbor (0 if absent/boundary)
int neighbor_top_se top height of SE neighbor (0 if absent/boundary)
int neighbor_top_sw top height of SW neighbor (0 if absent/boundary)
MAP
struct MAP
MAP with objects, tiles, skins (legacy structure)
Definition at line 599 of file n_iso_engine.h.
Data Fields
char * anim_group_names as for previous:char *object_group_names
ALLEGRO_COLOR bgcolor color of the bg
ALLEGRO_BITMAP * colortile default full colored background tile
CELL * grid Grid of each cell of the map.
ALLEGRO_BITMAP * mousemap Map for mouse collision between mouse pointer and map.
char * name Name of the map (used for linking between two map)
char * object_group_names name of the main group of the (kind of) library of objects, filled by zero else, size iz limited to 512 characaters
int ptanchorX X starting cell for drawing.
int ptanchorY Y starting cell for drawing.
char * quests_group_names as for previous:char *object_group_names
char * sounds_group_names as for previous:char *object_group_names
int TILEH size Y of tiles of the map (in pixel)
int TILEW size X of tiles of the map (in pixel)
ALLEGRO_COLOR wirecolor color of wire
int X X move in pixel for drawing.
int XSIZE size X of the grid (nbXcell)
int Y Y move in pixel for drawing.
int YSIZE size Y of the grid (nbYcell)
N_ISO_CAMERA
struct N_ISO_CAMERA
2D isometric camera for viewport management.
Examples
ex_gui_isometric.c.
Definition at line 177 of file n_iso_engine.h.
Data Fields
float x camera X offset (world units, pre-zoom)
float y camera Y offset (world units, pre-zoom)
float zoom zoom factor (1.0 = no zoom)
float zoom_max maximum allowed zoom
float zoom_min minimum allowed zoom
N_ISO_OBJECT
struct N_ISO_OBJECT
Drawable object for depth-sorted isometric rendering.
Examples
ex_gui_isometric.c.
Definition at line 481 of file n_iso_engine.h.
Data Fields
N_ISO_OBJECT_DRAW_FN draw draw callback
float fx fractional map X position
float fy fractional map Y position
float fz height in map units (elevation)
int is_occluded OUTPUT: set to 1 if behind tiles during last iso_map_draw() call.
float occluded_alpha overlay alpha when behind tiles [0..1], 0=hidden, 0.35=ghost, 1=always visible
float sprite_h entity height in world units for head occlusion (e.g.
2.0 for players)
void * user_data user data passed to draw callback
Macro Definition Documentation
BLCK
#define BLCK 3
FLAG of a stopping tile.
Examples
ex_iso_astar.c.
Definition at line 69 of file n_iso_engine.h.
ISO_CORNER_NE
#define ISO_CORNER_NE (1 << 1)
Corner bitmask: northeast diagonal has higher terrain.
Definition at line 93 of file n_iso_engine.h.
ISO_CORNER_NW
#define ISO_CORNER_NW (1 << 0)
Corner bitmask: northwest diagonal has higher terrain.
Definition at line 91 of file n_iso_engine.h.
ISO_CORNER_SE
#define ISO_CORNER_SE (1 << 2)
Corner bitmask: southeast diagonal has higher terrain.
Definition at line 95 of file n_iso_engine.h.
ISO_CORNER_SW
#define ISO_CORNER_SW (1 << 3)
Corner bitmask: southwest diagonal has higher terrain.
Definition at line 97 of file n_iso_engine.h.
ISO_EDGE_E
#define ISO_EDGE_E (1 << 2)
Edge bitmask: east neighbor has higher terrain.
Definition at line 84 of file n_iso_engine.h.
ISO_EDGE_N
#define ISO_EDGE_N (1 << 1)
Edge bitmask: north neighbor has higher terrain.
Definition at line 82 of file n_iso_engine.h.
ISO_EDGE_S
#define ISO_EDGE_S (1 << 3)
Edge bitmask: south neighbor has higher terrain.
Definition at line 86 of file n_iso_engine.h.
ISO_EDGE_W
#define ISO_EDGE_W (1 << 0)
Edge bitmask: west neighbor has higher terrain.
Definition at line 80 of file n_iso_engine.h.
ISO_MAX_SEGMENTS_PER_TILE
#define ISO_MAX_SEGMENTS_PER_TILE 2
Max height segments per tile (ground + one elevated structure).
Definition at line 129 of file n_iso_engine.h.
ISO_NUM_CORNER_MASKS
#define ISO_NUM_CORNER_MASKS 16
Number of possible corner mask combinations (2^4 = 16)
Definition at line 99 of file n_iso_engine.h.
ISO_NUM_EDGE_MASKS
#define ISO_NUM_EDGE_MASKS 16
Number of possible edge mask combinations (2^4 = 16)
Definition at line 88 of file n_iso_engine.h.
ISO_NUM_MASKS
#define ISO_NUM_MASKS (ISO_NUM_EDGE_MASKS + ISO_NUM_CORNER_MASKS)
Total number of transition masks (edge + corner)
Definition at line 101 of file n_iso_engine.h.
ISO_NUM_PROJECTIONS
#define ISO_NUM_PROJECTIONS 4
Number of built-in projection presets.
Definition at line 116 of file n_iso_engine.h.
ISO_PROJ_CLASSIC
#define ISO_PROJ_CLASSIC 0
Projection ID: classic 2:1 isometric (~26.565 degree angle)
Examples
ex_gui_isometric.c, and ex_iso_astar.c.
Definition at line 108 of file n_iso_engine.h.
ISO_PROJ_ISOMETRIC
#define ISO_PROJ_ISOMETRIC 1
Projection ID: true isometric (30 degree angle)
Definition at line 110 of file n_iso_engine.h.
ISO_PROJ_MILITARY
#define ISO_PROJ_MILITARY 2
Projection ID: military/planometric (45 degree angle)
Definition at line 112 of file n_iso_engine.h.
ISO_PROJ_STAGGERED
#define ISO_PROJ_STAGGERED 3
Projection ID: flatter dimetric (~18.43 degree angle)
Definition at line 114 of file n_iso_engine.h.
ISO_PROJ_STEEP
#define ISO_PROJ_STEEP ISO_PROJ_ISOMETRIC
Legacy alias: ISO_PROJ_STEEP maps to ISO_PROJ_ISOMETRIC.
Definition at line 120 of file n_iso_engine.h.
ISO_PROJ_WIDE
#define ISO_PROJ_WIDE ISO_PROJ_STAGGERED
Legacy alias: ISO_PROJ_WIDE maps to ISO_PROJ_STAGGERED.
Definition at line 122 of file n_iso_engine.h.
N_ABILITY
#define N_ABILITY 3
FLAG of ability type.
Definition at line 579 of file n_iso_engine.h.
N_MUSIC
#define N_MUSIC 4
FLAG of music type.
Definition at line 581 of file n_iso_engine.h.
N_OBJECT
#define N_OBJECT 5
FLAG of object type.
Definition at line 583 of file n_iso_engine.h.
N_TILE
#define N_TILE 2
FLAG of tile type.
Definition at line 577 of file n_iso_engine.h.
SWIM
#define SWIM 2
FLAG of a swimmable tile.
Examples
ex_iso_astar.c.
Definition at line 67 of file n_iso_engine.h.
WALK
#define WALK 1
FLAG of a walkable tile.
Examples
ex_iso_astar.c.
Definition at line 65 of file n_iso_engine.h.
Typedef Documentation
N_ISO_OBJECT_DRAW_FN
typedef void(* N_ISO_OBJECT_DRAW_FN) (float screen_x, float screen_y, float zoom, float alpha, void *user_data)
Object draw callback.
Parameters
screen_x screen pixel X position (camera-transformed)
screen_y screen pixel Y position (camera-transformed)
zoom current camera zoom factor
alpha opacity multiplier (1.0 = normal draw, <1.0 = occluded overlay)
user_data user pointer from N_ISO_OBJECT
Definition at line 478 of file n_iso_engine.h.
Function Documentation
camera_to_map()
int camera_to_map (MAP ** map, int tx, int ty, int x, int y)
Center Map on given map coordinate, with x & y offset.
Parameters
map A MAP *map to center on tx+x , ty+y
tx TILEX offset in tile
ty TILEY offset in tile
x X offset in pixel
y Y Offset in pixel
Returns
TRUE
Definition at line 320 of file n_iso_engine.c.
camera_to_scr()
int camera_to_scr (MAP ** map, int x, int y)
Center Map on given screen coordinate.
Parameters
map A MAP *map to center on x,y
x the X coordinate (in pixel) to center on;
y the Y coordintae (in pixel) to center on;
Returns
TRUE
Definition at line 294 of file n_iso_engine.c.
create_empty_map()
int create_empty_map (MAP ** map, char * name, int XSIZE, int YSIZE, int TILEW, int TILEH, int nbmaxobjects, int nbmaxgroup, int nbmaxanims, int nbtiles, int nbanims)
Create an empty map.
Parameters
map the map pointer to point on the allocated one
name Name of the map (used for linking between two map)
XSIZE the X size of the map (in tile)
YSIZE the Y size of the map (in tile)
TILEW the Width of a tile
TILEH the Heigh of a tile
nbmaxobjects the maximum number of objects in the map
nbmaxgroup the maximum number of active objects in the map
nbmaxanims the maximum number of animations in the map
nbtiles the maximum number of tiles in the map
nbanims the maximum number of animations in the map
Returns
TRUE on success FALSE on failure
Definition at line 59 of file n_iso_engine.c.
References Free, Malloc, N_ABILITY, N_MUSIC, N_OBJECT, N_TILE, and set_value().
Referenced by load_map().
draw_map()
int draw_map (MAP * map, ALLEGRO_BITMAP * bmp, int destx, int desty, int mode)
Draw the map using its coordinate on the specified bitmap.
Draw the map using its coordinate on the specified bitmap.
Parameters
map The Map to draw
bmp The screen destination
destx X offset on bmp
desty Y offste on bmp
mode Drawing mode
Returns
TRUE
Definition at line 338 of file n_iso_engine.c.
References MAP::colortile, MAP::grid, mode, MAP::ptanchorX, MAP::ptanchorY, MAP::TILEH, CELL::tilenumber, MAP::TILEW, MAP::wirecolor, MAP::X, MAP::XSIZE, MAP::Y, and MAP::YSIZE.
free_map()
int free_map (MAP ** map)
Free the map.
Parameters
map The map to free. The pointer will be set to NULL
Returns
TRUE or FALSE
Definition at line 578 of file n_iso_engine.c.
References Free.
Referenced by load_map().
get_value()
int get_value (MAP * map, int type, int x, int y)
Get the tilenumber of a cell.
Get the tilenumber of a cell.
Parameters
map A MAP *map to 'touch'
type It is the type of value to change , it can be N_TILE,N_ABILITY,N_MUSIC,N_OBJECT
x X coordinate of the cell
y Y coordinate of the cell
Returns
The specified type value of the cell, or FALSE if unavailable
Definition at line 198 of file n_iso_engine.c.
References CELL::ability, MAP::grid, CELL::music, N_ABILITY, N_MUSIC, N_OBJECT, N_TILE, CELL::objectnumber, CELL::tilenumber, MAP::XSIZE, and MAP::YSIZE.
iso_corner_to_screen()
void iso_corner_to_screen (const ISO_MAP * map, int cx, int cy, float fh, float cam_px, float cam_py, float zoom, float * sx, float * sy)
Project a tile corner to screen coordinates (canonical formula).
Produces bit-identical results for the same (cx,cy,fh) regardless of which tile's draw call computes the vertex. Used by the renderer to eliminate shared-edge seams between adjacent wall faces.
Public version of the canonical vertex projection used by the renderer. cam_px and cam_py must be integer-snapped pixel offsets: floor(cam_x * zoom), floor(cam_y * zoom). This eliminates sub-pixel aliasing shimmer by keeping each vertex's fractional pixel position constant across frames.
Parameters
map the map (uses map->proj)
cx corner X in tile grid (e.g. mx+1 for the East corner)
cy corner Y in tile grid
fh height (float, supports smooth-height interpolation)
cam_px integer-snapped camera pixel X: floor(cam_x * zoom)
cam_py integer-snapped camera pixel Y: floor(cam_y * zoom)
zoom zoom factor
sx output screen X
sy output screen Y
Definition at line 958 of file n_iso_engine.c.
References __n_assert, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, ISO_MAP::proj, and ISO_PROJECTION::tile_lift.
iso_diamond_dist()
float iso_diamond_dist (int px, int py, int tile_w, int tile_h)
distance from pixel to diamond edge (0 at edge, 1 at center)
distance from pixel to diamond edge (0 at edge, 1 at center)
Returns 0 at the edge, 1 at the center. Pixels outside the diamond return 0.
Parameters
px pixel X
py pixel Y
tile_w tile width in pixels
tile_h tile height in pixels
Returns
distance in [0, 1]
Definition at line 998 of file n_iso_engine.c.
iso_generate_transition_masks()
void iso_generate_transition_masks (ALLEGRO_BITMAP ** masks, int tile_w, int tile_h)
Generate the 32 procedural transition alpha masks (16 edge + 16 corner).
The masks array must have room for ISO_NUM_MASKS entries.
Parameters
masks output array of ALLEGRO_BITMAP* (caller must free)
tile_w tile width in pixels
tile_h tile height in pixels
For EDGE masks (0-15): each bit corresponds to one side of the diamond being "covered". The alpha fades from the edge inward using a gradient that follows the diamond edge normals.
For CORNER masks (16-31): each bit corresponds to one corner of the diamond being "covered". The alpha fades radially from the diamond tip inward.
Definition at line 3051 of file n_iso_engine.c.
References __n_assert, ISO_CORNER_NE, ISO_CORNER_NW, ISO_CORNER_SE, ISO_CORNER_SW, ISO_EDGE_E, ISO_EDGE_N, ISO_EDGE_S, ISO_EDGE_W, iso_is_in_diamond(), ISO_NUM_CORNER_MASKS, ISO_NUM_EDGE_MASKS, ISO_NUM_MASKS, LOG_INFO, and n_log.
Referenced by main().
iso_generate_transition_tiles()
void iso_generate_transition_tiles (ALLEGRO_BITMAP *** tiles, ALLEGRO_BITMAP ** masks, ALLEGRO_BITMAP ** tile_bitmaps, int num_terrains, int tile_w, int tile_h)
Pre-composite transition tiles (terrain texture * alpha mask).
tiles[t][m] = terrain t composited with mask m. tiles must be a [num_terrains][ISO_NUM_MASKS] array of ALLEGRO_BITMAP*.
Parameters
tiles output 2D array of ALLEGRO_BITMAP* (caller must free)
masks array of ISO_NUM_MASKS transition alpha masks
tile_bitmaps array of num_terrains terrain tile bitmaps
num_terrains number of terrain types
tile_w tile width in pixels
tile_h tile height in pixels
tiles[t][m] = terrain t composited with mask m.
Definition at line 3182 of file n_iso_engine.c.
References __n_assert, ISO_NUM_EDGE_MASKS, ISO_NUM_MASKS, LOG_INFO, n_log, and tile_bitmaps.
Referenced by main().
iso_is_in_diamond()
int iso_is_in_diamond (int px, int py, int tile_w, int tile_h)
test if pixel (px,py) is inside the isometric diamond of size tile_w x tile_h
test if pixel (px,py) is inside the isometric diamond of size tile_w x tile_h
The diamond is centered in a tile_w x tile_h rectangle.
Parameters
px pixel X (0..tile_w-1)
py pixel Y (0..tile_h-1)
tile_w tile width in pixels
tile_h tile height in pixels
Returns
1 if inside, 0 if outside
Definition at line 980 of file n_iso_engine.c.
Referenced by iso_generate_transition_masks(), iso_mask_tile_to_diamond(), iso_screen_to_map_height(), and iso_screen_to_map_height_f().
iso_map_build_draw_order()
int iso_map_build_draw_order (const ISO_MAP * map, ISO_DRAW_ENTRY * out, int max_entries)
Build the draw order for segment-sorted rendering.
Populates out[] with one entry per segment (or one per tile if no segment data is available), sorted by (bottom, my, mx).
Parameters
map the ISO_MAP
out output array, must have room for width*height*ISO_MAX_SEGMENTS_PER_TILE entries
max_entries capacity of out[]
Returns
number of entries written
Definition at line 1521 of file n_iso_engine.c.
References __n_assert, _cmp_draw_entry(), ISO_TILE_SEGMENT::bottom, ISO_DRAW_ENTRY::bottom, ISO_TILE_SEGMENTS::count, ISO_MAP::height, ISO_MAP::heightmap, ISO_DRAW_ENTRY::mx, ISO_DRAW_ENTRY::my, ISO_DRAW_ENTRY::seg_idx, ISO_MAP::segments, ISO_TILE_SEGMENTS::segs, ISO_TILE_SEGMENT::top, ISO_DRAW_ENTRY::top, ISO_DRAW_ENTRY::underside, and ISO_MAP::width.
Referenced by iso_map_draw().
iso_map_calc_transitions()
void iso_map_calc_transitions (const ISO_MAP * map, int mx, int my, int * edge_bits, int * corner_bits)
compute terrain transition bitmasks for a cell (Article 934)
compute terrain transition bitmasks for a cell (Article 934)
For a given terrain at (mx, my), checks all 8 neighbors. If a neighbor has a higher-priority (lower index) terrain, the corresponding edge or corner bit is set. Corner bits are only set when the adjacent edges do NOT have the foreign terrain (to avoid redundant overlaps).
Parameters
map the map
mx tile X
my tile Y
edge_bits output: 4-bit edge mask (W, N, E, S)
corner_bits output: 4-bit corner mask (NW, NE, SE, SW)
Definition at line 1231 of file n_iso_engine.c.
References __n_assert, ISO_CORNER_NE, ISO_CORNER_NW, ISO_CORNER_SE, ISO_CORNER_SW, ISO_EDGE_E, ISO_EDGE_N, ISO_EDGE_S, ISO_EDGE_W, and iso_map_get_terrain().
Referenced by demo_iso_engine().
iso_map_calc_transitions_full()
void iso_map_calc_transitions_full (const ISO_MAP * map, int mx, int my, int * edge_bits, int * corner_bits)
compute per-terrain transition bitmasks with height filtering (Article 934).
edge_bits and corner_bits must be arrays of size num_terrains.
compute per-terrain transition bitmasks with height filtering (Article 934).
Iterates terrains above the base terrain and sets edge/corner bits for each terrain that has higher visual priority than the cell. edge_bits and corner_bits must be arrays of at least map->num_terrains.
Parameters
map the map
mx tile X
my tile Y
edge_bits output array [num_terrains] of 4-bit edge masks
corner_bits output array [num_terrains] of 4-bit corner masks
Definition at line 1587 of file n_iso_engine.c.
References __n_assert, ISO_CORNER_NE, ISO_CORNER_NW, ISO_CORNER_SE, ISO_CORNER_SW, ISO_EDGE_E, ISO_EDGE_N, ISO_EDGE_S, ISO_EDGE_W, iso_map_get_terrain(), iso_map_should_transition_smooth(), and ISO_MAP::num_terrains.
Referenced by iso_map_draw().
iso_map_corner_heights()
void iso_map_corner_heights (const ISO_MAP * map, int mx, int my, float * h_n, float * h_e, float * h_s, float * h_w)
compute average corner heights for smooth rendering (Article 2026)
compute average corner heights for smooth rendering (Article 2026)
Each diamond corner is shared by 4 tiles. This averages the heights of the sharing tiles to produce smooth corners. North corner = average of (mx,my), (mx-1,my), (mx,my-1), (mx-1,my-1).
Parameters
map the map
mx tile X
my tile Y
h_n output: north (top) corner height
h_e output: east (right) corner height
h_s output: south (bottom) corner height
h_w output: west (left) corner height
Definition at line 1290 of file n_iso_engine.c.
References __n_assert, and iso_map_get_height().
Referenced by demo_iso_engine().
iso_map_draw()
void iso_map_draw (const ISO_MAP * map, ALLEGRO_BITMAP ** tile_bitmaps, ALLEGRO_BITMAP *** transition_tiles, int num_masks, ALLEGRO_BITMAP ** overlay_bitmaps, int num_overlay_tiles, float cam_px, float cam_py, float zoom, int screen_w, int screen_h, int player_mode, N_ISO_OBJECT * objects, int num_objects)
Draw the full ISO_MAP with height, transitions, overlays, cliff walls, hover, and grid.
Objects (if provided) are depth-sorted and interleaved with tiles using the painter's algorithm. Occluded objects are optionally redrawn as a transparent overlay based on their occluded_alpha setting.
Parameters
map the ISO_MAP
tile_bitmaps array of ALLEGRO_BITMAP* per terrain type
transition_tiles 2D array [num_terrains][num_masks] of pre-composited transitions
num_masks total number of masks (edge + corner, typically 32)
overlay_bitmaps array of ALLEGRO_BITMAP* per overlay tile (may be NULL)
num_overlay_tiles number of overlay bitmaps (0 if none)
cam_px camera X offset in pixels (pre-snapped)
cam_py camera Y offset in pixels (pre-snapped)
zoom display zoom factor
screen_w current screen width in pixels
screen_h current screen height in pixels
player_mode 1 if in player mode (hover is green), 0 for editor (hover is yellow)
objects array of N_ISO_OBJECT to depth-sort with tiles (may be NULL)
num_objects number of objects in the array (0 if none)
Draw the full ISO_MAP with height, transitions, overlays, cliff walls, hover, and grid.
When segment data is available, tiles are decomposed into individual segments and sorted by (segment.bottom, my, mx). This allows multi-segment tiles (bridges, overhangs) to interleave correctly with ground-level tiles in the painter's algorithm.
Per-segment rendering order: Step 0: Underside face (floating segments only, 65% tint) Step 1: Cliff walls (between bottom and top) Step 2: Tile top surface (flat or warped for ground segments) Step 3: Terrain transitions (ground segments only) Step 3.5: Height borders (ground segments only, Phase 12c extends this) Step 4: Objects (depth-sorted, interleaved by segment sort key) Step 5: Hover highlight Step 6: Grid overlay Step 7 (post-loop): Occluded object overlays
Definition at line 2488 of file n_iso_engine.c.
References __n_assert, _compute_tile_tint(), _draw_height_borders(), _draw_segment_sides(), _draw_segment_underside(), _draw_tile_warped(), _iso_corner_to_screen(), _iso_object_check_occlusion(), ISO_MAP::ambient_b, ISO_MAP::ambient_g, ISO_MAP::ambient_r, ISO_DRAW_ENTRY::bottom, N_ISO_OBJECT::draw, ISO_MAP::dynamic_light_map, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, ISO_MAP::height, ISO_MAP::height_tint_intensity, ISO_MAP::hover_mx, ISO_MAP::hover_my, N_ISO_OBJECT::is_occluded, iso_map_build_draw_order(), iso_map_calc_transitions_full(), iso_map_get_height(), iso_map_get_terrain(), iso_map_smooth_corner_heights(), iso_map_to_screen(), iso_map_to_screen_f(), ISO_MAX_SEGMENTS_PER_TILE, ISO_NUM_EDGE_MASKS, key, LOG_ERR, ISO_TILE_SEGMENT::lower_tile, ISO_MAP::max_height, ISO_DRAW_ENTRY::mx, ISO_DRAW_ENTRY::my, n_log, ISO_MAP::num_terrains, ISO_MAP::overlay, player_mode, ISO_MAP::proj, screen_h, screen_w, ISO_DRAW_ENTRY::seg_idx, ISO_MAP::segments, ISO_TILE_SEGMENTS::segs, ISO_MAP::show_grid, ISO_MAP::smooth_height, ISO_MAP::smooth_slope_max, tile_bitmaps, ISO_PROJECTION::tile_lift, ISO_DRAW_ENTRY::top, transition_tiles, ISO_TILE_SEGMENT::upper_tile, and ISO_MAP::width.
Referenced by main().
iso_map_free()
void iso_map_free (ISO_MAP ** map_ptr)
free an ISO_MAP and set the pointer to NULL
free an ISO_MAP and set the pointer to NULL
Parameters
map_ptr pointer to the ISO_MAP pointer
Definition at line 680 of file n_iso_engine.c.
References __n_assert, ISO_MAP::ability, Free, ISO_MAP::heightmap, ISO_MAP::overlay, ISO_MAP::segments, and ISO_MAP::terrain.
Referenced by demo_iso_engine(), iso_map_load(), and main().
iso_map_get_ability()
int iso_map_get_ability (const ISO_MAP * map, int mx, int my)
get ability for a cell (bounds-checked)
get ability for a cell (bounds-checked)
Parameters
map the map
mx tile X
my tile Y
Returns
ability value (WALK/SWIM/BLCK), or 0 if out of bounds
Definition at line 859 of file n_iso_engine.c.
References __n_assert, ISO_MAP::ability, ISO_MAP::height, and ISO_MAP::width.
Referenced by demo_astar(), demo_iso_engine(), and print_map_ascii().
iso_map_get_height()
int iso_map_get_height (const ISO_MAP * map, int mx, int my)
get height for a cell (bounds-checked, clamped)
get height for a cell (bounds-checked, clamped)
Parameters
map the map
mx tile X
my tile Y
Returns
height value, or 0 if out of bounds
Definition at line 831 of file n_iso_engine.c.
References __n_assert, ISO_MAP::height, ISO_MAP::heightmap, and ISO_MAP::width.
Referenced by _draw_segment_sides(), _iso_object_check_occlusion(), _smooth_neighbor_h(), _tile_covers_height(), demo_astar(), demo_iso_engine(), interpolate_height_at_clamped(), iso_map_corner_heights(), iso_map_draw(), iso_map_get_visible_edges(), iso_map_get_visible_edges_segment(), iso_map_interpolate_height(), iso_map_should_transition_smooth(), iso_map_smooth_corner_heights(), iso_screen_to_map_height(), iso_screen_to_map_height_f(), main(), on_ghost_toggle(), on_player_toggle(), print_map_ascii(), and randomize_map().
iso_map_get_segments()
const ISO_TILE_SEGMENTS * iso_map_get_segments (const ISO_MAP * map, int mx, int my)
get per-tile segments.
Returns NULL if no segment data is set.
Definition at line 1501 of file n_iso_engine.c.
References ISO_MAP::height, ISO_MAP::segments, and ISO_MAP::width.
Referenced by _tile_covers_height(), and iso_map_get_visible_edges_segment().
iso_map_get_terrain()
int iso_map_get_terrain (const ISO_MAP * map, int mx, int my)
get terrain type for a cell (bounds-checked)
get terrain type for a cell (bounds-checked)
Parameters
map the map
mx tile X
my tile Y
Returns
terrain type, or 0 if out of bounds
Definition at line 805 of file n_iso_engine.c.
References __n_assert, ISO_MAP::height, ISO_MAP::terrain, and ISO_MAP::width.
Referenced by _draw_segment_sides(), demo_iso_engine(), iso_map_calc_transitions(), iso_map_calc_transitions_full(), iso_map_draw(), iso_map_should_transition(), main(), and print_map_ascii().
iso_map_get_visible_edges()
ISO_VISIBLE_EDGES iso_map_get_visible_edges (const ISO_MAP * map, int mx, int my)
Compute which diamond edges of tile (mx, my) need a height border.
An edge is marked for drawing when the neighbor in that direction has a height difference > 1 or is out of bounds. Edge-to-neighbor mapping (diamond iso layout): NW → (mx-1, my), NE → (mx, my-1), SE → (mx+1, my), SW → (mx, my+1)
Parameters
map the ISO_MAP
mx tile X coordinate
my tile Y coordinate
Returns
ISO_VISIBLE_EDGES with flags set
Compute which diamond edges of tile (mx, my) need a height border.
An edge is marked for drawing when the neighbor in that direction has a height difference > 1 or is out of bounds (map boundary).
Edge-to-neighbor mapping (diamond isometric layout): NW (N→W, top-left) → neighbor (mx-1, my) NE (N→E, top-right) → neighbor (mx, my-1) SE (E→S, bottom-right) → neighbor (mx+1, my) SW (S→W, bottom-left) → neighbor (mx, my+1)
Definition at line 1753 of file n_iso_engine.c.
References ISO_VISIBLE_EDGES::draw_ne, ISO_VISIBLE_EDGES::draw_nw, ISO_VISIBLE_EDGES::draw_se, ISO_VISIBLE_EDGES::draw_sw, ISO_MAP::height, iso_map_get_height(), ISO_MAP::neighbor_heights_east, ISO_MAP::neighbor_heights_north, ISO_MAP::neighbor_heights_south, ISO_MAP::neighbor_heights_west, and ISO_MAP::width.
iso_map_get_visible_edges_segment()
ISO_VISIBLE_EDGES iso_map_get_visible_edges_segment (const ISO_MAP * map, int mx, int my, int seg_idx)
Compute per-segment edge visibility for height border rendering.
Uses height-range overlap to determine adjacency: two segments are "touching" only if max(b1,b2) < min(t1,t2). A segment with no overlapping neighbour on a given side draws that edge. Floating segments (bottom > 0) also compute underside border visibility.
Parameters
map the ISO_MAP
mx tile X coordinate
my tile Y coordinate
seg_idx segment index within tile (0..count-1)
Returns
ISO_VISIBLE_EDGES with flags set (including draw_underside)
Compute per-segment edge visibility for height border rendering.
ADJACENCY (per edge direction): For ALL segments (ground and floating): draw edge if no neighbour segment has the same top height. Same top = connected surface = no border. Different top = visible height step = border drawn. Range overlap is NOT used — overlapping ranges with different tops (e.g. {10,12} vs {10,11}) still have a visible step at the top.
OCCLUSION (painter-order): NW and NE edges face away from the camera. A tile drawn later (further south in isometric order) can visually cover these edges.
NW edge occluded if SW neighbour (mx, my+1) covers seg.top
NE edge occluded if SE neighbour (mx+1, my) covers seg.top SE and SW edges face the camera — never explicitly occluded (painter order handles them automatically).
UNDERSIDE (floating segments only): draw_underside = 1 if bottom > 0 AND any side has the gap below exposed (no neighbour segment reaches up to seg.bottom).
topVertex is never set — the struct has no field for it.
Definition at line 1864 of file n_iso_engine.c.
References _tile_covers_height(), ISO_TILE_SEGMENT::bottom, ISO_TILE_SEGMENTS::count, ISO_VISIBLE_EDGES::draw_ne, ISO_VISIBLE_EDGES::draw_nw, ISO_VISIBLE_EDGES::draw_se, ISO_VISIBLE_EDGES::draw_sw, ISO_VISIBLE_EDGES::draw_underside, ISO_MAP::height, iso_map_get_height(), iso_map_get_segments(), ISO_MAP::neighbor_heights_east, ISO_MAP::neighbor_heights_north, ISO_MAP::neighbor_heights_south, ISO_MAP::neighbor_heights_west, ISO_VISIBLE_EDGES::neighbor_top_ne, ISO_VISIBLE_EDGES::neighbor_top_nw, ISO_VISIBLE_EDGES::neighbor_top_se, ISO_VISIBLE_EDGES::neighbor_top_sw, ISO_TILE_SEGMENTS::segs, ISO_TILE_SEGMENT::top, and ISO_MAP::width.
Referenced by _draw_height_borders().
iso_map_interpolate_height()
float iso_map_interpolate_height (const ISO_MAP * map, float fx, float fy)
bilinear height interpolation at fractional map coordinates
bilinear height interpolation at fractional map coordinates
Samples the 4 surrounding tile corners and interpolates for smooth terrain.
Parameters
map the map
fx fractional tile X (e.g. 3.5 = halfway between tile 3 and 4)
fy fractional tile Y
Returns
interpolated height value
Definition at line 1186 of file n_iso_engine.c.
References __n_assert, ISO_MAP::height, iso_map_get_height(), and ISO_MAP::width.
Referenced by demo_dead_reckoning(), demo_iso_engine(), interpolate_height_at(), and iso_screen_to_map_height_f().
iso_map_lerp_projection()
void iso_map_lerp_projection (ISO_MAP * map, float dt)
smoothly interpolate current projection angle toward target (call every frame)
smoothly interpolate current projection angle toward target (call every frame)
Updates half_h from the new angle; half_w and tile_lift are unchanged.
Parameters
map the map
dt time step in seconds (e.g. 1.0/60.0)
Definition at line 748 of file n_iso_engine.c.
References __n_assert, ISO_PROJECTION::angle_deg, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, ISO_PROJECTION::lerp_speed, M_PI, ISO_MAP::proj, and ISO_PROJECTION::target_angle.
Referenced by main().
iso_map_load()
ISO_MAP * iso_map_load (const char * filename)
load ISO_MAP from binary file
load ISO_MAP from binary file
Parameters
filename input file path
Returns
loaded ISO_MAP, or NULL on failure
Definition at line 1356 of file n_iso_engine.c.
References __n_assert, ISO_MAP::ability, ISO_MAP::height, ISO_MAP::heightmap, iso_map_free(), iso_map_new(), LOG_ERR, n_log, ISO_MAP::terrain, and ISO_MAP::width.
Referenced by demo_iso_engine(), and main().
iso_map_new()
ISO_MAP * iso_map_new (int width, int height, int num_terrains, int max_height)
create a new height-aware ISO_MAP with given dimensions
create a new height-aware ISO_MAP with given dimensions
Parameters
width map width in tiles
height map height in tiles
num_terrains number of terrain types
max_height maximum height value per cell
Returns
new ISO_MAP or NULL on failure
Definition at line 608 of file n_iso_engine.c.
References __n_assert, ISO_MAP::ability, ISO_MAP::ambient_b, ISO_MAP::ambient_g, ISO_MAP::ambient_r, ISO_MAP::dynamic_light_map, Free, ISO_MAP::height, ISO_MAP::height_tint_intensity, ISO_MAP::heightmap, ISO_MAP::hover_mx, ISO_MAP::hover_my, iso_map_set_projection(), ISO_PROJ_CLASSIC, Malloc, ISO_MAP::max_height, ISO_MAP::num_terrains, ISO_MAP::overlay, ISO_MAP::segments, ISO_MAP::show_grid, ISO_MAP::smooth_height, ISO_MAP::smooth_slope_max, ISO_MAP::terrain, WALK, and ISO_MAP::width.
Referenced by iso_map_load(), and main().
iso_map_randomize()
void iso_map_randomize (ISO_MAP * map)
randomize terrain and height for testing/demo purposes
randomize terrain and height for testing/demo purposes
Parameters
map the map
Definition at line 1410 of file n_iso_engine.c.
References __n_assert, ISO_MAP::ability, ISO_MAP::height, ISO_MAP::heightmap, ISO_MAP::max_height, ISO_MAP::num_terrains, ISO_MAP::terrain, WALK, and ISO_MAP::width.
iso_map_save()
int iso_map_save (const ISO_MAP * map, const char * filename)
save ISO_MAP to binary file (chunk-based format)
save ISO_MAP to binary file (chunk-based format)
Format: 4-byte magic "ISOM", then int32 fields: width, height, num_terrains, max_height, followed by terrain[], heightmap[], ability[].
Parameters
map the map
filename output file path
Returns
TRUE on success, FALSE on failure
Definition at line 1321 of file n_iso_engine.c.
References __n_assert, ISO_MAP::ability, ISO_MAP::height, ISO_MAP::heightmap, LOG_ERR, ISO_MAP::max_height, n_log, ISO_MAP::num_terrains, ISO_MAP::terrain, and ISO_MAP::width.
Referenced by demo_iso_engine(), main(), and on_reset_click().
iso_map_set_ability()
void iso_map_set_ability (ISO_MAP * map, int mx, int my, int ab)
set ability for a cell (bounds-checked)
set ability for a cell (bounds-checked)
Parameters
map the map
mx tile X
my tile Y
ab ability value (WALK/SWIM/BLCK)
Definition at line 872 of file n_iso_engine.c.
References __n_assert, ISO_MAP::ability, ISO_MAP::height, and ISO_MAP::width.
Referenced by build_test_map().
iso_map_set_height()
void iso_map_set_height (ISO_MAP * map, int mx, int my, int h)
set height for a cell (bounds-checked, clamped)
set height for a cell (bounds-checked, clamped)
Parameters
map the map
mx tile X
my tile Y
h height value
Definition at line 844 of file n_iso_engine.c.
References __n_assert, ISO_MAP::height, ISO_MAP::heightmap, ISO_MAP::max_height, and ISO_MAP::width.
Referenced by build_test_map(), main(), and randomize_map().
iso_map_set_projection()
void iso_map_set_projection (ISO_MAP * map, int preset, float tile_width)
set projection preset and snap to it immediately
set projection preset and snap to it immediately
Parameters
map the map
preset one of ISO_PROJ_CLASSIC, ISO_PROJ_ISOMETRIC, ISO_PROJ_STAGGERED, ISO_PROJ_MILITARY
tile_width full tile width in pixels (half_w = tile_width / 2)
Definition at line 717 of file n_iso_engine.c.
References __n_assert, _iso_preset_angle(), ISO_PROJECTION::angle_deg, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, ISO_PROJECTION::lerp_speed, M_PI, ISO_MAP::proj, ISO_PROJECTION::target_angle, and ISO_PROJECTION::tile_lift.
Referenced by iso_map_new(), and main().
iso_map_set_projection_custom()
void iso_map_set_projection_custom (ISO_MAP * map, float half_w, float half_h, float tile_lift)
set custom projection parameters directly
set custom projection parameters directly
Parameters
map the map
half_w half-width of tile diamond
half_h half-height of tile diamond
tile_lift vertical pixel offset per height unit
Definition at line 789 of file n_iso_engine.c.
References __n_assert, ISO_PROJECTION::angle_deg, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, M_PI, ISO_MAP::proj, ISO_PROJECTION::target_angle, and ISO_PROJECTION::tile_lift.
iso_map_set_projection_target()
void iso_map_set_projection_target (ISO_MAP * map, int preset)
set target projection preset for smooth interpolation via iso_map_lerp_projection
set target projection preset for smooth interpolation via iso_map_lerp_projection
Call iso_map_lerp_projection() each frame to animate toward it.
Parameters
map the map
preset one of ISO_PROJ_CLASSIC, ISO_PROJ_ISOMETRIC, ISO_PROJ_STAGGERED, ISO_PROJ_MILITARY
Definition at line 737 of file n_iso_engine.c.
References __n_assert, _iso_preset_angle(), ISO_MAP::proj, and ISO_PROJECTION::target_angle.
Referenced by main(), and on_proj_select().
iso_map_set_segments()
int iso_map_set_segments (ISO_MAP * map, int mx, int my, const ISO_TILE_SEGMENT * segs, int count)
set per-tile segments on an ISO_MAP.
Copies data into map->segments (allocated on first call). Also updates heightmap for the tile.
Parameters
map the ISO_MAP
mx tile X coordinate
my tile Y coordinate
segs array of segments (may be NULL if count==0)
count number of segments (0..ISO_MAX_SEGMENTS_PER_TILE)
Returns
1 on success, 0 if invariants violated or out of range
Definition at line 1467 of file n_iso_engine.c.
References __n_assert, ISO_TILE_SEGMENT::bottom, ISO_TILE_SEGMENTS::count, ISO_MAP::height, ISO_MAP::heightmap, ISO_MAX_SEGMENTS_PER_TILE, ISO_TILE_SEGMENT::lower_tile, Malloc, ISO_MAP::segments, ISO_TILE_SEGMENTS::segs, ISO_TILE_SEGMENT::top, ISO_TILE_SEGMENT::upper_tile, and ISO_MAP::width.
iso_map_set_terrain()
void iso_map_set_terrain (ISO_MAP * map, int mx, int my, int terrain)
set terrain type for a cell (bounds-checked)
set terrain type for a cell (bounds-checked)
Parameters
map the map
mx tile X
my tile Y
terrain terrain type index
Definition at line 818 of file n_iso_engine.c.
References __n_assert, ISO_MAP::height, ISO_MAP::terrain, and ISO_MAP::width.
Referenced by build_test_map(), main(), and randomize_map().
iso_map_should_transition()
int iso_map_should_transition (const ISO_MAP * map, int mx1, int my1, int mx2, int my2)
check if terrain blending should occur between two adjacent cells
check if terrain blending should occur between two adjacent cells
Parameters
map the map
mx1 first tile X
my1 first tile Y
mx2 second tile X
my2 second tile Y
Returns
1 if terrains differ (blending needed), 0 if same
Definition at line 1272 of file n_iso_engine.c.
References __n_assert, and iso_map_get_terrain().
iso_map_should_transition_smooth()
int iso_map_should_transition_smooth (const ISO_MAP * map, int mx1, int my1, int mx2, int my2)
check if terrain transition should render between two cells (height-aware)
check if terrain transition should render between two cells (height-aware)
In cut mode: only same-height tiles get transitions. In smooth mode: tiles within smooth_slope_max get transitions.
Returns
1 if transition should render, 0 otherwise
Definition at line 1567 of file n_iso_engine.c.
References __n_assert, iso_map_get_height(), ISO_MAP::smooth_height, and ISO_MAP::smooth_slope_max.
Referenced by iso_map_calc_transitions_full().
iso_map_smooth_corner_heights()
void iso_map_smooth_corner_heights (const ISO_MAP * map, int mx, int my, float * h_n, float * h_e, float * h_s, float * h_w)
compute smooth corner heights with slope clamping (for rendering)
compute smooth corner heights with slope clamping (for rendering)
Like iso_map_corner_heights but clamps neighbors that exceed smooth_slope_max to prevent slopes across cliffs.
Parameters
map the map (uses map->smooth_slope_max)
mx tile X
my tile Y
h_n output north corner
h_e output east corner
h_s output south corner
h_w output west corner
Definition at line 1445 of file n_iso_engine.c.
References __n_assert, _smooth_neighbor_h(), and iso_map_get_height().
Referenced by iso_map_draw().
iso_map_to_screen()
void iso_map_to_screen (const ISO_MAP * map, int mx, int my, int h, float * screen_x, float * screen_y)
convert map tile coordinates to screen pixel coordinates
convert map tile coordinates to screen pixel coordinates
Uses the standard diamond isometric formula: sx = (mx - my) * half_w + half_w sy = (mx + my) * half_h - h * tile_lift
Parameters
map the map (uses map->proj)
mx tile X
my tile Y
h height value at this tile
screen_x output X in pixels
screen_y output Y in pixels
Definition at line 890 of file n_iso_engine.c.
References __n_assert, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, ISO_MAP::proj, and ISO_PROJECTION::tile_lift.
Referenced by _iso_object_check_occlusion(), demo_iso_engine(), iso_map_draw(), iso_screen_to_map_height(), iso_screen_to_map_height_f(), and main().
iso_map_to_screen_f()
void iso_map_to_screen_f (const ISO_MAP * map, float fmx, float fmy, float h, float * screen_x, float * screen_y)
convert map tile coordinates to screen pixel coordinates (float version)
convert map tile coordinates to screen pixel coordinates (float version)
Maps fractional tile positions to world screen coordinates. Unlike iso_map_to_screen (which returns the bounding box top-left), this returns the actual diamond position: (mx, my) maps to the N vertex and (mx+0.5, my+0.5) maps to the diamond center.
Parameters
map the map (uses map->proj)
fmx fractional tile X
fmy fractional tile Y
h height value (float for smooth interpolation)
screen_x output X in pixels
screen_y output Y in pixels
Definition at line 931 of file n_iso_engine.c.
References __n_assert, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, ISO_MAP::proj, and ISO_PROJECTION::tile_lift.
Referenced by draw_player_object(), iso_map_draw(), main(), and on_player_toggle().
iso_mask_tile_to_diamond()
void iso_mask_tile_to_diamond (ALLEGRO_BITMAP * bmp, int tile_w, int tile_h)
Mask a tile bitmap to the isometric diamond shape.
Pixels outside the diamond are set to fully transparent (0,0,0,0).
Parameters
bmp the tile bitmap to mask
tile_w tile width in pixels
tile_h tile height in pixels
Definition at line 3020 of file n_iso_engine.c.
References __n_assert, and iso_is_in_diamond().
Referenced by main().
iso_projection_name()
const char * iso_projection_name (int preset)
get the display name for a projection preset
get the display name for a projection preset
Parameters
preset projection ID
Returns
static string with the projection name
Definition at line 767 of file n_iso_engine.c.
References ISO_PROJ_CLASSIC, ISO_PROJ_ISOMETRIC, ISO_PROJ_MILITARY, and ISO_PROJ_STAGGERED.
Referenced by main().
iso_screen_to_map()
void iso_screen_to_map (const ISO_MAP * map, float screen_x, float screen_y, int * mx, int * my)
convert screen pixel coordinates to map tile coordinates (flat, no height)
convert screen pixel coordinates to map tile coordinates (flat, no height)
Inverse of iso_map_to_screen (without height, assumes h=0). Uses the diamond center to find which tile a screen pixel belongs to.
Parameters
map the map (uses map->proj)
screen_x X in pixels
screen_y Y in pixels
mx output tile X
my output tile Y
Definition at line 908 of file n_iso_engine.c.
References __n_assert, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, and ISO_MAP::proj.
Referenced by demo_iso_engine().
iso_screen_to_map_height()
void iso_screen_to_map_height (const ISO_MAP * map, float screen_x, float screen_y, int tile_w, int tile_h, int * mx, int * my)
height-aware screen-to-map conversion with diamond hit testing.
Tests all heights from max_height down to 0, returns the topmost tile at the given screen position.
height-aware screen-to-map conversion with diamond hit testing.
Iterates from max_height down to 0, testing each height layer for a tile that matches the screen coordinates. Uses iso_is_in_diamond for precise pixel-level hit detection within the diamond boundary.
Parameters
map the map
screen_x world X coordinate (from camera screen-to-world)
screen_y world Y coordinate
tile_w tile width in pixels (for diamond test)
tile_h tile height in pixels (for diamond test)
mx output tile X
my output tile Y
Definition at line 1021 of file n_iso_engine.c.
References __n_assert, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, ISO_MAP::height, iso_is_in_diamond(), iso_map_get_height(), iso_map_to_screen(), ISO_MAP::max_height, ISO_MAP::proj, ISO_PROJECTION::tile_lift, and ISO_MAP::width.
Referenced by main().
iso_screen_to_map_height_f()
void iso_screen_to_map_height_f (const ISO_MAP * map, float screen_x, float screen_y, int tile_w, int tile_h, int * mx, int * my, float * out_fx, float * out_fy)
height-aware screen-to-map conversion returning fractional tile coordinates.
Like iso_screen_to_map_height but outputs the exact position within the tile via out_fx/out_fy (range: tile.x .. tile.x+1).
height-aware screen-to-map conversion returning fractional tile coordinates.
Works like iso_screen_to_map_height but additionally outputs the exact fractional tile position via out_fx/out_fy.
Parameters
map the iso map
screen_x world-space X
screen_y world-space Y
tile_w tile bitmap width in pixels (for diamond hit test)
tile_h tile bitmap height in pixels
mx receives integer tile X
my receives integer tile Y
out_fx receives fractional tile X (NULL-safe)
out_fy receives fractional tile Y (NULL-safe)
Definition at line 1077 of file n_iso_engine.c.
References __n_assert, ISO_PROJECTION::half_h, ISO_PROJECTION::half_w, ISO_MAP::height, iso_is_in_diamond(), iso_map_get_height(), iso_map_interpolate_height(), iso_map_to_screen(), ISO_MAP::max_height, ISO_MAP::proj, ISO_MAP::smooth_height, ISO_PROJECTION::tile_lift, and ISO_MAP::width.
Referenced by main().
load_map()
int load_map (MAP ** map, char * filename)
Load the map.
Load the map.
Parameters
map A MAP *pointer to point on the loaded map
filename The filename of the map to load
Returns
TRUE or FALSE
Definition at line 436 of file n_iso_engine.c.
References create_empty_map(), free_map(), LOG_ERR, and n_log.
n_iso_camera_center_on()
void n_iso_camera_center_on (N_ISO_CAMERA * cam, float world_x, float world_y, int screen_w, int screen_h)
Center the camera so that a world point is at screen center.
Parameters
cam the camera
world_x world X to center on
world_y world Y to center on
screen_w viewport width in pixels
screen_h viewport height in pixels
Definition at line 1696 of file n_iso_engine.c.
References __n_assert, screen_h, screen_w, N_ISO_CAMERA::x, N_ISO_CAMERA::y, and N_ISO_CAMERA::zoom.
Referenced by main(), and on_player_toggle().
n_iso_camera_follow()
void n_iso_camera_follow (N_ISO_CAMERA * cam, float target_x, float target_y, int screen_w, int screen_h, float smoothing, float dt)
Smoothly follow a world-space target (camera lerp).
Parameters
cam the camera
target_x target world X
target_y target world Y
screen_w viewport width
screen_h viewport height
smoothing lerp speed factor (higher = snappier, e.g. 8.0)
dt time step in seconds
Smoothly follow a world-space target (camera lerp).
Definition at line 1705 of file n_iso_engine.c.
References __n_assert, screen_h, screen_w, N_ISO_CAMERA::x, N_ISO_CAMERA::y, and N_ISO_CAMERA::zoom.
Referenced by main().
n_iso_camera_free()
void n_iso_camera_free (N_ISO_CAMERA ** cam)
Free a camera and set the pointer to NULL.
Definition at line 1663 of file n_iso_engine.c.
References __n_assert, and Free.
Referenced by main().
n_iso_camera_new()
N_ISO_CAMERA * n_iso_camera_new (float zoom_min, float zoom_max)
Create a new camera with the given zoom limits.
Parameters
zoom_min minimum zoom factor (e.g. 0.5)
zoom_max maximum zoom factor (e.g. 6.0)
Returns
new camera, or NULL on failure
Create a new camera with the given zoom limits.
Definition at line 1648 of file n_iso_engine.c.
References __n_assert, Malloc, N_ISO_CAMERA::x, N_ISO_CAMERA::y, N_ISO_CAMERA::zoom, N_ISO_CAMERA::zoom_max, and N_ISO_CAMERA::zoom_min.
Referenced by main().
n_iso_camera_screen_to_world()
void n_iso_camera_screen_to_world (const N_ISO_CAMERA * cam, float sx, float sy, float * wx, float * wy)
Convert screen pixel coordinates to world coordinates.
Parameters
cam the camera
sx screen X
sy screen Y
wx output world X
wy output world Y
Definition at line 1718 of file n_iso_engine.c.
References __n_assert, N_ISO_CAMERA::x, N_ISO_CAMERA::y, and N_ISO_CAMERA::zoom.
Referenced by main().
n_iso_camera_scroll()
void n_iso_camera_scroll (N_ISO_CAMERA * cam, float dx, float dy)
Scroll the camera by (dx, dy) world units.
Definition at line 1671 of file n_iso_engine.c.
References __n_assert, N_ISO_CAMERA::x, and N_ISO_CAMERA::y.
Referenced by main().
n_iso_camera_world_to_screen()
void n_iso_camera_world_to_screen (const N_ISO_CAMERA * cam, float wx, float wy, float * sx, float * sy)
Convert world coordinates to screen pixel coordinates.
Parameters
cam the camera
wx world X
wy world Y
sx output screen X
sy output screen Y
Definition at line 1729 of file n_iso_engine.c.
References __n_assert, N_ISO_CAMERA::x, N_ISO_CAMERA::y, and N_ISO_CAMERA::zoom.
Referenced by draw_ghost_object(), and draw_player_object().
n_iso_camera_zoom()
void n_iso_camera_zoom (N_ISO_CAMERA * cam, float dz, float mouse_x, float mouse_y)
Zoom the camera toward a screen-space point (e.g.
mouse cursor).
Parameters
cam the camera
dz zoom delta (positive = zoom in)
mouse_x screen X of zoom pivot
mouse_y screen Y of zoom pivot
Zoom the camera toward a screen-space point (e.g.
Adjusts the camera position so the world point under the mouse stays fixed on screen after zooming.
Definition at line 1682 of file n_iso_engine.c.
References __n_assert, N_ISO_CAMERA::x, N_ISO_CAMERA::y, N_ISO_CAMERA::zoom, N_ISO_CAMERA::zoom_max, and N_ISO_CAMERA::zoom_min.
Referenced by main().
save_map()
int save_map (MAP * map, char * filename)
Save the map.
Save the map.
Parameters
map A MAP *pointer
filename The filename of the file where to save the map
Returns
TRUE or FALSE
Definition at line 522 of file n_iso_engine.c.
References CELL::ability, MAP::bgcolor, MAP::grid, LOG_ERR, CELL::music, n_log, MAP::name, CELL::objectnumber, MAP::ptanchorX, MAP::ptanchorY, MAP::TILEH, CELL::tilenumber, MAP::TILEW, MAP::wirecolor, MAP::X, MAP::XSIZE, MAP::Y, and MAP::YSIZE.
ScreenToMap()
int ScreenToMap (int mx, int my, int * Tilex, int * Tiley, ALLEGRO_BITMAP * mousemap)
Convert screen coordinate to map coordinate.
Parameters
mx The 'x' coordinate in pixel
my The 'y' coordinate in pixel
Tilex Output for the generated Tilex
Tiley Output for the generated Tiley
mousemap A mousemap with colors for one tile
Returns
TRUE
Definition at line 227 of file n_iso_engine.c.
set_value()
int set_value (MAP * map, int type, int x, int y, int value)
Set the tilenumber of a cell.
Set the tilenumber of a cell.
Parameters
map A MAP *map to 'touch'
type It is the type of value to change , it can be N_TILE,N_ABILITY,N_MUSIC,N_OBJECT
x X coordinate of the cell
y Y coordinate of the cell
value Value to give to the cell
Returns
TRUE or FALSE
Definition at line 159 of file n_iso_engine.c.
References CELL::ability, MAP::grid, CELL::music, N_ABILITY, N_MUSIC, N_OBJECT, N_TILE, CELL::objectnumber, CELL::tilenumber, MAP::XSIZE, and MAP::YSIZE.
Referenced by create_empty_map().