Nilorea Library: GUI: allegro5 widget system with pseudo-windows
GUI: allegro5 widget system with pseudo-windows
Data Structures
struct N_GUI_BUTTON_DATA
button specific data
struct N_GUI_CHECKBOX_DATA
checkbox specific data
struct N_GUI_COMBOBOX_DATA
combo box specific data
struct N_GUI_CTX
The top-level GUI context that holds all windows.
struct N_GUI_DROPMENU_DATA
dropdown menu specific data
struct N_GUI_DROPMENU_ENTRY
A single entry in a dropdown menu (static or dynamic)
struct N_GUI_IMAGE_DATA
image widget specific data
struct N_GUI_KV_ROW
a single row in the KV table
struct N_GUI_KVTABLE
key-value table built from textareas, checkboxes, and buttons
struct N_GUI_LABEL_DATA
static text label specific data
struct N_GUI_LISTBOX_DATA
listbox specific data
struct N_GUI_LISTITEM
a single item in a list/radio/combo widget
struct N_GUI_PENDING_GEOM
A saved window position retained for a window not yet created at load time (see N_GUI_CTX::pending_layout).
struct N_GUI_RADIOLIST_DATA
radio list specific data
struct N_GUI_SCROLLBAR_DATA
scrollbar specific data
struct N_GUI_SECTION
a single foldable section: a clickable header plus the member widgets it shows/hides
struct N_GUI_SECTIONLIST
a vertical accordion of foldable sections inside one window; folding hides a section's widgets and re-stacks the rest, leaving the window's N_GUI_WIN_AUTO_SCROLLBAR to absorb any overflow
struct N_GUI_SLIDER_DATA
slider specific data
struct N_GUI_STYLE
Global style holding every configurable layout constant.
struct N_GUI_TAB_PANEL
tab panel built from toggle buttons with content window management
struct N_GUI_TB_BUTTONS
Titlebar button state for a window (minimize, maximize, close)
struct N_GUI_TEXT_DIMS
bounding box dimensions returned by n_gui_get_text_dims()
struct N_GUI_TEXTAREA_DATA
text area specific data
struct N_GUI_THEME
Color theme for a widget.
struct N_GUI_TREE
tree view built from an N_GUI listbox
struct N_GUI_TREE_NODE
a single node in the tree view
struct N_GUI_WIDGET
A single GUI widget.
struct N_GUI_WINDOW
A pseudo window that contains widgets.
Macros
#define N_GUI_ALIGN_CENTER 1
center aligned text
#define N_GUI_ALIGN_JUSTIFIED 3
justified text (spread words to fill width)
#define N_GUI_ALIGN_LEFT 0
left aligned text
#define N_GUI_ALIGN_RIGHT 2
right aligned text
#define N_GUI_AUTOFIT_CENTER 16
center the window on its insertion point after auto-fit (overrides EXPAND_LEFT/EXPAND_UP for centering)
#define N_GUI_AUTOFIT_EXPAND_LEFT 4
expand leftward instead of rightward when adjusting width
#define N_GUI_AUTOFIT_EXPAND_UP 8
expand upward instead of downward when adjusting height
#define N_GUI_AUTOFIT_H 2
auto-adjust window height to content
#define N_GUI_AUTOFIT_W 1
auto-adjust window width to content
#define N_GUI_AUTOFIT_WH 3
auto-adjust both width and height (convenience: W|H)
#define N_GUI_COMBOBOX_AUTO_WIDTH 1
dropdown panel expands to fit the longest item text
#define N_GUI_COMBOBOX_EXPAND_UP 2
dropdown panel opens upward (above the widget) instead of downward.
#define N_GUI_DROP_AFTER 2
#define N_GUI_DROP_BEFORE 0
drop position relative to a tree row (drag-and-drop)
#define N_GUI_DROP_INTO 1
#define N_GUI_DROPMENU_EXPAND_UP 1
dropdown panel opens upward (above the button) instead of downward.
#define N_GUI_ID_MAX 128
maximum length for widget id/name strings
#define N_GUI_IMAGE_CENTER 2
draw at original size, centered
#define N_GUI_IMAGE_FIT 0
scale to fit within bounds, keep aspect ratio
#define N_GUI_IMAGE_STRETCH 1
stretch to fill bounds
#define N_GUI_KEY_MOD_MASK (ALLEGRO_KEYMOD_SHIFT | ALLEGRO_KEYMOD_CTRL | ALLEGRO_KEYMOD_ALT | ALLEGRO_KEYMOD_ALTGR)
mask of supported modifier flags for button keybind matching
#define N_GUI_KEY_SOURCES_MAX 8
maximum number of source widgets for a focused key binding
#define N_GUI_KV_MAX 128
maximum number of rows in a KV table
#define N_GUI_RESIZE_ADAPTIVE 1
virtual size tracks display; windows adapt per their resize_policy
#define N_GUI_RESIZE_VIRTUAL 0
fixed virtual canvas with uniform scaling (default/existing behavior)
#define N_GUI_SCROLLBAR_H 0
horizontal scrollbar
#define N_GUI_SCROLLBAR_V 1
vertical scrollbar
#define N_GUI_SECTION_WIDGETS_MAX 48
maximum number of member widgets per section
#define N_GUI_SECTIONLIST_MAX 16
maximum number of foldable sections in a section list
#define N_GUI_SELECT_MULTIPLE 2
multiple item selection
#define N_GUI_SELECT_NONE 0
no selection allowed (display only)
#define N_GUI_SELECT_SINGLE 1
single item selection
#define N_GUI_SHAPE_BITMAP 2
bitmap-based rendering
#define N_GUI_SHAPE_RECT 0
rectangle shape (default)
#define N_GUI_SHAPE_ROUNDED 1
rounded rectangle shape
#define N_GUI_SLIDER_H 0
horizontal slider (default)
#define N_GUI_SLIDER_PERCENT 1
slider uses 0-100 percentage
#define N_GUI_SLIDER_V 1
vertical slider
#define N_GUI_SLIDER_VALUE 0
slider uses raw start/end values
#define N_GUI_STATE_ACTIVE 2
widget is being pressed / dragged
#define N_GUI_STATE_FOCUSED 4
widget has keyboard focus
#define N_GUI_STATE_HOVER 1
mouse is hovering the widget
#define N_GUI_STATE_IDLE 0
widget is idle / normal state
#define N_GUI_STATE_SCROLLBAR_DRAG 8
widget scrollbar is being dragged
#define N_GUI_TAB_MAX 16
maximum number of tabs in a single tab panel
#define N_GUI_TB_BTN_CLOSE 3
close titlebar button
#define N_GUI_TB_BTN_MAXIMIZE 2
maximize/restore titlebar button
#define N_GUI_TB_BTN_MINIMIZE 1
minimize titlebar button
#define N_GUI_TB_BTN_NONE 0
no titlebar button
#define N_GUI_TEXT_MAX 4096
maximum length for textarea content
#define N_GUI_TREE_MAX 2048
maximum number of nodes in a tree view
#define N_GUI_TYPE_BUTTON 1
widget type: button
#define N_GUI_TYPE_CHECKBOX 4
widget type: checkbox
#define N_GUI_TYPE_COMBOBOX 8
widget type: combo box (dropdown)
#define N_GUI_TYPE_DROPMENU 11
widget type: dropdown menu with static and dynamic entries
#define N_GUI_TYPE_IMAGE 9
widget type: image display
#define N_GUI_TYPE_LABEL 10
widget type: static text label (with optional hyperlink)
#define N_GUI_TYPE_LISTBOX 6
widget type: listbox (selectable list)
#define N_GUI_TYPE_RADIOLIST 7
widget type: radio list (single select radio buttons)
#define N_GUI_TYPE_SCROLLBAR 5
widget type: scrollbar
#define N_GUI_TYPE_SLIDER 2
widget type: slider
#define N_GUI_TYPE_TEXTAREA 3
widget type: text area
#define N_GUI_WIN_AUTO_SCROLLBAR 16
enable automatic scrollbars when content exceeds window size
#define N_GUI_WIN_BTN_ALL (N_GUI_WIN_BTN_MINIMIZE | N_GUI_WIN_BTN_MAXIMIZE | N_GUI_WIN_BTN_CLOSE)
enable all three title bar buttons (minimize + maximize + close)
#define N_GUI_WIN_BTN_CLOSE 1024
enable close button on the title bar
#define N_GUI_WIN_BTN_MAXIMIZE 512
enable maximize/restore button on the title bar
#define N_GUI_WIN_BTN_MINIMIZE 256
enable minimize button on the title bar
#define N_GUI_WIN_DRAGGING 4
window is being dragged
#define N_GUI_WIN_FIXED_POSITION 64
disable window dragging (default:enable)
#define N_GUI_WIN_FRAMELESS 128
frameless window: no title bar drawn, drag via window body unless N_GUI_WIN_FIXED_POSITION is also set
#define N_GUI_WIN_HSCROLL_DRAG 32
window horizontal auto-scrollbar is being dragged
#define N_GUI_WIN_MAXIMISED 64
window is maximised (full display size)
#define N_GUI_WIN_MINIMISED 2
window is minimised (title bar only)
#define N_GUI_WIN_OPEN 1
window is visible
#define N_GUI_WIN_RESIZABLE 32
enable user-resizable window with a drag handle at bottom-right
#define N_GUI_WIN_RESIZE_MOVE 1
reposition proportionally, keep pixel size
#define N_GUI_WIN_RESIZE_NONE 0
no adaptation: absolute position and size unchanged
#define N_GUI_WIN_RESIZE_SCALE 2
reposition AND resize proportionally, child widgets scale too
#define N_GUI_WIN_RESIZING 8
window is being resized
#define N_GUI_WIN_VSCROLL_DRAG 16
window vertical auto-scrollbar is being dragged
#define N_GUI_ZORDER_ALWAYS_BEHIND 2
always drawn behind normal windows, cannot be raised above them
#define N_GUI_ZORDER_ALWAYS_ON_TOP 1
always drawn on top of normal windows, cannot be lowered behind them
#define N_GUI_ZORDER_FIXED 3
fixed z-value: window is sorted within a dedicated group between ALWAYS_BEHIND and NORMAL windows.
#define N_GUI_ZORDER_NORMAL 0
default z-order: window participates in normal raise/lower ordering
#define N_GUI_ZORDER_POPUP 4
popup/modal dialogs: drawn above EVERYTHING including ALWAYS_ON_TOP windows.
Typedefs
typedef int(* n_gui_tree_on_drop_t) (int src_node, int dst_node, int position, void *user_data)
drag-reorder drop callback.
Functions
int n_gui_add_button (N_GUI_CTX *ctx, int window_id, const char *label, float x, float y, float w, float h, int shape, void(*on_click)(int, void *), void *user_data)
add a button widget
int n_gui_add_button_bitmap (N_GUI_CTX *ctx, int window_id, const char *label, float x, float y, float w, float h, ALLEGRO_BITMAP *normal, ALLEGRO_BITMAP *hover, ALLEGRO_BITMAP *active, void(*on_click)(int, void *), void *user_data)
add a bitmap-based button widget
int n_gui_add_checkbox (N_GUI_CTX *ctx, int window_id, const char *label, float x, float y, float w, float h, int initial_checked, void(*on_toggle)(int, int, void *), void *user_data)
add a checkbox widget
int n_gui_add_combobox (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, void(*on_select)(int, int, void *), void *user_data)
add a combo box widget
int n_gui_add_dropmenu (N_GUI_CTX *ctx, int window_id, const char *label, float x, float y, float w, float h, void(*on_open)(int, void *), void *on_open_user_data)
add a dropdown menu widget (button that opens a menu panel with entries)
int n_gui_add_image (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, ALLEGRO_BITMAP *bitmap, int scale_mode)
add an image widget
int n_gui_add_label (N_GUI_CTX *ctx, int window_id, const char *text, float x, float y, float w, float h, int align)
add a text label widget
int n_gui_add_label_link (N_GUI_CTX *ctx, int window_id, const char *text, const char *link, float x, float y, float w, float h, int align, void(*on_link_click)(int, const char *, void *), void *user_data)
add a text label with hyperlink
int n_gui_add_listbox (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, int selection_mode, void(*on_select)(int, int, int, void *), void *user_data)
add a listbox widget
int n_gui_add_radiolist (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, void(*on_select)(int, int, void *), void *user_data)
add a radio list widget
int n_gui_add_scrollbar (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, int orientation, int shape, double content_size, double viewport_size, void(*on_scroll)(int, double, void *), void *user_data)
add a scrollbar widget
int n_gui_add_slider (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, double min_val, double max_val, double initial, int mode, void(*on_change)(int, double, void *), void *user_data)
add a horizontal slider widget
int n_gui_add_textarea (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, int multiline, size_t char_limit, void(*on_change)(int, const char *, void *), void *user_data)
add a text area widget
int n_gui_add_toggle_button (N_GUI_CTX *ctx, int window_id, const char *label, float x, float y, float w, float h, int shape, int initial_state, void(*on_click)(int, void *), void *user_data)
toggle button creation (returns widget id)
int n_gui_add_vslider (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, double min_val, double max_val, double initial, int mode, void(*on_change)(int, double, void *), void *user_data)
add a vertical slider (same as n_gui_add_slider but oriented vertically)
int n_gui_add_window (N_GUI_CTX *ctx, const char *title, float x, float y, float w, float h)
add a window to the GUI context
int n_gui_add_window_auto (N_GUI_CTX *ctx, const char *title, float x, float y)
add a window that sizes itself automatically to fit its widgets (call n_gui_window_autosize after adding all widgets)
void n_gui_apply_adaptive_resize (N_GUI_CTX *ctx, float new_w, float new_h)
apply adaptive resize: reposition/resize all windows according to their policies for the new display dimensions.
int n_gui_button_is_toggled (N_GUI_CTX *ctx, int widget_id)
check if button is toggled
void n_gui_button_set_keycode (N_GUI_CTX *ctx, int widget_id, int keycode, int modifiers)
bind a keyboard key with optional modifier requirements to a button.
void n_gui_button_set_keycode_focused (N_GUI_CTX *ctx, int widget_id, int keycode, int modifiers, const int *sources, int source_count)
bind a keyboard key to a button that fires only when specific widgets have focus.
void n_gui_button_set_label (N_GUI_CTX *ctx, int widget_id, const char *label)
replace the label text drawn on a button
void n_gui_button_set_state_bitmaps (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *normal, ALLEGRO_BITMAP *hover, ALLEGRO_BITMAP *active)
skin a button or toggle button with caller-owned per-state bitmaps (switches its shape to N_GUI_SHAPE_BITMAP; toggled-on renders active)
void n_gui_button_set_toggle_mode (N_GUI_CTX *ctx, int widget_id, int toggle_mode)
set button toggle mode
void n_gui_button_set_toggled (N_GUI_CTX *ctx, int widget_id, int toggled)
set button toggled state
int n_gui_checkbox_is_checked (N_GUI_CTX *ctx, int widget_id)
check if checkbox is checked
void n_gui_checkbox_set_bitmaps (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *box, ALLEGRO_BITMAP *box_checked, ALLEGRO_BITMAP *box_hover)
set optional bitmap overlays on a checkbox widget.
void n_gui_checkbox_set_checked (N_GUI_CTX *ctx, int widget_id, int checked)
set checkbox checked state
void n_gui_close_window (N_GUI_CTX *ctx, int window_id)
close (hide) a window
int n_gui_combobox_add_item (N_GUI_CTX *ctx, int widget_id, const char *text)
add an item to a combo box
void n_gui_combobox_clear (N_GUI_CTX *ctx, int widget_id)
remove all items from a combobox
const char * n_gui_combobox_get_item_text (N_GUI_CTX *ctx, int widget_id, int index)
get the text of the combobox item at index ("" if out of range / not a combobox)
int n_gui_combobox_get_selected (N_GUI_CTX *ctx, int widget_id)
get the selected item index
void n_gui_combobox_set_bitmaps (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *bg, ALLEGRO_BITMAP *item_bg, ALLEGRO_BITMAP *item_selected)
set optional bitmap overlays on a combobox widget.
void n_gui_combobox_set_flags (N_GUI_CTX *ctx, int widget_id, int flags)
set combobox feature flags (bitmask of N_GUI_COMBOBOX_* values)
void n_gui_combobox_set_selected (N_GUI_CTX *ctx, int widget_id, int index)
set the selected item index
N_GUI_STYLE n_gui_default_style (void)
return the built-in default style
N_GUI_THEME n_gui_default_tb_btn_theme (void)
return the built-in default theme for titlebar minimize/maximize buttons
N_GUI_THEME n_gui_default_tb_close_theme (void)
return the built-in default theme for the titlebar close button (red hover/active)
N_GUI_THEME n_gui_default_theme (void)
return the built-in default theme
void n_gui_destroy_ctx (N_GUI_CTX **ctx)
destroy a GUI context and free all resources
float n_gui_detect_dpi_scale (N_GUI_CTX *ctx, ALLEGRO_DISPLAY *display)
detect and apply DPI scale from the given allegro display.
void n_gui_draw (N_GUI_CTX *ctx)
draw all visible GUI windows and widgets
int n_gui_dropmenu_add_dynamic_entry (N_GUI_CTX *ctx, int widget_id, const char *text, int tag, void(*on_click)(int, int, int, void *), void *user_data)
add a dynamic entry (rebuilt each time menu opens)
int n_gui_dropmenu_add_entry (N_GUI_CTX *ctx, int widget_id, const char *text, int tag, void(*on_click)(int, int, int, void *), void *user_data)
add a static entry to a dropdown menu
void n_gui_dropmenu_clear (N_GUI_CTX *ctx, int widget_id)
remove all entries
void n_gui_dropmenu_clear_dynamic (N_GUI_CTX *ctx, int widget_id)
remove all dynamic entries (call from on_open callback before re-adding)
int n_gui_dropmenu_get_count (N_GUI_CTX *ctx, int widget_id)
get number of entries
void n_gui_dropmenu_set_bitmaps (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *panel, ALLEGRO_BITMAP *item_hover)
set optional bitmap overlays on a dropmenu widget.
void n_gui_dropmenu_set_entry_text (N_GUI_CTX *ctx, int widget_id, int index, const char *text)
update text of an existing entry by index
void n_gui_dropmenu_set_flags (N_GUI_CTX *ctx, int widget_id, int flags)
set dropmenu feature flags (bitmask of N_GUI_DROPMENU_* values)
void n_gui_focus_window (N_GUI_CTX *ctx, int window_id)
give a window keyboard focus: raise it within its z-order group and focus its first focusable widget (clears focus if it has none)
float n_gui_get_dpi_scale (const N_GUI_CTX *ctx)
get current DPI scale factor
int n_gui_get_resize_mode (N_GUI_CTX *ctx)
get current resize mode
N_GUI_TEXT_DIMS n_gui_get_text_dims (ALLEGRO_FONT *font, const char *text)
get the bounding box dimensions of text rendered with the given font.
int n_gui_get_topmost_open_window (const N_GUI_CTX *ctx)
get the id of the frontmost open, non-minimized window (the last one in draw order), or -1 if no window is open.
N_GUI_WIDGET * n_gui_get_widget (N_GUI_CTX *ctx, int widget_id)
get a widget by id
N_GUI_WINDOW * n_gui_get_window (N_GUI_CTX *ctx, int window_id)
get a window by id
void n_gui_image_set_bitmap (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *bitmap)
set the bitmap on an image widget
int n_gui_is_widget_enabled (N_GUI_CTX *ctx, int widget_id)
check if a widget is enabled
int n_gui_kvtable_add_row (N_GUI_KVTABLE *table, const char *key, const char *value, const char *description, int enabled)
add a row to the KV table
N_GUI_KVTABLE * n_gui_kvtable_create (N_GUI_CTX *ctx, int window_id, float row_height, float padding, void(*on_remove)(int, void *), void *user_data)
create a KV table in an existing window
void n_gui_kvtable_free (N_GUI_KVTABLE **table)
free a KV table (does not destroy the N_GUI widgets)
int n_gui_kvtable_get_count (N_GUI_KVTABLE *table)
get the number of active rows
void n_gui_kvtable_relayout (N_GUI_KVTABLE *table)
re-apply layout to all KV table widgets (positions, sizes, normalized coords).
void n_gui_kvtable_remove_row (N_GUI_KVTABLE *table, int row_index)
remove a row by index (hides widgets, marks inactive)
void n_gui_label_set_bitmap (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *bg)
set optional background bitmap on a label widget.
void n_gui_label_set_link (N_GUI_CTX *ctx, int widget_id, const char *link)
set label hyperlink URL
void n_gui_label_set_text (N_GUI_CTX *ctx, int widget_id, const char *text)
set label text content
int n_gui_listbox_add_item (N_GUI_CTX *ctx, int widget_id, const char *text)
add an item to a listbox
void n_gui_listbox_clear (N_GUI_CTX *ctx, int widget_id)
clear all items from a listbox
int n_gui_listbox_get_count (N_GUI_CTX *ctx, int widget_id)
get number of items in a listbox
const char * n_gui_listbox_get_item_text (N_GUI_CTX *ctx, int widget_id, int index)
get item text by index
int n_gui_listbox_get_scroll_offset (N_GUI_CTX *ctx, int widget_id)
get the current scroll offset (in items)
int n_gui_listbox_get_selected (N_GUI_CTX *ctx, int widget_id)
get the first selected item index
int n_gui_listbox_is_selected (N_GUI_CTX *ctx, int widget_id, int index)
check if an item is selected
int n_gui_listbox_remove_item (N_GUI_CTX *ctx, int widget_id, int index)
remove an item from a listbox by index
void n_gui_listbox_set_bitmaps (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *bg, ALLEGRO_BITMAP *item_bg, ALLEGRO_BITMAP *item_selected)
set optional bitmap overlays on a listbox widget.
void n_gui_listbox_set_scroll_offset (N_GUI_CTX *ctx, int widget_id, int offset)
set the scroll offset (in items), clamps to valid range
void n_gui_listbox_set_selected (N_GUI_CTX *ctx, int widget_id, int index, int selected)
set item selection state
int n_gui_load_layout_json (N_GUI_CTX *ctx, const char *filepath)
Load a JSON window layout file and apply it to matching windows in the context.
int n_gui_load_theme_json (N_GUI_CTX *ctx, const char *filepath)
Load a JSON theme file and apply it to the context.
void n_gui_lower_window (N_GUI_CTX *ctx, int window_id)
lower a window to the bottom of the stack (respects z-order constraints)
N_GUI_THEME n_gui_make_theme (ALLEGRO_COLOR bg, ALLEGRO_COLOR bg_hover, ALLEGRO_COLOR bg_active, ALLEGRO_COLOR border, ALLEGRO_COLOR border_hover, ALLEGRO_COLOR border_active, ALLEGRO_COLOR text, ALLEGRO_COLOR text_hover, ALLEGRO_COLOR text_active, float border_thickness, float corner_rx, float corner_ry)
create a custom theme from individual colors and properties
void n_gui_maximize_window (N_GUI_CTX *ctx, int window_id)
toggle maximised state (full display or restore to previous size)
void n_gui_minimize_window (N_GUI_CTX *ctx, int window_id)
minimize a window (title bar only)
N_GUI_CTX * n_gui_new_ctx (ALLEGRO_FONT *default_font)
create a new GUI context
void n_gui_open_window (N_GUI_CTX *ctx, int window_id)
open (show) a window
int n_gui_process_event (N_GUI_CTX *ctx, ALLEGRO_EVENT event)
process an allegro event for the GUI
int n_gui_radiolist_add_item (N_GUI_CTX *ctx, int widget_id, const char *text)
add an item to a radio list
void n_gui_radiolist_clear (N_GUI_CTX *ctx, int widget_id)
remove all items from a radio list
int n_gui_radiolist_get_selected (N_GUI_CTX *ctx, int widget_id)
get the selected item index
void n_gui_radiolist_set_bitmaps (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *bg, ALLEGRO_BITMAP *item_bg, ALLEGRO_BITMAP *item_selected)
set optional bitmap overlays on a radiolist widget.
void n_gui_radiolist_set_selected (N_GUI_CTX *ctx, int widget_id, int index)
set the selected item index
void n_gui_raise_window (N_GUI_CTX *ctx, int window_id)
raise a window to the top of the stack (respects z-order constraints)
void n_gui_reset_all_widget_themes (N_GUI_CTX *ctx)
reset all widget and window themes to ctx->default_theme
int n_gui_save_layout_json (N_GUI_CTX *ctx, const char *filepath)
Save the geometry + persistent state of every window in the context to a JSON file.
int n_gui_save_theme_json (N_GUI_CTX *ctx, const char *filepath)
Save the full theme (default_theme + style) to a JSON file.
void n_gui_screen_to_virtual (const N_GUI_CTX *ctx, float sx, float sy, float *vx, float *vy)
convert physical screen coordinates to virtual canvas coordinates.
double n_gui_scrollbar_get_pos (N_GUI_CTX *ctx, int widget_id)
get scrollbar position
void n_gui_scrollbar_set_bitmaps (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *track, ALLEGRO_BITMAP *thumb, ALLEGRO_BITMAP *thumb_hover, ALLEGRO_BITMAP *thumb_active)
set optional bitmap overlays on a scrollbar widget.
void n_gui_scrollbar_set_pos (N_GUI_CTX *ctx, int widget_id, double pos)
set scrollbar position
void n_gui_scrollbar_set_sizes (N_GUI_CTX *ctx, int widget_id, double content_size, double viewport_size)
set scrollbar content and viewport sizes
int n_gui_sectionlist_add_section (N_GUI_SECTIONLIST *sl, const char *title, float header_y, int folded)
add a section with a header button at header_y (members added next are captured relative to it); returns the section index or -1
void n_gui_sectionlist_add_widget (N_GUI_SECTIONLIST *sl, int section_index, int widget_id)
register an existing widget as a member of a section (captures its current y as the fold offset)
float n_gui_sectionlist_content_height (const N_GUI_SECTIONLIST *sl)
total content height in pixels under the current fold state, for sizing/scrolling the host window
N_GUI_SECTIONLIST * n_gui_sectionlist_create (N_GUI_CTX *ctx, int window_id, float x, float y0, float width, float header_h, float gap, void(*on_toggle)(int, int, void *), void *user_data)
create an empty section list anchored at (x,y0) in window_id; sections stack downward from y0
void n_gui_sectionlist_free (N_GUI_SECTIONLIST **sl)
free the section list (does not destroy the N_GUI widgets or window)
int n_gui_sectionlist_get_count (const N_GUI_SECTIONLIST *sl)
number of sections in the list
int n_gui_sectionlist_is_folded (const N_GUI_SECTIONLIST *sl, int section_index)
query a section's folded state (1 = folded, 0 = expanded)
void n_gui_sectionlist_relayout (N_GUI_SECTIONLIST *sl)
re-stack all sections from y0 by current fold state: hide folded members, show and reposition expanded ones
void n_gui_sectionlist_set_first_inset (N_GUI_SECTIONLIST *sl, float inset)
set a left inset applied to the FIRST section's header only, so a caller can place a button before it on the same row; relayout re-applies it
void n_gui_sectionlist_set_folded (N_GUI_SECTIONLIST *sl, int section_index, int folded)
set a section's folded state and relayout; does NOT fire on_toggle (for programmatic restore)
void n_gui_set_default_theme (N_GUI_CTX *ctx, N_GUI_THEME theme)
Set the default theme on a context and sync scrollbar style colors.
void n_gui_set_display (N_GUI_CTX *ctx, ALLEGRO_DISPLAY *display)
set the display pointer for clipboard operations (copy/paste)
void n_gui_set_display_size (N_GUI_CTX *ctx, float w, float h)
set the display (viewport) size so global scrollbars can be computed.
void n_gui_set_dpi_scale (N_GUI_CTX *ctx, float scale)
set DPI scale factor manually (default is 1.0).
void n_gui_set_focus (N_GUI_CTX *ctx, int widget_id)
set keyboard focus to a specific widget (-1 to clear focus)
void n_gui_set_resize_mode (N_GUI_CTX *ctx, int mode)
set context-level resize mode: N_GUI_RESIZE_VIRTUAL (default) or N_GUI_RESIZE_ADAPTIVE
void n_gui_set_virtual_size (N_GUI_CTX *ctx, float w, float h)
set the virtual canvas size for resolution-independent scaling.
void n_gui_set_widget_enabled (N_GUI_CTX *ctx, int widget_id, int enabled)
set widget enabled state (0 = disabled: drawn dimmed and ignores all input)
void n_gui_set_widget_theme (N_GUI_CTX *ctx, int widget_id, N_GUI_THEME theme)
set the theme on a widget
void n_gui_set_widget_tooltip (N_GUI_CTX *ctx, int widget_id, const char *text)
set (or clear with "" / NULL) the tooltip text shown after the pointer rests on a widget
void n_gui_set_widget_visible (N_GUI_CTX *ctx, int widget_id, int visible)
set widget visibility
double n_gui_slider_get_value (N_GUI_CTX *ctx, int widget_id)
get slider current value
void n_gui_slider_set_bitmaps (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *track, ALLEGRO_BITMAP *fill, ALLEGRO_BITMAP *handle, ALLEGRO_BITMAP *handle_hover, ALLEGRO_BITMAP *handle_active)
set optional bitmap overlays on a slider widget.
void n_gui_slider_set_range (N_GUI_CTX *ctx, int widget_id, double min_val, double max_val)
set slider min/max range, clamping the current value if needed
void n_gui_slider_set_step (N_GUI_CTX *ctx, int widget_id, double step)
set slider step increment (0 is treated as 1).
void n_gui_slider_set_value (N_GUI_CTX *ctx, int widget_id, double value)
set slider value
void n_gui_slider_set_value_format (N_GUI_CTX *ctx, int widget_id, const char *fmt)
Override the built-in value readout's printf format string.
void n_gui_slider_set_value_visible (N_GUI_CTX *ctx, int widget_id, int visible)
Toggle the built-in value label.
int n_gui_tab_add (N_GUI_TAB_PANEL *panel, const char *label)
add a tab to the panel, returns tab index
N_GUI_TAB_PANEL * n_gui_tab_create (N_GUI_CTX *ctx, int window_id, float x, float y, float button_w, float button_h, void(*on_tab_change)(int, void *), void *user_data)
create a tab panel in an existing window
void n_gui_tab_free (N_GUI_TAB_PANEL **panel)
free a tab panel (does not destroy the N_GUI widgets)
int n_gui_tab_get_active (N_GUI_TAB_PANEL *panel)
get the active tab index
void n_gui_tab_set_active (N_GUI_TAB_PANEL *panel, int index)
set the active tab (toggles buttons, opens/closes content windows)
void n_gui_tab_set_content_window (N_GUI_TAB_PANEL *panel, int tab_index, int window_id)
associate a content window with a tab
const char * n_gui_textarea_get_text (N_GUI_CTX *ctx, int widget_id)
get text area content
size_t n_gui_textarea_get_text_length (N_GUI_CTX *ctx, int widget_id)
return the current text length in bytes (0 if widget is invalid)
void n_gui_textarea_scroll_to_bottom (N_GUI_CTX *ctx, int widget_id)
scroll a multiline textarea to the bottom
void n_gui_textarea_scroll_to_offset (N_GUI_CTX *ctx, int widget_id, size_t byte_offset)
scroll a multiline textarea so that the given byte offset is vertically centered
void n_gui_textarea_set_bitmap (N_GUI_CTX *ctx, int widget_id, ALLEGRO_BITMAP *bg)
set optional background bitmap on a textarea widget.
void n_gui_textarea_set_mask_char (N_GUI_CTX *ctx, int widget_id, char mask)
set a mask character for password-style input (e.g.
void n_gui_textarea_set_selection (N_GUI_CTX *ctx, int widget_id, size_t start, size_t end)
set the text selection range (byte offsets into text content)
void n_gui_textarea_set_text (N_GUI_CTX *ctx, int widget_id, const char *text)
set text area content
void n_gui_toggle_window (N_GUI_CTX *ctx, int window_id)
toggle window visibility (show/hide)
int n_gui_tooltip_pending (N_GUI_CTX *ctx)
tooltip phase: 0 = none (or tooltips disabled via style.tooltip_delay <= 0), 1 = arming (hosts with cached GUI renders must keep redrawing so the bubble can appear on time), 2 = shown (static - re-render once on the transition, then stop)
int n_gui_tree_add_node (N_GUI_TREE *tree, const char *label, int parent_index, void *user_data)
add a node to the tree
void n_gui_tree_clear (N_GUI_TREE *tree)
remove all nodes and clear the backing listbox; tree object remains valid
N_GUI_TREE * n_gui_tree_create (N_GUI_CTX *ctx, int window_id, float x, float y, float w, float h, void(*on_select)(int, void *), void *user_data)
create a tree view in an existing window
void n_gui_tree_draw_overlay (N_GUI_TREE *tree)
per-frame overlay drawing: draws the active drop-indicator on top of the listbox.
int n_gui_tree_find_by_user_data (const N_GUI_TREE *tree, const void *ptr)
find the first node whose user_data pointer equals ptr, or -1.
void n_gui_tree_free (N_GUI_TREE **tree)
free a tree view (does not destroy the N_GUI listbox)
int n_gui_tree_get_selection (N_GUI_TREE *tree)
get the index of the currently selected node, or -1 when nothing is selected or the selection points at a hidden row
void n_gui_tree_rebuild (N_GUI_TREE *tree)
rebuild the listbox to reflect current tree state
void n_gui_tree_remove_node (N_GUI_TREE *tree, int node_index)
remove a node and its entire subtree; remaining node indices are compacted (callers holding indices across the call must discard or re-resolve them)
void n_gui_tree_set_label (N_GUI_TREE *tree, int node_index, const char *new_label)
change the display label of a node
void n_gui_tree_set_on_drop (N_GUI_TREE *tree, n_gui_tree_on_drop_t on_drop, void *user_data)
install (or clear, with NULL) a drag-reorder drop callback.
void n_gui_tree_set_selection (N_GUI_TREE *tree, int node_index)
programmatically select a node; ancestors are expanded so the node is visible, and the listbox scrolls to reveal it.
void n_gui_tree_tick (N_GUI_TREE *tree)
per-frame poll: reads ctx->mouse_* to track drag state and fires the on_drop callback on release.
void n_gui_tree_toggle_expand (N_GUI_TREE *tree, int node_index)
toggle expand/collapse of a node
void n_gui_update_transform (N_GUI_CTX *ctx)
recalculate scale and offset from virtual canvas to display.
int n_gui_wants_mouse (N_GUI_CTX *ctx)
check if the mouse is currently over any open GUI window (use to prevent click-through to the game world)
void n_gui_window_apply_autofit (N_GUI_CTX *ctx, int window_id)
trigger auto-fit recalculation for a window (call after adding/removing/resizing widgets)
void n_gui_window_autosize (N_GUI_CTX *ctx, int window_id)
recompute and apply minimum-fit size for a window based on its current widgets
int n_gui_window_get_flags (N_GUI_CTX *ctx, int window_id)
get feature flags of a window
int n_gui_window_get_resize_policy (N_GUI_CTX *ctx, int window_id)
get per-window resize policy
int n_gui_window_get_zorder (N_GUI_CTX *ctx, int window_id)
get window z-order mode
int n_gui_window_get_zvalue (N_GUI_CTX *ctx, int window_id)
get window z-value (for N_GUI_ZORDER_FIXED mode)
int n_gui_window_is_maximised (N_GUI_CTX *ctx, int window_id)
check if a window is currently maximised
int n_gui_window_is_open (N_GUI_CTX *ctx, int window_id)
check if window is visible
void n_gui_window_set_autofit (N_GUI_CTX *ctx, int window_id, int autofit_flags, float border)
configure auto-fit behavior for a dialog window
void n_gui_window_set_bitmaps (N_GUI_CTX *ctx, int window_id, ALLEGRO_BITMAP *bg, ALLEGRO_BITMAP *titlebar, int bg_scale_mode)
set optional bitmap overlays on a window's body and titlebar.
void n_gui_window_set_close_callback (N_GUI_CTX *ctx, int window_id, void(*on_close)(int, void *), void *user_data)
set the close button callback for a window (NULL = default: hide window)
void n_gui_window_set_content_draw_callback (N_GUI_CTX *ctx, int window_id, void(*on_content_draw)(int, void *), void *user_data)
set a content-draw callback for a window, invoked during n_gui_draw right after the window's own content is drawn (at the window's z-order)
void n_gui_window_set_flags (N_GUI_CTX *ctx, int window_id, int flags)
set feature flags on a window (N_GUI_WIN_AUTO_SCROLLBAR, N_GUI_WIN_RESIZABLE, ...)
void n_gui_window_set_maximize_callback (N_GUI_CTX *ctx, int window_id, void(*on_maximize)(int, void *), void *user_data)
set the maximize button callback for a window (NULL = default: toggle maximised)
void n_gui_window_set_minimize_callback (N_GUI_CTX *ctx, int window_id, void(*on_minimize)(int, void *), void *user_data)
set the minimize button callback for a window (NULL = default: toggle minimised)
void n_gui_window_set_resize_policy (N_GUI_CTX *ctx, int window_id, int policy)
set per-window resize policy (N_GUI_WIN_RESIZE_NONE / _MOVE / _SCALE).
void n_gui_window_set_tb_btn_theme (N_GUI_CTX *ctx, int window_id, N_GUI_THEME theme)
set the theme for titlebar minimize/maximize buttons on a specific window
void n_gui_window_set_tb_button_bitmaps (N_GUI_CTX *ctx, int window_id, int btn_type, ALLEGRO_BITMAP *normal, ALLEGRO_BITMAP *hover, ALLEGRO_BITMAP *active)
set optional bitmap overlays on a titlebar button
void n_gui_window_set_tb_close_theme (N_GUI_CTX *ctx, int window_id, N_GUI_THEME theme)
set the theme for the titlebar close button on a specific window
void n_gui_window_set_zorder (N_GUI_CTX *ctx, int window_id, int z_mode, int z_value)
set window z-order mode and value
void n_gui_window_update_normalized (N_GUI_CTX *ctx, int window_id)
recapture normalized coordinates for a window from its current absolute position/size.
Detailed Description
Bitmap Skinning
All widgets support optional bitmap overlays for visual customization. By default, every bitmap pointer is NULL and the standard color theme is used. To skin a widget element, call the corresponding _set_bitmaps() function after widget creation.
Bitmaps are NOT owned by N_GUI, the caller is responsible for loading and destroying them. N_GUI only stores the pointer.
Fallback Chain
For widgets with per-state bitmaps (normal/hover/active):
If the state-specific bitmap is NULL, the normal bitmap is used.
If the normal bitmap is also NULL, the color theme is used.
Supported Widgets
Windows: body background, titlebar background (n_gui_window_set_bitmaps())
Buttons: already supported via n_gui_add_button_bitmap()
Sliders: track, fill, handle with per-state variants (n_gui_slider_set_bitmaps())
Scrollbars: track, thumb with per-state variants (n_gui_scrollbar_set_bitmaps())
Checkboxes: box unchecked, box checked, box hover (n_gui_checkbox_set_bitmaps())
Textareas: background (n_gui_textarea_set_bitmap())
Listbox/Radiolist/Combobox: background, item background, item selected
Dropmenus: panel background, item hover (n_gui_dropmenu_set_bitmaps())
Labels: background (n_gui_label_set_bitmap())
JSON Theme
Bitmap assignments are programmatic (via setter functions), not part of the JSON theme file. The JSON theme remains the color/layout fallback.
Data Structure Documentation
N_GUI_BUTTON_DATA
struct N_GUI_BUTTON_DATA
button specific data
Definition at line 322 of file n_gui.h.
Data Fields
ALLEGRO_BITMAP * bitmap
optional bitmap for the button (NULL = color theme)
ALLEGRO_BITMAP * bitmap_active
optional bitmap for active/pressed state
ALLEGRO_BITMAP * bitmap_hover
optional bitmap for hover state
int key_focus_only
if 1, keycode fires only when the button itself or a source widget has focus.
int key_modifiers
required modifier key flags for the keybind (0 = no modifier requirement, matches any modifier state for backward compatibility).
double key_press_until
absolute al_get_time() deadline until which the button is rendered in its pressed (N_GUI_STATE_ACTIVE) visual state after a keybind trigger.
int key_sources [8]
widget IDs that can trigger this focused key binding.
int keycode
bound keyboard keycode (0 = none).
char label [128]
label displayed on the button
void(* on_click)(int widget_id, void *user_data)
callback on click (widget_id passed)
int shape
shape type: N_GUI_SHAPE_RECT, N_GUI_SHAPE_ROUNDED, N_GUI_SHAPE_BITMAP
int toggle_mode
toggle mode: 0 = momentary (default), 1 = toggle (stays clicked/unclicked)
int toggled
toggle state: 0 = off/unclicked, 1 = on/clicked (only used when toggle_mode=1)
void * user_data
user data for callback
Field Documentation
bitmap
ALLEGRO_BITMAP* N_GUI_BUTTON_DATA::bitmap
optional bitmap for the button (NULL = color theme)
Definition at line 326 of file n_gui.h.
Referenced by _draw_button(), n_gui_add_button(), n_gui_add_button_bitmap(), and n_gui_button_set_state_bitmaps().
bitmap_active
ALLEGRO_BITMAP* N_GUI_BUTTON_DATA::bitmap_active
optional bitmap for active/pressed state
Definition at line 330 of file n_gui.h.
Referenced by _draw_button(), n_gui_add_button(), n_gui_add_button_bitmap(), and n_gui_button_set_state_bitmaps().
bitmap_hover
ALLEGRO_BITMAP* N_GUI_BUTTON_DATA::bitmap_hover
optional bitmap for hover state
Definition at line 328 of file n_gui.h.
Referenced by _draw_button(), n_gui_add_button(), n_gui_add_button_bitmap(), and n_gui_button_set_state_bitmaps().
key_focus_only
int N_GUI_BUTTON_DATA::key_focus_only
if 1, keycode fires only when the button itself or a source widget has focus.
if 0 (default), keycode fires globally when no interactive widget has focus.
Definition at line 348 of file n_gui.h.
Referenced by n_gui_button_set_keycode_focused(), and n_gui_process_event().
key_modifiers
int N_GUI_BUTTON_DATA::key_modifiers
required modifier key flags for the keybind (0 = no modifier requirement, matches any modifier state for backward compatibility).
Use ALLEGRO_KEYMOD_SHIFT, ALLEGRO_KEYMOD_CTRL, ALLEGRO_KEYMOD_ALT, ALLEGRO_KEYMOD_ALTGR ORed together. When non-zero, only the specified modifier combination triggers the keybind (exact match on N_GUI_KEY_MOD_MASK bits).
Definition at line 345 of file n_gui.h.
Referenced by n_gui_add_button(), n_gui_button_set_keycode(), n_gui_button_set_keycode_focused(), and n_gui_process_event().
key_press_until
double N_GUI_BUTTON_DATA::key_press_until
absolute al_get_time() deadline until which the button is rendered in its pressed (N_GUI_STATE_ACTIVE) visual state after a keybind trigger.
0.0 = no pending key-press flash.
Definition at line 355 of file n_gui.h.
Referenced by _draw_button(), and n_gui_process_event().
key_sources
int N_GUI_BUTTON_DATA::key_sources[8]
widget IDs that can trigger this focused key binding.
Terminated by -1. Only used when key_focus_only == 1. Up to N_GUI_KEY_SOURCES_MAX entries.
Definition at line 351 of file n_gui.h.
Referenced by n_gui_button_set_keycode_focused(), and n_gui_process_event().
keycode
int N_GUI_BUTTON_DATA::keycode
bound keyboard keycode (0 = none).
When this key is pressed and no text input widget has focus, the button's on_click callback is triggered.
Definition at line 339 of file n_gui.h.
Referenced by n_gui_add_button(), n_gui_button_set_keycode(), n_gui_button_set_keycode_focused(), and n_gui_process_event().
label
char N_GUI_BUTTON_DATA::label[128]
label displayed on the button
Definition at line 324 of file n_gui.h.
Referenced by _draw_button(), n_gui_add_button(), and n_gui_button_set_label().
on_click
void(* N_GUI_BUTTON_DATA::on_click) (int widget_id, void *user_data)
callback on click (widget_id passed)
Definition at line 357 of file n_gui.h.
Referenced by n_gui_add_button(), and n_gui_process_event().
shape
int N_GUI_BUTTON_DATA::shape
shape type: N_GUI_SHAPE_RECT, N_GUI_SHAPE_ROUNDED, N_GUI_SHAPE_BITMAP
Definition at line 332 of file n_gui.h.
Referenced by _draw_button(), n_gui_add_button(), and n_gui_button_set_state_bitmaps().
toggle_mode
int N_GUI_BUTTON_DATA::toggle_mode
toggle mode: 0 = momentary (default), 1 = toggle (stays clicked/unclicked)
Definition at line 334 of file n_gui.h.
Referenced by _draw_button(), n_gui_add_button(), n_gui_add_toggle_button(), n_gui_button_set_toggle_mode(), and n_gui_process_event().
toggled
int N_GUI_BUTTON_DATA::toggled
toggle state: 0 = off/unclicked, 1 = on/clicked (only used when toggle_mode=1)
Definition at line 336 of file n_gui.h.
Referenced by _draw_button(), n_gui_add_button(), n_gui_add_toggle_button(), n_gui_button_set_toggle_mode(), and n_gui_process_event().
user_data
void* N_GUI_BUTTON_DATA::user_data
user data for callback
Definition at line 359 of file n_gui.h.
Referenced by n_gui_add_button(), and n_gui_process_event().
N_GUI_CHECKBOX_DATA
struct N_GUI_CHECKBOX_DATA
checkbox specific data
Definition at line 440 of file n_gui.h.
Data Fields
ALLEGRO_BITMAP * box_bitmap
optional bitmap for the checkbox square, unchecked state (NULL = color theme)
ALLEGRO_BITMAP * box_checked_bitmap
optional bitmap for the checkbox square, checked state (NULL = color theme)
ALLEGRO_BITMAP * box_hover_bitmap
optional bitmap for the checkbox square on hover (NULL = fallback to box_bitmap/box_checked_bitmap)
int checked
checked state
char label [128]
label displayed next to the checkbox
void(* on_toggle)(int widget_id, int checked, void *user_data)
callback on toggle
void * user_data
user data for callback
Field Documentation
box_bitmap
ALLEGRO_BITMAP* N_GUI_CHECKBOX_DATA::box_bitmap
optional bitmap for the checkbox square, unchecked state (NULL = color theme)
Definition at line 446 of file n_gui.h.
Referenced by _draw_checkbox(), and n_gui_checkbox_set_bitmaps().
box_checked_bitmap
ALLEGRO_BITMAP* N_GUI_CHECKBOX_DATA::box_checked_bitmap
optional bitmap for the checkbox square, checked state (NULL = color theme)
Definition at line 448 of file n_gui.h.
Referenced by _draw_checkbox(), and n_gui_checkbox_set_bitmaps().
box_hover_bitmap
ALLEGRO_BITMAP* N_GUI_CHECKBOX_DATA::box_hover_bitmap
optional bitmap for the checkbox square on hover (NULL = fallback to box_bitmap/box_checked_bitmap)
Definition at line 450 of file n_gui.h.
Referenced by _draw_checkbox(), and n_gui_checkbox_set_bitmaps().
checked
int N_GUI_CHECKBOX_DATA::checked
checked state
Definition at line 444 of file n_gui.h.
Referenced by _draw_checkbox(), n_gui_add_checkbox(), and n_gui_process_event().
label
char N_GUI_CHECKBOX_DATA::label[128]
label displayed next to the checkbox
Definition at line 442 of file n_gui.h.
Referenced by _draw_checkbox(), and n_gui_add_checkbox().
on_toggle
void(* N_GUI_CHECKBOX_DATA::on_toggle) (int widget_id, int checked, void *user_data)
callback on toggle
Definition at line 452 of file n_gui.h.
Referenced by n_gui_add_checkbox(), and n_gui_process_event().
user_data
void* N_GUI_CHECKBOX_DATA::user_data
user data for callback
Definition at line 454 of file n_gui.h.
Referenced by n_gui_add_checkbox(), and n_gui_process_event().
N_GUI_COMBOBOX_DATA
struct N_GUI_COMBOBOX_DATA
combo box specific data
Definition at line 557 of file n_gui.h.
Data Fields
ALLEGRO_BITMAP * bg_bitmap
optional bitmap for the combobox background (NULL = color theme)
int flags
bitmask of N_GUI_COMBOBOX_* flags
int is_open
is dropdown currently open
ALLEGRO_BITMAP * item_bg_bitmap
optional bitmap for per-item background, normal state (NULL = color theme)
float item_height
item height in dropdown
ALLEGRO_BITMAP * item_selected_bitmap
optional bitmap for per-item background, selected/highlighted (NULL = color theme)
N_GUI_LISTITEM * items
dynamic array of items
size_t items_capacity
allocated capacity
int max_visible
max visible items in dropdown
size_t nb_items
number of items
void(* on_select)(int widget_id, int index, void *user_data)
callback on selection change (widget_id, selected_index, user_data)
int scroll_offset
scroll offset in dropdown
int selected_index
currently selected index (-1 = none)
void * user_data
user data for callback
Field Documentation
bg_bitmap
ALLEGRO_BITMAP* N_GUI_COMBOBOX_DATA::bg_bitmap
optional bitmap for the combobox background (NULL = color theme)
Definition at line 575 of file n_gui.h.
Referenced by _draw_combobox(), _draw_combobox_dropdown(), and n_gui_combobox_set_bitmaps().
flags
int N_GUI_COMBOBOX_DATA::flags
bitmask of N_GUI_COMBOBOX_* flags
Definition at line 585 of file n_gui.h.
Referenced by _draw_combobox_dropdown(), n_gui_add_combobox(), n_gui_combobox_set_flags(), and n_gui_process_event().
is_open
int N_GUI_COMBOBOX_DATA::is_open
is dropdown currently open
Definition at line 567 of file n_gui.h.
Referenced by _draw_combobox_dropdown(), n_gui_add_combobox(), n_gui_combobox_clear(), and n_gui_process_event().
item_bg_bitmap
ALLEGRO_BITMAP* N_GUI_COMBOBOX_DATA::item_bg_bitmap
optional bitmap for per-item background, normal state (NULL = color theme)
Definition at line 577 of file n_gui.h.
Referenced by _draw_combobox_dropdown(), and n_gui_combobox_set_bitmaps().
item_height
float N_GUI_COMBOBOX_DATA::item_height
item height in dropdown
Definition at line 571 of file n_gui.h.
Referenced by _draw_combobox_dropdown(), n_gui_add_combobox(), and n_gui_process_event().
item_selected_bitmap
ALLEGRO_BITMAP* N_GUI_COMBOBOX_DATA::item_selected_bitmap
optional bitmap for per-item background, selected/highlighted (NULL = color theme)
Definition at line 579 of file n_gui.h.
Referenced by _draw_combobox_dropdown(), and n_gui_combobox_set_bitmaps().
items
N_GUI_LISTITEM* N_GUI_COMBOBOX_DATA::items
dynamic array of items
Definition at line 559 of file n_gui.h.
Referenced by _destroy_widget(), _draw_combobox(), _draw_combobox_dropdown(), n_gui_add_combobox(), n_gui_combobox_add_item(), n_gui_combobox_clear(), n_gui_combobox_get_item_text(), and n_gui_process_event().
items_capacity
size_t N_GUI_COMBOBOX_DATA::items_capacity
allocated capacity
Definition at line 563 of file n_gui.h.
Referenced by n_gui_add_combobox(), and n_gui_combobox_add_item().
max_visible
int N_GUI_COMBOBOX_DATA::max_visible
max visible items in dropdown
Definition at line 573 of file n_gui.h.
Referenced by _draw_combobox_dropdown(), n_gui_add_combobox(), and n_gui_process_event().
nb_items
size_t N_GUI_COMBOBOX_DATA::nb_items
number of items
Definition at line 561 of file n_gui.h.
Referenced by _draw_combobox(), _draw_combobox_dropdown(), n_gui_add_combobox(), n_gui_combobox_add_item(), n_gui_combobox_clear(), and n_gui_process_event().
on_select
void(* N_GUI_COMBOBOX_DATA::on_select) (int widget_id, int index, void *user_data)
callback on selection change (widget_id, selected_index, user_data)
Definition at line 581 of file n_gui.h.
Referenced by n_gui_add_combobox(), and n_gui_process_event().
scroll_offset
int N_GUI_COMBOBOX_DATA::scroll_offset
scroll offset in dropdown
Definition at line 569 of file n_gui.h.
Referenced by _draw_combobox_dropdown(), n_gui_add_combobox(), n_gui_combobox_clear(), and n_gui_process_event().
selected_index
int N_GUI_COMBOBOX_DATA::selected_index
currently selected index (-1 = none)
Definition at line 565 of file n_gui.h.
Referenced by _draw_combobox(), _draw_combobox_dropdown(), n_gui_add_combobox(), n_gui_combobox_clear(), n_gui_combobox_set_selected(), and n_gui_process_event().
user_data
void* N_GUI_COMBOBOX_DATA::user_data
user data for callback
Definition at line 583 of file n_gui.h.
Referenced by n_gui_add_combobox(), and n_gui_process_event().
N_GUI_CTX
struct N_GUI_CTX
The top-level GUI context that holds all windows.
Examples
ex_gui.c, ex_gui_dictionary.c, ex_gui_isometric.c, ex_gui_kvtable.c, ex_gui_network.c, and ex_gui_particles.c.
Definition at line 1030 of file n_gui.h.
Data Fields
ALLEGRO_FONT * default_font default font (must be set before adding widgets)
N_GUI_THEME default_tb_btn_theme default theme for titlebar minimize/maximize buttons
N_GUI_THEME default_tb_close_theme default theme for titlebar close button
N_GUI_THEME default_theme default theme (applied to new widgets/windows)
ALLEGRO_DISPLAY * display display pointer for clipboard operations (set via n_gui_set_display)
float display_h display/viewport height
float display_w display/viewport width (set via n_gui_set_display_size)
float dpi_scale DPI scale factor (1.0 = normal, 1.25 = 125%, 2.0 = HiDPI, etc.)
int focused_widget_id id of the widget that currently has focus, or -1
int global_hscroll_drag 1 if global scrollbar horizontal thumb is being dragged
float global_scroll_x global horizontal scroll offset (when GUI exceeds display)
float global_scroll_y global vertical scroll offset (when GUI exceeds display)
int global_vscroll_drag 1 if global scrollbar vertical thumb is being dragged
float gui_bounds_h total bounding box height of all windows (computed internally)
float gui_bounds_w total bounding box width of all windows (computed internally)
float gui_offset_x horizontal letterbox offset for virtual canvas
float gui_offset_y vertical letterbox offset for virtual canvas
float gui_scale computed uniform scale factor for virtual canvas
int mouse_b1 mouse button 1 state
int mouse_b1_prev previous mouse button 1 state
int mouse_x mouse state tracking
int mouse_y mouse state tracking
int next_widget_id next widget id to assign
int next_window_id next window id to assign
int open_combobox_id id of the combobox whose dropdown is currently open, or -1
int open_dropmenu_id id of the dropdown menu whose panel is currently open, or -1
N_GUI_PENDING_GEOM * pending_layout layout entries for windows that did NOT exist when the saved layout was loaded (lazily-created panels).
n_gui_add_window applies the saved (x,y) to the first window created later with a matching title, giving cross-session position restore without eager-creating every window. Owned by the ctx; freed in n_gui_destroy_ctx.
int pending_layout_count number of valid entries in pending_layout
float ref_display_h reference display height at the time normalized values were last captured
float ref_display_w reference display width at the time normalized values were last captured
int resize_mode context resize mode: N_GUI_RESIZE_VIRTUAL or N_GUI_RESIZE_ADAPTIVE
int scrollbar_drag_widget_id id of the widget whose scrollbar is being dragged, or -1
int selected_label_id id of the label widget with the most recent text selection, or -1
N_GUI_STYLE style configurable style (sizes, colours, paddings)
int tooltip_anchor_x pointer x when the tooltip was last armed (movement re-arms)
int tooltip_anchor_y pointer y when the tooltip was last armed
double tooltip_armed_at time the tooltip hover was (re)armed, from al_get_time()
int tooltip_widget_id widget the pointer is resting on for tooltip purposes (-1 = none)
float virtual_h virtual canvas height (0 = disabled / identity transform)
float virtual_w virtual canvas width (0 = disabled / identity transform)
HASH_TABLE * widgets_by_id hash table for fast widget lookup by id
LIST * windows ordered list of N_GUI_WINDOW* (back to front)
N_GUI_DROPMENU_DATA
struct N_GUI_DROPMENU_DATA
dropdown menu specific data
Definition at line 641 of file n_gui.h.
Data Fields
N_GUI_DROPMENU_ENTRY * entries
dynamic array of entries
size_t entries_capacity
allocated capacity
int flags
bitmask of N_GUI_DROPMENU_* flags
int is_open
is the menu currently open
float item_height
item height
ALLEGRO_BITMAP * item_hover_bitmap
optional bitmap for the hovered entry background (NULL = color theme)
char label [128]
menu label (shown on the button)
int max_visible
max visible items
size_t nb_entries
number of entries
void(* on_open)(int widget_id, void *user_data)
callback to rebuild dynamic entries each time the menu is opened.
void * on_open_user_data
user data for on_open callback
ALLEGRO_BITMAP * panel_bitmap
optional bitmap for the dropdown panel background (NULL = color theme)
int scroll_offset
scroll offset
Field Documentation
entries
N_GUI_DROPMENU_ENTRY* N_GUI_DROPMENU_DATA::entries
dynamic array of entries
Definition at line 645 of file n_gui.h.
Referenced by _destroy_widget(), _draw_dropmenu_panel(), n_gui_add_dropmenu(), n_gui_dropmenu_add_dynamic_entry(), n_gui_dropmenu_add_entry(), n_gui_dropmenu_clear_dynamic(), n_gui_dropmenu_set_entry_text(), and n_gui_process_event().
entries_capacity
size_t N_GUI_DROPMENU_DATA::entries_capacity
allocated capacity
Definition at line 649 of file n_gui.h.
Referenced by n_gui_add_dropmenu(), and n_gui_dropmenu_add_entry().
flags
int N_GUI_DROPMENU_DATA::flags
bitmask of N_GUI_DROPMENU_* flags
Definition at line 669 of file n_gui.h.
Referenced by _draw_dropmenu_panel(), n_gui_add_dropmenu(), n_gui_dropmenu_set_flags(), and n_gui_process_event().
is_open
int N_GUI_DROPMENU_DATA::is_open
is the menu currently open
Definition at line 651 of file n_gui.h.
Referenced by _draw_dropmenu(), _draw_dropmenu_panel(), n_gui_add_dropmenu(), and n_gui_process_event().
item_height
float N_GUI_DROPMENU_DATA::item_height
item height
Definition at line 657 of file n_gui.h.
Referenced by _draw_dropmenu_panel(), n_gui_add_dropmenu(), and n_gui_process_event().
item_hover_bitmap
ALLEGRO_BITMAP* N_GUI_DROPMENU_DATA::item_hover_bitmap
optional bitmap for the hovered entry background (NULL = color theme)
Definition at line 661 of file n_gui.h.
Referenced by _draw_dropmenu_panel(), n_gui_add_dropmenu(), and n_gui_dropmenu_set_bitmaps().
label
char N_GUI_DROPMENU_DATA::label[128]
menu label (shown on the button)
Definition at line 643 of file n_gui.h.
Referenced by _draw_dropmenu(), and n_gui_add_dropmenu().
max_visible
int N_GUI_DROPMENU_DATA::max_visible
max visible items
Definition at line 655 of file n_gui.h.
Referenced by _draw_dropmenu_panel(), n_gui_add_dropmenu(), n_gui_dropmenu_clear_dynamic(), and n_gui_process_event().
nb_entries
size_t N_GUI_DROPMENU_DATA::nb_entries
number of entries
Definition at line 647 of file n_gui.h.
Referenced by _draw_dropmenu_panel(), n_gui_add_dropmenu(), n_gui_dropmenu_add_entry(), n_gui_dropmenu_clear(), n_gui_dropmenu_clear_dynamic(), n_gui_dropmenu_set_entry_text(), and n_gui_process_event().
on_open
void(* N_GUI_DROPMENU_DATA::on_open) (int widget_id, void *user_data)
callback to rebuild dynamic entries each time the menu is opened.
signature: void rebuild(int widget_id, void* user_data) The callback should call n_gui_dropmenu_clear_dynamic() then add dynamic entries.
Definition at line 665 of file n_gui.h.
Referenced by n_gui_add_dropmenu(), and n_gui_process_event().
on_open_user_data
void* N_GUI_DROPMENU_DATA::on_open_user_data
user data for on_open callback
Definition at line 667 of file n_gui.h.
Referenced by n_gui_add_dropmenu(), and n_gui_process_event().
panel_bitmap
ALLEGRO_BITMAP* N_GUI_DROPMENU_DATA::panel_bitmap
optional bitmap for the dropdown panel background (NULL = color theme)
Definition at line 659 of file n_gui.h.
Referenced by _draw_dropmenu_panel(), n_gui_add_dropmenu(), and n_gui_dropmenu_set_bitmaps().
scroll_offset
int N_GUI_DROPMENU_DATA::scroll_offset
scroll offset
Definition at line 653 of file n_gui.h.
Referenced by _draw_dropmenu_panel(), n_gui_add_dropmenu(), n_gui_dropmenu_clear(), n_gui_dropmenu_clear_dynamic(), and n_gui_process_event().
N_GUI_DROPMENU_ENTRY
struct N_GUI_DROPMENU_ENTRY
A single entry in a dropdown menu (static or dynamic)
Definition at line 621 of file n_gui.h.
Data Fields
int is_dynamic
is this entry dynamic (rebuilt via callback each time menu opens)
void(* on_click)(int widget_id, int entry_index, int tag, void *user_data)
callback when this entry is clicked (widget_id, entry_index, tag, user_data)
int tag
user-defined tag for the entry (e.g.
char text [128]
display text
void * user_data
user data for callback
Field Documentation
is_dynamic
int N_GUI_DROPMENU_ENTRY::is_dynamic
is this entry dynamic (rebuilt via callback each time menu opens)
Definition at line 625 of file n_gui.h.
Referenced by n_gui_dropmenu_add_dynamic_entry(), n_gui_dropmenu_add_entry(), and n_gui_dropmenu_clear_dynamic().
on_click
void(* N_GUI_DROPMENU_ENTRY::on_click) (int widget_id, int entry_index, int tag, void *user_data)
callback when this entry is clicked (widget_id, entry_index, tag, user_data)
Definition at line 629 of file n_gui.h.
Referenced by n_gui_dropmenu_add_entry(), and n_gui_process_event().
tag
int N_GUI_DROPMENU_ENTRY::tag
user-defined tag for the entry (e.g.
a window id)
Definition at line 627 of file n_gui.h.
Referenced by n_gui_dropmenu_add_entry(), and n_gui_process_event().
text
char N_GUI_DROPMENU_ENTRY::text[128]
display text
Definition at line 623 of file n_gui.h.
Referenced by _draw_dropmenu_panel(), n_gui_dropmenu_add_entry(), and n_gui_dropmenu_set_entry_text().
user_data
void* N_GUI_DROPMENU_ENTRY::user_data
user data for callback
Definition at line 631 of file n_gui.h.
Referenced by n_gui_dropmenu_add_entry(), and n_gui_process_event().
N_GUI_IMAGE_DATA
struct N_GUI_IMAGE_DATA
image widget specific data
Definition at line 589 of file n_gui.h.
Data Fields
ALLEGRO_BITMAP * bitmap bitmap to display (not owned, not freed)
int scale_mode scale mode: N_GUI_IMAGE_FIT, N_GUI_IMAGE_STRETCH, N_GUI_IMAGE_CENTER
N_GUI_KV_ROW
struct N_GUI_KV_ROW
a single row in the KV table
Definition at line 1886 of file n_gui.h.
Data Fields
int active 1 if active, 0 if removed
int desc_id textarea widget ID for the description
int enabled_id checkbox widget ID for the enabled toggle
int key_id textarea widget ID for the key
int remove_id button widget ID for the remove action
int value_id textarea widget ID for the value
N_GUI_KVTABLE
struct N_GUI_KVTABLE
key-value table built from textareas, checkboxes, and buttons
Examples
ex_gui_kvtable.c.
Definition at line 1896 of file n_gui.h.
Data Fields
int btn_add
button widget ID for "+" add row
N_GUI_CTX * ctx
GUI context.
float header_height
unscaled column-header row height
float init_win_h
parent window height at create time
float init_win_w
parent window width at create time
int lbl_desc
label widget ID for "Description" header
int lbl_enabled
label widget ID for "On" header
int lbl_key
label widget ID for "Key" header
int lbl_value
label widget ID for "Value" header
int nb_active
active row count
int nb_rows
total rows (including removed)
void(* on_remove)(int, void *)
callback on row removal
float padding
unscaled padding in pixels
float row_height
unscaled row height in pixels
N_GUI_KV_ROW rows [128]
row storage
void * user_data
user data for callback
int window_id
parent window
Field Documentation
btn_add
int N_GUI_KVTABLE::btn_add
button widget ID for "+" add row
Examples
ex_gui_kvtable.c.
Definition at line 1911 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), main(), and n_gui_kvtable_create().
ctx
N_GUI_CTX* N_GUI_KVTABLE::ctx
GUI context.
Definition at line 1897 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), n_gui_kvtable_add_row(), n_gui_kvtable_create(), and n_gui_kvtable_remove_row().
header_height
float N_GUI_KVTABLE::header_height
unscaled column-header row height
Definition at line 1904 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), and n_gui_kvtable_create().
init_win_h
float N_GUI_KVTABLE::init_win_h
parent window height at create time
Definition at line 1906 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), and n_gui_kvtable_create().
init_win_w
float N_GUI_KVTABLE::init_win_w
parent window width at create time
Definition at line 1905 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), and n_gui_kvtable_create().
lbl_desc
int N_GUI_KVTABLE::lbl_desc
label widget ID for "Description" header
Definition at line 1909 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), and n_gui_kvtable_create().
lbl_enabled
int N_GUI_KVTABLE::lbl_enabled
label widget ID for "On" header
Definition at line 1910 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), and n_gui_kvtable_create().
lbl_key
int N_GUI_KVTABLE::lbl_key
label widget ID for "Key" header
Examples
ex_gui_kvtable.c.
Definition at line 1907 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), main(), and n_gui_kvtable_create().
lbl_value
int N_GUI_KVTABLE::lbl_value
label widget ID for "Value" header
Definition at line 1908 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), and n_gui_kvtable_create().
nb_active
int N_GUI_KVTABLE::nb_active
active row count
Definition at line 1901 of file n_gui.h.
Referenced by n_gui_kvtable_add_row(), n_gui_kvtable_create(), n_gui_kvtable_get_count(), and n_gui_kvtable_remove_row().
nb_rows
int N_GUI_KVTABLE::nb_rows
total rows (including removed)
Examples
ex_gui_kvtable.c.
Definition at line 1900 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), _n_gui_kv_remove_clicked(), main(), n_gui_kvtable_add_row(), n_gui_kvtable_create(), and n_gui_kvtable_remove_row().
on_remove
void(* N_GUI_KVTABLE::on_remove) (int, void *)
callback on row removal
Definition at line 1912 of file n_gui.h.
Referenced by _n_gui_kv_remove_clicked(), and n_gui_kvtable_create().
padding
float N_GUI_KVTABLE::padding
unscaled padding in pixels
Definition at line 1903 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), n_gui_kvtable_add_row(), and n_gui_kvtable_create().
row_height
float N_GUI_KVTABLE::row_height
unscaled row height in pixels
Definition at line 1902 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), n_gui_kvtable_add_row(), and n_gui_kvtable_create().
rows
N_GUI_KV_ROW N_GUI_KVTABLE::rows[128]
row storage
Examples
ex_gui_kvtable.c.
Definition at line 1899 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), _n_gui_kv_remove_clicked(), main(), n_gui_kvtable_add_row(), and n_gui_kvtable_remove_row().
user_data
void* N_GUI_KVTABLE::user_data
user data for callback
Definition at line 1913 of file n_gui.h.
Referenced by _n_gui_kv_remove_clicked(), and n_gui_kvtable_create().
window_id
int N_GUI_KVTABLE::window_id
parent window
Definition at line 1898 of file n_gui.h.
Referenced by _n_gui_kv_apply_layout(), n_gui_kvtable_add_row(), and n_gui_kvtable_create().
N_GUI_LABEL_DATA
struct N_GUI_LABEL_DATA
static text label specific data
Definition at line 597 of file n_gui.h.
Data Fields
int align
text alignment: N_GUI_ALIGN_LEFT, N_GUI_ALIGN_CENTER, N_GUI_ALIGN_RIGHT
ALLEGRO_BITMAP * bg_bitmap
optional bitmap for the label background (NULL = no background)
char link [4096]
optional hyperlink URL (empty string = no link)
void(* on_link_click)(int widget_id, const char *link, void *user_data)
callback when link is clicked (widget_id, link_url, user_data)
float scroll_y
vertical scroll offset for overflowing text (pixels)
int sel_dragging
1 if mouse is actively dragging to select text
int sel_end
selection end byte offset (-1 = no selection)
int sel_start
selection start byte offset (-1 = no selection)
char text [4096]
text to display
void * user_data
user data for callback
Field Documentation
align
int N_GUI_LABEL_DATA::align
text alignment: N_GUI_ALIGN_LEFT, N_GUI_ALIGN_CENTER, N_GUI_ALIGN_RIGHT
Definition at line 603 of file n_gui.h.
Referenced by _draw_label(), _label_text_origin_x(), _window_update_content_size(), n_gui_add_label(), and n_gui_process_event().
bg_bitmap
ALLEGRO_BITMAP* N_GUI_LABEL_DATA::bg_bitmap
optional bitmap for the label background (NULL = no background)
Definition at line 613 of file n_gui.h.
Referenced by _draw_label().
link
char N_GUI_LABEL_DATA::link[4096]
optional hyperlink URL (empty string = no link)
Definition at line 601 of file n_gui.h.
Referenced by _draw_label(), n_gui_add_label(), n_gui_add_label_link(), n_gui_label_set_link(), and n_gui_process_event().
on_link_click
void(* N_GUI_LABEL_DATA::on_link_click) (int widget_id, const char *link, void *user_data)
callback when link is clicked (widget_id, link_url, user_data)
Definition at line 615 of file n_gui.h.
Referenced by n_gui_add_label(), n_gui_add_label_link(), and n_gui_process_event().
scroll_y
float N_GUI_LABEL_DATA::scroll_y
vertical scroll offset for overflowing text (pixels)
Definition at line 605 of file n_gui.h.
Referenced by _draw_label(), n_gui_add_label(), and n_gui_process_event().
sel_dragging
int N_GUI_LABEL_DATA::sel_dragging
1 if mouse is actively dragging to select text
Definition at line 611 of file n_gui.h.
Referenced by n_gui_add_label(), and n_gui_process_event().
sel_end
int N_GUI_LABEL_DATA::sel_end
selection end byte offset (-1 = no selection)
Definition at line 609 of file n_gui.h.
Referenced by _draw_label(), n_gui_add_label(), and n_gui_process_event().
sel_start
int N_GUI_LABEL_DATA::sel_start
selection start byte offset (-1 = no selection)
Definition at line 607 of file n_gui.h.
Referenced by _draw_label(), n_gui_add_label(), and n_gui_process_event().
text
char N_GUI_LABEL_DATA::text[4096]
text to display
Definition at line 599 of file n_gui.h.
Referenced by _draw_label(), _label_char_at_x(), _label_text_origin_x(), _window_update_content_size(), n_gui_add_label(), n_gui_label_set_text(), and n_gui_process_event().
user_data
void* N_GUI_LABEL_DATA::user_data
user data for callback
Definition at line 617 of file n_gui.h.
Referenced by n_gui_add_label(), n_gui_add_label_link(), and n_gui_process_event().
N_GUI_LISTBOX_DATA
struct N_GUI_LISTBOX_DATA
listbox specific data
Definition at line 492 of file n_gui.h.
Data Fields
ALLEGRO_BITMAP * bg_bitmap
optional bitmap for the listbox background (NULL = color theme)
int hover_row
index of the row the mouse is currently over, or -1.
ALLEGRO_BITMAP * item_bg_bitmap
optional bitmap for per-item background, normal state (NULL = color theme)
float item_height
item height in pixels
ALLEGRO_BITMAP * item_selected_bitmap
optional bitmap for per-item background, selected/highlighted (NULL = color theme)
N_GUI_LISTITEM * items
dynamic array of items
size_t items_capacity
allocated capacity
size_t nb_items
number of items
void(* on_select)(int widget_id, int index, int selected, void *user_data)
callback on selection change (widget_id, item_index, selected, user_data)
int scroll_offset
scroll offset in items
int selection_mode
selection mode: N_GUI_SELECT_NONE, N_GUI_SELECT_SINGLE, N_GUI_SELECT_MULTIPLE
void * user_data
user data for callback
Field Documentation
bg_bitmap
ALLEGRO_BITMAP* N_GUI_LISTBOX_DATA::bg_bitmap
optional bitmap for the listbox background (NULL = color theme)
Definition at line 506 of file n_gui.h.
Referenced by _draw_listbox(), and n_gui_listbox_set_bitmaps().
hover_row
int N_GUI_LISTBOX_DATA::hover_row
index of the row the mouse is currently over, or -1.
Updated in the event loop when the widget gains N_GUI_STATE_HOVER; consumed by the draw path to paint a hover highlight.
Definition at line 518 of file n_gui.h.
Referenced by _draw_listbox(), n_gui_add_listbox(), and n_gui_process_event().
item_bg_bitmap
ALLEGRO_BITMAP* N_GUI_LISTBOX_DATA::item_bg_bitmap
optional bitmap for per-item background, normal state (NULL = color theme)
Definition at line 508 of file n_gui.h.
Referenced by _draw_listbox(), and n_gui_listbox_set_bitmaps().
item_height
float N_GUI_LISTBOX_DATA::item_height
item height in pixels
Definition at line 504 of file n_gui.h.
Referenced by _draw_listbox(), _n_gui_tree_listbox_bounds(), n_gui_add_listbox(), n_gui_listbox_set_scroll_offset(), and n_gui_process_event().
item_selected_bitmap
ALLEGRO_BITMAP* N_GUI_LISTBOX_DATA::item_selected_bitmap
optional bitmap for per-item background, selected/highlighted (NULL = color theme)
Definition at line 510 of file n_gui.h.
Referenced by _draw_listbox(), and n_gui_listbox_set_bitmaps().
items
N_GUI_LISTITEM* N_GUI_LISTBOX_DATA::items
dynamic array of items
Definition at line 494 of file n_gui.h.
Referenced by _destroy_widget(), _draw_listbox(), n_gui_add_listbox(), n_gui_listbox_add_item(), n_gui_listbox_get_item_text(), n_gui_listbox_get_selected(), n_gui_listbox_is_selected(), n_gui_listbox_remove_item(), n_gui_listbox_set_selected(), and n_gui_process_event().
items_capacity
size_t N_GUI_LISTBOX_DATA::items_capacity
allocated capacity
Definition at line 498 of file n_gui.h.
Referenced by n_gui_add_listbox(), and n_gui_listbox_add_item().
nb_items
size_t N_GUI_LISTBOX_DATA::nb_items
number of items
Definition at line 496 of file n_gui.h.
Referenced by _draw_listbox(), _n_gui_tree_listbox_bounds(), n_gui_add_listbox(), n_gui_listbox_add_item(), n_gui_listbox_clear(), n_gui_listbox_get_selected(), n_gui_listbox_remove_item(), n_gui_listbox_set_scroll_offset(), n_gui_listbox_set_selected(), and n_gui_process_event().
on_select
void(* N_GUI_LISTBOX_DATA::on_select) (int widget_id, int index, int selected, void *user_data)
callback on selection change (widget_id, item_index, selected, user_data)
Definition at line 512 of file n_gui.h.
Referenced by n_gui_add_listbox(), and n_gui_process_event().
scroll_offset
int N_GUI_LISTBOX_DATA::scroll_offset
scroll offset in items
Definition at line 502 of file n_gui.h.
Referenced by _draw_listbox(), _n_gui_tree_listbox_bounds(), n_gui_add_listbox(), n_gui_listbox_clear(), n_gui_listbox_get_scroll_offset(), n_gui_listbox_remove_item(), n_gui_listbox_set_scroll_offset(), and n_gui_process_event().
selection_mode
int N_GUI_LISTBOX_DATA::selection_mode
selection mode: N_GUI_SELECT_NONE, N_GUI_SELECT_SINGLE, N_GUI_SELECT_MULTIPLE
Definition at line 500 of file n_gui.h.
Referenced by n_gui_add_listbox(), n_gui_listbox_set_selected(), and n_gui_process_event().
user_data
void* N_GUI_LISTBOX_DATA::user_data
user data for callback
Definition at line 514 of file n_gui.h.
Referenced by n_gui_add_listbox(), and n_gui_process_event().
N_GUI_LISTITEM
struct N_GUI_LISTITEM
a single item in a list/radio/combo widget
Definition at line 484 of file n_gui.h.
Data Fields
int selected selection state (for listbox)
char text[128] item display text
N_GUI_PENDING_GEOM
struct N_GUI_PENDING_GEOM
A saved window position retained for a window not yet created at load time (see N_GUI_CTX::pending_layout).
Applied on first matching create.
Definition at line 1022 of file n_gui.h.
Data Fields
unsigned char consumed 1 once applied to a created window
char title[128] window title to match on
float x saved x (already display-scaled)
float y saved y
N_GUI_RADIOLIST_DATA
struct N_GUI_RADIOLIST_DATA
radio list specific data
Definition at line 522 of file n_gui.h.
Data Fields
ALLEGRO_BITMAP * bg_bitmap
optional bitmap for the radiolist background (NULL = color theme)
ALLEGRO_BITMAP * item_bg_bitmap
optional bitmap for per-item background, normal state (NULL = color theme)
float item_height
item height in pixels
ALLEGRO_BITMAP * item_selected_bitmap
optional bitmap for per-item background, selected/highlighted (NULL = color theme)
N_GUI_LISTITEM * items
dynamic array of items
size_t items_capacity
allocated capacity
size_t nb_items
number of items
void(* on_select)(int widget_id, int index, void *user_data)
callback on selection change (widget_id, selected_index, user_data)
int scroll_offset
scroll offset in items
int selected_index
currently selected index (-1 = none)
void * user_data
user data for callback
Field Documentation
bg_bitmap
ALLEGRO_BITMAP* N_GUI_RADIOLIST_DATA::bg_bitmap
optional bitmap for the radiolist background (NULL = color theme)
Definition at line 536 of file n_gui.h.
Referenced by _draw_radiolist(), and n_gui_radiolist_set_bitmaps().
item_bg_bitmap
ALLEGRO_BITMAP* N_GUI_RADIOLIST_DATA::item_bg_bitmap
optional bitmap for per-item background, normal state (NULL = color theme)
Definition at line 538 of file n_gui.h.
Referenced by _draw_radiolist(), and n_gui_radiolist_set_bitmaps().
item_height
float N_GUI_RADIOLIST_DATA::item_height
item height in pixels
Definition at line 534 of file n_gui.h.
Referenced by _draw_radiolist(), n_gui_add_radiolist(), and n_gui_process_event().
item_selected_bitmap
ALLEGRO_BITMAP* N_GUI_RADIOLIST_DATA::item_selected_bitmap
optional bitmap for per-item background, selected/highlighted (NULL = color theme)
Definition at line 540 of file n_gui.h.
Referenced by _draw_radiolist(), and n_gui_radiolist_set_bitmaps().
items
N_GUI_LISTITEM* N_GUI_RADIOLIST_DATA::items
dynamic array of items
Definition at line 524 of file n_gui.h.
Referenced by _destroy_widget(), _draw_radiolist(), n_gui_add_radiolist(), and n_gui_radiolist_add_item().
items_capacity
size_t N_GUI_RADIOLIST_DATA::items_capacity
allocated capacity
Definition at line 528 of file n_gui.h.
Referenced by n_gui_add_radiolist(), and n_gui_radiolist_add_item().
nb_items
size_t N_GUI_RADIOLIST_DATA::nb_items
number of items
Definition at line 526 of file n_gui.h.
Referenced by _draw_radiolist(), n_gui_add_radiolist(), n_gui_process_event(), n_gui_radiolist_add_item(), and n_gui_radiolist_clear().
on_select
void(* N_GUI_RADIOLIST_DATA::on_select) (int widget_id, int index, void *user_data)
callback on selection change (widget_id, selected_index, user_data)
Definition at line 542 of file n_gui.h.
Referenced by n_gui_add_radiolist(), and n_gui_process_event().
scroll_offset
int N_GUI_RADIOLIST_DATA::scroll_offset
scroll offset in items
Definition at line 532 of file n_gui.h.
Referenced by _draw_radiolist(), n_gui_add_radiolist(), n_gui_process_event(), and n_gui_radiolist_clear().
selected_index
int N_GUI_RADIOLIST_DATA::selected_index
currently selected index (-1 = none)
Definition at line 530 of file n_gui.h.
Referenced by _draw_radiolist(), n_gui_add_radiolist(), n_gui_process_event(), n_gui_radiolist_clear(), and n_gui_radiolist_set_selected().
user_data
void* N_GUI_RADIOLIST_DATA::user_data
user data for callback
Definition at line 544 of file n_gui.h.
Referenced by n_gui_add_radiolist(), and n_gui_process_event().
N_GUI_SCROLLBAR_DATA
struct N_GUI_SCROLLBAR_DATA
scrollbar specific data
Definition at line 458 of file n_gui.h.
Data Fields
double content_size
total content size
void(* on_scroll)(int widget_id, double scroll_pos, void *user_data)
callback on scroll
int orientation
orientation: N_GUI_SCROLLBAR_H or N_GUI_SCROLLBAR_V
double scroll_pos
current scroll position
int shape
shape type: N_GUI_SHAPE_RECT or N_GUI_SHAPE_ROUNDED
ALLEGRO_BITMAP * thumb_active_bitmap
optional bitmap for the thumb while dragging (NULL = fallback to thumb_bitmap)
ALLEGRO_BITMAP * thumb_bitmap
optional bitmap for the thumb/handle, normal state (NULL = color theme)
ALLEGRO_BITMAP * thumb_hover_bitmap
optional bitmap for the thumb on hover (NULL = fallback to thumb_bitmap)
ALLEGRO_BITMAP * track_bitmap
optional bitmap for the scrollbar track background (NULL = color theme)
void * user_data
user data for callback
double viewport_size
visible viewport size
Field Documentation
content_size
double N_GUI_SCROLLBAR_DATA::content_size
total content size
Definition at line 462 of file n_gui.h.
Referenced by _draw_scrollbar(), _scrollbar_update_from_mouse(), n_gui_add_scrollbar(), n_gui_process_event(), n_gui_scrollbar_set_pos(), and n_gui_scrollbar_set_sizes().
on_scroll
void(* N_GUI_SCROLLBAR_DATA::on_scroll) (int widget_id, double scroll_pos, void *user_data)
callback on scroll
Definition at line 478 of file n_gui.h.
Referenced by _scrollbar_update_from_mouse(), n_gui_add_scrollbar(), and n_gui_process_event().
orientation
int N_GUI_SCROLLBAR_DATA::orientation
orientation: N_GUI_SCROLLBAR_H or N_GUI_SCROLLBAR_V
Definition at line 460 of file n_gui.h.
Referenced by _draw_scrollbar(), _scrollbar_update_from_mouse(), n_gui_add_scrollbar(), and n_gui_process_event().
scroll_pos
double N_GUI_SCROLLBAR_DATA::scroll_pos
current scroll position
Definition at line 466 of file n_gui.h.
Referenced by _draw_scrollbar(), _scrollbar_update_from_mouse(), n_gui_add_scrollbar(), n_gui_process_event(), n_gui_scrollbar_set_pos(), and n_gui_scrollbar_set_sizes().
shape
int N_GUI_SCROLLBAR_DATA::shape
shape type: N_GUI_SHAPE_RECT or N_GUI_SHAPE_ROUNDED
Definition at line 468 of file n_gui.h.
Referenced by _draw_scrollbar(), and n_gui_add_scrollbar().
thumb_active_bitmap
ALLEGRO_BITMAP* N_GUI_SCROLLBAR_DATA::thumb_active_bitmap
optional bitmap for the thumb while dragging (NULL = fallback to thumb_bitmap)
Definition at line 476 of file n_gui.h.
Referenced by _draw_scrollbar(), and n_gui_scrollbar_set_bitmaps().
thumb_bitmap
ALLEGRO_BITMAP* N_GUI_SCROLLBAR_DATA::thumb_bitmap
optional bitmap for the thumb/handle, normal state (NULL = color theme)
Definition at line 472 of file n_gui.h.
Referenced by _draw_scrollbar(), and n_gui_scrollbar_set_bitmaps().
thumb_hover_bitmap
ALLEGRO_BITMAP* N_GUI_SCROLLBAR_DATA::thumb_hover_bitmap
optional bitmap for the thumb on hover (NULL = fallback to thumb_bitmap)
Definition at line 474 of file n_gui.h.
Referenced by _draw_scrollbar(), and n_gui_scrollbar_set_bitmaps().
track_bitmap
ALLEGRO_BITMAP* N_GUI_SCROLLBAR_DATA::track_bitmap
optional bitmap for the scrollbar track background (NULL = color theme)
Definition at line 470 of file n_gui.h.
Referenced by _draw_scrollbar(), and n_gui_scrollbar_set_bitmaps().
user_data
void* N_GUI_SCROLLBAR_DATA::user_data
user data for callback
Definition at line 480 of file n_gui.h.
Referenced by _scrollbar_update_from_mouse(), n_gui_add_scrollbar(), and n_gui_process_event().
viewport_size
double N_GUI_SCROLLBAR_DATA::viewport_size
visible viewport size
Definition at line 464 of file n_gui.h.
Referenced by _draw_scrollbar(), _scrollbar_update_from_mouse(), n_gui_add_scrollbar(), n_gui_process_event(), n_gui_scrollbar_set_pos(), and n_gui_scrollbar_set_sizes().
N_GUI_SECTION
struct N_GUI_SECTION
a single foldable section: a clickable header plus the member widgets it shows/hides
Definition at line 1735 of file n_gui.h.
Data Fields
int folded 1 = collapsed (members hidden), 0 = expanded
int header_id clickable header button widget id
float natural_h stacked height of the members when expanded
int nb_widgets number of member widgets
char title[64] section title (header label minus the fold glyph)
float widget_dy[48] each member's y offset from the section content top, captured at add time
int widget_ids[48] member widget ids
N_GUI_SECTIONLIST
struct N_GUI_SECTIONLIST
a vertical accordion of foldable sections inside one window; folding hides a section's widgets and re-stacks the rest, leaving the window's N_GUI_WIN_AUTO_SCROLLBAR to absorb any overflow
Definition at line 1748 of file n_gui.h.
Data Fields
N_GUI_CTX * ctx
GUI context.
float first_inset
content-local left inset applied to the FIRST header only, so a button can sit before it on the same row (0 = none)
float gap
vertical gap between rows
float header_h
header button height
int nb_sections
number of sections
void(* on_toggle)(int, int, void *)
callback(section_index, folded, user_data) on a header click (may be NULL)
N_GUI_SECTION sections [16]
section storage
void * user_data
user data for the callback
float width
header width
int window_id
window holding the headers and members
float x
content-local x of every header and the layout origin
float y0
content-local y of the first header
Field Documentation
ctx
N_GUI_CTX* N_GUI_SECTIONLIST::ctx
GUI context.
Definition at line 1749 of file n_gui.h.
Referenced by _n_gui_sectionlist_set_header_label(), n_gui_sectionlist_add_section(), n_gui_sectionlist_add_widget(), n_gui_sectionlist_create(), and n_gui_sectionlist_relayout().
first_inset
float N_GUI_SECTIONLIST::first_inset
content-local left inset applied to the FIRST header only, so a button can sit before it on the same row (0 = none)
Definition at line 1758 of file n_gui.h.
Referenced by n_gui_sectionlist_relayout(), and n_gui_sectionlist_set_first_inset().
gap
float N_GUI_SECTIONLIST::gap
vertical gap between rows
Definition at line 1755 of file n_gui.h.
Referenced by n_gui_sectionlist_add_widget(), n_gui_sectionlist_content_height(), n_gui_sectionlist_create(), and n_gui_sectionlist_relayout().
header_h
float N_GUI_SECTIONLIST::header_h
header button height
Definition at line 1754 of file n_gui.h.
Referenced by n_gui_sectionlist_add_section(), n_gui_sectionlist_add_widget(), n_gui_sectionlist_content_height(), n_gui_sectionlist_create(), and n_gui_sectionlist_relayout().
nb_sections
int N_GUI_SECTIONLIST::nb_sections
number of sections
Definition at line 1757 of file n_gui.h.
Referenced by _n_gui_sectionlist_header_clicked(), n_gui_sectionlist_add_section(), n_gui_sectionlist_add_widget(), n_gui_sectionlist_content_height(), n_gui_sectionlist_create(), n_gui_sectionlist_get_count(), n_gui_sectionlist_is_folded(), n_gui_sectionlist_relayout(), and n_gui_sectionlist_set_folded().
on_toggle
void(* N_GUI_SECTIONLIST::on_toggle) (int, int, void *)
callback(section_index, folded, user_data) on a header click (may be NULL)
Definition at line 1759 of file n_gui.h.
Referenced by _n_gui_sectionlist_header_clicked(), and n_gui_sectionlist_create().
sections
N_GUI_SECTION N_GUI_SECTIONLIST::sections[16]
section storage
Definition at line 1756 of file n_gui.h.
Referenced by _n_gui_sectionlist_header_clicked(), _n_gui_sectionlist_set_header_label(), n_gui_sectionlist_add_section(), n_gui_sectionlist_add_widget(), n_gui_sectionlist_content_height(), n_gui_sectionlist_is_folded(), n_gui_sectionlist_relayout(), and n_gui_sectionlist_set_folded().
user_data
void* N_GUI_SECTIONLIST::user_data
user data for the callback
Definition at line 1760 of file n_gui.h.
Referenced by _n_gui_sectionlist_header_clicked(), and n_gui_sectionlist_create().
width
float N_GUI_SECTIONLIST::width
header width
Definition at line 1753 of file n_gui.h.
Referenced by n_gui_sectionlist_add_section(), n_gui_sectionlist_create(), and n_gui_sectionlist_relayout().
window_id
int N_GUI_SECTIONLIST::window_id
window holding the headers and members
Definition at line 1750 of file n_gui.h.
Referenced by n_gui_sectionlist_add_section(), n_gui_sectionlist_create(), and n_gui_sectionlist_relayout().
x
float N_GUI_SECTIONLIST::x
content-local x of every header and the layout origin
Definition at line 1751 of file n_gui.h.
Referenced by n_gui_sectionlist_add_section(), n_gui_sectionlist_create(), and n_gui_sectionlist_relayout().
y0
float N_GUI_SECTIONLIST::y0
content-local y of the first header
Definition at line 1752 of file n_gui.h.
Referenced by n_gui_sectionlist_content_height(), n_gui_sectionlist_create(), and n_gui_sectionlist_relayout().
N_GUI_SLIDER_DATA
struct N_GUI_SLIDER_DATA
slider specific data
Definition at line 363 of file n_gui.h.
Data Fields
ALLEGRO_BITMAP * fill_bitmap
optional bitmap for the filled portion of the track (NULL = color theme)
ALLEGRO_BITMAP * handle_active_bitmap
optional bitmap for the handle while dragging (NULL = fallback to handle_bitmap)
ALLEGRO_BITMAP * handle_bitmap
optional bitmap for the draggable handle, normal state (NULL = color theme)
ALLEGRO_BITMAP * handle_hover_bitmap
optional bitmap for the handle on hover (NULL = fallback to handle_bitmap)
double max_val
maximum value
double min_val
minimum value
int mode
mode: N_GUI_SLIDER_VALUE or N_GUI_SLIDER_PERCENT
void(* on_change)(int widget_id, double value, void *user_data)
callback on value change
int orientation
orientation: N_GUI_SLIDER_H or N_GUI_SLIDER_V
double step
step increment (0 is treated as 1).
ALLEGRO_BITMAP * track_bitmap
optional bitmap for the track/rail background (NULL = color theme)
void * user_data
user data for callback
double value
current value (always snapped to step)
char value_format [32]
printf-style format string applied to the numeric value when the built-in readout draws.
int value_visible
draw the built-in value label next to/below the handle.
Field Documentation
fill_bitmap
ALLEGRO_BITMAP* N_GUI_SLIDER_DATA::fill_bitmap
optional bitmap for the filled portion of the track (NULL = color theme)
Definition at line 379 of file n_gui.h.
Referenced by _draw_slider(), and n_gui_slider_set_bitmaps().
handle_active_bitmap
ALLEGRO_BITMAP* N_GUI_SLIDER_DATA::handle_active_bitmap
optional bitmap for the handle while dragging (NULL = fallback to handle_bitmap)
Definition at line 385 of file n_gui.h.
Referenced by _draw_slider(), and n_gui_slider_set_bitmaps().
handle_bitmap
ALLEGRO_BITMAP* N_GUI_SLIDER_DATA::handle_bitmap
optional bitmap for the draggable handle, normal state (NULL = color theme)
Definition at line 381 of file n_gui.h.
Referenced by _draw_slider(), and n_gui_slider_set_bitmaps().
handle_hover_bitmap
ALLEGRO_BITMAP* N_GUI_SLIDER_DATA::handle_hover_bitmap
optional bitmap for the handle on hover (NULL = fallback to handle_bitmap)
Definition at line 383 of file n_gui.h.
Referenced by _draw_slider(), and n_gui_slider_set_bitmaps().
max_val
double N_GUI_SLIDER_DATA::max_val
maximum value
Definition at line 367 of file n_gui.h.
Referenced by _draw_slider(), _slider_update_from_mouse(), n_gui_add_slider(), n_gui_process_event(), n_gui_slider_set_range(), n_gui_slider_set_step(), and n_gui_slider_set_value().
min_val
double N_GUI_SLIDER_DATA::min_val
minimum value
Definition at line 365 of file n_gui.h.
Referenced by _draw_slider(), _slider_update_from_mouse(), n_gui_add_slider(), n_gui_process_event(), n_gui_slider_set_range(), n_gui_slider_set_step(), and n_gui_slider_set_value().
mode
int N_GUI_SLIDER_DATA::mode
mode: N_GUI_SLIDER_VALUE or N_GUI_SLIDER_PERCENT
Definition at line 373 of file n_gui.h.
Referenced by _draw_slider(), and n_gui_add_slider().
on_change
void(* N_GUI_SLIDER_DATA::on_change) (int widget_id, double value, void *user_data)
callback on value change
Definition at line 387 of file n_gui.h.
Referenced by _slider_update_from_mouse(), n_gui_add_slider(), and n_gui_process_event().
orientation
int N_GUI_SLIDER_DATA::orientation
orientation: N_GUI_SLIDER_H or N_GUI_SLIDER_V
Definition at line 375 of file n_gui.h.
Referenced by _draw_slider(), _slider_update_from_mouse(), n_gui_add_slider(), and n_gui_process_event().
step
double N_GUI_SLIDER_DATA::step
step increment (0 is treated as 1).
All values snap to nearest multiple of step from min_val.
Definition at line 371 of file n_gui.h.
Referenced by _slider_update_from_mouse(), n_gui_add_slider(), n_gui_process_event(), n_gui_slider_set_range(), n_gui_slider_set_step(), and n_gui_slider_set_value().
track_bitmap
ALLEGRO_BITMAP* N_GUI_SLIDER_DATA::track_bitmap
optional bitmap for the track/rail background (NULL = color theme)
Definition at line 377 of file n_gui.h.
Referenced by _draw_slider(), and n_gui_slider_set_bitmaps().
user_data
void* N_GUI_SLIDER_DATA::user_data
user data for callback
Definition at line 389 of file n_gui.h.
Referenced by _slider_update_from_mouse(), n_gui_add_slider(), and n_gui_process_event().
value
double N_GUI_SLIDER_DATA::value
current value (always snapped to step)
Definition at line 369 of file n_gui.h.
Referenced by _draw_slider(), _slider_update_from_mouse(), n_gui_add_slider(), n_gui_process_event(), n_gui_slider_set_range(), n_gui_slider_set_step(), and n_gui_slider_set_value().
value_format
char N_GUI_SLIDER_DATA::value_format[32]
printf-style format string applied to the numeric value when the built-in readout draws.
Empty (first byte '\0') selects the legacy defaults: "%.1f" for VALUE mode, "%.0f%%" for PERCENT. Set via n_gui_slider_set_value_format().
Definition at line 394 of file n_gui.h.
Referenced by _draw_slider(), n_gui_add_slider(), and n_gui_slider_set_value_format().
value_visible
int N_GUI_SLIDER_DATA::value_visible
draw the built-in value label next to/below the handle.
Default 1 (on) for backward compatibility. Set to 0 when the consumer is already painting the value elsewhere (e.g. a status bar) to avoid the double-render gotcha.
Definition at line 399 of file n_gui.h.
Referenced by _draw_slider(), n_gui_add_slider(), and n_gui_slider_set_value_visible().
N_GUI_STYLE
struct N_GUI_STYLE
Global style holding every configurable layout constant.
Initialised with sensible defaults by n_gui_default_style(). Can be serialised/deserialised to/from JSON with n_gui_style_to_json / n_gui_style_from_json.
Definition at line 852 of file n_gui.h.
Data Fields
float checkbox_label_gap gap between box and label text
float checkbox_label_offset horizontal offset from box edge to label text
float checkbox_mark_margin checkmark inset from box edge
float checkbox_mark_thickness checkmark line thickness
float checkbox_max_size maximum box size
float combobox_max_dropdown_width maximum dropdown width for N_GUI_COMBOBOX_AUTO_WIDTH (0 = display width)
int combobox_max_visible default max visible items for combobox dropdown
float dropdown_arrow_half_h vertical half-extent of the arrow chevron
float dropdown_arrow_half_w horizontal half-extent of the arrow chevron
float dropdown_arrow_reserve horizontal space reserved for the arrow on the right
float dropdown_arrow_thickness arrow stroke thickness
float dropdown_border_thickness dropdown panel border thickness
int dropmenu_max_visible default max visible items for dropmenu panel
float global_scroll_step pixels per mouse wheel notch for global scroll
float global_scrollbar_border_thickness global thumb border thickness
float global_scrollbar_size global scrollbar track width/height
ALLEGRO_COLOR global_scrollbar_thumb_border_color global scrollbar thumb border colour
ALLEGRO_COLOR global_scrollbar_thumb_color global scrollbar thumb colour
float global_scrollbar_thumb_corner_r global thumb corner radius
float global_scrollbar_thumb_min global minimum thumb dimension
float global_scrollbar_thumb_padding global thumb inset from track edge
ALLEGRO_COLOR global_scrollbar_track_color global scrollbar track colour
ALLEGRO_COLOR grip_color grip line colour
float grip_line_thickness grip line thickness
float grip_size grip area size
float item_height_pad min padding added to font height for item height
float item_selection_inset item highlight inset from left/right edges
float item_text_padding text padding inside list/combo/dropmenu items
float label_padding horizontal padding each side
ALLEGRO_COLOR link_color_hover link colour (hover)
ALLEGRO_COLOR link_color_normal link colour (normal)
float link_underline_thickness link underline thickness
float listbox_default_item_height default item height for listbox
float min_win_h minimum window height (for resize)
float min_win_w minimum window width (for resize)
float radio_circle_border_thickness outer circle border thickness
float radio_circle_min_r minimum outer circle radius
float radio_inner_offset inner filled circle shrink from outer
float radio_label_gap gap between circle and label text
float radiolist_default_item_height default item height for radiolist
float scroll_step pixels per mouse wheel notch for window auto-scroll
float scrollbar_size scrollbar track width/height
ALLEGRO_COLOR scrollbar_thumb_color scrollbar thumb colour
float scrollbar_thumb_corner_r thumb corner radius
float scrollbar_thumb_min minimum thumb dimension
float scrollbar_thumb_padding thumb inset from track edge
ALLEGRO_COLOR scrollbar_track_color scrollbar track colour
float slider_handle_border_thickness handle border thickness
float slider_handle_edge_offset handle circle offset from edge
float slider_handle_min_r minimum handle circle radius
float slider_track_border_thickness track outline thickness
float slider_track_corner_r track corner radius
float slider_track_size track width (vertical) or height (horizontal)
float slider_value_label_offset gap between slider end and value label
float tb_btn_glyph_thickness line thickness for titlebar button glyphs
float tb_btn_right_margin right margin from window edge to rightmost button
float tb_btn_size titlebar button size (0 = auto: titlebar_h - 4)
float tb_btn_spacing gap between titlebar buttons
float textarea_cursor_blink_period cursor blink period in seconds (full cycle on+off)
float textarea_cursor_width cursor width in pixels
float textarea_padding
float title_max_w_reserve pixels reserved right of title for truncation
float title_padding padding left of title text
float titlebar_h title bar height
ALLEGRO_COLOR tooltip_bg tooltip bubble background color
ALLEGRO_COLOR tooltip_border tooltip bubble border color
float tooltip_delay inner padding
seconds the pointer must rest on a widget before its tooltip shows
ALLEGRO_COLOR tooltip_fg tooltip text color
N_GUI_TAB_PANEL
struct N_GUI_TAB_PANEL
tab panel built from toggle buttons with content window management
Definition at line 1700 of file n_gui.h.
Data Fields
int active_tab
currently active tab index
float button_h
height of each tab button
int button_ids [16]
toggle button widget IDs
float button_w
width of each tab button
int content_window_ids [16]
content window IDs (-1 = none)
N_GUI_CTX * ctx
GUI context.
int nb_tabs
number of tabs
void(* on_tab_change)(int, void *)
callback on tab switch (may be NULL)
int parent_window_id
parent window for tab buttons
void * user_data
user data for callback
float x
x origin of first tab button
float y
y origin of tab button row
Field Documentation
active_tab
int N_GUI_TAB_PANEL::active_tab
currently active tab index
Definition at line 1706 of file n_gui.h.
Referenced by n_gui_tab_add(), n_gui_tab_create(), n_gui_tab_get_active(), and n_gui_tab_set_active().
button_h
float N_GUI_TAB_PANEL::button_h
height of each tab button
Definition at line 1710 of file n_gui.h.
Referenced by n_gui_tab_add(), and n_gui_tab_create().
button_ids
int N_GUI_TAB_PANEL::button_ids[16]
toggle button widget IDs
Definition at line 1703 of file n_gui.h.
Referenced by _n_gui_tab_button_clicked(), n_gui_tab_add(), n_gui_tab_create(), and n_gui_tab_set_active().
button_w
float N_GUI_TAB_PANEL::button_w
width of each tab button
Definition at line 1709 of file n_gui.h.
Referenced by n_gui_tab_add(), and n_gui_tab_create().
content_window_ids
int N_GUI_TAB_PANEL::content_window_ids[16]
content window IDs (-1 = none)
Definition at line 1704 of file n_gui.h.
Referenced by n_gui_tab_create(), n_gui_tab_set_active(), and n_gui_tab_set_content_window().
ctx
N_GUI_CTX* N_GUI_TAB_PANEL::ctx
GUI context.
Definition at line 1701 of file n_gui.h.
Referenced by n_gui_tab_add(), n_gui_tab_create(), and n_gui_tab_set_active().
nb_tabs
int N_GUI_TAB_PANEL::nb_tabs
number of tabs
Definition at line 1705 of file n_gui.h.
Referenced by _n_gui_tab_button_clicked(), n_gui_tab_add(), n_gui_tab_create(), n_gui_tab_set_active(), and n_gui_tab_set_content_window().
on_tab_change
void(* N_GUI_TAB_PANEL::on_tab_change) (int, void *)
callback on tab switch (may be NULL)
Definition at line 1711 of file n_gui.h.
Referenced by _n_gui_tab_button_clicked(), and n_gui_tab_create().
parent_window_id
int N_GUI_TAB_PANEL::parent_window_id
parent window for tab buttons
Definition at line 1702 of file n_gui.h.
Referenced by n_gui_tab_add(), and n_gui_tab_create().
user_data
void* N_GUI_TAB_PANEL::user_data
user data for callback
Definition at line 1712 of file n_gui.h.
Referenced by _n_gui_tab_button_clicked(), and n_gui_tab_create().
x
float N_GUI_TAB_PANEL::x
x origin of first tab button
Definition at line 1707 of file n_gui.h.
Referenced by n_gui_tab_add(), and n_gui_tab_create().
y
float N_GUI_TAB_PANEL::y
y origin of tab button row
Definition at line 1708 of file n_gui.h.
Referenced by n_gui_tab_add(), and n_gui_tab_create().
N_GUI_TB_BUTTONS
struct N_GUI_TB_BUTTONS
Titlebar button state for a window (minimize, maximize, close)
Definition at line 715 of file n_gui.h.
Data Fields
N_GUI_THEME btn_theme
theme for minimize and maximize buttons
ALLEGRO_BITMAP * close_active_bitmap
optional bitmap for close button active state
ALLEGRO_BITMAP * close_bitmap
optional bitmap for close button normal state (NULL = color theme)
ALLEGRO_BITMAP * close_hover_bitmap
optional bitmap for close button hover state
N_GUI_THEME close_theme
theme for close button (defaults to red hover/active)
int hovered
which button is currently hovered (N_GUI_TB_BTN_*)
ALLEGRO_BITMAP * maximize_active_bitmap
optional bitmap for maximize button active state
ALLEGRO_BITMAP * maximize_bitmap
optional bitmap for maximize button normal state (NULL = color theme)
ALLEGRO_BITMAP * maximize_hover_bitmap
optional bitmap for maximize button hover state
ALLEGRO_BITMAP * minimize_active_bitmap
optional bitmap for minimize button active state
ALLEGRO_BITMAP * minimize_bitmap
optional bitmap for minimize button normal state (NULL = color theme)
ALLEGRO_BITMAP * minimize_hover_bitmap
optional bitmap for minimize button hover state
void(* on_close)(int window_id, void *user_data)
callback on close button click (NULL = default: clear N_GUI_WIN_OPEN)
void * on_close_user_data
user data for on_close callback
void(* on_maximize)(int window_id, void *user_data)
callback on maximize button click (NULL = default: toggle N_GUI_WIN_MAXIMISED)
void * on_maximize_user_data
user data for on_maximize callback
void(* on_minimize)(int window_id, void *user_data)
callback on minimize button click (NULL = default: toggle N_GUI_WIN_MINIMISED)
void * on_minimize_user_data
user data for on_minimize callback
int pressed
which button is currently pressed (N_GUI_TB_BTN_*)
float restore_h
saved height before maximise (for restore)
float restore_w
saved width before maximise (for restore)
float restore_x
saved x position before maximise (for restore)
float restore_y
saved y position before maximise (for restore)
Field Documentation
btn_theme
N_GUI_THEME N_GUI_TB_BUTTONS::btn_theme
theme for minimize and maximize buttons
Definition at line 729 of file n_gui.h.
Referenced by _draw_tb_buttons(), n_gui_add_window(), n_gui_reset_all_widget_themes(), and n_gui_window_set_tb_btn_theme().
close_active_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::close_active_bitmap
optional bitmap for close button active state
Definition at line 749 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
close_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::close_bitmap
optional bitmap for close button normal state (NULL = color theme)
Definition at line 745 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
close_hover_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::close_hover_bitmap
optional bitmap for close button hover state
Definition at line 747 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
close_theme
N_GUI_THEME N_GUI_TB_BUTTONS::close_theme
theme for close button (defaults to red hover/active)
Definition at line 731 of file n_gui.h.
Referenced by _draw_tb_buttons(), n_gui_add_window(), n_gui_reset_all_widget_themes(), and n_gui_window_set_tb_close_theme().
hovered
int N_GUI_TB_BUTTONS::hovered
which button is currently hovered (N_GUI_TB_BTN_*)
Definition at line 717 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_process_event().
maximize_active_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::maximize_active_bitmap
optional bitmap for maximize button active state
Definition at line 743 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
maximize_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::maximize_bitmap
optional bitmap for maximize button normal state (NULL = color theme)
Definition at line 739 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
maximize_hover_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::maximize_hover_bitmap
optional bitmap for maximize button hover state
Definition at line 741 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
minimize_active_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::minimize_active_bitmap
optional bitmap for minimize button active state
Definition at line 737 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
minimize_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::minimize_bitmap
optional bitmap for minimize button normal state (NULL = color theme)
Definition at line 733 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
minimize_hover_bitmap
ALLEGRO_BITMAP* N_GUI_TB_BUTTONS::minimize_hover_bitmap
optional bitmap for minimize button hover state
Definition at line 735 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_window_set_tb_button_bitmaps().
on_close
void(* N_GUI_TB_BUTTONS::on_close) (int window_id, void *user_data)
callback on close button click (NULL = default: clear N_GUI_WIN_OPEN)
Definition at line 759 of file n_gui.h.
Referenced by _tb_button_action(), and n_gui_window_set_close_callback().
on_close_user_data
void* N_GUI_TB_BUTTONS::on_close_user_data
user data for on_close callback
Definition at line 761 of file n_gui.h.
Referenced by _tb_button_action(), and n_gui_window_set_close_callback().
on_maximize
void(* N_GUI_TB_BUTTONS::on_maximize) (int window_id, void *user_data)
callback on maximize button click (NULL = default: toggle N_GUI_WIN_MAXIMISED)
Definition at line 755 of file n_gui.h.
Referenced by _tb_button_action(), and n_gui_window_set_maximize_callback().
on_maximize_user_data
void* N_GUI_TB_BUTTONS::on_maximize_user_data
user data for on_maximize callback
Definition at line 757 of file n_gui.h.
Referenced by _tb_button_action(), and n_gui_window_set_maximize_callback().
on_minimize
void(* N_GUI_TB_BUTTONS::on_minimize) (int window_id, void *user_data)
callback on minimize button click (NULL = default: toggle N_GUI_WIN_MINIMISED)
Definition at line 751 of file n_gui.h.
Referenced by _tb_button_action(), and n_gui_window_set_minimize_callback().
on_minimize_user_data
void* N_GUI_TB_BUTTONS::on_minimize_user_data
user data for on_minimize callback
Definition at line 753 of file n_gui.h.
Referenced by _tb_button_action(), and n_gui_window_set_minimize_callback().
pressed
int N_GUI_TB_BUTTONS::pressed
which button is currently pressed (N_GUI_TB_BTN_*)
Definition at line 719 of file n_gui.h.
Referenced by _draw_tb_buttons(), and n_gui_process_event().
restore_h
float N_GUI_TB_BUTTONS::restore_h
saved height before maximise (for restore)
Definition at line 727 of file n_gui.h.
Referenced by n_gui_maximize_window().
restore_w
float N_GUI_TB_BUTTONS::restore_w
saved width before maximise (for restore)
Definition at line 725 of file n_gui.h.
Referenced by n_gui_maximize_window().
restore_x
float N_GUI_TB_BUTTONS::restore_x
saved x position before maximise (for restore)
Definition at line 721 of file n_gui.h.
Referenced by n_gui_maximize_window().
restore_y
float N_GUI_TB_BUTTONS::restore_y
saved y position before maximise (for restore)
Definition at line 723 of file n_gui.h.
Referenced by n_gui_maximize_window().
N_GUI_TEXT_DIMS
struct N_GUI_TEXT_DIMS
bounding box dimensions returned by n_gui_get_text_dims()
Definition at line 273 of file n_gui.h.
Data Fields
int h bounding box height in pixels
int w bounding box width in pixels
int x bounding box x offset from draw origin
int y bounding box y offset from draw origin
N_GUI_TEXTAREA_DATA
struct N_GUI_TEXTAREA_DATA
text area specific data
Definition at line 403 of file n_gui.h.
Data Fields
ALLEGRO_BITMAP * bg_bitmap
optional bitmap for the text area background (NULL = color theme)
size_t char_limit
maximum character limit (0 = N_GUI_TEXT_MAX)
size_t cursor_pos
cursor position in text
double cursor_time
timestamp of last cursor activity (for blink reset)
char mask_char
mask character for password fields (0 = no masking, e.g.
int multiline
0 = single line, 1 = multiline
void(* on_change)(int widget_id, const char *text, void *user_data)
callback on text change
int scroll_from_wheel
set to 1 when scroll was changed by mouse wheel, cleared on key input
float scroll_x
horizontal scroll offset for single-line text (pixels)
int scroll_y
scroll offset for long text
size_t sel_end
selection end position (tracks cursor during selection)
size_t sel_start
selection anchor position (where shift-click/shift-arrow started).
char * text
text content (dynamically allocated, text_alloc bytes)
size_t text_alloc
allocated buffer size (char_limit + 1)
size_t text_len
current text length
void * user_data
user data for callback
Field Documentation
bg_bitmap
ALLEGRO_BITMAP* N_GUI_TEXTAREA_DATA::bg_bitmap
optional bitmap for the text area background (NULL = color theme)
Definition at line 430 of file n_gui.h.
Referenced by _draw_textarea(), and n_gui_add_textarea().
char_limit
size_t N_GUI_TEXTAREA_DATA::char_limit
maximum character limit (0 = N_GUI_TEXT_MAX)
Definition at line 411 of file n_gui.h.
Referenced by _textarea_handle_key(), n_gui_add_textarea(), and n_gui_textarea_set_text().
cursor_pos
size_t N_GUI_TEXTAREA_DATA::cursor_pos
cursor position in text
Definition at line 415 of file n_gui.h.
Referenced by _draw_textarea(), _textarea_clear_selection(), _textarea_delete_selection(), _textarea_handle_key(), n_gui_add_textarea(), n_gui_process_event(), n_gui_textarea_set_selection(), and n_gui_textarea_set_text().
cursor_time
double N_GUI_TEXTAREA_DATA::cursor_time
timestamp of last cursor activity (for blink reset)
Definition at line 428 of file n_gui.h.
Referenced by _draw_textarea(), _textarea_handle_key(), n_gui_add_textarea(), n_gui_process_event(), and n_gui_set_focus().
mask_char
char N_GUI_TEXTAREA_DATA::mask_char
mask character for password fields (0 = no masking, e.g.
'*')
Definition at line 432 of file n_gui.h.
Referenced by _draw_textarea(), _textarea_pos_from_mouse(), and n_gui_add_textarea().
multiline
int N_GUI_TEXTAREA_DATA::multiline
0 = single line, 1 = multiline
Definition at line 413 of file n_gui.h.
Referenced by _draw_textarea(), _textarea_handle_key(), _textarea_pos_from_mouse(), n_gui_add_textarea(), n_gui_process_event(), n_gui_textarea_scroll_to_bottom(), and n_gui_textarea_scroll_to_offset().
on_change
void(* N_GUI_TEXTAREA_DATA::on_change) (int widget_id, const char *text, void *user_data)
callback on text change
Definition at line 434 of file n_gui.h.
Referenced by _textarea_delete_selection(), _textarea_handle_key(), and n_gui_add_textarea().
scroll_from_wheel
int N_GUI_TEXTAREA_DATA::scroll_from_wheel
set to 1 when scroll was changed by mouse wheel, cleared on key input
Definition at line 426 of file n_gui.h.
Referenced by _draw_textarea(), _textarea_handle_key(), n_gui_process_event(), and n_gui_textarea_scroll_to_offset().
scroll_x
float N_GUI_TEXTAREA_DATA::scroll_x
horizontal scroll offset for single-line text (pixels)
Definition at line 424 of file n_gui.h.
Referenced by _draw_textarea(), _textarea_pos_from_mouse(), n_gui_add_textarea(), and n_gui_textarea_set_text().
scroll_y
int N_GUI_TEXTAREA_DATA::scroll_y
scroll offset for long text
Definition at line 422 of file n_gui.h.
Referenced by _draw_textarea(), _textarea_pos_from_mouse(), n_gui_add_textarea(), n_gui_process_event(), n_gui_textarea_scroll_to_bottom(), and n_gui_textarea_scroll_to_offset().
sel_end
size_t N_GUI_TEXTAREA_DATA::sel_end
selection end position (tracks cursor during selection)
Definition at line 420 of file n_gui.h.
Referenced by _textarea_clear_selection(), _textarea_handle_key(), _textarea_has_selection(), _textarea_sel_range(), n_gui_add_textarea(), n_gui_process_event(), and n_gui_textarea_set_selection().
sel_start
size_t N_GUI_TEXTAREA_DATA::sel_start
selection anchor position (where shift-click/shift-arrow started).
When sel_start == sel_end, no selection is active.
Definition at line 418 of file n_gui.h.
Referenced by _textarea_clear_selection(), _textarea_handle_key(), _textarea_has_selection(), _textarea_sel_range(), n_gui_add_textarea(), n_gui_process_event(), and n_gui_textarea_set_selection().
text
char* N_GUI_TEXTAREA_DATA::text
text content (dynamically allocated, text_alloc bytes)
Definition at line 405 of file n_gui.h.
Referenced by _destroy_widget(), _draw_textarea(), _textarea_content_height(), _textarea_copy_to_clipboard(), _textarea_delete_selection(), _textarea_handle_key(), _textarea_pos_from_mouse(), n_gui_add_textarea(), n_gui_textarea_scroll_to_offset(), and n_gui_textarea_set_text().
text_alloc
size_t N_GUI_TEXTAREA_DATA::text_alloc
allocated buffer size (char_limit + 1)
Definition at line 409 of file n_gui.h.
Referenced by n_gui_add_textarea().
text_len
size_t N_GUI_TEXTAREA_DATA::text_len
current text length
Definition at line 407 of file n_gui.h.
Referenced by _draw_textarea(), _textarea_content_height(), _textarea_delete_selection(), _textarea_handle_key(), _textarea_pos_from_mouse(), n_gui_add_textarea(), n_gui_textarea_get_text_length(), n_gui_textarea_scroll_to_bottom(), n_gui_textarea_scroll_to_offset(), n_gui_textarea_set_selection(), and n_gui_textarea_set_text().
user_data
void* N_GUI_TEXTAREA_DATA::user_data
user data for callback
Definition at line 436 of file n_gui.h.
Referenced by _textarea_delete_selection(), _textarea_handle_key(), and n_gui_add_textarea().
N_GUI_THEME
struct N_GUI_THEME
Color theme for a widget.
Examples
ex_gui.c.
Definition at line 283 of file n_gui.h.
Data Fields
ALLEGRO_COLOR bg_active background active/pressed
ALLEGRO_COLOR bg_hover background hover
ALLEGRO_COLOR bg_normal background normal
ALLEGRO_COLOR border_active border active
ALLEGRO_COLOR border_hover border hover
ALLEGRO_COLOR border_normal border normal
float border_thickness border thickness
float corner_rx corner radius for rounded shapes
float corner_ry corner radius Y for rounded shapes
ALLEGRO_COLOR selection_color text selection highlight colour (semi-transparent recommended)
ALLEGRO_COLOR text_active text active
ALLEGRO_COLOR text_hover text hover
ALLEGRO_COLOR text_normal text normal
N_GUI_TREE
struct N_GUI_TREE
tree view built from an N_GUI listbox
Definition at line 1811 of file n_gui.h.
Data Fields
N_GUI_CTX * ctx
GUI context.
int drag_active
1 once past threshold
int drag_armed_node
pressed-but-not-yet-dragging
int drag_hover_node
current hover node, or -1
float drag_press_x
mouse x at press time
float drag_press_y
mouse y at press time
int drag_source_node
node being dragged, or -1
int drop_position
N_GUI_DROP_BEFORE / INTO / AFTER.
void * drop_user_data
user data for on_drop
int listbox_id
listbox widget ID
int mouse_b1_prev
previous frame's b1 state
int nb_nodes
number of nodes
int nb_visible
number of visible rows
N_GUI_TREE_NODE nodes [2048]
node storage
n_gui_tree_on_drop_t on_drop
drag-reorder state (managed by n_gui_tree_tick)
void(* on_select)(int, void *)
selection callback
void * user_data
user data for callback
int visible_map [2048]
visible row to node index
int window_id
owning window for coord math
Field Documentation
ctx
N_GUI_CTX* N_GUI_TREE::ctx
GUI context.
Definition at line 1812 of file n_gui.h.
Referenced by _n_gui_tree_listbox_bounds(), n_gui_tree_clear(), n_gui_tree_create(), n_gui_tree_draw_overlay(), n_gui_tree_get_selection(), n_gui_tree_rebuild(), n_gui_tree_set_selection(), and n_gui_tree_tick().
drag_active
int N_GUI_TREE::drag_active
1 once past threshold
Definition at line 1829 of file n_gui.h.
Referenced by n_gui_tree_create(), n_gui_tree_draw_overlay(), n_gui_tree_set_on_drop(), and n_gui_tree_tick().
drag_armed_node
int N_GUI_TREE::drag_armed_node
pressed-but-not-yet-dragging
Definition at line 1826 of file n_gui.h.
Referenced by n_gui_tree_create(), n_gui_tree_set_on_drop(), and n_gui_tree_tick().
drag_hover_node
int N_GUI_TREE::drag_hover_node
current hover node, or -1
Definition at line 1827 of file n_gui.h.
Referenced by n_gui_tree_create(), n_gui_tree_draw_overlay(), n_gui_tree_set_on_drop(), and n_gui_tree_tick().
drag_press_x
float N_GUI_TREE::drag_press_x
mouse x at press time
Definition at line 1830 of file n_gui.h.
Referenced by n_gui_tree_create(), and n_gui_tree_tick().
drag_press_y
float N_GUI_TREE::drag_press_y
mouse y at press time
Definition at line 1831 of file n_gui.h.
Referenced by n_gui_tree_create(), and n_gui_tree_tick().
drag_source_node
int N_GUI_TREE::drag_source_node
node being dragged, or -1
Definition at line 1825 of file n_gui.h.
Referenced by n_gui_tree_create(), n_gui_tree_set_on_drop(), and n_gui_tree_tick().
drop_position
int N_GUI_TREE::drop_position
N_GUI_DROP_BEFORE / INTO / AFTER.
Definition at line 1828 of file n_gui.h.
Referenced by n_gui_tree_create(), n_gui_tree_draw_overlay(), and n_gui_tree_tick().
drop_user_data
void* N_GUI_TREE::drop_user_data
user data for on_drop
Definition at line 1824 of file n_gui.h.
Referenced by n_gui_tree_create(), n_gui_tree_set_on_drop(), and n_gui_tree_tick().
listbox_id
int N_GUI_TREE::listbox_id
listbox widget ID
Definition at line 1813 of file n_gui.h.
Referenced by _n_gui_tree_listbox_bounds(), n_gui_tree_clear(), n_gui_tree_create(), n_gui_tree_draw_overlay(), n_gui_tree_get_selection(), n_gui_tree_rebuild(), and n_gui_tree_set_selection().
mouse_b1_prev
int N_GUI_TREE::mouse_b1_prev
previous frame's b1 state
Definition at line 1832 of file n_gui.h.
Referenced by n_gui_tree_create(), and n_gui_tree_tick().
nb_nodes
int N_GUI_TREE::nb_nodes
number of nodes
Definition at line 1816 of file n_gui.h.
Referenced by _n_gui_tree_hit_row(), _n_gui_tree_listbox_selected(), n_gui_tree_add_node(), n_gui_tree_clear(), n_gui_tree_create(), n_gui_tree_find_by_user_data(), n_gui_tree_rebuild(), n_gui_tree_remove_node(), n_gui_tree_set_label(), n_gui_tree_set_selection(), and n_gui_tree_toggle_expand().
nb_visible
int N_GUI_TREE::nb_visible
number of visible rows
Definition at line 1818 of file n_gui.h.
Referenced by _n_gui_tree_hit_row(), _n_gui_tree_listbox_selected(), n_gui_tree_clear(), n_gui_tree_create(), n_gui_tree_draw_overlay(), n_gui_tree_get_selection(), n_gui_tree_rebuild(), and n_gui_tree_set_selection().
nodes
N_GUI_TREE_NODE N_GUI_TREE::nodes[2048]
node storage
Definition at line 1815 of file n_gui.h.
Referenced by _n_gui_tree_listbox_selected(), _n_gui_tree_node_visible(), n_gui_tree_add_node(), n_gui_tree_find_by_user_data(), n_gui_tree_rebuild(), n_gui_tree_remove_node(), n_gui_tree_set_label(), n_gui_tree_set_selection(), and n_gui_tree_toggle_expand().
on_drop
n_gui_tree_on_drop_t N_GUI_TREE::on_drop
drag-reorder state (managed by n_gui_tree_tick)
drop callback, or NULL
Definition at line 1823 of file n_gui.h.
Referenced by n_gui_tree_create(), n_gui_tree_set_on_drop(), and n_gui_tree_tick().
on_select
void(* N_GUI_TREE::on_select) (int, void *)
selection callback
Definition at line 1819 of file n_gui.h.
Referenced by _n_gui_tree_listbox_selected(), and n_gui_tree_create().
user_data
void* N_GUI_TREE::user_data
user data for callback
Definition at line 1820 of file n_gui.h.
Referenced by _n_gui_tree_listbox_selected(), and n_gui_tree_create().
visible_map
int N_GUI_TREE::visible_map[2048]
visible row to node index
Definition at line 1817 of file n_gui.h.
Referenced by _n_gui_tree_hit_row(), _n_gui_tree_listbox_selected(), n_gui_tree_draw_overlay(), n_gui_tree_get_selection(), n_gui_tree_rebuild(), and n_gui_tree_set_selection().
window_id
int N_GUI_TREE::window_id
owning window for coord math
Definition at line 1814 of file n_gui.h.
Referenced by _n_gui_tree_listbox_bounds(), and n_gui_tree_create().
N_GUI_TREE_NODE
struct N_GUI_TREE_NODE
a single node in the tree view
Definition at line 1788 of file n_gui.h.
Data Fields
int depth depth in tree (0 = root)
int expanded 1 if expanded
int has_children 1 if node has children
char label[128] display text
int parent_index parent node index, or -1 for root
void * user_data user data for this node
N_GUI_WIDGET
struct N_GUI_WIDGET
A single GUI widget.
Examples
ex_gui_kvtable.c.
Definition at line 675 of file n_gui.h.
Data Fields
void * data widget-specific data (union via void pointer)
int enabled enabled flag (1 = enabled, 0 = disabled: drawn dimmed and ignores input)
ALLEGRO_FONT * font font used by this widget (NULL = context default)
float h height
int id unique widget id
float norm_h normalized height (fraction of parent window h)
float norm_w normalized width (fraction of parent window w)
float norm_x normalized position x (fraction of parent window w, used for SCALE resize)
float norm_y normalized position y (fraction of parent window h, used for SCALE resize)
int state current state flags (N_GUI_STATE_*)
N_GUI_THEME theme color theme for this widget
char tooltip[96] tooltip text shown after the pointer rests on the widget ("" = none)
int type widget type (N_GUI_TYPE_*)
int visible visibility flag
float w width
float x position x relative to parent window
float y position y relative to parent window
N_GUI_WINDOW
struct N_GUI_WINDOW
A pseudo window that contains widgets.
Definition at line 767 of file n_gui.h.
Data Fields
float autofit_border
padding/border around content for auto-fit (pixels, applied on each side)
int autofit_flags
bitmask of N_GUI_AUTOFIT_* flags (0 = no auto-fitting)
float autofit_origin_x
original insertion point x for N_GUI_AUTOFIT_CENTER (set by n_gui_window_set_autofit)
float autofit_origin_y
original insertion point y for N_GUI_AUTOFIT_CENTER (set by n_gui_window_set_autofit)
ALLEGRO_BITMAP * bg_bitmap
optional bitmap for the window body background (NULL = color fill)
int bg_scale_mode
scale mode for bg_bitmap: N_GUI_IMAGE_FIT, N_GUI_IMAGE_STRETCH, or N_GUI_IMAGE_CENTER
float content_h
total content height computed from widgets (internal)
float content_w
total content width computed from widgets (internal)
float drag_ox
drag offset x (internal)
float drag_oy
drag offset y (internal)
int flags
feature flags (N_GUI_WIN_AUTO_SCROLLBAR, N_GUI_WIN_RESIZABLE, etc.)
ALLEGRO_FONT * font
font for the title bar
float h
window height
int id
unique window id
float min_h
minimum height
float min_w
minimum width
float norm_h
normalized height (fraction of reference display height, used in SCALE mode)
float norm_w
normalized width (fraction of reference display width, used in SCALE mode)
float norm_x
normalized position x (0.0-1.0 fraction of reference display width)
float norm_y
normalized position y (0.0-1.0 fraction of reference display height)
void(* on_content_draw)(int window_id, void *user_data)
optional callback invoked during n_gui_draw immediately after this window's own content is drawn, at the window's z-order (NULL = none).
void * on_content_draw_data
user data passed to on_content_draw
int resize_policy
per-window resize policy: N_GUI_WIN_RESIZE_NONE, _MOVE, or _SCALE
float scroll_x
horizontal scroll offset for auto-scrollbar (pixels)
float scroll_y
vertical scroll offset for auto-scrollbar (pixels)
int state
state flags (N_GUI_WIN_*)
N_GUI_TB_BUTTONS tb_buttons
titlebar button state (minimize, maximize, close)
N_GUI_THEME theme
color theme for this window chrome
char title [128]
window title
ALLEGRO_BITMAP * titlebar_bitmap
optional bitmap for the titlebar background (NULL = color fill)
float titlebar_h
title bar height
float w
window width
LIST * widgets
list of N_GUI_WIDGET* contained in this window
float x
position x on screen
float y
position y on screen
int z_order
z-order mode (N_GUI_ZORDER_NORMAL, _ALWAYS_ON_TOP, _ALWAYS_BEHIND, _FIXED)
int z_value
z-value for N_GUI_ZORDER_FIXED mode (lower = behind, higher = on top)
Field Documentation
autofit_border
float N_GUI_WINDOW::autofit_border
padding/border around content for auto-fit (pixels, applied on each side)
Definition at line 821 of file n_gui.h.
Referenced by n_gui_add_window(), n_gui_load_layout_json(), n_gui_save_layout_json(), n_gui_window_apply_autofit(), and n_gui_window_set_autofit().
autofit_flags
int N_GUI_WINDOW::autofit_flags
bitmask of N_GUI_AUTOFIT_* flags (0 = no auto-fitting)
Definition at line 819 of file n_gui.h.
Referenced by n_gui_add_window(), n_gui_draw(), n_gui_load_layout_json(), n_gui_save_layout_json(), n_gui_window_apply_autofit(), and n_gui_window_set_autofit().
autofit_origin_x
float N_GUI_WINDOW::autofit_origin_x
original insertion point x for N_GUI_AUTOFIT_CENTER (set by n_gui_window_set_autofit)
Definition at line 823 of file n_gui.h.
Referenced by n_gui_add_window(), n_gui_window_apply_autofit(), and n_gui_window_set_autofit().
autofit_origin_y
float N_GUI_WINDOW::autofit_origin_y
original insertion point y for N_GUI_AUTOFIT_CENTER (set by n_gui_window_set_autofit)
Definition at line 825 of file n_gui.h.
Referenced by n_gui_add_window(), n_gui_window_apply_autofit(), and n_gui_window_set_autofit().
bg_bitmap
ALLEGRO_BITMAP* N_GUI_WINDOW::bg_bitmap
optional bitmap for the window body background (NULL = color fill)
Definition at line 813 of file n_gui.h.
Referenced by _draw_window(), and n_gui_window_set_bitmaps().
bg_scale_mode
int N_GUI_WINDOW::bg_scale_mode
scale mode for bg_bitmap: N_GUI_IMAGE_FIT, N_GUI_IMAGE_STRETCH, or N_GUI_IMAGE_CENTER
Definition at line 817 of file n_gui.h.
Referenced by _draw_window(), and n_gui_window_set_bitmaps().
content_h
float N_GUI_WINDOW::content_h
total content height computed from widgets (internal)
Definition at line 805 of file n_gui.h.
Referenced by _draw_window(), _window_update_content_size(), n_gui_add_window(), n_gui_process_event(), and n_gui_window_apply_autofit().
content_w
float N_GUI_WINDOW::content_w
total content width computed from widgets (internal)
Definition at line 807 of file n_gui.h.
Referenced by _draw_window(), _window_update_content_size(), n_gui_add_window(), n_gui_process_event(), and n_gui_window_apply_autofit().
drag_ox
float N_GUI_WINDOW::drag_ox
drag offset x (internal)
Definition at line 793 of file n_gui.h.
Referenced by n_gui_add_window(), and n_gui_process_event().
drag_oy
float N_GUI_WINDOW::drag_oy
drag offset y (internal)
Definition at line 795 of file n_gui.h.
Referenced by n_gui_add_window(), and n_gui_process_event().
flags
int N_GUI_WINDOW::flags
feature flags (N_GUI_WIN_AUTO_SCROLLBAR, N_GUI_WIN_RESIZABLE, etc.)
Definition at line 785 of file n_gui.h.
Referenced by _draw_window(), _tb_button_rect(), _tb_buttons_area_width(), _win_tbh(), _window_update_content_size(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_load_layout_json(), n_gui_process_event(), n_gui_save_layout_json(), n_gui_window_get_flags(), and n_gui_window_set_flags().
font
ALLEGRO_FONT* N_GUI_WINDOW::font
font for the title bar
Definition at line 791 of file n_gui.h.
Referenced by _draw_window(), and n_gui_add_window().
h
float N_GUI_WINDOW::h
window height
Definition at line 779 of file n_gui.h.
Referenced by _compute_gui_bounds(), _draw_window(), _n_gui_kv_apply_layout(), _n_gui_widget_capture_normalized(), _n_gui_window_capture_normalized(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_kvtable_create(), n_gui_load_layout_json(), n_gui_maximize_window(), n_gui_process_event(), n_gui_save_layout_json(), n_gui_wants_mouse(), n_gui_window_apply_autofit(), and n_gui_window_autosize().
id
int N_GUI_WINDOW::id
unique window id
Definition at line 769 of file n_gui.h.
Referenced by _find_window_node(), _tb_button_action(), n_gui_add_window(), n_gui_draw(), n_gui_get_topmost_open_window(), n_gui_process_event(), and n_gui_set_focus().
min_h
float N_GUI_WINDOW::min_h
minimum height
Definition at line 799 of file n_gui.h.
Referenced by n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_process_event(), n_gui_window_apply_autofit(), and n_gui_window_autosize().
min_w
float N_GUI_WINDOW::min_w
minimum width
Definition at line 797 of file n_gui.h.
Referenced by n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_process_event(), n_gui_window_apply_autofit(), and n_gui_window_autosize().
norm_h
float N_GUI_WINDOW::norm_h
normalized height (fraction of reference display height, used in SCALE mode)
Definition at line 835 of file n_gui.h.
Referenced by _n_gui_window_capture_normalized(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_load_layout_json(), and n_gui_save_layout_json().
norm_w
float N_GUI_WINDOW::norm_w
normalized width (fraction of reference display width, used in SCALE mode)
Definition at line 833 of file n_gui.h.
Referenced by _n_gui_window_capture_normalized(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_load_layout_json(), and n_gui_save_layout_json().
norm_x
float N_GUI_WINDOW::norm_x
normalized position x (0.0-1.0 fraction of reference display width)
Definition at line 829 of file n_gui.h.
Referenced by _n_gui_window_capture_normalized(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_load_layout_json(), and n_gui_save_layout_json().
norm_y
float N_GUI_WINDOW::norm_y
normalized position y (0.0-1.0 fraction of reference display height)
Definition at line 831 of file n_gui.h.
Referenced by _n_gui_window_capture_normalized(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_load_layout_json(), and n_gui_save_layout_json().
on_content_draw
void(* N_GUI_WINDOW::on_content_draw) (int window_id, void *user_data)
optional callback invoked during n_gui_draw immediately after this window's own content is drawn, at the window's z-order (NULL = none).
Lets a caller add custom immediate-mode rendering that is correctly occluded by any window drawn on top of this one.
Definition at line 842 of file n_gui.h.
Referenced by n_gui_draw(), and n_gui_window_set_content_draw_callback().
on_content_draw_data
void* N_GUI_WINDOW::on_content_draw_data
user data passed to on_content_draw
Definition at line 844 of file n_gui.h.
Referenced by n_gui_draw(), and n_gui_window_set_content_draw_callback().
resize_policy
int N_GUI_WINDOW::resize_policy
per-window resize policy: N_GUI_WIN_RESIZE_NONE, _MOVE, or _SCALE
Definition at line 827 of file n_gui.h.
Referenced by _n_gui_window_capture_normalized(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_load_layout_json(), n_gui_save_layout_json(), n_gui_window_get_resize_policy(), and n_gui_window_set_resize_policy().
scroll_x
float N_GUI_WINDOW::scroll_x
horizontal scroll offset for auto-scrollbar (pixels)
Definition at line 803 of file n_gui.h.
Referenced by _draw_window(), _find_widget_window(), _tooltip_widget_at(), n_gui_add_window(), and n_gui_process_event().
scroll_y
float N_GUI_WINDOW::scroll_y
vertical scroll offset for auto-scrollbar (pixels)
Definition at line 801 of file n_gui.h.
Referenced by _draw_window(), _find_widget_window(), _tooltip_widget_at(), n_gui_add_window(), and n_gui_process_event().
state
int N_GUI_WINDOW::state
state flags (N_GUI_WIN_*)
Definition at line 783 of file n_gui.h.
Referenced by _compute_gui_bounds(), _draw_tb_buttons(), _draw_window(), _find_focused_window(), _find_widget_window(), _tooltip_widget_at(), n_gui_add_window(), n_gui_close_window(), n_gui_draw(), n_gui_get_topmost_open_window(), n_gui_load_layout_json(), n_gui_maximize_window(), n_gui_minimize_window(), n_gui_open_window(), n_gui_process_event(), n_gui_save_layout_json(), n_gui_set_focus(), n_gui_toggle_window(), n_gui_wants_mouse(), n_gui_window_is_maximised(), and n_gui_window_is_open().
tb_buttons
N_GUI_TB_BUTTONS N_GUI_WINDOW::tb_buttons
titlebar button state (minimize, maximize, close)
Definition at line 837 of file n_gui.h.
Referenced by _draw_tb_buttons(), _tb_button_action(), n_gui_add_window(), n_gui_maximize_window(), n_gui_process_event(), n_gui_reset_all_widget_themes(), n_gui_window_set_close_callback(), n_gui_window_set_maximize_callback(), n_gui_window_set_minimize_callback(), n_gui_window_set_tb_btn_theme(), n_gui_window_set_tb_button_bitmaps(), and n_gui_window_set_tb_close_theme().
theme
N_GUI_THEME N_GUI_WINDOW::theme
color theme for this window chrome
Definition at line 789 of file n_gui.h.
Referenced by _draw_window(), n_gui_add_window(), n_gui_load_theme_json(), and n_gui_reset_all_widget_themes().
title
char N_GUI_WINDOW::title[128]
window title
Definition at line 771 of file n_gui.h.
Referenced by _draw_window(), n_gui_add_window(), n_gui_load_layout_json(), and n_gui_save_layout_json().
titlebar_bitmap
ALLEGRO_BITMAP* N_GUI_WINDOW::titlebar_bitmap
optional bitmap for the titlebar background (NULL = color fill)
Definition at line 815 of file n_gui.h.
Referenced by _draw_window(), and n_gui_window_set_bitmaps().
titlebar_h
float N_GUI_WINDOW::titlebar_h
title bar height
Definition at line 781 of file n_gui.h.
Referenced by _draw_window(), _n_gui_tree_listbox_bounds(), _tb_btn_resolved_size(), _tb_button_rect(), _win_tbh(), and n_gui_add_window().
w
float N_GUI_WINDOW::w
window width
Definition at line 777 of file n_gui.h.
Referenced by _compute_gui_bounds(), _draw_window(), _n_gui_kv_apply_layout(), _n_gui_widget_capture_normalized(), _n_gui_window_capture_normalized(), _tb_button_rect(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_kvtable_create(), n_gui_load_layout_json(), n_gui_maximize_window(), n_gui_process_event(), n_gui_save_layout_json(), n_gui_wants_mouse(), n_gui_window_apply_autofit(), and n_gui_window_autosize().
widgets
LIST* N_GUI_WINDOW::widgets
list of N_GUI_WIDGET* contained in this window
Definition at line 787 of file n_gui.h.
Referenced by _destroy_window(), _draw_window(), _find_focused_window(), _find_widget_window(), _n_gui_window_capture_normalized(), _tooltip_widget_at(), _window_update_content_size(), n_gui_add_button(), n_gui_add_checkbox(), n_gui_add_combobox(), n_gui_add_dropmenu(), n_gui_add_image(), n_gui_add_label(), n_gui_add_listbox(), n_gui_add_radiolist(), n_gui_add_scrollbar(), n_gui_add_slider(), n_gui_add_textarea(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_focus_window(), n_gui_load_theme_json(), n_gui_process_event(), n_gui_reset_all_widget_themes(), n_gui_set_focus(), n_gui_window_apply_autofit(), and n_gui_window_autosize().
x
float N_GUI_WINDOW::x
position x on screen
Definition at line 773 of file n_gui.h.
Referenced by _compute_gui_bounds(), _draw_window(), _find_widget_window(), _n_gui_tree_listbox_bounds(), _n_gui_window_capture_normalized(), _tb_button_rect(), _tooltip_widget_at(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_load_layout_json(), n_gui_maximize_window(), n_gui_process_event(), n_gui_save_layout_json(), n_gui_wants_mouse(), n_gui_window_apply_autofit(), and n_gui_window_set_autofit().
y
float N_GUI_WINDOW::y
position y on screen
Definition at line 775 of file n_gui.h.
Referenced by _compute_gui_bounds(), _draw_window(), _find_widget_window(), _n_gui_tree_listbox_bounds(), _n_gui_window_capture_normalized(), _tb_button_rect(), _tooltip_widget_at(), n_gui_add_window(), n_gui_apply_adaptive_resize(), n_gui_load_layout_json(), n_gui_maximize_window(), n_gui_process_event(), n_gui_save_layout_json(), n_gui_wants_mouse(), n_gui_window_apply_autofit(), and n_gui_window_set_autofit().
z_order
int N_GUI_WINDOW::z_order
z-order mode (N_GUI_ZORDER_NORMAL, _ALWAYS_ON_TOP, _ALWAYS_BEHIND, _FIXED)
Definition at line 809 of file n_gui.h.
Referenced by _zorder_group(), n_gui_add_window(), n_gui_load_layout_json(), n_gui_lower_window(), n_gui_raise_window(), n_gui_save_layout_json(), n_gui_window_get_zorder(), and n_gui_window_set_zorder().
z_value
int N_GUI_WINDOW::z_value
z-value for N_GUI_ZORDER_FIXED mode (lower = behind, higher = on top)
Definition at line 811 of file n_gui.h.
Referenced by _sort_windows_by_zorder(), n_gui_add_window(), n_gui_load_layout_json(), n_gui_save_layout_json(), n_gui_window_get_zvalue(), and n_gui_window_set_zorder().
Macro Definition Documentation
N_GUI_ALIGN_CENTER
#define N_GUI_ALIGN_CENTER 1
center aligned text
Examples
ex_gui.c.
Definition at line 158 of file n_gui.h.
N_GUI_ALIGN_JUSTIFIED
#define N_GUI_ALIGN_JUSTIFIED 3
justified text (spread words to fill width)
Examples
ex_gui.c, and ex_gui_dictionary.c.
Definition at line 162 of file n_gui.h.
N_GUI_ALIGN_LEFT
#define N_GUI_ALIGN_LEFT 0
left aligned text
Examples
ex_gui.c, ex_gui_dictionary.c, ex_gui_isometric.c, ex_gui_network.c, and ex_gui_particles.c.
Definition at line 156 of file n_gui.h.
N_GUI_ALIGN_RIGHT
#define N_GUI_ALIGN_RIGHT 2
right aligned text
Examples
ex_gui.c.
Definition at line 160 of file n_gui.h.
N_GUI_AUTOFIT_CENTER
#define N_GUI_AUTOFIT_CENTER 16
center the window on its insertion point after auto-fit (overrides EXPAND_LEFT/EXPAND_UP for centering)
Examples
ex_gui.c.
Definition at line 246 of file n_gui.h.
N_GUI_AUTOFIT_EXPAND_LEFT
#define N_GUI_AUTOFIT_EXPAND_LEFT 4
expand leftward instead of rightward when adjusting width
Definition at line 242 of file n_gui.h.
N_GUI_AUTOFIT_EXPAND_UP
#define N_GUI_AUTOFIT_EXPAND_UP 8
expand upward instead of downward when adjusting height
Definition at line 244 of file n_gui.h.
N_GUI_AUTOFIT_H
#define N_GUI_AUTOFIT_H 2
auto-adjust window height to content
Definition at line 238 of file n_gui.h.
N_GUI_AUTOFIT_W
#define N_GUI_AUTOFIT_W 1
auto-adjust window width to content
Definition at line 236 of file n_gui.h.
N_GUI_AUTOFIT_WH
#define N_GUI_AUTOFIT_WH 3
auto-adjust both width and height (convenience: W|H)
Examples
ex_gui.c.
Definition at line 240 of file n_gui.h.
N_GUI_COMBOBOX_AUTO_WIDTH
#define N_GUI_COMBOBOX_AUTO_WIDTH 1
dropdown panel expands to fit the longest item text
Definition at line 549 of file n_gui.h.
N_GUI_COMBOBOX_EXPAND_UP
#define N_GUI_COMBOBOX_EXPAND_UP 2
dropdown panel opens upward (above the widget) instead of downward.
Useful for bottom-anchored comboboxes where the default downward panel would render off-screen. Without the flag, an auto-flip fallback still kicks in whenever the panel doesn't fit below and does fit above.
Definition at line 554 of file n_gui.h.
N_GUI_DROP_AFTER
#define N_GUI_DROP_AFTER 2
Definition at line 1800 of file n_gui.h.
N_GUI_DROP_BEFORE
#define N_GUI_DROP_BEFORE 0
drop position relative to a tree row (drag-and-drop)
Definition at line 1798 of file n_gui.h.
N_GUI_DROP_INTO
#define N_GUI_DROP_INTO 1
Definition at line 1799 of file n_gui.h.
N_GUI_DROPMENU_EXPAND_UP
#define N_GUI_DROPMENU_EXPAND_UP 1
dropdown panel opens upward (above the button) instead of downward.
Auto-flip fallback (pick direction based on available space) also kicks in whenever the panel doesn't fit below and does fit above.
Definition at line 638 of file n_gui.h.
N_GUI_ID_MAX
#define N_GUI_ID_MAX 128
maximum length for widget id/name strings
Examples
ex_gui.c.
Definition at line 84 of file n_gui.h.
N_GUI_IMAGE_CENTER
#define N_GUI_IMAGE_CENTER 2
draw at original size, centered
Examples
ex_gui.c.
Definition at line 152 of file n_gui.h.
N_GUI_IMAGE_FIT
#define N_GUI_IMAGE_FIT 0
scale to fit within bounds, keep aspect ratio
Examples
ex_gui.c.
Definition at line 148 of file n_gui.h.
N_GUI_IMAGE_STRETCH
#define N_GUI_IMAGE_STRETCH 1
stretch to fill bounds
Examples
ex_gui.c.
Definition at line 150 of file n_gui.h.
N_GUI_KEY_MOD_MASK
#define N_GUI_KEY_MOD_MASK (ALLEGRO_KEYMOD_SHIFT | ALLEGRO_KEYMOD_CTRL | ALLEGRO_KEYMOD_ALT | ALLEGRO_KEYMOD_ALTGR)
mask of supported modifier flags for button keybind matching
Definition at line 314 of file n_gui.h.
N_GUI_KEY_SOURCES_MAX
#define N_GUI_KEY_SOURCES_MAX 8
maximum number of source widgets for a focused key binding
Definition at line 317 of file n_gui.h.
N_GUI_KV_MAX
#define N_GUI_KV_MAX 128
maximum number of rows in a KV table
Definition at line 1883 of file n_gui.h.
N_GUI_RESIZE_ADAPTIVE
#define N_GUI_RESIZE_ADAPTIVE 1
virtual size tracks display; windows adapt per their resize_policy
Examples
ex_gui.c, and ex_gui_kvtable.c.
Definition at line 224 of file n_gui.h.
N_GUI_RESIZE_VIRTUAL
#define N_GUI_RESIZE_VIRTUAL 0
fixed virtual canvas with uniform scaling (default/existing behavior)
Definition at line 222 of file n_gui.h.
N_GUI_SCROLLBAR_H
#define N_GUI_SCROLLBAR_H 0
horizontal scrollbar
Examples
ex_gui.c.
Definition at line 134 of file n_gui.h.
N_GUI_SCROLLBAR_V
#define N_GUI_SCROLLBAR_V 1
vertical scrollbar
Examples
ex_gui.c.
Definition at line 136 of file n_gui.h.
N_GUI_SECTION_WIDGETS_MAX
#define N_GUI_SECTION_WIDGETS_MAX 48
maximum number of member widgets per section
Definition at line 1732 of file n_gui.h.
N_GUI_SECTIONLIST_MAX
#define N_GUI_SECTIONLIST_MAX 16
maximum number of foldable sections in a section list
Definition at line 1729 of file n_gui.h.
N_GUI_SELECT_MULTIPLE
#define N_GUI_SELECT_MULTIPLE 2
multiple item selection
Examples
ex_gui.c.
Definition at line 144 of file n_gui.h.
N_GUI_SELECT_NONE
#define N_GUI_SELECT_NONE 0
no selection allowed (display only)
Examples
ex_gui_network.c.
Definition at line 140 of file n_gui.h.
N_GUI_SELECT_SINGLE
#define N_GUI_SELECT_SINGLE 1
single item selection
Examples
ex_gui.c, ex_gui_dictionary.c, and ex_gui_isometric.c.
Definition at line 142 of file n_gui.h.
N_GUI_SHAPE_BITMAP
#define N_GUI_SHAPE_BITMAP 2
bitmap-based rendering
Definition at line 118 of file n_gui.h.
N_GUI_SHAPE_RECT
#define N_GUI_SHAPE_RECT 0
rectangle shape (default)
Examples
ex_gui.c.
Definition at line 114 of file n_gui.h.
N_GUI_SHAPE_ROUNDED
#define N_GUI_SHAPE_ROUNDED 1
rounded rectangle shape
Examples
ex_gui.c, ex_gui_dictionary.c, ex_gui_isometric.c, and ex_gui_network.c.
Definition at line 116 of file n_gui.h.
N_GUI_SLIDER_H
#define N_GUI_SLIDER_H 0
horizontal slider (default)
Definition at line 128 of file n_gui.h.
N_GUI_SLIDER_PERCENT
#define N_GUI_SLIDER_PERCENT 1
slider uses 0-100 percentage
Examples
ex_gui.c.
Definition at line 124 of file n_gui.h.
N_GUI_SLIDER_V
#define N_GUI_SLIDER_V 1
vertical slider
Definition at line 130 of file n_gui.h.
N_GUI_SLIDER_VALUE
#define N_GUI_SLIDER_VALUE 0
slider uses raw start/end values
Examples
ex_gui.c, and ex_gui_isometric.c.
Definition at line 122 of file n_gui.h.
N_GUI_STATE_ACTIVE
#define N_GUI_STATE_ACTIVE 2
widget is being pressed / dragged
Definition at line 170 of file n_gui.h.
N_GUI_STATE_FOCUSED
#define N_GUI_STATE_FOCUSED 4
widget has keyboard focus
Definition at line 172 of file n_gui.h.
N_GUI_STATE_HOVER
#define N_GUI_STATE_HOVER 1
mouse is hovering the widget
Definition at line 168 of file n_gui.h.
N_GUI_STATE_IDLE
#define N_GUI_STATE_IDLE 0
widget is idle / normal state
Definition at line 166 of file n_gui.h.
N_GUI_STATE_SCROLLBAR_DRAG
#define N_GUI_STATE_SCROLLBAR_DRAG 8
widget scrollbar is being dragged
Definition at line 174 of file n_gui.h.
N_GUI_TAB_MAX
#define N_GUI_TAB_MAX 16
maximum number of tabs in a single tab panel
Definition at line 1697 of file n_gui.h.
N_GUI_TB_BTN_CLOSE
#define N_GUI_TB_BTN_CLOSE 3
close titlebar button
Examples
ex_gui.c.
Definition at line 218 of file n_gui.h.
N_GUI_TB_BTN_MAXIMIZE
#define N_GUI_TB_BTN_MAXIMIZE 2
maximize/restore titlebar button
Definition at line 216 of file n_gui.h.
N_GUI_TB_BTN_MINIMIZE
#define N_GUI_TB_BTN_MINIMIZE 1
minimize titlebar button
Definition at line 214 of file n_gui.h.
N_GUI_TB_BTN_NONE
#define N_GUI_TB_BTN_NONE 0
no titlebar button
Definition at line 212 of file n_gui.h.
N_GUI_TEXT_MAX
#define N_GUI_TEXT_MAX 4096
maximum length for textarea content
Definition at line 86 of file n_gui.h.
N_GUI_TREE_MAX
#define N_GUI_TREE_MAX 2048
maximum number of nodes in a tree view
Definition at line 1785 of file n_gui.h.
N_GUI_TYPE_BUTTON
#define N_GUI_TYPE_BUTTON 1
widget type: button
Definition at line 90 of file n_gui.h.
N_GUI_TYPE_CHECKBOX
#define N_GUI_TYPE_CHECKBOX 4
widget type: checkbox
Definition at line 96 of file n_gui.h.
N_GUI_TYPE_COMBOBOX
#define N_GUI_TYPE_COMBOBOX 8
widget type: combo box (dropdown)
Definition at line 104 of file n_gui.h.
N_GUI_TYPE_DROPMENU
#define N_GUI_TYPE_DROPMENU 11
widget type: dropdown menu with static and dynamic entries
Definition at line 110 of file n_gui.h.
N_GUI_TYPE_IMAGE
#define N_GUI_TYPE_IMAGE 9
widget type: image display
Definition at line 106 of file n_gui.h.
N_GUI_TYPE_LABEL
#define N_GUI_TYPE_LABEL 10
widget type: static text label (with optional hyperlink)
Definition at line 108 of file n_gui.h.
N_GUI_TYPE_LISTBOX
#define N_GUI_TYPE_LISTBOX 6
widget type: listbox (selectable list)
Definition at line 100 of file n_gui.h.
N_GUI_TYPE_RADIOLIST
#define N_GUI_TYPE_RADIOLIST 7
widget type: radio list (single select radio buttons)
Definition at line 102 of file n_gui.h.
N_GUI_TYPE_SCROLLBAR
#define N_GUI_TYPE_SCROLLBAR 5
widget type: scrollbar
Definition at line 98 of file n_gui.h.
N_GUI_TYPE_SLIDER
#define N_GUI_TYPE_SLIDER 2
widget type: slider
Definition at line 92 of file n_gui.h.
N_GUI_TYPE_TEXTAREA
#define N_GUI_TYPE_TEXTAREA 3
widget type: text area
Definition at line 94 of file n_gui.h.
N_GUI_WIN_AUTO_SCROLLBAR
#define N_GUI_WIN_AUTO_SCROLLBAR 16
enable automatic scrollbars when content exceeds window size
Examples
ex_gui.c.
Definition at line 194 of file n_gui.h.
N_GUI_WIN_BTN_ALL
#define N_GUI_WIN_BTN_ALL (N_GUI_WIN_BTN_MINIMIZE | N_GUI_WIN_BTN_MAXIMIZE | N_GUI_WIN_BTN_CLOSE)
enable all three title bar buttons (minimize + maximize + close)
Definition at line 208 of file n_gui.h.
N_GUI_WIN_BTN_CLOSE
#define N_GUI_WIN_BTN_CLOSE 1024
enable close button on the title bar
Definition at line 206 of file n_gui.h.
N_GUI_WIN_BTN_MAXIMIZE
#define N_GUI_WIN_BTN_MAXIMIZE 512
enable maximize/restore button on the title bar
Definition at line 204 of file n_gui.h.
N_GUI_WIN_BTN_MINIMIZE
#define N_GUI_WIN_BTN_MINIMIZE 256
enable minimize button on the title bar
Definition at line 202 of file n_gui.h.
N_GUI_WIN_DRAGGING
#define N_GUI_WIN_DRAGGING 4
window is being dragged
Definition at line 182 of file n_gui.h.
N_GUI_WIN_FIXED_POSITION
#define N_GUI_WIN_FIXED_POSITION 64
disable window dragging (default:enable)
Examples
ex_gui.c, ex_gui_dictionary.c, and ex_gui_network.c.
Definition at line 198 of file n_gui.h.
N_GUI_WIN_FRAMELESS
#define N_GUI_WIN_FRAMELESS 128
frameless window: no title bar drawn, drag via window body unless N_GUI_WIN_FIXED_POSITION is also set
Examples
ex_gui.c.
Definition at line 200 of file n_gui.h.
N_GUI_WIN_HSCROLL_DRAG
#define N_GUI_WIN_HSCROLL_DRAG 32
window horizontal auto-scrollbar is being dragged
Definition at line 188 of file n_gui.h.
N_GUI_WIN_MAXIMISED
#define N_GUI_WIN_MAXIMISED 64
window is maximised (full display size)
Definition at line 190 of file n_gui.h.
N_GUI_WIN_MINIMISED
#define N_GUI_WIN_MINIMISED 2
window is minimised (title bar only)
Definition at line 180 of file n_gui.h.
N_GUI_WIN_OPEN
#define N_GUI_WIN_OPEN 1
window is visible
Definition at line 178 of file n_gui.h.
N_GUI_WIN_RESIZABLE
#define N_GUI_WIN_RESIZABLE 32
enable user-resizable window with a drag handle at bottom-right
Examples
ex_gui.c, and ex_gui_network.c.
Definition at line 196 of file n_gui.h.
N_GUI_WIN_RESIZE_MOVE
#define N_GUI_WIN_RESIZE_MOVE 1
reposition proportionally, keep pixel size
Examples
ex_gui.c.
Definition at line 230 of file n_gui.h.
N_GUI_WIN_RESIZE_NONE
#define N_GUI_WIN_RESIZE_NONE 0
no adaptation: absolute position and size unchanged
Examples
ex_gui.c.
Definition at line 228 of file n_gui.h.
N_GUI_WIN_RESIZE_SCALE
#define N_GUI_WIN_RESIZE_SCALE 2
reposition AND resize proportionally, child widgets scale too
Examples
ex_gui.c, and ex_gui_kvtable.c.
Definition at line 232 of file n_gui.h.
N_GUI_WIN_RESIZING
#define N_GUI_WIN_RESIZING 8
window is being resized
Definition at line 184 of file n_gui.h.
N_GUI_WIN_VSCROLL_DRAG
#define N_GUI_WIN_VSCROLL_DRAG 16
window vertical auto-scrollbar is being dragged
Definition at line 186 of file n_gui.h.
N_GUI_ZORDER_ALWAYS_BEHIND
#define N_GUI_ZORDER_ALWAYS_BEHIND 2
always drawn behind normal windows, cannot be raised above them
Definition at line 254 of file n_gui.h.
N_GUI_ZORDER_ALWAYS_ON_TOP
#define N_GUI_ZORDER_ALWAYS_ON_TOP 1
always drawn on top of normal windows, cannot be lowered behind them
Definition at line 252 of file n_gui.h.
N_GUI_ZORDER_FIXED
#define N_GUI_ZORDER_FIXED 3
fixed z-value: window is sorted within a dedicated group between ALWAYS_BEHIND and NORMAL windows.
The draw order of groups is: ALWAYS_BEHIND < FIXED < NORMAL < ALWAYS_ON_TOP < POPUP. Within the FIXED group, windows are ordered by z_value (lower = drawn first / behind, higher = drawn last / on top). z_value has no effect on other z-order modes. Windows with the same z_value preserve their relative list order (stable sort).
Definition at line 261 of file n_gui.h.
N_GUI_ZORDER_NORMAL
#define N_GUI_ZORDER_NORMAL 0
default z-order: window participates in normal raise/lower ordering
Definition at line 250 of file n_gui.h.
N_GUI_ZORDER_POPUP
#define N_GUI_ZORDER_POPUP 4
popup/modal dialogs: drawn above EVERYTHING including ALWAYS_ON_TOP windows.
Use for transient attention-demanding windows (confirmations, invitations, NPC dialogs, loot/reward popups, context menus). Unlike ALWAYS_ON_TOP, POPUP windows ARE raisable (n_gui_raise_window / click-to-raise) WITHIN their group, so the most recently opened/clicked popup wins among popups while none of them can ever be covered by HUD furniture.
Definition at line 268 of file n_gui.h.
Typedef Documentation
n_gui_tree_on_drop_t
typedef int(* n_gui_tree_on_drop_t) (int src_node, int dst_node, int position, void *user_data)
drag-reorder drop callback.
Called when the user drags node src_node and releases the mouse over dst_node at position (N_GUI_DROP_BEFORE / INTO / AFTER). Return 1 to accept; the caller is responsible for mutating the underlying data model and rebuilding the tree. Return 0 to reject (widget clears its drag state silently).
Definition at line 1808 of file n_gui.h.
Function Documentation
n_gui_add_button()
int n_gui_add_button (N_GUI_CTX * ctx, int window_id, const char * label, float x, float y, float w, float h, int shape, void(*)(int, void *) on_click, void * user_data)
add a button widget
add a button widget
Returns
widget id, or -1 on error
Definition at line 1303 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_BUTTON_DATA::bitmap, N_GUI_BUTTON_DATA::bitmap_active, N_GUI_BUTTON_DATA::bitmap_hover, N_GUI_WIDGET::data, Free, N_GUI_WIDGET::id, N_GUI_BUTTON_DATA::key_modifiers, N_GUI_BUTTON_DATA::keycode, N_GUI_BUTTON_DATA::label, list_push(), Malloc, n_gui_get_window(), N_GUI_ID_MAX, N_GUI_TYPE_BUTTON, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_BUTTON_DATA::on_click, N_GUI_BUTTON_DATA::shape, N_GUI_BUTTON_DATA::toggle_mode, N_GUI_BUTTON_DATA::toggled, N_GUI_BUTTON_DATA::user_data, and N_GUI_WINDOW::widgets.
Referenced by main(), main(), n_gui_add_button_bitmap(), n_gui_add_toggle_button(), n_gui_kvtable_add_row(), n_gui_kvtable_create(), and n_gui_sectionlist_add_section().
n_gui_add_button_bitmap()
int n_gui_add_button_bitmap (N_GUI_CTX * ctx, int window_id, const char * label, float x, float y, float w, float h, ALLEGRO_BITMAP * normal, ALLEGRO_BITMAP * hover, ALLEGRO_BITMAP * active, void(*)(int, void *) on_click, void * user_data)
add a bitmap-based button widget
add a bitmap-based button widget
Returns
widget id, or -1 on error
Definition at line 1344 of file n_gui.c.
References N_GUI_BUTTON_DATA::bitmap, N_GUI_BUTTON_DATA::bitmap_active, N_GUI_BUTTON_DATA::bitmap_hover, N_GUI_WIDGET::data, n_gui_add_button(), n_gui_get_widget(), and N_GUI_SHAPE_BITMAP.
Referenced by main().
n_gui_add_checkbox()
int n_gui_add_checkbox (N_GUI_CTX * ctx, int window_id, const char * label, float x, float y, float w, float h, int initial_checked, void(*)(int, int, void *) on_toggle, void * user_data)
add a checkbox widget
add a checkbox widget
Returns
widget id, or -1 on error
Definition at line 1655 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_CHECKBOX_DATA::checked, N_GUI_WIDGET::data, Free, N_GUI_WIDGET::id, N_GUI_CHECKBOX_DATA::label, list_push(), Malloc, n_gui_get_window(), N_GUI_ID_MAX, N_GUI_TYPE_CHECKBOX, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_CHECKBOX_DATA::on_toggle, N_GUI_CHECKBOX_DATA::user_data, and N_GUI_WINDOW::widgets.
Referenced by main(), and n_gui_kvtable_add_row().
n_gui_add_combobox()
int n_gui_add_combobox (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, void(*)(int, int, void *) on_select, void * user_data)
add a combo box widget
add a combo box widget
Returns
widget id, or -1 on error
Definition at line 1803 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_STYLE::combobox_max_visible, N_GUI_WIDGET::data, N_GUI_COMBOBOX_DATA::flags, Free, N_GUI_WIDGET::id, N_GUI_COMBOBOX_DATA::is_open, N_GUI_COMBOBOX_DATA::item_height, N_GUI_COMBOBOX_DATA::items, N_GUI_COMBOBOX_DATA::items_capacity, list_push(), Malloc, N_GUI_COMBOBOX_DATA::max_visible, n_gui_get_window(), N_GUI_TYPE_COMBOBOX, N_GUI_COMBOBOX_DATA::nb_items, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_COMBOBOX_DATA::on_select, N_GUI_COMBOBOX_DATA::scroll_offset, N_GUI_COMBOBOX_DATA::selected_index, N_GUI_CTX::style, N_GUI_COMBOBOX_DATA::user_data, and N_GUI_WINDOW::widgets.
Referenced by main().
n_gui_add_dropmenu()
int n_gui_add_dropmenu (N_GUI_CTX * ctx, int window_id, const char * label, float x, float y, float w, float h, void(*)(int, void *) on_open, void * on_open_user_data)
add a dropdown menu widget (button that opens a menu panel with entries)
Parameters
ctx the GUI context
window_id id of the parent window
label button label text
x horizontal position
y vertical position
w widget width
h widget height
on_open callback invoked when the menu is opened (or NULL)
on_open_user_data user data passed to on_open callback
Returns
widget id, or -1 on error
add a dropdown menu widget (button that opens a menu panel with entries)
Returns
widget id, or -1 on error
Definition at line 2685 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_WIDGET::data, N_GUI_STYLE::dropmenu_max_visible, N_GUI_DROPMENU_DATA::entries, N_GUI_DROPMENU_DATA::entries_capacity, N_GUI_DROPMENU_DATA::flags, Free, N_GUI_WIDGET::id, N_GUI_DROPMENU_DATA::is_open, N_GUI_DROPMENU_DATA::item_height, N_GUI_DROPMENU_DATA::item_hover_bitmap, N_GUI_DROPMENU_DATA::label, list_push(), Malloc, N_GUI_DROPMENU_DATA::max_visible, n_gui_get_window(), N_GUI_ID_MAX, N_GUI_TYPE_DROPMENU, N_GUI_DROPMENU_DATA::nb_entries, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_DROPMENU_DATA::on_open, N_GUI_DROPMENU_DATA::on_open_user_data, N_GUI_DROPMENU_DATA::panel_bitmap, N_GUI_DROPMENU_DATA::scroll_offset, N_GUI_CTX::style, and N_GUI_WINDOW::widgets.
Referenced by main().
n_gui_add_image()
int n_gui_add_image (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, ALLEGRO_BITMAP * bitmap, int scale_mode)
add an image widget
add an image widget
Parameters
ctx the GUI context
window_id id of the parent window
x horizontal position
y vertical position
w widget width
h widget height
bitmap the bitmap to display (not owned by the widget)
scale_mode N_GUI_IMAGE_FIT, N_GUI_IMAGE_STRETCH, or N_GUI_IMAGE_CENTER
Returns
widget id, or -1 on error
Definition at line 1865 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_WIDGET::data, Free, N_GUI_WIDGET::id, list_push(), Malloc, n_gui_get_window(), N_GUI_TYPE_IMAGE, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, and N_GUI_WINDOW::widgets.
Referenced by main().
n_gui_add_label()
int n_gui_add_label (N_GUI_CTX * ctx, int window_id, const char * text, float x, float y, float w, float h, int align)
add a text label widget
add a text label widget
Returns
widget id, or -1 on error
Definition at line 1894 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _normalize_crlf(), _register_widget(), N_GUI_LABEL_DATA::align, N_GUI_WIDGET::data, Free, N_GUI_WIDGET::id, N_GUI_LABEL_DATA::link, list_push(), Malloc, n_gui_get_window(), N_GUI_TEXT_MAX, N_GUI_TYPE_LABEL, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_LABEL_DATA::on_link_click, N_GUI_LABEL_DATA::scroll_y, N_GUI_LABEL_DATA::sel_dragging, N_GUI_LABEL_DATA::sel_end, N_GUI_LABEL_DATA::sel_start, N_GUI_LABEL_DATA::text, N_GUI_LABEL_DATA::user_data, and N_GUI_WINDOW::widgets.
Referenced by main(), main(), n_gui_add_label_link(), and n_gui_kvtable_create().
n_gui_add_label_link()
int n_gui_add_label_link (N_GUI_CTX * ctx, int window_id, const char * text, const char * link, float x, float y, float w, float h, int align, void(*)(int, const char *, void *) on_link_click, void * user_data)
add a text label with hyperlink
add a text label with hyperlink
Returns
widget id, or -1 on error
Definition at line 1935 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_LABEL_DATA::link, n_gui_add_label(), n_gui_get_widget(), N_GUI_TEXT_MAX, on_link_click(), N_GUI_LABEL_DATA::on_link_click, and N_GUI_LABEL_DATA::user_data.
Referenced by main().
n_gui_add_listbox()
int n_gui_add_listbox (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, int selection_mode, void(*)(int, int, int, void *) on_select, void * user_data)
add a listbox widget
add a listbox widget
Parameters
ctx the GUI context
window_id id of the parent window
x horizontal position
y vertical position
w widget width
h widget height
selection_mode N_GUI_SELECT_NONE, N_GUI_SELECT_SINGLE, or N_GUI_SELECT_MULTIPLE
on_select callback invoked when an item is selected (or NULL)
user_data user data passed to on_select callback
Returns
widget id, or -1 on error
Definition at line 1732 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_WIDGET::data, Free, N_GUI_LISTBOX_DATA::hover_row, N_GUI_WIDGET::id, N_GUI_LISTBOX_DATA::item_height, N_GUI_LISTBOX_DATA::items, N_GUI_LISTBOX_DATA::items_capacity, list_push(), N_GUI_STYLE::listbox_default_item_height, Malloc, n_gui_get_window(), N_GUI_TYPE_LISTBOX, N_GUI_LISTBOX_DATA::nb_items, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_LISTBOX_DATA::on_select, N_GUI_LISTBOX_DATA::scroll_offset, N_GUI_LISTBOX_DATA::selection_mode, N_GUI_CTX::style, N_GUI_LISTBOX_DATA::user_data, and N_GUI_WINDOW::widgets.
Referenced by main(), main(), and n_gui_tree_create().
n_gui_add_radiolist()
int n_gui_add_radiolist (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, void(*)(int, int, void *) on_select, void * user_data)
add a radio list widget
add a radio list widget
Returns
widget id, or -1 on error
Definition at line 1768 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_WIDGET::data, Free, N_GUI_WIDGET::id, N_GUI_RADIOLIST_DATA::item_height, N_GUI_RADIOLIST_DATA::items, N_GUI_RADIOLIST_DATA::items_capacity, list_push(), Malloc, n_gui_get_window(), N_GUI_TYPE_RADIOLIST, N_GUI_RADIOLIST_DATA::nb_items, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_RADIOLIST_DATA::on_select, N_GUI_STYLE::radiolist_default_item_height, N_GUI_RADIOLIST_DATA::scroll_offset, N_GUI_RADIOLIST_DATA::selected_index, N_GUI_CTX::style, N_GUI_RADIOLIST_DATA::user_data, and N_GUI_WINDOW::widgets.
Referenced by main().
n_gui_add_scrollbar()
int n_gui_add_scrollbar (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, int orientation, int shape, double content_size, double viewport_size, void(*)(int, double, void *) on_scroll, void * user_data)
add a scrollbar widget
add a scrollbar widget
Returns
widget id, or -1 on error
Definition at line 1689 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_SCROLLBAR_DATA::content_size, N_GUI_WIDGET::data, Free, N_GUI_WIDGET::id, list_push(), Malloc, n_gui_get_window(), N_GUI_TYPE_SCROLLBAR, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, on_scroll(), N_GUI_SCROLLBAR_DATA::on_scroll, N_GUI_SCROLLBAR_DATA::orientation, N_GUI_SCROLLBAR_DATA::scroll_pos, N_GUI_SCROLLBAR_DATA::shape, N_GUI_SCROLLBAR_DATA::user_data, N_GUI_SCROLLBAR_DATA::viewport_size, and N_GUI_WINDOW::widgets.
Referenced by main().
n_gui_add_slider()
int n_gui_add_slider (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, double min_val, double max_val, double initial, int mode, void(*)(int, double, void *) on_change, void * user_data)
add a horizontal slider widget
add a horizontal slider widget
Returns
widget id, or -1 on error
Definition at line 1554 of file n_gui.c.
References __n_assert, _clamp(), _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_WIDGET::data, Free, N_GUI_WIDGET::id, list_push(), Malloc, N_GUI_SLIDER_DATA::max_val, N_GUI_SLIDER_DATA::min_val, mode, N_GUI_SLIDER_DATA::mode, n_gui_get_window(), N_GUI_SLIDER_H, N_GUI_SLIDER_PERCENT, N_GUI_TYPE_SLIDER, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_SLIDER_DATA::on_change, N_GUI_SLIDER_DATA::orientation, N_GUI_SLIDER_DATA::step, N_GUI_SLIDER_DATA::user_data, N_GUI_SLIDER_DATA::value, N_GUI_SLIDER_DATA::value_format, N_GUI_SLIDER_DATA::value_visible, and N_GUI_WINDOW::widgets.
Referenced by main(), and n_gui_add_vslider().
n_gui_add_textarea()
int n_gui_add_textarea (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, int multiline, size_t char_limit, void(*)(int, const char *, void *) on_change, void * user_data)
add a text area widget
add a text area widget
Returns
widget id, or -1 on error
Definition at line 1610 of file n_gui.c.
References __n_assert, _destroy_widget(), _n_gui_widget_capture_normalized(), _new_widget(), _register_widget(), N_GUI_TEXTAREA_DATA::bg_bitmap, N_GUI_TEXTAREA_DATA::char_limit, N_GUI_TEXTAREA_DATA::cursor_pos, N_GUI_TEXTAREA_DATA::cursor_time, N_GUI_WIDGET::data, Free, N_GUI_WIDGET::id, list_push(), Malloc, N_GUI_TEXTAREA_DATA::mask_char, N_GUI_TEXTAREA_DATA::multiline, n_gui_get_window(), N_GUI_TEXT_MAX, N_GUI_TYPE_TEXTAREA, N_GUI_WIDGET::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WIDGET::norm_y, N_GUI_TEXTAREA_DATA::on_change, N_GUI_TEXTAREA_DATA::scroll_x, N_GUI_TEXTAREA_DATA::scroll_y, N_GUI_TEXTAREA_DATA::sel_end, N_GUI_TEXTAREA_DATA::sel_start, N_GUI_TEXTAREA_DATA::text, N_GUI_TEXTAREA_DATA::text_alloc, N_GUI_TEXTAREA_DATA::text_len, N_GUI_TEXTAREA_DATA::user_data, and N_GUI_WINDOW::widgets.
Referenced by main(), main(), and n_gui_kvtable_add_row().
n_gui_add_toggle_button()
int n_gui_add_toggle_button (N_GUI_CTX * ctx, int window_id, const char * label, float x, float y, float w, float h, int shape, int initial_state, void(*)(int, void *) on_click, void * user_data)
toggle button creation (returns widget id)
toggle button creation (returns widget id)
Parameters
ctx the GUI context
window_id id of the parent window
label button label text
x horizontal position
y vertical position
w widget width
h widget height
shape button shape (N_GUI_SHAPE_*)
initial_state 0 = off, 1 = on
on_click callback invoked on click (or NULL)
user_data user data passed to on_click callback
Returns
widget id, or -1 on error
Definition at line 1372 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_add_button(), n_gui_get_widget(), N_GUI_BUTTON_DATA::toggle_mode, and N_GUI_BUTTON_DATA::toggled.
Referenced by main(), and n_gui_tab_add().
n_gui_add_vslider()
int n_gui_add_vslider (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, double min_val, double max_val, double initial, int mode, void(*)(int, double, void *) on_change, void * user_data)
add a vertical slider (same as n_gui_add_slider but oriented vertically)
add a vertical slider (same as n_gui_add_slider but oriented vertically)
Returns
widget id, or -1 on error
Definition at line 1596 of file n_gui.c.
References N_GUI_WIDGET::data, mode, n_gui_add_slider(), n_gui_get_widget(), and N_GUI_SLIDER_V.
Referenced by main().
n_gui_add_window()
int n_gui_add_window (N_GUI_CTX * ctx, const char * title, float x, float y, float w, float h)
add a window to the GUI context
add a window to the GUI context
Returns
the window id, or -1 on error
Definition at line 665 of file n_gui.c.
References __n_assert, _destroy_window(), _n_gui_window_capture_normalized(), _sort_windows_by_zorder(), N_GUI_WINDOW::autofit_border, N_GUI_WINDOW::autofit_flags, N_GUI_WINDOW::autofit_origin_x, N_GUI_WINDOW::autofit_origin_y, N_GUI_TB_BUTTONS::btn_theme, N_GUI_TB_BUTTONS::close_theme, N_GUI_PENDING_GEOM::consumed, N_GUI_WINDOW::content_h, N_GUI_WINDOW::content_w, N_GUI_CTX::default_tb_btn_theme, N_GUI_CTX::default_tb_close_theme, N_GUI_CTX::default_theme, N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_WINDOW::drag_ox, N_GUI_WINDOW::drag_oy, N_GUI_WINDOW::flags, N_GUI_WINDOW::font, Free, N_GUI_WINDOW::h, N_GUI_WINDOW::id, list_push(), LOG_ERR, Malloc, N_GUI_WINDOW::min_h, N_GUI_WINDOW::min_w, N_GUI_STYLE::min_win_h, N_GUI_STYLE::min_win_w, N_GUI_ID_MAX, N_GUI_RESIZE_ADAPTIVE, N_GUI_WIN_OPEN, N_GUI_WIN_RESIZE_NONE, N_GUI_ZORDER_NORMAL, n_log, new_generic_list(), N_GUI_CTX::next_window_id, N_GUI_WINDOW::norm_h, N_GUI_WINDOW::norm_w, N_GUI_WINDOW::norm_x, N_GUI_WINDOW::norm_y, N_GUI_CTX::pending_layout, N_GUI_CTX::pending_layout_count, N_GUI_CTX::resize_mode, N_GUI_WINDOW::resize_policy, N_GUI_WINDOW::scroll_x, N_GUI_WINDOW::scroll_y, N_GUI_WINDOW::state, N_GUI_CTX::style, N_GUI_WINDOW::tb_buttons, N_GUI_WINDOW::theme, N_GUI_WINDOW::title, N_GUI_PENDING_GEOM::title, N_GUI_WINDOW::titlebar_h, N_GUI_STYLE::titlebar_h, UNLIMITED_LIST_ITEMS, N_GUI_WINDOW::w, N_GUI_WINDOW::widgets, N_GUI_CTX::windows, N_GUI_WINDOW::x, N_GUI_PENDING_GEOM::x, N_GUI_WINDOW::y, N_GUI_PENDING_GEOM::y, N_GUI_WINDOW::z_order, and N_GUI_WINDOW::z_value.
Referenced by main(), main(), and n_gui_add_window_auto().
n_gui_add_window_auto()
int n_gui_add_window_auto (N_GUI_CTX * ctx, const char * title, float x, float y)
add a window that sizes itself automatically to fit its widgets (call n_gui_window_autosize after adding all widgets)
add a window that sizes itself automatically to fit its widgets (call n_gui_window_autosize after adding all widgets)
Returns
the window id, or -1 on error
Definition at line 1121 of file n_gui.c.
References N_GUI_STYLE::min_win_h, N_GUI_STYLE::min_win_w, n_gui_add_window(), and N_GUI_CTX::style.
Referenced by main().
n_gui_apply_adaptive_resize()
void n_gui_apply_adaptive_resize (N_GUI_CTX * ctx, float new_w, float new_h)
apply adaptive resize: reposition/resize all windows according to their policies for the new display dimensions.
Called automatically from n_gui_set_display_size() when in ADAPTIVE mode, but can also be called manually.
apply adaptive resize: reposition/resize all windows according to their policies for the new display dimensions.
Called automatically from n_gui_set_display_size() when in ADAPTIVE mode, but can also be called manually.
Definition at line 5834 of file n_gui.c.
References __n_assert, N_GUI_WINDOW::flags, N_GUI_WIDGET::h, N_GUI_WINDOW::h, list_foreach, N_GUI_WINDOW::min_h, N_GUI_WINDOW::min_w, N_GUI_WIN_FRAMELESS, N_GUI_WIN_RESIZE_MOVE, N_GUI_WIN_RESIZE_NONE, N_GUI_WIN_RESIZE_SCALE, N_GUI_WIDGET::norm_h, N_GUI_WINDOW::norm_h, N_GUI_WIDGET::norm_w, N_GUI_WINDOW::norm_w, N_GUI_WIDGET::norm_x, N_GUI_WINDOW::norm_x, N_GUI_WIDGET::norm_y, N_GUI_WINDOW::norm_y, N_GUI_WINDOW::resize_policy, N_GUI_WIDGET::w, N_GUI_WINDOW::w, N_GUI_WINDOW::widgets, N_GUI_CTX::windows, N_GUI_WIDGET::x, N_GUI_WINDOW::x, N_GUI_WIDGET::y, and N_GUI_WINDOW::y.
Referenced by n_gui_set_display_size().
n_gui_button_is_toggled()
int n_gui_button_is_toggled (N_GUI_CTX * ctx, int widget_id)
check if button is toggled
check if button is toggled
Returns
1 if toggled on, 0 if off or not a toggle button
Definition at line 1388 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_BUTTON, and N_GUI_WIDGET::type.
Referenced by main(), on_ghost_toggle(), on_ghost_toggle(), on_grid_toggle(), on_grid_toggle(), on_height_toggle(), on_height_toggle(), on_player_toggle(), on_player_toggle(), on_smooth_toggle(), and on_smooth_toggle().
n_gui_button_set_keycode()
void n_gui_button_set_keycode (N_GUI_CTX * ctx, int widget_id, int keycode, int modifiers)
bind a keyboard key with optional modifier requirements to a button.
When the key is pressed (with matching modifiers) and no text input widget has focus, the button's on_click callback is triggered. Pass keycode 0 to unbind. Use ALLEGRO_KEY_* constants for the keycode. When modifiers is 0, any modifier state matches (no modifier requirement). When modifiers is non-zero, only an exact match of the specified modifiers (masked by N_GUI_KEY_MOD_MASK) triggers the keybind. Example: n_gui_button_set_keycode(ctx, id, ALLEGRO_KEY_A, ALLEGRO_KEYMOD_SHIFT | ALLEGRO_KEYMOD_CTRL)
Parameters
ctx GUI context
widget_id button widget id
keycode ALLEGRO_KEY_* constant, or 0 to unbind
modifiers ALLEGRO_KEYMOD_* flags ORed together, or 0 for no requirement
bind a keyboard key with optional modifier requirements to a button.
When the key is pressed (with matching modifiers) and no text input widget has focus, the button's on_click callback is triggered (and toggle state flipped for toggle buttons). Pass keycode 0 to unbind. When modifiers is 0, any modifier state matches (no modifier requirement). When modifiers is non-zero, only an exact match triggers the keybind. Example: ALLEGRO_KEY_A with ALLEGRO_KEYMOD_SHIFT | ALLEGRO_KEYMOD_CTRL
Definition at line 1523 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_BUTTON_DATA::key_modifiers, N_GUI_BUTTON_DATA::keycode, n_gui_get_widget(), N_GUI_KEY_MOD_MASK, N_GUI_TYPE_BUTTON, and N_GUI_WIDGET::type.
Referenced by main(), and main().
n_gui_button_set_keycode_focused()
void n_gui_button_set_keycode_focused (N_GUI_CTX * ctx, int widget_id, int keycode, int modifiers, const int * sources, int source_count)
bind a keyboard key to a button that fires only when specific widgets have focus.
Unlike n_gui_button_set_keycode (global), this binding triggers only when the button itself or one of the listed source widgets currently has focus. This allows e.g. ENTER in a URL textarea to trigger a Send button without interfering with ENTER in other textareas.
Parameters
ctx GUI context
widget_id button widget id
keycode ALLEGRO_KEY_* constant, or 0 to unbind
modifiers ALLEGRO_KEYMOD_* flags ORed together, or 0 for no requirement
sources array of widget IDs whose focus can trigger this binding
source_count number of entries in sources (max N_GUI_KEY_SOURCES_MAX)
bind a keyboard key to a button that fires only when specific widgets have focus.
Definition at line 1533 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_BUTTON_DATA::key_focus_only, N_GUI_BUTTON_DATA::key_modifiers, N_GUI_BUTTON_DATA::key_sources, N_GUI_BUTTON_DATA::keycode, n_gui_get_widget(), N_GUI_KEY_MOD_MASK, N_GUI_KEY_SOURCES_MAX, N_GUI_TYPE_BUTTON, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_button_set_label()
void n_gui_button_set_label (N_GUI_CTX * ctx, int widget_id, const char * label)
replace the label text drawn on a button
replace the label text drawn on a button
No-op on non-button widgets or NULL label.
Definition at line 1400 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_BUTTON_DATA::label, n_gui_get_widget(), N_GUI_TYPE_BUTTON, and N_GUI_WIDGET::type.
Referenced by _n_gui_sectionlist_set_header_label().
n_gui_button_set_state_bitmaps()
void n_gui_button_set_state_bitmaps (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * normal, ALLEGRO_BITMAP * hover, ALLEGRO_BITMAP * active)
skin a button or toggle button with caller-owned per-state bitmaps (switches its shape to N_GUI_SHAPE_BITMAP; toggled-on renders active)
skin a button or toggle button with caller-owned per-state bitmaps (switches its shape to N_GUI_SHAPE_BITMAP; toggled-on renders active)
Switches the button shape to N_GUI_SHAPE_BITMAP and assigns the three state bitmaps; a toggled-on toggle button renders active persistently (the draw path already maps toggled to the ACTIVE visual state). The bitmaps stay owned by the caller, exactly like n_gui_add_button_bitmap; the label keeps drawing on top, so pass "" at creation for icon-only buttons. No-op on non-button widgets.
Parameters
ctx the GUI context
widget_id id of the target button widget
normal bitmap for the idle state
hover bitmap for the hover state (NULL = normal)
active bitmap for the pressed / toggled-on state (NULL = normal)
Definition at line 1477 of file n_gui.c.
References N_GUI_BUTTON_DATA::bitmap, N_GUI_BUTTON_DATA::bitmap_active, N_GUI_BUTTON_DATA::bitmap_hover, N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_SHAPE_BITMAP, N_GUI_TYPE_BUTTON, N_GUI_BUTTON_DATA::shape, and N_GUI_WIDGET::type.
n_gui_button_set_toggle_mode()
void n_gui_button_set_toggle_mode (N_GUI_CTX * ctx, int widget_id, int toggle_mode)
set button toggle mode
set button toggle mode
Parameters
ctx the GUI context
widget_id id of the target button widget
toggle_mode 0 = momentary, 1 = toggle
Definition at line 1504 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_BUTTON, N_GUI_BUTTON_DATA::toggle_mode, N_GUI_BUTTON_DATA::toggled, and N_GUI_WIDGET::type.
n_gui_button_set_toggled()
void n_gui_button_set_toggled (N_GUI_CTX * ctx, int widget_id, int toggled)
set button toggled state
set button toggled state
Definition at line 1491 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_BUTTON, and N_GUI_WIDGET::type.
Referenced by main(), n_gui_tab_set_active(), on_height_toggle(), on_player_toggle(), on_proj_select(), and on_proj_select().
n_gui_checkbox_is_checked()
int n_gui_checkbox_is_checked (N_GUI_CTX * ctx, int widget_id)
check if checkbox is checked
check if checkbox is checked
Parameters
ctx GUI context
widget_id id of the checkbox widget
Returns
1 if checked, 0 otherwise
Definition at line 2218 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_CHECKBOX, and N_GUI_WIDGET::type.
n_gui_checkbox_set_bitmaps()
void n_gui_checkbox_set_bitmaps (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * box, ALLEGRO_BITMAP * box_checked, ALLEGRO_BITMAP * box_hover)
set optional bitmap overlays on a checkbox widget.
Pass NULL for any bitmap you don't want to set.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional bitmap overlays on a checkbox widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 2906 of file n_gui.c.
References N_GUI_CHECKBOX_DATA::box_bitmap, N_GUI_CHECKBOX_DATA::box_checked_bitmap, N_GUI_CHECKBOX_DATA::box_hover_bitmap, N_GUI_WIDGET::data, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_CHECKBOX, n_log, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_checkbox_set_checked()
void n_gui_checkbox_set_checked (N_GUI_CTX * ctx, int widget_id, int checked)
set checkbox checked state
set checkbox checked state
Parameters
ctx GUI context
widget_id id of the checkbox widget
checked 1 to check, 0 to uncheck
Definition at line 2232 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_CHECKBOX, and N_GUI_WIDGET::type.
n_gui_close_window()
void n_gui_close_window (N_GUI_CTX * ctx, int window_id)
close (hide) a window
close (hide) a window
Definition at line 759 of file n_gui.c.
References n_gui_get_window(), and N_GUI_WINDOW::state.
Referenced by _tb_button_action(), main(), n_gui_tab_set_active(), and on_ghost_toggle().
n_gui_combobox_add_item()
int n_gui_combobox_add_item (N_GUI_CTX * ctx, int widget_id, const char * text)
add an item to a combo box
Definition at line 2548 of file n_gui.c.
References _items_grow(), N_GUI_WIDGET::data, N_GUI_COMBOBOX_DATA::items, N_GUI_COMBOBOX_DATA::items_capacity, n_gui_get_widget(), N_GUI_ID_MAX, N_GUI_TYPE_COMBOBOX, N_GUI_COMBOBOX_DATA::nb_items, N_GUI_LISTITEM::selected, N_GUI_LISTITEM::text, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_combobox_clear()
void n_gui_combobox_clear (N_GUI_CTX * ctx, int widget_id)
remove all items from a combobox
remove all items from a combobox
Parameters
ctx GUI context
widget_id id of the combobox widget
Definition at line 2535 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_COMBOBOX_DATA::is_open, N_GUI_COMBOBOX_DATA::items, n_gui_get_widget(), N_GUI_TYPE_COMBOBOX, N_GUI_COMBOBOX_DATA::nb_items, N_GUI_COMBOBOX_DATA::scroll_offset, N_GUI_COMBOBOX_DATA::selected_index, and N_GUI_WIDGET::type.
n_gui_combobox_get_item_text()
const char * n_gui_combobox_get_item_text (N_GUI_CTX * ctx, int widget_id, int index)
get the text of the combobox item at index ("" if out of range / not a combobox)
Definition at line 2578 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_COMBOBOX_DATA::items, n_gui_get_widget(), N_GUI_TYPE_COMBOBOX, N_GUI_LISTITEM::text, and N_GUI_WIDGET::type.
n_gui_combobox_get_selected()
int n_gui_combobox_get_selected (N_GUI_CTX * ctx, int widget_id)
get the selected item index
get the selected item index
Parameters
ctx GUI context
widget_id id of the combobox widget
Returns
index of the selected item, or -1 if none
Definition at line 2570 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_COMBOBOX, and N_GUI_WIDGET::type.
n_gui_combobox_set_bitmaps()
void n_gui_combobox_set_bitmaps (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * bg, ALLEGRO_BITMAP * item_bg, ALLEGRO_BITMAP * item_selected)
set optional bitmap overlays on a combobox widget.
Pass NULL for any bitmap you don't want to set.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional bitmap overlays on a combobox widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 2981 of file n_gui.c.
References N_GUI_COMBOBOX_DATA::bg_bitmap, N_GUI_WIDGET::data, N_GUI_COMBOBOX_DATA::item_bg_bitmap, N_GUI_COMBOBOX_DATA::item_selected_bitmap, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_COMBOBOX, n_log, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_combobox_set_flags()
void n_gui_combobox_set_flags (N_GUI_CTX * ctx, int widget_id, int flags)
set combobox feature flags (bitmask of N_GUI_COMBOBOX_* values)
set combobox feature flags (bitmask of N_GUI_COMBOBOX_* values)
Parameters
ctx GUI context. Must not be NULL.
widget_id Combobox widget id.
flags Bitmask of N_GUI_COMBOBOX_* values.
Definition at line 1843 of file n_gui.c.
References __n_assert, N_GUI_WIDGET::data, N_GUI_COMBOBOX_DATA::flags, n_gui_get_widget(), N_GUI_TYPE_COMBOBOX, and N_GUI_WIDGET::type.
n_gui_combobox_set_selected()
void n_gui_combobox_set_selected (N_GUI_CTX * ctx, int widget_id, int index)
set the selected item index
set the selected item index
Parameters
ctx GUI context
widget_id id of the combobox widget
index index of the item to select, or -1 for none
Definition at line 2595 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_COMBOBOX, N_GUI_COMBOBOX_DATA::selected_index, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_default_style()
N_GUI_STYLE n_gui_default_style (void)
return the built-in default style
return the built-in default style
Definition at line 432 of file n_gui.c.
References N_GUI_STYLE::checkbox_label_gap, N_GUI_STYLE::checkbox_label_offset, N_GUI_STYLE::checkbox_mark_margin, N_GUI_STYLE::checkbox_mark_thickness, N_GUI_STYLE::checkbox_max_size, N_GUI_STYLE::combobox_max_dropdown_width, N_GUI_STYLE::combobox_max_visible, N_GUI_STYLE::dropdown_arrow_half_h, N_GUI_STYLE::dropdown_arrow_half_w, N_GUI_STYLE::dropdown_arrow_reserve, N_GUI_STYLE::dropdown_arrow_thickness, N_GUI_STYLE::dropdown_border_thickness, N_GUI_STYLE::dropmenu_max_visible, N_GUI_STYLE::global_scroll_step, N_GUI_STYLE::global_scrollbar_border_thickness, N_GUI_STYLE::global_scrollbar_size, N_GUI_STYLE::global_scrollbar_thumb_border_color, N_GUI_STYLE::global_scrollbar_thumb_color, N_GUI_STYLE::global_scrollbar_thumb_corner_r, N_GUI_STYLE::global_scrollbar_thumb_min, N_GUI_STYLE::global_scrollbar_thumb_padding, N_GUI_STYLE::global_scrollbar_track_color, N_GUI_STYLE::grip_color, N_GUI_STYLE::grip_line_thickness, N_GUI_STYLE::grip_size, N_GUI_STYLE::item_height_pad, N_GUI_STYLE::item_selection_inset, N_GUI_STYLE::item_text_padding, N_GUI_STYLE::label_padding, N_GUI_STYLE::link_color_hover, N_GUI_STYLE::link_color_normal, N_GUI_STYLE::link_underline_thickness, N_GUI_STYLE::listbox_default_item_height, N_GUI_STYLE::min_win_h, N_GUI_STYLE::min_win_w, N_GUI_STYLE::radio_circle_border_thickness, N_GUI_STYLE::radio_circle_min_r, N_GUI_STYLE::radio_inner_offset, N_GUI_STYLE::radio_label_gap, N_GUI_STYLE::radiolist_default_item_height, N_GUI_STYLE::scroll_step, N_GUI_STYLE::scrollbar_size, N_GUI_STYLE::scrollbar_thumb_color, N_GUI_STYLE::scrollbar_thumb_corner_r, N_GUI_STYLE::scrollbar_thumb_min, N_GUI_STYLE::scrollbar_thumb_padding, N_GUI_STYLE::scrollbar_track_color, N_GUI_STYLE::slider_handle_border_thickness, N_GUI_STYLE::slider_handle_edge_offset, N_GUI_STYLE::slider_handle_min_r, N_GUI_STYLE::slider_track_border_thickness, N_GUI_STYLE::slider_track_corner_r, N_GUI_STYLE::slider_track_size, N_GUI_STYLE::slider_value_label_offset, N_GUI_STYLE::tb_btn_glyph_thickness, N_GUI_STYLE::tb_btn_right_margin, N_GUI_STYLE::tb_btn_size, N_GUI_STYLE::tb_btn_spacing, N_GUI_STYLE::textarea_cursor_blink_period, N_GUI_STYLE::textarea_cursor_width, N_GUI_STYLE::textarea_padding, N_GUI_STYLE::title_max_w_reserve, N_GUI_STYLE::title_padding, N_GUI_STYLE::titlebar_h, N_GUI_STYLE::tooltip_bg, N_GUI_STYLE::tooltip_border, N_GUI_STYLE::tooltip_delay, and N_GUI_STYLE::tooltip_fg.
Referenced by n_gui_new_ctx().
n_gui_default_tb_btn_theme()
N_GUI_THEME n_gui_default_tb_btn_theme (void)
return the built-in default theme for titlebar minimize/maximize buttons
return the built-in default theme for titlebar minimize/maximize buttons
Semi-transparent, blends with the titlebar background.
Definition at line 372 of file n_gui.c.
References N_GUI_THEME::bg_active, N_GUI_THEME::bg_hover, N_GUI_THEME::bg_normal, N_GUI_THEME::border_active, N_GUI_THEME::border_hover, N_GUI_THEME::border_normal, N_GUI_THEME::border_thickness, N_GUI_THEME::corner_rx, N_GUI_THEME::corner_ry, N_GUI_THEME::selection_color, N_GUI_THEME::text_active, N_GUI_THEME::text_hover, and N_GUI_THEME::text_normal.
Referenced by n_gui_default_tb_close_theme(), and n_gui_new_ctx().
n_gui_default_tb_close_theme()
N_GUI_THEME n_gui_default_tb_close_theme (void)
return the built-in default theme for the titlebar close button (red hover/active)
return the built-in default theme for the titlebar close button (red hover/active)
Same as the btn theme but with red hover/active backgrounds.
Definition at line 395 of file n_gui.c.
References N_GUI_THEME::bg_active, N_GUI_THEME::bg_hover, and n_gui_default_tb_btn_theme().
Referenced by n_gui_new_ctx().
n_gui_default_theme()
N_GUI_THEME n_gui_default_theme (void)
return the built-in default theme
return the built-in default theme
Returns
a N_GUI_THEME with dark-ish colours
Definition at line 295 of file n_gui.c.
References N_GUI_THEME::bg_active, N_GUI_THEME::bg_hover, N_GUI_THEME::bg_normal, N_GUI_THEME::border_active, N_GUI_THEME::border_hover, N_GUI_THEME::border_normal, N_GUI_THEME::border_thickness, N_GUI_THEME::corner_rx, N_GUI_THEME::corner_ry, N_GUI_THEME::selection_color, N_GUI_THEME::text_active, N_GUI_THEME::text_hover, and N_GUI_THEME::text_normal.
Referenced by n_gui_new_ctx().
n_gui_destroy_ctx()
void n_gui_destroy_ctx (N_GUI_CTX ** ctx)
destroy a GUI context and free all resources
destroy a GUI context and free all resources
Parameters
ctx pointer to the context pointer (set to NULL)
Definition at line 608 of file n_gui.c.
References __n_assert, destroy_ht(), Free, FreeNoLog, and list_destroy().
Referenced by main(), and main().
n_gui_detect_dpi_scale()
float n_gui_detect_dpi_scale (N_GUI_CTX * ctx, ALLEGRO_DISPLAY * display)
detect and apply DPI scale from the given allegro display.
Works on Linux (X11/Wayland), Windows, and Android. Returns the detected scale factor.
detect and apply DPI scale from the given allegro display.
Detection strategy (cross-platform):
Compare the physical pixel size (framebuffer) to the logical window size. On HiDPI displays these differ (e.g. a 1920-logical window may have a 3840-pixel framebuffer on a 2x Retina display).
On Android, al_get_display_option(ALLEGRO_DEFAULT_DISPLAY_ADAPTER) and the framebuffer/window ratio gives the density scale.
On Windows with per-monitor DPI awareness, the ratio reflects the OS scaling percentage (125% = 1.25, 150% = 1.5, etc.).
On Linux/X11/Wayland, the ratio picks up Xft.dpi or Wayland scale factor if Allegro was built with the appropriate backend.
If the framebuffer and window sizes are both reported identically (no HiDPI support from the Allegro build), the function falls back to 1.0.
Returns
the detected scale factor (also stored in ctx->dpi_scale)
Definition at line 5945 of file n_gui.c.
References __n_assert, display, and N_GUI_CTX::dpi_scale.
Referenced by main().
n_gui_draw()
void n_gui_draw (N_GUI_CTX * ctx)
draw all visible GUI windows and widgets
draw all visible GUI windows and widgets
When a display size has been set (via n_gui_set_display_size) and the total GUI bounding box exceeds it, global scrollbars are drawn at the edges of the display and all windows are offset by the global scroll position.
Parameters
ctx the GUI context
Definition at line 5488 of file n_gui.c.
References __n_assert, _compute_gui_bounds(), _draw_combobox_dropdown(), _draw_dropmenu_panel(), _draw_window(), _text_w(), N_GUI_WINDOW::autofit_flags, N_GUI_CTX::default_font, N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_CTX::global_scroll_x, N_GUI_CTX::global_scroll_y, N_GUI_STYLE::global_scrollbar_border_thickness, N_GUI_STYLE::global_scrollbar_size, N_GUI_STYLE::global_scrollbar_thumb_border_color, N_GUI_STYLE::global_scrollbar_thumb_color, N_GUI_STYLE::global_scrollbar_thumb_corner_r, N_GUI_STYLE::global_scrollbar_thumb_min, N_GUI_STYLE::global_scrollbar_thumb_padding, N_GUI_STYLE::global_scrollbar_track_color, N_GUI_CTX::gui_bounds_h, N_GUI_CTX::gui_bounds_w, N_GUI_CTX::gui_offset_x, N_GUI_CTX::gui_offset_y, N_GUI_CTX::gui_scale, N_GUI_WINDOW::id, list_foreach, N_GUI_CTX::mouse_x, N_GUI_CTX::mouse_y, n_gui_get_widget(), N_GUI_WIN_MINIMISED, N_GUI_WIN_OPEN, n_gui_window_apply_autofit(), N_GUI_WINDOW::on_content_draw, N_GUI_WINDOW::on_content_draw_data, N_GUI_WINDOW::state, N_GUI_CTX::style, N_GUI_WIDGET::tooltip, N_GUI_CTX::tooltip_armed_at, N_GUI_STYLE::tooltip_bg, N_GUI_STYLE::tooltip_border, N_GUI_STYLE::tooltip_delay, N_GUI_STYLE::tooltip_fg, N_GUI_CTX::tooltip_widget_id, N_GUI_CTX::virtual_h, N_GUI_CTX::virtual_w, N_GUI_WIDGET::visible, and N_GUI_CTX::windows.
Referenced by main(), and main().
n_gui_dropmenu_add_dynamic_entry()
int n_gui_dropmenu_add_dynamic_entry (N_GUI_CTX * ctx, int widget_id, const char * text, int tag, void(*)(int, int, int, void *) on_click, void * user_data)
add a dynamic entry (rebuilt each time menu opens)
add a dynamic entry (rebuilt each time menu opens)
Returns
entry index, or -1 on error
Definition at line 2762 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_DROPMENU_DATA::entries, N_GUI_DROPMENU_ENTRY::is_dynamic, LOG_ERR, n_gui_dropmenu_add_entry(), n_gui_get_widget(), and n_log.
Referenced by on_windows_menu_open().
n_gui_dropmenu_add_entry()
int n_gui_dropmenu_add_entry (N_GUI_CTX * ctx, int widget_id, const char * text, int tag, void(*)(int, int, int, void *) on_click, void * user_data)
add a static entry to a dropdown menu
add a static entry to a dropdown menu
Returns
entry index, or -1 on error
Definition at line 2739 of file n_gui.c.
References _dropmenu_entries_grow(), N_GUI_WIDGET::data, N_GUI_DROPMENU_DATA::entries, N_GUI_DROPMENU_DATA::entries_capacity, N_GUI_DROPMENU_ENTRY::is_dynamic, n_gui_get_widget(), N_GUI_ID_MAX, N_GUI_TYPE_DROPMENU, N_GUI_DROPMENU_DATA::nb_entries, N_GUI_DROPMENU_ENTRY::on_click, N_GUI_DROPMENU_ENTRY::tag, N_GUI_DROPMENU_ENTRY::text, N_GUI_WIDGET::type, and N_GUI_DROPMENU_ENTRY::user_data.
Referenced by main(), and n_gui_dropmenu_add_dynamic_entry().
n_gui_dropmenu_clear()
void n_gui_dropmenu_clear (N_GUI_CTX * ctx, int widget_id)
remove all entries
remove all entries
Definition at line 2816 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_DROPMENU, N_GUI_DROPMENU_DATA::nb_entries, N_GUI_DROPMENU_DATA::scroll_offset, and N_GUI_WIDGET::type.
n_gui_dropmenu_clear_dynamic()
void n_gui_dropmenu_clear_dynamic (N_GUI_CTX * ctx, int widget_id)
remove all dynamic entries (call from on_open callback before re-adding)
remove all dynamic entries (call from on_open callback before re-adding)
Definition at line 2787 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_DROPMENU_DATA::entries, N_GUI_DROPMENU_ENTRY::is_dynamic, N_GUI_DROPMENU_DATA::max_visible, n_gui_get_widget(), N_GUI_TYPE_DROPMENU, N_GUI_DROPMENU_DATA::nb_entries, N_GUI_DROPMENU_DATA::scroll_offset, and N_GUI_WIDGET::type.
Referenced by on_windows_menu_open().
n_gui_dropmenu_get_count()
int n_gui_dropmenu_get_count (N_GUI_CTX * ctx, int widget_id)
get number of entries
get number of entries
Definition at line 2841 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_DROPMENU, and N_GUI_WIDGET::type.
n_gui_dropmenu_set_bitmaps()
void n_gui_dropmenu_set_bitmaps (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * panel, ALLEGRO_BITMAP * item_hover)
set optional bitmap overlays on a dropmenu widget.
Pass NULL for any bitmap you don't want to set.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional bitmap overlays on a dropmenu widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 2997 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_DROPMENU_DATA::item_hover_bitmap, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_DROPMENU, n_log, N_GUI_DROPMENU_DATA::panel_bitmap, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_dropmenu_set_entry_text()
void n_gui_dropmenu_set_entry_text (N_GUI_CTX * ctx, int widget_id, int index, const char * text)
update text of an existing entry by index
update text of an existing entry by index
Definition at line 2827 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_DROPMENU_DATA::entries, n_gui_get_widget(), N_GUI_ID_MAX, N_GUI_TYPE_DROPMENU, N_GUI_DROPMENU_DATA::nb_entries, N_GUI_DROPMENU_ENTRY::text, and N_GUI_WIDGET::type.
n_gui_dropmenu_set_flags()
void n_gui_dropmenu_set_flags (N_GUI_CTX * ctx, int widget_id, int flags)
set dropmenu feature flags (bitmask of N_GUI_DROPMENU_* values)
set dropmenu feature flags (bitmask of N_GUI_DROPMENU_* values)
Definition at line 2728 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_DROPMENU_DATA::flags, n_gui_get_widget(), N_GUI_TYPE_DROPMENU, and N_GUI_WIDGET::type.
n_gui_focus_window()
void n_gui_focus_window (N_GUI_CTX * ctx, int window_id)
give a window keyboard focus: raise it within its z-order group and focus its first focusable widget (clears focus if it has none)
give a window keyboard focus: raise it within its z-order group and focus its first focusable widget (clears focus if it has none)
Raises the window within its z-order group (so it is drawn on top of its peers) and moves keyboard focus to its first focusable, visible, enabled widget. If the window has no focusable widget, focus is cleared so global key bindings still fire. Does nothing if the window id is unknown.
Definition at line 1060 of file n_gui.c.
References __n_assert, _is_focusable_type(), N_GUI_WIDGET::enabled, N_GUI_WIDGET::id, list_foreach, n_gui_get_window(), n_gui_raise_window(), n_gui_set_focus(), N_GUI_WIDGET::type, N_GUI_WIDGET::visible, and N_GUI_WINDOW::widgets.
n_gui_get_dpi_scale()
float n_gui_get_dpi_scale (const N_GUI_CTX * ctx)
get current DPI scale factor
get current DPI scale factor
Definition at line 5921 of file n_gui.c.
References __n_assert, and N_GUI_CTX::dpi_scale.
n_gui_get_resize_mode()
int n_gui_get_resize_mode (N_GUI_CTX * ctx)
get current resize mode
get current resize mode
Returns
N_GUI_RESIZE_VIRTUAL or N_GUI_RESIZE_ADAPTIVE
Definition at line 5782 of file n_gui.c.
References __n_assert, and N_GUI_CTX::resize_mode.
n_gui_get_text_dims()
N_GUI_TEXT_DIMS n_gui_get_text_dims (ALLEGRO_FONT * font, const char * text)
get the bounding box dimensions of text rendered with the given font.
Uses al_get_text_dimensions for accurate measurement including glyph overhangs.
Definition at line 61 of file n_gui.c.
References N_GUI_TEXT_DIMS::h, N_GUI_TEXT_DIMS::w, N_GUI_TEXT_DIMS::x, and N_GUI_TEXT_DIMS::y.
n_gui_get_topmost_open_window()
int n_gui_get_topmost_open_window (const N_GUI_CTX * ctx)
get the id of the frontmost open, non-minimized window (the last one in draw order), or -1 if no window is open.
Because the window list is kept sorted by z-order group, this is the topmost window currently on screen.
get the id of the frontmost open, non-minimized window (the last one in draw order), or -1 if no window is open.
The window list is kept sorted by z-order group with the topmost group last, so the last open window in list order is the one drawn on top. Returns -1 when no window is open.
Definition at line 1039 of file n_gui.c.
References __n_assert, LIST::end, N_GUI_WINDOW::id, N_GUI_WIN_MINIMISED, N_GUI_WIN_OPEN, N_GUI_WINDOW::state, and N_GUI_CTX::windows.
n_gui_get_widget()
N_GUI_WIDGET * n_gui_get_widget (N_GUI_CTX * ctx, int widget_id)
get a widget by id
get a widget by id
Definition at line 1956 of file n_gui.c.
References __n_assert, ht_get_ptr(), key, and N_GUI_CTX::widgets_by_id.
Referenced by _draw_combobox_dropdown(), _draw_dropmenu_panel(), _n_gui_kv_apply_layout(), _n_gui_tree_listbox_bounds(), main(), n_gui_add_button_bitmap(), n_gui_add_label_link(), n_gui_add_toggle_button(), n_gui_add_vslider(), n_gui_button_is_toggled(), n_gui_button_set_keycode(), n_gui_button_set_keycode_focused(), n_gui_button_set_label(), n_gui_button_set_state_bitmaps(), n_gui_button_set_toggle_mode(), n_gui_button_set_toggled(), n_gui_checkbox_is_checked(), n_gui_checkbox_set_bitmaps(), n_gui_checkbox_set_checked(), n_gui_combobox_add_item(), n_gui_combobox_clear(), n_gui_combobox_get_item_text(), n_gui_combobox_get_selected(), n_gui_combobox_set_bitmaps(), n_gui_combobox_set_flags(), n_gui_combobox_set_selected(), n_gui_draw(), n_gui_dropmenu_add_dynamic_entry(), n_gui_dropmenu_add_entry(), n_gui_dropmenu_clear(), n_gui_dropmenu_clear_dynamic(), n_gui_dropmenu_get_count(), n_gui_dropmenu_set_bitmaps(), n_gui_dropmenu_set_entry_text(), n_gui_dropmenu_set_flags(), n_gui_image_set_bitmap(), n_gui_is_widget_enabled(), n_gui_label_set_bitmap(), n_gui_label_set_link(), n_gui_label_set_text(), n_gui_listbox_add_item(), n_gui_listbox_clear(), n_gui_listbox_get_count(), n_gui_listbox_get_item_text(), n_gui_listbox_get_scroll_offset(), n_gui_listbox_get_selected(), n_gui_listbox_is_selected(), n_gui_listbox_remove_item(), n_gui_listbox_set_bitmaps(), n_gui_listbox_set_scroll_offset(), n_gui_listbox_set_selected(), n_gui_process_event(), n_gui_radiolist_add_item(), n_gui_radiolist_clear(), n_gui_radiolist_get_selected(), n_gui_radiolist_set_bitmaps(), n_gui_radiolist_set_selected(), n_gui_scrollbar_get_pos(), n_gui_scrollbar_set_bitmaps(), n_gui_scrollbar_set_pos(), n_gui_scrollbar_set_sizes(), n_gui_sectionlist_add_widget(), n_gui_sectionlist_relayout(), n_gui_set_focus(), n_gui_set_widget_enabled(), n_gui_set_widget_theme(), n_gui_set_widget_tooltip(), n_gui_set_widget_visible(), n_gui_slider_get_value(), n_gui_slider_set_bitmaps(), n_gui_slider_set_range(), n_gui_slider_set_step(), n_gui_slider_set_value(), n_gui_slider_set_value_format(), n_gui_slider_set_value_visible(), n_gui_textarea_get_text(), n_gui_textarea_get_text_length(), n_gui_textarea_scroll_to_bottom(), n_gui_textarea_scroll_to_offset(), n_gui_textarea_set_bitmap(), n_gui_textarea_set_mask_char(), n_gui_textarea_set_selection(), n_gui_textarea_set_text(), and n_gui_tree_draw_overlay().
n_gui_get_window()
N_GUI_WINDOW * n_gui_get_window (N_GUI_CTX * ctx, int window_id)
get a window by id
get a window by id
Definition at line 750 of file n_gui.c.
References _find_window_node(), and LIST_NODE::ptr.
Referenced by _n_gui_kv_apply_layout(), _n_gui_tree_listbox_bounds(), n_gui_add_button(), n_gui_add_checkbox(), n_gui_add_combobox(), n_gui_add_dropmenu(), n_gui_add_image(), n_gui_add_label(), n_gui_add_listbox(), n_gui_add_radiolist(), n_gui_add_scrollbar(), n_gui_add_slider(), n_gui_add_textarea(), n_gui_close_window(), n_gui_focus_window(), n_gui_kvtable_create(), n_gui_maximize_window(), n_gui_minimize_window(), n_gui_open_window(), n_gui_process_event(), n_gui_sectionlist_relayout(), n_gui_toggle_window(), n_gui_window_apply_autofit(), n_gui_window_autosize(), n_gui_window_get_flags(), n_gui_window_get_resize_policy(), n_gui_window_get_zorder(), n_gui_window_get_zvalue(), n_gui_window_is_maximised(), n_gui_window_is_open(), n_gui_window_set_autofit(), n_gui_window_set_bitmaps(), n_gui_window_set_close_callback(), n_gui_window_set_content_draw_callback(), n_gui_window_set_flags(), n_gui_window_set_maximize_callback(), n_gui_window_set_minimize_callback(), n_gui_window_set_resize_policy(), n_gui_window_set_tb_btn_theme(), n_gui_window_set_tb_button_bitmaps(), n_gui_window_set_tb_close_theme(), n_gui_window_set_zorder(), and n_gui_window_update_normalized().
n_gui_image_set_bitmap()
void n_gui_image_set_bitmap (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * bitmap)
set the bitmap on an image widget
set the bitmap on an image widget
Parameters
ctx GUI context
widget_id id of the image widget
bitmap pointer to the ALLEGRO_BITMAP to set
Definition at line 2613 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_IMAGE, and N_GUI_WIDGET::type.
n_gui_is_widget_enabled()
int n_gui_is_widget_enabled (N_GUI_CTX * ctx, int widget_id)
check if a widget is enabled
check if a widget is enabled
Returns
1 if enabled, 0 if disabled
Definition at line 2021 of file n_gui.c.
References N_GUI_WIDGET::enabled, and n_gui_get_widget().
n_gui_kvtable_add_row()
int n_gui_kvtable_add_row (N_GUI_KVTABLE * table, const char * key, const char * value, const char * description, int enabled)
add a row to the KV table
Definition at line 9631 of file n_gui.c.
References _n_gui_kv_apply_layout(), _n_gui_kv_remove_clicked(), N_GUI_KV_ROW::active, N_GUI_KVTABLE::ctx, N_GUI_KV_ROW::desc_id, N_GUI_KV_ROW::enabled_id, key, N_GUI_KV_ROW::key_id, n_gui_add_button(), n_gui_add_checkbox(), n_gui_add_textarea(), N_GUI_KV_MAX, N_GUI_SHAPE_RECT, n_gui_textarea_set_text(), N_GUI_KVTABLE::nb_active, N_GUI_KVTABLE::nb_rows, N_GUI_KVTABLE::padding, N_GUI_KV_ROW::remove_id, N_GUI_KVTABLE::row_height, N_GUI_KVTABLE::rows, N_GUI_KV_ROW::value_id, and N_GUI_KVTABLE::window_id.
Referenced by _n_gui_kv_add_clicked(), and main().
n_gui_kvtable_create()
N_GUI_KVTABLE * n_gui_kvtable_create (N_GUI_CTX * ctx, int window_id, float row_height, float padding, void(*)(int, void *) on_remove, void * user_data)
create a KV table in an existing window
Definition at line 9588 of file n_gui.c.
References _n_gui_kv_add_clicked(), _n_gui_kv_apply_layout(), N_GUI_KVTABLE::btn_add, N_GUI_KVTABLE::ctx, N_GUI_WINDOW::h, N_GUI_KVTABLE::header_height, N_GUI_KVTABLE::init_win_h, N_GUI_KVTABLE::init_win_w, N_GUI_KVTABLE::lbl_desc, N_GUI_KVTABLE::lbl_enabled, N_GUI_KVTABLE::lbl_key, N_GUI_KVTABLE::lbl_value, Malloc, n_gui_add_button(), n_gui_add_label(), N_GUI_ALIGN_LEFT, n_gui_get_window(), N_GUI_SHAPE_ROUNDED, N_GUI_KVTABLE::nb_active, N_GUI_KVTABLE::nb_rows, N_GUI_KVTABLE::on_remove, N_GUI_KVTABLE::padding, N_GUI_KVTABLE::row_height, N_GUI_KVTABLE::user_data, N_GUI_WINDOW::w, and N_GUI_KVTABLE::window_id.
Referenced by main().
n_gui_kvtable_free()
void n_gui_kvtable_free (N_GUI_KVTABLE ** table)
free a KV table (does not destroy the N_GUI widgets)
Definition at line 9686 of file n_gui.c.
References FreeNoLog.
Referenced by main().
n_gui_kvtable_get_count()
int n_gui_kvtable_get_count (N_GUI_KVTABLE * table)
get the number of active rows
Definition at line 9678 of file n_gui.c.
References N_GUI_KVTABLE::nb_active.
n_gui_kvtable_relayout()
void n_gui_kvtable_relayout (N_GUI_KVTABLE * table)
re-apply layout to all KV table widgets (positions, sizes, normalized coords).
Called automatically on create/add/remove; callers should invoke it after any manual window size change the kvtable cannot see.
Definition at line 9682 of file n_gui.c.
References _n_gui_kv_apply_layout().
Referenced by main().
n_gui_kvtable_remove_row()
void n_gui_kvtable_remove_row (N_GUI_KVTABLE * table, int row_index)
remove a row by index (hides widgets, marks inactive)
Definition at line 9664 of file n_gui.c.
References _n_gui_kv_apply_layout(), N_GUI_KV_ROW::active, N_GUI_KVTABLE::ctx, N_GUI_KV_ROW::desc_id, N_GUI_KV_ROW::enabled_id, N_GUI_KV_ROW::key_id, n_gui_set_widget_visible(), N_GUI_KVTABLE::nb_active, N_GUI_KVTABLE::nb_rows, N_GUI_KV_ROW::remove_id, N_GUI_KVTABLE::rows, and N_GUI_KV_ROW::value_id.
Referenced by _n_gui_kv_remove_clicked(), and main().
n_gui_label_set_bitmap()
void n_gui_label_set_bitmap (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * bg)
set optional background bitmap on a label widget.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional background bitmap on a label widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 3012 of file n_gui.c.
References N_GUI_WIDGET::data, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_LABEL, n_log, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_label_set_link()
void n_gui_label_set_link (N_GUI_CTX * ctx, int widget_id, const char * link)
set label hyperlink URL
set label hyperlink URL
Parameters
ctx GUI context
widget_id id of the label widget
link the URL to set, or NULL to clear
Definition at line 2648 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_LABEL_DATA::link, n_gui_get_widget(), N_GUI_TEXT_MAX, N_GUI_TYPE_LABEL, and N_GUI_WIDGET::type.
n_gui_label_set_text()
void n_gui_label_set_text (N_GUI_CTX * ctx, int widget_id, const char * text)
set label text content
set label text content
Parameters
ctx GUI context
widget_id id of the label widget
text the text to set, or NULL to clear
Definition at line 2628 of file n_gui.c.
References _normalize_crlf(), N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TEXT_MAX, N_GUI_TYPE_LABEL, N_GUI_LABEL_DATA::text, and N_GUI_WIDGET::type.
Referenced by main(), main(), and update_definitions().
n_gui_listbox_add_item()
int n_gui_listbox_add_item (N_GUI_CTX * ctx, int widget_id, const char * text)
add an item to a listbox
add an item to a listbox
Parameters
ctx GUI context
widget_id id of the listbox widget
text text of the item to add
Returns
index of the new item or -1 on error
Definition at line 2299 of file n_gui.c.
References _items_grow(), N_GUI_WIDGET::data, N_GUI_LISTBOX_DATA::items, N_GUI_LISTBOX_DATA::items_capacity, n_gui_get_widget(), N_GUI_ID_MAX, N_GUI_TYPE_LISTBOX, N_GUI_LISTBOX_DATA::nb_items, N_GUI_LISTITEM::selected, N_GUI_LISTITEM::text, and N_GUI_WIDGET::type.
Referenced by chat_log_add(), main(), n_gui_tree_rebuild(), and update_completion().
n_gui_listbox_clear()
void n_gui_listbox_clear (N_GUI_CTX * ctx, int widget_id)
clear all items from a listbox
clear all items from a listbox
Parameters
ctx GUI context
widget_id id of the listbox widget
Definition at line 2346 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, N_GUI_LISTBOX_DATA::nb_items, N_GUI_LISTBOX_DATA::scroll_offset, and N_GUI_WIDGET::type.
Referenced by n_gui_tree_clear(), n_gui_tree_rebuild(), refresh_clients_list(), and update_completion().
n_gui_listbox_get_count()
int n_gui_listbox_get_count (N_GUI_CTX * ctx, int widget_id)
get number of items in a listbox
get number of items in a listbox
Parameters
ctx GUI context
widget_id id of the listbox widget
Returns
number of items
Definition at line 2361 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, and N_GUI_WIDGET::type.
n_gui_listbox_get_item_text()
const char * n_gui_listbox_get_item_text (N_GUI_CTX * ctx, int widget_id, int index)
get item text by index
get item text by index
Parameters
ctx GUI context
widget_id id of the listbox widget
index index of the item
Returns
pointer to the item text, or empty string on error
Definition at line 2376 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_LISTBOX_DATA::items, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, N_GUI_LISTITEM::text, and N_GUI_WIDGET::type.
Referenced by on_completion_select().
n_gui_listbox_get_scroll_offset()
int n_gui_listbox_get_scroll_offset (N_GUI_CTX * ctx, int widget_id)
get the current scroll offset (in items)
Definition at line 2440 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, N_GUI_LISTBOX_DATA::scroll_offset, and N_GUI_WIDGET::type.
Referenced by n_gui_tree_rebuild().
n_gui_listbox_get_selected()
int n_gui_listbox_get_selected (N_GUI_CTX * ctx, int widget_id)
get the first selected item index
get the first selected item index
Parameters
ctx GUI context
widget_id id of the listbox widget
Returns
index of the first selected item, or -1 if none
Definition at line 2393 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_LISTBOX_DATA::items, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, N_GUI_LISTBOX_DATA::nb_items, N_GUI_LISTITEM::selected, and N_GUI_WIDGET::type.
Referenced by main(), and n_gui_tree_get_selection().
n_gui_listbox_is_selected()
int n_gui_listbox_is_selected (N_GUI_CTX * ctx, int widget_id, int index)
check if an item is selected
check if an item is selected
Parameters
ctx GUI context
widget_id id of the listbox widget
index index of the item to check
Returns
1 if selected, 0 otherwise
Definition at line 2411 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_LISTBOX_DATA::items, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, N_GUI_LISTITEM::selected, and N_GUI_WIDGET::type.
n_gui_listbox_remove_item()
int n_gui_listbox_remove_item (N_GUI_CTX * ctx, int widget_id, int index)
remove an item from a listbox by index
remove an item from a listbox by index
Parameters
ctx GUI context
widget_id id of the listbox widget
index index of the item to remove
Returns
0 on success, -1 on error
Definition at line 2322 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_LISTBOX_DATA::items, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, N_GUI_LISTBOX_DATA::nb_items, N_GUI_LISTBOX_DATA::scroll_offset, and N_GUI_WIDGET::type.
n_gui_listbox_set_bitmaps()
void n_gui_listbox_set_bitmaps (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * bg, ALLEGRO_BITMAP * item_bg, ALLEGRO_BITMAP * item_selected)
set optional bitmap overlays on a listbox widget.
Pass NULL for any bitmap you don't want to set.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional bitmap overlays on a listbox widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 2949 of file n_gui.c.
References N_GUI_LISTBOX_DATA::bg_bitmap, N_GUI_WIDGET::data, N_GUI_LISTBOX_DATA::item_bg_bitmap, N_GUI_LISTBOX_DATA::item_selected_bitmap, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, n_log, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_listbox_set_scroll_offset()
void n_gui_listbox_set_scroll_offset (N_GUI_CTX * ctx, int widget_id, int offset)
set the scroll offset (in items), clamps to valid range
Definition at line 2447 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_WIDGET::h, N_GUI_LISTBOX_DATA::item_height, n_gui_get_widget(), N_GUI_TYPE_LISTBOX, N_GUI_LISTBOX_DATA::nb_items, N_GUI_LISTBOX_DATA::scroll_offset, and N_GUI_WIDGET::type.
Referenced by n_gui_tree_rebuild(), and n_gui_tree_set_selection().
n_gui_listbox_set_selected()
void n_gui_listbox_set_selected (N_GUI_CTX * ctx, int widget_id, int index, int selected)
set item selection state
set item selection state
Parameters
ctx GUI context
widget_id id of the listbox widget
index index of the item
selected 1 to select, 0 to deselect
Definition at line 2429 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_LISTBOX_DATA::items, n_gui_get_widget(), N_GUI_SELECT_SINGLE, N_GUI_TYPE_LISTBOX, N_GUI_LISTBOX_DATA::nb_items, N_GUI_LISTITEM::selected, N_GUI_LISTBOX_DATA::selection_mode, and N_GUI_WIDGET::type.
Referenced by main(), n_gui_tree_rebuild(), and n_gui_tree_set_selection().
n_gui_load_layout_json()
int n_gui_load_layout_json (N_GUI_CTX * ctx, const char * filepath)
Load a JSON window layout file and apply it to matching windows in the context.
Matching is by window title (IDs are not stable across runs). If multiple windows share a title, they are matched in creation order (first-seen-first-match). Unknown titles in the file are ignored (defensive for versions). Missing titles in the context are ignored (no-op for windows not yet created). A missing file is treated as a successful no-op (returns -1 with LOG_DEBUG). Returns 0 on success, -1 on error.
Load a JSON window layout file and apply it to matching windows in the context.
Parameters
ctx GUI context
filepath path to the input JSON file
Returns
0 on success, -1 on error
Definition at line 8611 of file n_gui.c.
References __n_assert, _json_get_float(), _json_get_int(), _N_GUI_WIN_STATE_PERSIST_MASK, N_GUI_WINDOW::autofit_border, N_GUI_WINDOW::autofit_flags, N_GUI_PENDING_GEOM::consumed, N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_WINDOW::flags, FreeNoLog, N_GUI_WINDOW::h, list_foreach, LOG_DEBUG, Malloc, N_GUI_ID_MAX, N_GUI_WIN_OPEN, n_log, N_GUI_WINDOW::norm_h, N_GUI_WINDOW::norm_w, N_GUI_WINDOW::norm_x, N_GUI_WINDOW::norm_y, N_GUI_CTX::pending_layout, N_GUI_CTX::pending_layout_count, N_GUI_WINDOW::resize_policy, N_GUI_WINDOW::state, N_GUI_WINDOW::title, N_GUI_PENDING_GEOM::title, N_GUI_WINDOW::w, N_GUI_CTX::windows, N_GUI_WINDOW::x, N_GUI_PENDING_GEOM::x, N_GUI_WINDOW::y, N_GUI_PENDING_GEOM::y, N_GUI_WINDOW::z_order, and N_GUI_WINDOW::z_value.
Referenced by on_load_layout_click().
n_gui_load_theme_json()
int n_gui_load_theme_json (N_GUI_CTX * ctx, const char * filepath)
Load a JSON theme file and apply it to the context.
Returns 0 on success, -1 on error.
Load a JSON theme file and apply it to the context.
Parameters
ctx GUI context
filepath path to the input JSON file
Returns
0 on success, -1 on error
Definition at line 8377 of file n_gui.c.
References __n_assert, _json_get_color(), _json_get_float(), _json_get_int(), N_GUI_THEME::bg_active, N_GUI_THEME::bg_hover, N_GUI_THEME::bg_normal, N_GUI_THEME::border_active, N_GUI_THEME::border_hover, N_GUI_THEME::border_normal, N_GUI_THEME::border_thickness, N_GUI_STYLE::checkbox_label_gap, N_GUI_STYLE::checkbox_label_offset, N_GUI_STYLE::checkbox_mark_margin, N_GUI_STYLE::checkbox_mark_thickness, N_GUI_STYLE::checkbox_max_size, N_GUI_STYLE::combobox_max_dropdown_width, N_GUI_STYLE::combobox_max_visible, N_GUI_THEME::corner_rx, N_GUI_THEME::corner_ry, N_GUI_CTX::default_theme, N_GUI_STYLE::dropdown_arrow_half_h, N_GUI_STYLE::dropdown_arrow_half_w, N_GUI_STYLE::dropdown_arrow_reserve, N_GUI_STYLE::dropdown_arrow_thickness, N_GUI_STYLE::dropdown_border_thickness, N_GUI_STYLE::dropmenu_max_visible, FreeNoLog, N_GUI_STYLE::global_scroll_step, N_GUI_STYLE::global_scrollbar_border_thickness, N_GUI_STYLE::global_scrollbar_size, N_GUI_STYLE::global_scrollbar_thumb_border_color, N_GUI_STYLE::global_scrollbar_thumb_color, N_GUI_STYLE::global_scrollbar_thumb_corner_r, N_GUI_STYLE::global_scrollbar_thumb_min, N_GUI_STYLE::global_scrollbar_thumb_padding, N_GUI_STYLE::global_scrollbar_track_color, N_GUI_STYLE::grip_color, N_GUI_STYLE::grip_line_thickness, N_GUI_STYLE::grip_size, N_GUI_STYLE::item_height_pad, N_GUI_STYLE::item_selection_inset, N_GUI_STYLE::item_text_padding, N_GUI_STYLE::label_padding, N_GUI_STYLE::link_color_hover, N_GUI_STYLE::link_color_normal, N_GUI_STYLE::link_underline_thickness, list_foreach, N_GUI_STYLE::listbox_default_item_height, Malloc, N_GUI_STYLE::min_win_h, N_GUI_STYLE::min_win_w, N_GUI_STYLE::radio_circle_border_thickness, N_GUI_STYLE::radio_circle_min_r, N_GUI_STYLE::radio_inner_offset, N_GUI_STYLE::radio_label_gap, N_GUI_STYLE::radiolist_default_item_height, N_GUI_STYLE::scroll_step, N_GUI_STYLE::scrollbar_size, N_GUI_STYLE::scrollbar_thumb_color, N_GUI_STYLE::scrollbar_thumb_corner_r, N_GUI_STYLE::scrollbar_thumb_min, N_GUI_STYLE::scrollbar_thumb_padding, N_GUI_STYLE::scrollbar_track_color, N_GUI_THEME::selection_color, N_GUI_STYLE::slider_handle_border_thickness, N_GUI_STYLE::slider_handle_edge_offset, N_GUI_STYLE::slider_handle_min_r, N_GUI_STYLE::slider_track_border_thickness, N_GUI_STYLE::slider_track_corner_r, N_GUI_STYLE::slider_track_size, N_GUI_STYLE::slider_value_label_offset, N_GUI_CTX::style, N_GUI_STYLE::tb_btn_glyph_thickness, N_GUI_STYLE::tb_btn_right_margin, N_GUI_STYLE::tb_btn_size, N_GUI_STYLE::tb_btn_spacing, N_GUI_THEME::text_active, N_GUI_THEME::text_hover, N_GUI_THEME::text_normal, N_GUI_STYLE::textarea_cursor_blink_period, N_GUI_STYLE::textarea_cursor_width, N_GUI_STYLE::textarea_padding, N_GUI_WIDGET::theme, N_GUI_WINDOW::theme, N_GUI_STYLE::title_max_w_reserve, N_GUI_STYLE::title_padding, N_GUI_STYLE::titlebar_h, N_GUI_WINDOW::widgets, and N_GUI_CTX::windows.
Referenced by main().
n_gui_lower_window()
void n_gui_lower_window (N_GUI_CTX * ctx, int window_id)
lower a window to the bottom of the stack (respects z-order constraints)
lower a window to the bottom of the stack (respects z-order constraints)
Only NORMAL windows can be lowered.
Definition at line 1020 of file n_gui.c.
References __n_assert, _destroy_window(), _find_window_node(), _sort_windows_by_zorder(), LIST_NODE::destroy_func, list_unshift(), N_GUI_ZORDER_NORMAL, LIST_NODE::ptr, remove_list_node_f(), N_GUI_CTX::windows, and N_GUI_WINDOW::z_order.
n_gui_make_theme()
N_GUI_THEME n_gui_make_theme (ALLEGRO_COLOR bg, ALLEGRO_COLOR bg_hover, ALLEGRO_COLOR bg_active, ALLEGRO_COLOR border, ALLEGRO_COLOR border_hover, ALLEGRO_COLOR border_active, ALLEGRO_COLOR text, ALLEGRO_COLOR text_hover, ALLEGRO_COLOR text_active, float border_thickness, float corner_rx, float corner_ry)
create a custom theme from individual colors and properties
create a custom theme from individual colors and properties
Parameters
bg background colour
bg_hover background colour on hover
bg_active background colour when active
border border colour
border_hover border colour on hover
border_active border colour when active
text text colour
text_hover text colour on hover
text_active text colour when active
border_thickness border thickness in pixels
corner_rx horizontal corner radius
corner_ry vertical corner radius
Returns
configured N_GUI_THEME
Definition at line 329 of file n_gui.c.
References N_GUI_THEME::bg_active, N_GUI_THEME::bg_hover, N_GUI_THEME::bg_normal, N_GUI_THEME::border_active, N_GUI_THEME::border_hover, N_GUI_THEME::border_normal, N_GUI_THEME::border_thickness, N_GUI_THEME::corner_rx, N_GUI_THEME::corner_ry, N_GUI_THEME::selection_color, N_GUI_THEME::text_active, N_GUI_THEME::text_hover, and N_GUI_THEME::text_normal.
Referenced by main().
n_gui_maximize_window()
void n_gui_maximize_window (N_GUI_CTX * ctx, int window_id)
toggle maximised state (full display or restore to previous size)
toggle maximised state (full display or restore to previous size)
When maximising: saves current position/size, expands to fill the display (or virtual canvas if enabled), and clears minimised state. When restoring: returns to the saved position/size.
Definition at line 787 of file n_gui.c.
References __n_assert, _n_gui_window_capture_normalized(), N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_WINDOW::h, n_gui_get_window(), N_GUI_RESIZE_ADAPTIVE, N_GUI_WIN_MAXIMISED, N_GUI_CTX::resize_mode, N_GUI_TB_BUTTONS::restore_h, N_GUI_TB_BUTTONS::restore_w, N_GUI_TB_BUTTONS::restore_x, N_GUI_TB_BUTTONS::restore_y, N_GUI_WINDOW::state, N_GUI_WINDOW::tb_buttons, N_GUI_CTX::virtual_h, N_GUI_CTX::virtual_w, N_GUI_WINDOW::w, N_GUI_WINDOW::x, and N_GUI_WINDOW::y.
Referenced by _tb_button_action().
n_gui_minimize_window()
void n_gui_minimize_window (N_GUI_CTX * ctx, int window_id)
minimize a window (title bar only)
minimize a window (title bar only)
Definition at line 775 of file n_gui.c.
References n_gui_get_window(), N_GUI_WIN_MINIMISED, and N_GUI_WINDOW::state.
Referenced by _tb_button_action().
n_gui_new_ctx()
N_GUI_CTX * n_gui_new_ctx (ALLEGRO_FONT * default_font)
create a new GUI context
create a new GUI context
Parameters
default_font the default ALLEGRO_FONT to use
Returns
a new N_GUI_CTX or NULL on error
Definition at line 543 of file n_gui.c.
References __n_assert, N_GUI_CTX::default_font, N_GUI_CTX::default_tb_btn_theme, N_GUI_CTX::default_tb_close_theme, N_GUI_CTX::default_theme, N_GUI_CTX::display, N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_CTX::dpi_scale, N_GUI_CTX::focused_widget_id, Free, N_GUI_CTX::global_hscroll_drag, N_GUI_CTX::global_scroll_x, N_GUI_CTX::global_scroll_y, N_GUI_CTX::global_vscroll_drag, N_GUI_CTX::gui_bounds_h, N_GUI_CTX::gui_bounds_w, N_GUI_CTX::gui_offset_x, N_GUI_CTX::gui_offset_y, N_GUI_CTX::gui_scale, list_destroy(), LOG_ERR, Malloc, N_GUI_CTX::mouse_b1, N_GUI_CTX::mouse_b1_prev, N_GUI_CTX::mouse_x, N_GUI_CTX::mouse_y, n_gui_default_style(), n_gui_default_tb_btn_theme(), n_gui_default_tb_close_theme(), n_gui_default_theme(), N_GUI_RESIZE_VIRTUAL, n_log, new_generic_list(), new_ht(), N_GUI_CTX::next_widget_id, N_GUI_CTX::next_window_id, N_GUI_CTX::open_combobox_id, N_GUI_CTX::open_dropmenu_id, N_GUI_CTX::pending_layout, N_GUI_CTX::pending_layout_count, N_GUI_CTX::ref_display_h, N_GUI_CTX::ref_display_w, N_GUI_CTX::resize_mode, N_GUI_CTX::scrollbar_drag_widget_id, N_GUI_CTX::selected_label_id, N_GUI_CTX::style, N_GUI_CTX::tooltip_anchor_x, N_GUI_CTX::tooltip_anchor_y, N_GUI_CTX::tooltip_armed_at, N_GUI_CTX::tooltip_widget_id, UNLIMITED_LIST_ITEMS, N_GUI_CTX::virtual_h, N_GUI_CTX::virtual_w, N_GUI_CTX::widgets_by_id, and N_GUI_CTX::windows.
Referenced by main(), and main().
n_gui_open_window()
void n_gui_open_window (N_GUI_CTX * ctx, int window_id)
open (show) a window
open (show) a window
Definition at line 767 of file n_gui.c.
References n_gui_get_window(), N_GUI_WIN_OPEN, and N_GUI_WINDOW::state.
Referenced by main(), n_gui_tab_set_active(), and on_ghost_toggle().
n_gui_process_event()
int n_gui_process_event (N_GUI_CTX * ctx, ALLEGRO_EVENT event)
process an allegro event for the GUI
process an allegro event for the GUI
Parameters
ctx the GUI context
event the allegro event to process
Returns
1 if the event was consumed by the GUI (mouse over a window/widget, active capture operation, keyboard input to focused widget, etc.), 0 if the event was not handled by the GUI and can be processed by the application (e.g. game logic).
Definition at line 6502 of file n_gui.c.
References __n_assert, _clamp(), _compute_gui_bounds(), _dropdown_panel_y(), _find_focused_window(), _find_widget_window(), _is_focusable_type(), _justified_char_at_pos(), _label_char_at_x(), _label_content_height(), _label_text_origin_x(), _n_gui_window_capture_normalized(), _point_in_rect(), _scrollbar_calc_scroll(), _scrollbar_calc_scroll_int(), _scrollbar_update_from_mouse(), _slider_snap_value(), _slider_update_from_mouse(), _tb_button_action(), _tb_button_rect(), _text_w(), _textarea_content_height(), _textarea_handle_key(), _textarea_pos_from_mouse(), _tooltip_widget_at(), _win_tbh(), _window_update_content_size(), N_GUI_LABEL_DATA::align, N_GUI_CHECKBOX_DATA::checked, N_GUI_STYLE::combobox_max_dropdown_width, N_GUI_WINDOW::content_h, N_GUI_SCROLLBAR_DATA::content_size, N_GUI_WINDOW::content_w, N_GUI_TEXTAREA_DATA::cursor_pos, N_GUI_TEXTAREA_DATA::cursor_time, N_GUI_WIDGET::data, N_GUI_CTX::default_font, N_GUI_CTX::display, N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_WINDOW::drag_ox, N_GUI_WINDOW::drag_oy, N_GUI_WIDGET::enabled, LIST::end, N_GUI_DROPMENU_DATA::entries, N_GUI_COMBOBOX_DATA::flags, N_GUI_DROPMENU_DATA::flags, N_GUI_WINDOW::flags, N_GUI_CTX::focused_widget_id, N_GUI_WIDGET::font, N_GUI_CTX::global_hscroll_drag, N_GUI_STYLE::global_scroll_step, N_GUI_CTX::global_scroll_x, N_GUI_CTX::global_scroll_y, N_GUI_STYLE::global_scrollbar_size, N_GUI_STYLE::global_scrollbar_thumb_min, N_GUI_CTX::global_vscroll_drag, N_GUI_STYLE::grip_size, N_GUI_CTX::gui_bounds_h, N_GUI_CTX::gui_bounds_w, N_GUI_CTX::gui_offset_x, N_GUI_CTX::gui_offset_y, N_GUI_CTX::gui_scale, N_GUI_WIDGET::h, N_GUI_WINDOW::h, N_GUI_LISTBOX_DATA::hover_row, N_GUI_TB_BUTTONS::hovered, N_GUI_WIDGET::id, N_GUI_WINDOW::id, N_GUI_COMBOBOX_DATA::is_open, N_GUI_DROPMENU_DATA::is_open, N_GUI_LISTBOX_DATA::item_height, N_GUI_RADIOLIST_DATA::item_height, N_GUI_COMBOBOX_DATA::item_height, N_GUI_DROPMENU_DATA::item_height, N_GUI_STYLE::item_height_pad, N_GUI_STYLE::item_text_padding, N_GUI_LISTBOX_DATA::items, N_GUI_COMBOBOX_DATA::items, N_GUI_BUTTON_DATA::key_focus_only, N_GUI_BUTTON_DATA::key_modifiers, N_GUI_BUTTON_DATA::key_press_until, N_GUI_BUTTON_DATA::key_sources, N_GUI_BUTTON_DATA::keycode, N_GUI_STYLE::label_padding, N_GUI_LABEL_DATA::link, list_foreach, N_GUI_SLIDER_DATA::max_val, N_GUI_COMBOBOX_DATA::max_visible, N_GUI_DROPMENU_DATA::max_visible, N_GUI_WINDOW::min_h, N_GUI_SLIDER_DATA::min_val, N_GUI_WINDOW::min_w, N_GUI_CTX::mouse_b1, N_GUI_CTX::mouse_b1_prev, N_GUI_CTX::mouse_x, N_GUI_CTX::mouse_y, N_GUI_TEXTAREA_DATA::multiline, N_GUI_ALIGN_JUSTIFIED, N_GUI_COMBOBOX_AUTO_WIDTH, N_GUI_COMBOBOX_EXPAND_UP, N_GUI_DROPMENU_EXPAND_UP, n_gui_get_widget(), n_gui_get_window(), N_GUI_KEY_MOD_MASK, N_GUI_KEY_PRESS_FLASH_SEC, N_GUI_KEY_SOURCES_MAX, n_gui_raise_window(), N_GUI_RESIZE_ADAPTIVE, N_GUI_SCROLLBAR_V, N_GUI_SELECT_MULTIPLE, N_GUI_SELECT_NONE, N_GUI_SELECT_SINGLE, n_gui_set_focus(), N_GUI_SLIDER_H, N_GUI_STATE_ACTIVE, N_GUI_STATE_FOCUSED, N_GUI_STATE_HOVER, N_GUI_TB_BTN_CLOSE, N_GUI_TB_BTN_MAXIMIZE, N_GUI_TB_BTN_MINIMIZE, N_GUI_TB_BTN_NONE, N_GUI_TEXT_MAX, N_GUI_TYPE_BUTTON, N_GUI_TYPE_CHECKBOX, N_GUI_TYPE_COMBOBOX, N_GUI_TYPE_DROPMENU, N_GUI_TYPE_LABEL, N_GUI_TYPE_LISTBOX, N_GUI_TYPE_RADIOLIST, N_GUI_TYPE_SCROLLBAR, N_GUI_TYPE_SLIDER, N_GUI_TYPE_TEXTAREA, N_GUI_WIN_AUTO_SCROLLBAR, N_GUI_WIN_DRAGGING, N_GUI_WIN_FIXED_POSITION, N_GUI_WIN_FRAMELESS, N_GUI_WIN_HSCROLL_DRAG, N_GUI_WIN_MAXIMISED, N_GUI_WIN_MINIMISED, N_GUI_WIN_OPEN, N_GUI_WIN_RESIZABLE, N_GUI_WIN_RESIZING, N_GUI_WIN_VSCROLL_DRAG, N_GUI_DROPMENU_DATA::nb_entries, N_GUI_LISTBOX_DATA::nb_items, N_GUI_RADIOLIST_DATA::nb_items, N_GUI_COMBOBOX_DATA::nb_items, LIST::nb_items, N_GUI_SLIDER_DATA::on_change, N_GUI_DROPMENU_ENTRY::on_click, N_GUI_BUTTON_DATA::on_click, N_GUI_LABEL_DATA::on_link_click, N_GUI_DROPMENU_DATA::on_open, N_GUI_DROPMENU_DATA::on_open_user_data, N_GUI_SCROLLBAR_DATA::on_scroll, N_GUI_LISTBOX_DATA::on_select, N_GUI_RADIOLIST_DATA::on_select, N_GUI_COMBOBOX_DATA::on_select, N_GUI_CHECKBOX_DATA::on_toggle, N_GUI_CTX::open_combobox_id, N_GUI_CTX::open_dropmenu_id, N_GUI_SLIDER_DATA::orientation, N_GUI_SCROLLBAR_DATA::orientation, N_GUI_TB_BUTTONS::pressed, LIST_NODE::ptr, N_GUI_CTX::resize_mode, N_GUI_TEXTAREA_DATA::scroll_from_wheel, N_GUI_LISTBOX_DATA::scroll_offset, N_GUI_RADIOLIST_DATA::scroll_offset, N_GUI_COMBOBOX_DATA::scroll_offset, N_GUI_DROPMENU_DATA::scroll_offset, N_GUI_SCROLLBAR_DATA::scroll_pos, N_GUI_STYLE::scroll_step, N_GUI_WINDOW::scroll_x, N_GUI_TEXTAREA_DATA::scroll_y, N_GUI_LABEL_DATA::scroll_y, N_GUI_WINDOW::scroll_y, N_GUI_CTX::scrollbar_drag_widget_id, N_GUI_STYLE::scrollbar_size, N_GUI_STYLE::scrollbar_thumb_min, N_GUI_LABEL_DATA::sel_dragging, N_GUI_TEXTAREA_DATA::sel_end, N_GUI_LABEL_DATA::sel_end, N_GUI_TEXTAREA_DATA::sel_start, N_GUI_LABEL_DATA::sel_start, N_GUI_LISTITEM::selected, N_GUI_RADIOLIST_DATA::selected_index, N_GUI_COMBOBOX_DATA::selected_index, N_GUI_CTX::selected_label_id, N_GUI_LISTBOX_DATA::selection_mode, N_GUI_WIDGET::state, N_GUI_WINDOW::state, N_GUI_SLIDER_DATA::step, N_GUI_CTX::style, N_GUI_DROPMENU_ENTRY::tag, N_GUI_WINDOW::tb_buttons, N_GUI_LISTITEM::text, N_GUI_LABEL_DATA::text, N_GUI_STYLE::textarea_padding, N_GUI_STYLE::title_max_w_reserve, N_GUI_BUTTON_DATA::toggle_mode, N_GUI_BUTTON_DATA::toggled, N_GUI_CTX::tooltip_anchor_x, N_GUI_CTX::tooltip_anchor_y, N_GUI_CTX::tooltip_armed_at, N_GUI_STYLE::tooltip_delay, N_GUI_CTX::tooltip_widget_id, N_GUI_WIDGET::type, N_GUI_BUTTON_DATA::user_data, N_GUI_SLIDER_DATA::user_data, N_GUI_CHECKBOX_DATA::user_data, N_GUI_SCROLLBAR_DATA::user_data, N_GUI_LISTBOX_DATA::user_data, N_GUI_RADIOLIST_DATA::user_data, N_GUI_COMBOBOX_DATA::user_data, N_GUI_LABEL_DATA::user_data, N_GUI_DROPMENU_ENTRY::user_data, N_GUI_SLIDER_DATA::value, N_GUI_SCROLLBAR_DATA::viewport_size, N_GUI_CTX::virtual_h, N_GUI_CTX::virtual_w, N_GUI_WIDGET::visible, N_GUI_WIDGET::w, N_GUI_WINDOW::w, N_GUI_WINDOW::widgets, N_GUI_CTX::windows, N_GUI_WIDGET::x, N_GUI_WINDOW::x, N_GUI_WIDGET::y, and N_GUI_WINDOW::y.
Referenced by main(), and main().
n_gui_radiolist_add_item()
int n_gui_radiolist_add_item (N_GUI_CTX * ctx, int widget_id, const char * text)
add an item to a radio list
add an item to a radio list
Parameters
ctx GUI context
widget_id id of the radiolist widget
text text of the item to add
Returns
index of the new item or -1 on error
Definition at line 2467 of file n_gui.c.
References _items_grow(), N_GUI_WIDGET::data, N_GUI_RADIOLIST_DATA::items, N_GUI_RADIOLIST_DATA::items_capacity, n_gui_get_widget(), N_GUI_ID_MAX, N_GUI_TYPE_RADIOLIST, N_GUI_RADIOLIST_DATA::nb_items, N_GUI_LISTITEM::selected, N_GUI_LISTITEM::text, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_radiolist_clear()
void n_gui_radiolist_clear (N_GUI_CTX * ctx, int widget_id)
remove all items from a radio list
remove all items from a radio list
Parameters
ctx GUI context
widget_id id of the radiolist widget
Definition at line 2488 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_RADIOLIST, N_GUI_RADIOLIST_DATA::nb_items, N_GUI_RADIOLIST_DATA::scroll_offset, N_GUI_RADIOLIST_DATA::selected_index, and N_GUI_WIDGET::type.
n_gui_radiolist_get_selected()
int n_gui_radiolist_get_selected (N_GUI_CTX * ctx, int widget_id)
get the selected item index
get the selected item index
Parameters
ctx GUI context
widget_id id of the radiolist widget
Returns
index of the selected item, or -1 if none
Definition at line 2504 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_RADIOLIST, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_radiolist_set_bitmaps()
void n_gui_radiolist_set_bitmaps (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * bg, ALLEGRO_BITMAP * item_bg, ALLEGRO_BITMAP * item_selected)
set optional bitmap overlays on a radiolist widget.
Pass NULL for any bitmap you don't want to set.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional bitmap overlays on a radiolist widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 2965 of file n_gui.c.
References N_GUI_RADIOLIST_DATA::bg_bitmap, N_GUI_WIDGET::data, N_GUI_RADIOLIST_DATA::item_bg_bitmap, N_GUI_RADIOLIST_DATA::item_selected_bitmap, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_RADIOLIST, n_log, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_radiolist_set_selected()
void n_gui_radiolist_set_selected (N_GUI_CTX * ctx, int widget_id, int index)
set the selected item index
set the selected item index
Parameters
ctx GUI context
widget_id id of the radiolist widget
index index of the item to select, or -1 for none
Definition at line 2518 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_RADIOLIST, N_GUI_RADIOLIST_DATA::selected_index, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_raise_window()
void n_gui_raise_window (N_GUI_CTX * ctx, int window_id)
raise a window to the top of the stack (respects z-order constraints)
raise a window to the top of the stack (respects z-order constraints)
Respects z-order constraints: ALWAYS_BEHIND, FIXED and ALWAYS_ON_TOP windows are not moved. NORMAL and POPUP windows are raised WITHIN their own z-group (the stable re-sort keeps group boundaries). After raising, the window list is re-sorted.
Definition at line 1002 of file n_gui.c.
References __n_assert, _destroy_window(), _find_window_node(), _sort_windows_by_zorder(), LIST_NODE::destroy_func, list_push(), N_GUI_ZORDER_NORMAL, N_GUI_ZORDER_POPUP, LIST_NODE::ptr, remove_list_node_f(), N_GUI_CTX::windows, and N_GUI_WINDOW::z_order.
Referenced by n_gui_focus_window(), n_gui_process_event(), and n_gui_set_focus().
n_gui_reset_all_widget_themes()
void n_gui_reset_all_widget_themes (N_GUI_CTX * ctx)
reset all widget and window themes to ctx->default_theme
reset all widget and window themes to ctx->default_theme
Iterates every window and every widget, setting their theme to the context default. Call this after changing ctx->default_theme so that all existing widgets pick up the new palette. Widgets that need a custom theme (accent buttons, status labels, etc.) must be re-themed individually after this call.
Definition at line 1984 of file n_gui.c.
References N_GUI_TB_BUTTONS::btn_theme, N_GUI_TB_BUTTONS::close_theme, N_GUI_CTX::default_tb_btn_theme, N_GUI_CTX::default_tb_close_theme, N_GUI_CTX::default_theme, list_foreach, N_GUI_WINDOW::tb_buttons, N_GUI_WIDGET::theme, N_GUI_WINDOW::theme, N_GUI_WINDOW::widgets, and N_GUI_CTX::windows.
n_gui_save_layout_json()
int n_gui_save_layout_json (N_GUI_CTX * ctx, const char * filepath)
Save the geometry + persistent state of every window in the context to a JSON file.
Persists per-window: title, x, y, w, h, state (persistent bits only), z_order, z_value, flags, norm_x/y/w/h, autofit_flags, autofit_border, resize_policy. Widget content and callbacks are NOT saved, they are domain data owned by the calling program. Returns 0 on success, -1 on error.
Save the geometry + persistent state of every window in the context to a JSON file.
Parameters
ctx GUI context
filepath path to the output JSON file
Returns
0 on success, -1 on error
Definition at line 8530 of file n_gui.c.
References __n_assert, _N_GUI_WIN_STATE_PERSIST_MASK, N_GUI_WINDOW::autofit_border, N_GUI_WINDOW::autofit_flags, N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_WINDOW::flags, N_GUI_WINDOW::h, list_foreach, N_GUI_WINDOW::norm_h, N_GUI_WINDOW::norm_w, N_GUI_WINDOW::norm_x, N_GUI_WINDOW::norm_y, N_GUI_WINDOW::resize_policy, N_GUI_WINDOW::state, N_GUI_WINDOW::title, N_GUI_WINDOW::w, N_GUI_CTX::windows, N_GUI_WINDOW::x, N_GUI_WINDOW::y, N_GUI_WINDOW::z_order, and N_GUI_WINDOW::z_value.
Referenced by on_save_layout_click().
n_gui_save_theme_json()
int n_gui_save_theme_json (N_GUI_CTX * ctx, const char * filepath)
Save the full theme (default_theme + style) to a JSON file.
Returns 0 on success, -1 on error.
Save the full theme (default_theme + style) to a JSON file.
Parameters
ctx GUI context
filepath path to the output JSON file
Returns
0 on success, -1 on error
Definition at line 8249 of file n_gui.c.
References __n_assert, _json_add_color(), N_GUI_THEME::bg_active, N_GUI_THEME::bg_hover, N_GUI_THEME::bg_normal, N_GUI_THEME::border_active, N_GUI_THEME::border_hover, N_GUI_THEME::border_normal, N_GUI_THEME::border_thickness, N_GUI_STYLE::checkbox_label_gap, N_GUI_STYLE::checkbox_label_offset, N_GUI_STYLE::checkbox_mark_margin, N_GUI_STYLE::checkbox_mark_thickness, N_GUI_STYLE::checkbox_max_size, N_GUI_STYLE::combobox_max_dropdown_width, N_GUI_STYLE::combobox_max_visible, N_GUI_THEME::corner_rx, N_GUI_THEME::corner_ry, N_GUI_CTX::default_theme, N_GUI_STYLE::dropdown_arrow_half_h, N_GUI_STYLE::dropdown_arrow_half_w, N_GUI_STYLE::dropdown_arrow_reserve, N_GUI_STYLE::dropdown_arrow_thickness, N_GUI_STYLE::dropdown_border_thickness, N_GUI_STYLE::dropmenu_max_visible, N_GUI_STYLE::global_scroll_step, N_GUI_STYLE::global_scrollbar_border_thickness, N_GUI_STYLE::global_scrollbar_size, N_GUI_STYLE::global_scrollbar_thumb_border_color, N_GUI_STYLE::global_scrollbar_thumb_color, N_GUI_STYLE::global_scrollbar_thumb_corner_r, N_GUI_STYLE::global_scrollbar_thumb_min, N_GUI_STYLE::global_scrollbar_thumb_padding, N_GUI_STYLE::global_scrollbar_track_color, N_GUI_STYLE::grip_color, N_GUI_STYLE::grip_line_thickness, N_GUI_STYLE::grip_size, N_GUI_STYLE::item_height_pad, N_GUI_STYLE::item_selection_inset, N_GUI_STYLE::item_text_padding, N_GUI_STYLE::label_padding, N_GUI_STYLE::link_color_hover, N_GUI_STYLE::link_color_normal, N_GUI_STYLE::link_underline_thickness, N_GUI_STYLE::listbox_default_item_height, N_GUI_STYLE::min_win_h, N_GUI_STYLE::min_win_w, N_GUI_STYLE::radio_circle_border_thickness, N_GUI_STYLE::radio_circle_min_r, N_GUI_STYLE::radio_inner_offset, N_GUI_STYLE::radio_label_gap, N_GUI_STYLE::radiolist_default_item_height, N_GUI_STYLE::scroll_step, N_GUI_STYLE::scrollbar_size, N_GUI_STYLE::scrollbar_thumb_color, N_GUI_STYLE::scrollbar_thumb_corner_r, N_GUI_STYLE::scrollbar_thumb_min, N_GUI_STYLE::scrollbar_thumb_padding, N_GUI_STYLE::scrollbar_track_color, N_GUI_THEME::selection_color, N_GUI_STYLE::slider_handle_border_thickness, N_GUI_STYLE::slider_handle_edge_offset, N_GUI_STYLE::slider_handle_min_r, N_GUI_STYLE::slider_track_border_thickness, N_GUI_STYLE::slider_track_corner_r, N_GUI_STYLE::slider_track_size, N_GUI_STYLE::slider_value_label_offset, N_GUI_CTX::style, N_GUI_STYLE::tb_btn_glyph_thickness, N_GUI_STYLE::tb_btn_right_margin, N_GUI_STYLE::tb_btn_size, N_GUI_STYLE::tb_btn_spacing, N_GUI_THEME::text_active, N_GUI_THEME::text_hover, N_GUI_THEME::text_normal, N_GUI_STYLE::textarea_cursor_blink_period, N_GUI_STYLE::textarea_cursor_width, N_GUI_STYLE::textarea_padding, N_GUI_STYLE::title_max_w_reserve, N_GUI_STYLE::title_padding, and N_GUI_STYLE::titlebar_h.
n_gui_screen_to_virtual()
void n_gui_screen_to_virtual (const N_GUI_CTX * ctx, float sx, float sy, float * vx, float * vy)
convert physical screen coordinates to virtual canvas coordinates.
If virtual canvas is disabled, outputs equal inputs.
Parameters
ctx GUI context
sx screen X (physical pixels)
sy screen Y (physical pixels)
vx output virtual X (may be NULL)
vy output virtual Y (may be NULL)
convert physical screen coordinates to virtual canvas coordinates.
If virtual canvas is disabled (virtual_w/virtual_h == 0), outputs equal inputs.
Definition at line 5732 of file n_gui.c.
References __n_assert, N_GUI_CTX::gui_offset_x, N_GUI_CTX::gui_offset_y, N_GUI_CTX::gui_scale, N_GUI_CTX::virtual_h, and N_GUI_CTX::virtual_w.
Referenced by main().
n_gui_scrollbar_get_pos()
double n_gui_scrollbar_get_pos (N_GUI_CTX * ctx, int widget_id)
get scrollbar position
get scrollbar position
Parameters
ctx GUI context
widget_id id of the scrollbar widget
Returns
current scroll position
Definition at line 2247 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_SCROLLBAR, and N_GUI_WIDGET::type.
n_gui_scrollbar_set_bitmaps()
void n_gui_scrollbar_set_bitmaps (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * track, ALLEGRO_BITMAP * thumb, ALLEGRO_BITMAP * thumb_hover, ALLEGRO_BITMAP * thumb_active)
set optional bitmap overlays on a scrollbar widget.
Pass NULL for any bitmap you don't want to set.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional bitmap overlays on a scrollbar widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 2889 of file n_gui.c.
References N_GUI_WIDGET::data, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_SCROLLBAR, n_log, N_GUI_SCROLLBAR_DATA::thumb_active_bitmap, N_GUI_SCROLLBAR_DATA::thumb_bitmap, N_GUI_SCROLLBAR_DATA::thumb_hover_bitmap, N_GUI_SCROLLBAR_DATA::track_bitmap, and N_GUI_WIDGET::type.
n_gui_scrollbar_set_pos()
void n_gui_scrollbar_set_pos (N_GUI_CTX * ctx, int widget_id, double pos)
set scrollbar position
set scrollbar position
Parameters
ctx GUI context
widget_id id of the scrollbar widget
pos new scroll position
Definition at line 2261 of file n_gui.c.
References _clamp(), N_GUI_SCROLLBAR_DATA::content_size, N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_SCROLLBAR, N_GUI_SCROLLBAR_DATA::scroll_pos, N_GUI_WIDGET::type, and N_GUI_SCROLLBAR_DATA::viewport_size.
n_gui_scrollbar_set_sizes()
void n_gui_scrollbar_set_sizes (N_GUI_CTX * ctx, int widget_id, double content_size, double viewport_size)
set scrollbar content and viewport sizes
set scrollbar content and viewport sizes
Parameters
ctx GUI context
widget_id id of the scrollbar widget
content_size total size of the content
viewport_size visible viewport size
Definition at line 2278 of file n_gui.c.
References _clamp(), N_GUI_SCROLLBAR_DATA::content_size, N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_SCROLLBAR, N_GUI_SCROLLBAR_DATA::scroll_pos, N_GUI_WIDGET::type, and N_GUI_SCROLLBAR_DATA::viewport_size.
n_gui_sectionlist_add_section()
int n_gui_sectionlist_add_section (N_GUI_SECTIONLIST * sl, const char * title, float header_y, int folded)
add a section with a header button at header_y (members added next are captured relative to it); returns the section index or -1
Definition at line 9742 of file n_gui.c.
References _n_gui_sectionlist_header_clicked(), N_GUI_SECTIONLIST::ctx, N_GUI_SECTION::folded, N_GUI_SECTIONLIST::header_h, N_GUI_SECTION::header_id, n_gui_add_button(), N_GUI_SECTIONLIST_MAX, N_GUI_SHAPE_ROUNDED, N_GUI_SECTION::natural_h, N_GUI_SECTIONLIST::nb_sections, N_GUI_SECTION::nb_widgets, N_GUI_SECTIONLIST::sections, N_GUI_SECTION::title, N_GUI_SECTIONLIST::width, N_GUI_SECTIONLIST::window_id, and N_GUI_SECTIONLIST::x.
n_gui_sectionlist_add_widget()
void n_gui_sectionlist_add_widget (N_GUI_SECTIONLIST * sl, int section_index, int widget_id)
register an existing widget as a member of a section (captures its current y as the fold offset)
Definition at line 9759 of file n_gui.c.
References N_GUI_SECTIONLIST::ctx, N_GUI_SECTIONLIST::gap, N_GUI_WIDGET::h, N_GUI_SECTIONLIST::header_h, N_GUI_SECTION::header_id, n_gui_get_widget(), N_GUI_SECTION_WIDGETS_MAX, N_GUI_SECTION::natural_h, N_GUI_SECTIONLIST::nb_sections, N_GUI_SECTION::nb_widgets, N_GUI_SECTIONLIST::sections, N_GUI_SECTION::widget_dy, N_GUI_SECTION::widget_ids, and N_GUI_WIDGET::y.
n_gui_sectionlist_content_height()
float n_gui_sectionlist_content_height (const N_GUI_SECTIONLIST * sl)
total content height in pixels under the current fold state, for sizing/scrolling the host window
Definition at line 9826 of file n_gui.c.
References N_GUI_SECTION::folded, N_GUI_SECTIONLIST::gap, N_GUI_SECTIONLIST::header_h, N_GUI_SECTION::natural_h, N_GUI_SECTIONLIST::nb_sections, N_GUI_SECTIONLIST::sections, and N_GUI_SECTIONLIST::y0.
n_gui_sectionlist_create()
N_GUI_SECTIONLIST * n_gui_sectionlist_create (N_GUI_CTX * ctx, int window_id, float x, float y0, float width, float header_h, float gap, void(*)(int, int, void *) on_toggle, void * user_data)
create an empty section list anchored at (x,y0) in window_id; sections stack downward from y0
Definition at line 9723 of file n_gui.c.
References N_GUI_SECTIONLIST::ctx, N_GUI_SECTIONLIST::gap, N_GUI_SECTIONLIST::header_h, Malloc, N_GUI_SECTIONLIST::nb_sections, N_GUI_SECTIONLIST::on_toggle, N_GUI_SECTIONLIST::user_data, N_GUI_SECTIONLIST::width, N_GUI_SECTIONLIST::window_id, N_GUI_SECTIONLIST::x, and N_GUI_SECTIONLIST::y0.
n_gui_sectionlist_free()
void n_gui_sectionlist_free (N_GUI_SECTIONLIST ** sl)
free the section list (does not destroy the N_GUI widgets or window)
Definition at line 9840 of file n_gui.c.
References FreeNoLog.
n_gui_sectionlist_get_count()
int n_gui_sectionlist_get_count (const N_GUI_SECTIONLIST * sl)
number of sections in the list
Definition at line 9836 of file n_gui.c.
References N_GUI_SECTIONLIST::nb_sections.
n_gui_sectionlist_is_folded()
int n_gui_sectionlist_is_folded (const N_GUI_SECTIONLIST * sl, int section_index)
query a section's folded state (1 = folded, 0 = expanded)
Definition at line 9821 of file n_gui.c.
References N_GUI_SECTION::folded, N_GUI_SECTIONLIST::nb_sections, and N_GUI_SECTIONLIST::sections.
n_gui_sectionlist_relayout()
void n_gui_sectionlist_relayout (N_GUI_SECTIONLIST * sl)
re-stack all sections from y0 by current fold state: hide folded members, show and reposition expanded ones
Definition at line 9782 of file n_gui.c.
References _n_gui_sectionlist_set_header_label(), _n_gui_widget_capture_normalized(), N_GUI_SECTIONLIST::ctx, N_GUI_SECTIONLIST::first_inset, N_GUI_SECTION::folded, N_GUI_SECTIONLIST::gap, N_GUI_SECTIONLIST::header_h, N_GUI_SECTION::header_id, n_gui_get_widget(), n_gui_get_window(), n_gui_set_widget_visible(), N_GUI_SECTION::natural_h, N_GUI_SECTIONLIST::nb_sections, N_GUI_SECTION::nb_widgets, N_GUI_SECTIONLIST::sections, N_GUI_WIDGET::w, N_GUI_SECTION::widget_dy, N_GUI_SECTION::widget_ids, N_GUI_SECTIONLIST::width, N_GUI_SECTIONLIST::window_id, N_GUI_WIDGET::x, N_GUI_SECTIONLIST::x, N_GUI_WIDGET::y, and N_GUI_SECTIONLIST::y0.
Referenced by _n_gui_sectionlist_header_clicked(), and n_gui_sectionlist_set_folded().
n_gui_sectionlist_set_first_inset()
void n_gui_sectionlist_set_first_inset (N_GUI_SECTIONLIST * sl, float inset)
set a left inset applied to the FIRST section's header only, so a caller can place a button before it on the same row; relayout re-applies it
Definition at line 9777 of file n_gui.c.
References N_GUI_SECTIONLIST::first_inset.
n_gui_sectionlist_set_folded()
void n_gui_sectionlist_set_folded (N_GUI_SECTIONLIST * sl, int section_index, int folded)
set a section's folded state and relayout; does NOT fire on_toggle (for programmatic restore)
Definition at line 9815 of file n_gui.c.
References N_GUI_SECTION::folded, n_gui_sectionlist_relayout(), N_GUI_SECTIONLIST::nb_sections, and N_GUI_SECTIONLIST::sections.
n_gui_set_default_theme()
void n_gui_set_default_theme (N_GUI_CTX * ctx, N_GUI_THEME theme)
Set the default theme on a context and sync scrollbar style colors.
Sets ctx->default_theme and derives scrollbar track/thumb colors from the theme's bg_normal and border_normal fields so scrollbars match the active theme automatically.
Parameters
ctx N_GUI context. Must not be NULL.
theme Theme to apply as the new default.
Definition at line 402 of file n_gui.c.
References _color_with_alpha(), N_GUI_THEME::bg_active, N_GUI_THEME::bg_normal, N_GUI_THEME::border_normal, N_GUI_CTX::default_tb_btn_theme, N_GUI_CTX::default_tb_close_theme, N_GUI_CTX::default_theme, N_GUI_STYLE::global_scrollbar_thumb_border_color, N_GUI_STYLE::global_scrollbar_thumb_color, N_GUI_STYLE::global_scrollbar_track_color, N_GUI_STYLE::scrollbar_thumb_color, N_GUI_STYLE::scrollbar_track_color, N_GUI_CTX::style, N_GUI_THEME::text_active, N_GUI_THEME::text_hover, and N_GUI_THEME::text_normal.
n_gui_set_display()
void n_gui_set_display (N_GUI_CTX * ctx, ALLEGRO_DISPLAY * display)
set the display pointer for clipboard operations (copy/paste)
set the display pointer for clipboard operations (copy/paste)
Definition at line 5903 of file n_gui.c.
References __n_assert, display, and N_GUI_CTX::display.
Referenced by main().
n_gui_set_display_size()
void n_gui_set_display_size (N_GUI_CTX * ctx, float w, float h)
set the display (viewport) size so global scrollbars can be computed.
Call this on startup and whenever the display is resized. When virtual canvas is enabled, also updates the virtual-to-display transform.
set the display (viewport) size so global scrollbars can be computed.
Call on startup and whenever ALLEGRO_EVENT_DISPLAY_RESIZE is received. When virtual canvas is enabled, also recalculates the virtual-to-display transform.
Definition at line 5887 of file n_gui.c.
References __n_assert, N_GUI_CTX::display_h, N_GUI_CTX::display_w, n_gui_apply_adaptive_resize(), N_GUI_RESIZE_ADAPTIVE, n_gui_update_transform(), N_GUI_CTX::resize_mode, N_GUI_CTX::virtual_h, and N_GUI_CTX::virtual_w.
Referenced by main(), and main().
n_gui_set_dpi_scale()
void n_gui_set_dpi_scale (N_GUI_CTX * ctx, float scale)
set DPI scale factor manually (default is 1.0).
Affects global scrollbar rendering and can be queried by the application.
set DPI scale factor manually (default is 1.0).
Definition at line 5911 of file n_gui.c.
References __n_assert, and N_GUI_CTX::dpi_scale.
n_gui_set_focus()
void n_gui_set_focus (N_GUI_CTX * ctx, int widget_id)
set keyboard focus to a specific widget (-1 to clear focus)
Parameters
ctx the GUI context
widget_id the widget to focus (-1 to clear focus)
set keyboard focus to a specific widget (-1 to clear focus)
Pass widget_id = -1 to clear focus. If the widget is a textarea, resets cursor blink timer. Raises the parent window if it exists and is open.
Definition at line 2033 of file n_gui.c.
References __n_assert, N_GUI_TEXTAREA_DATA::cursor_time, N_GUI_WIDGET::data, N_GUI_CTX::focused_widget_id, N_GUI_WIDGET::id, N_GUI_WINDOW::id, list_foreach, LOG_ERR, n_gui_get_widget(), n_gui_raise_window(), N_GUI_STATE_FOCUSED, N_GUI_TYPE_TEXTAREA, N_GUI_WIN_OPEN, n_log, N_GUI_WIDGET::state, N_GUI_WINDOW::state, N_GUI_WIDGET::type, N_GUI_WINDOW::widgets, and N_GUI_CTX::windows.
Referenced by main(), n_gui_focus_window(), and n_gui_process_event().
n_gui_set_resize_mode()
void n_gui_set_resize_mode (N_GUI_CTX * ctx, int mode)
set context-level resize mode: N_GUI_RESIZE_VIRTUAL (default) or N_GUI_RESIZE_ADAPTIVE
set context-level resize mode: N_GUI_RESIZE_VIRTUAL (default) or N_GUI_RESIZE_ADAPTIVE
When switching to ADAPTIVE, the virtual canvas is disabled and normalized coordinates are captured for all existing windows.
Definition at line 5753 of file n_gui.c.
References __n_assert, _n_gui_window_capture_normalized(), N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_CTX::gui_offset_x, N_GUI_CTX::gui_offset_y, N_GUI_CTX::gui_scale, list_foreach, mode, N_GUI_RESIZE_ADAPTIVE, N_GUI_CTX::ref_display_h, N_GUI_CTX::ref_display_w, N_GUI_CTX::resize_mode, N_GUI_CTX::virtual_h, N_GUI_CTX::virtual_w, and N_GUI_CTX::windows.
Referenced by main(), and main().
n_gui_set_virtual_size()
void n_gui_set_virtual_size (N_GUI_CTX * ctx, float w, float h)
set the virtual canvas size for resolution-independent scaling.
When set (w > 0 && h > 0), all widget coordinates are in virtual space. An ALLEGRO_TRANSFORM is applied during draw and mouse input is reverse- transformed automatically. Pass (0, 0) to disable (identity transform). This is opt-in: the virtual canvas is enabled only when both w and h are > 0, and disabled when both are 0 (legacy behaviour).
set the virtual canvas size for resolution-independent scaling.
When enabled (w > 0 && h > 0), all widget coordinates are treated as virtual pixels. An ALLEGRO_TRANSFORM is applied in n_gui_draw() and mouse input is reverse-transformed in n_gui_process_event(). Pass (0, 0) to disable (identity transform, legacy behaviour).
Definition at line 5687 of file n_gui.c.
References __n_assert, LOG_ERR, n_gui_update_transform(), n_log, N_GUI_CTX::virtual_h, and N_GUI_CTX::virtual_w.
Referenced by main().
n_gui_set_widget_enabled()
void n_gui_set_widget_enabled (N_GUI_CTX * ctx, int widget_id, int enabled)
set widget enabled state (0 = disabled: drawn dimmed and ignores all input)
set widget enabled state (0 = disabled: drawn dimmed and ignores all input)
Disabled widgets are drawn dimmed and ignore all mouse/keyboard input.
Definition at line 2012 of file n_gui.c.
References N_GUI_WIDGET::enabled, and n_gui_get_widget().
Referenced by main().
n_gui_set_widget_theme()
void n_gui_set_widget_theme (N_GUI_CTX * ctx, int widget_id, N_GUI_THEME theme)
set the theme on a widget
set the theme on a widget
Definition at line 1970 of file n_gui.c.
References n_gui_get_widget(), and N_GUI_WIDGET::theme.
Referenced by main().
n_gui_set_widget_tooltip()
void n_gui_set_widget_tooltip (N_GUI_CTX * ctx, int widget_id, const char * text)
set (or clear with "" / NULL) the tooltip text shown after the pointer rests on a widget
set (or clear with "" / NULL) the tooltip text shown after the pointer rests on a widget
The tooltip appears after the pointer rests on the widget for style.tooltip_delay seconds and hides on movement, click, or leave.
Parameters
ctx the GUI context
widget_id id of the target widget
text tooltip text; NULL or "" clears it
Definition at line 1419 of file n_gui.c.
References n_gui_get_widget(), and N_GUI_WIDGET::tooltip.
n_gui_set_widget_visible()
void n_gui_set_widget_visible (N_GUI_CTX * ctx, int widget_id, int visible)
set widget visibility
set widget visibility
Definition at line 2003 of file n_gui.c.
References n_gui_get_widget(), and N_GUI_WIDGET::visible.
Referenced by main(), n_gui_kvtable_remove_row(), and n_gui_sectionlist_relayout().
n_gui_slider_get_value()
double n_gui_slider_get_value (N_GUI_CTX * ctx, int widget_id)
get slider current value
get slider current value
Parameters
ctx GUI context
widget_id id of the slider widget
Returns
current slider value
Definition at line 2087 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_SLIDER, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_slider_set_bitmaps()
void n_gui_slider_set_bitmaps (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * track, ALLEGRO_BITMAP * fill, ALLEGRO_BITMAP * handle, ALLEGRO_BITMAP * handle_hover, ALLEGRO_BITMAP * handle_active)
set optional bitmap overlays on a slider widget.
Pass NULL for any bitmap you don't want to set.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional bitmap overlays on a slider widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 2871 of file n_gui.c.
References N_GUI_WIDGET::data, N_GUI_SLIDER_DATA::fill_bitmap, N_GUI_SLIDER_DATA::handle_active_bitmap, N_GUI_SLIDER_DATA::handle_bitmap, N_GUI_SLIDER_DATA::handle_hover_bitmap, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_SLIDER, n_log, N_GUI_SLIDER_DATA::track_bitmap, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_slider_set_range()
void n_gui_slider_set_range (N_GUI_CTX * ctx, int widget_id, double min_val, double max_val)
set slider min/max range, clamping the current value if needed
Parameters
ctx GUI context
widget_id id of the slider widget
min_val new minimum value
max_val new maximum value
Definition at line 2119 of file n_gui.c.
References _clamp(), _slider_snap_value(), N_GUI_WIDGET::data, N_GUI_SLIDER_DATA::max_val, N_GUI_SLIDER_DATA::min_val, n_gui_get_widget(), N_GUI_TYPE_SLIDER, N_GUI_SLIDER_DATA::step, N_GUI_WIDGET::type, and N_GUI_SLIDER_DATA::value.
n_gui_slider_set_step()
void n_gui_slider_set_step (N_GUI_CTX * ctx, int widget_id, double step)
set slider step increment (0 is treated as 1).
Value is re-snapped.
set slider step increment (0 is treated as 1).
0 means continuous (no snapping). When step > 0, the current value is immediately snapped.
Parameters
ctx GUI context
widget_id id of the slider widget
step step increment (0 = continuous)
Definition at line 2139 of file n_gui.c.
References _slider_snap_value(), N_GUI_WIDGET::data, N_GUI_SLIDER_DATA::max_val, N_GUI_SLIDER_DATA::min_val, n_gui_get_widget(), N_GUI_TYPE_SLIDER, N_GUI_SLIDER_DATA::step, N_GUI_WIDGET::type, and N_GUI_SLIDER_DATA::value.
n_gui_slider_set_value()
void n_gui_slider_set_value (N_GUI_CTX * ctx, int widget_id, double value)
set slider value
set slider value
Parameters
ctx GUI context
widget_id id of the slider widget
value new value to set
Definition at line 2101 of file n_gui.c.
References _clamp(), _slider_snap_value(), N_GUI_WIDGET::data, N_GUI_SLIDER_DATA::max_val, N_GUI_SLIDER_DATA::min_val, n_gui_get_widget(), N_GUI_TYPE_SLIDER, N_GUI_SLIDER_DATA::step, N_GUI_WIDGET::type, and N_GUI_SLIDER_DATA::value.
Referenced by main().
n_gui_slider_set_value_format()
void n_gui_slider_set_value_format (N_GUI_CTX * ctx, int widget_id, const char * fmt)
Override the built-in value readout's printf format string.
Pass NULL or "" to restore the default ("%.1f" in VALUE mode, "%.0f%%" in PERCENT mode). Format must consume the slider's double value (use f/g/e or cast with a precision width, a single d works too via stringification fallbacks). Buffer cap is 32 bytes.
Definition at line 2150 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_SLIDER, N_GUI_WIDGET::type, and N_GUI_SLIDER_DATA::value_format.
n_gui_slider_set_value_visible()
void n_gui_slider_set_value_visible (N_GUI_CTX * ctx, int widget_id, int visible)
Toggle the built-in value label.
Default 1 (visible). Set to 0 when the caller is already painting the value elsewhere so the slider doesn't double-render it.
Definition at line 2162 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_SLIDER, N_GUI_WIDGET::type, and N_GUI_SLIDER_DATA::value_visible.
n_gui_tab_add()
int n_gui_tab_add (N_GUI_TAB_PANEL * panel, const char * label)
add a tab to the panel, returns tab index
Definition at line 8923 of file n_gui.c.
References _n_gui_tab_button_clicked(), N_GUI_TAB_PANEL::active_tab, N_GUI_TAB_PANEL::button_h, N_GUI_TAB_PANEL::button_ids, N_GUI_TAB_PANEL::button_w, N_GUI_TAB_PANEL::ctx, n_gui_add_toggle_button(), N_GUI_SHAPE_RECT, N_GUI_TAB_MAX, N_GUI_TAB_PANEL::nb_tabs, N_GUI_TAB_PANEL::parent_window_id, N_GUI_TAB_PANEL::x, and N_GUI_TAB_PANEL::y.
n_gui_tab_create()
N_GUI_TAB_PANEL * n_gui_tab_create (N_GUI_CTX * ctx, int window_id, float x, float y, float button_w, float button_h, void(*)(int, void *) on_tab_change, void * user_data)
create a tab panel in an existing window
Definition at line 8901 of file n_gui.c.
References N_GUI_TAB_PANEL::active_tab, N_GUI_TAB_PANEL::button_h, N_GUI_TAB_PANEL::button_ids, N_GUI_TAB_PANEL::button_w, N_GUI_TAB_PANEL::content_window_ids, N_GUI_TAB_PANEL::ctx, Malloc, N_GUI_TAB_MAX, N_GUI_TAB_PANEL::nb_tabs, N_GUI_TAB_PANEL::on_tab_change, N_GUI_TAB_PANEL::parent_window_id, N_GUI_TAB_PANEL::user_data, N_GUI_TAB_PANEL::x, and N_GUI_TAB_PANEL::y.
n_gui_tab_free()
void n_gui_tab_free (N_GUI_TAB_PANEL ** panel)
free a tab panel (does not destroy the N_GUI widgets)
Definition at line 8961 of file n_gui.c.
References FreeNoLog.
n_gui_tab_get_active()
int n_gui_tab_get_active (N_GUI_TAB_PANEL * panel)
get the active tab index
Definition at line 8957 of file n_gui.c.
References N_GUI_TAB_PANEL::active_tab.
n_gui_tab_set_active()
void n_gui_tab_set_active (N_GUI_TAB_PANEL * panel, int index)
set the active tab (toggles buttons, opens/closes content windows)
Definition at line 8943 of file n_gui.c.
References N_GUI_TAB_PANEL::active_tab, N_GUI_TAB_PANEL::button_ids, N_GUI_TAB_PANEL::content_window_ids, N_GUI_TAB_PANEL::ctx, n_gui_button_set_toggled(), n_gui_close_window(), n_gui_open_window(), and N_GUI_TAB_PANEL::nb_tabs.
Referenced by _n_gui_tab_button_clicked().
n_gui_tab_set_content_window()
void n_gui_tab_set_content_window (N_GUI_TAB_PANEL * panel, int tab_index, int window_id)
associate a content window with a tab
Definition at line 8938 of file n_gui.c.
References N_GUI_TAB_PANEL::content_window_ids, and N_GUI_TAB_PANEL::nb_tabs.
n_gui_textarea_get_text()
const char * n_gui_textarea_get_text (N_GUI_CTX * ctx, int widget_id)
get text area content
get text area content
Parameters
ctx GUI context
widget_id id of the textarea widget
Returns
pointer to the text content
Definition at line 2177 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_TEXTAREA, and N_GUI_WIDGET::type.
Referenced by on_send_click().
n_gui_textarea_get_text_length()
size_t n_gui_textarea_get_text_length (N_GUI_CTX * ctx, int widget_id)
return the current text length in bytes (0 if widget is invalid)
return the current text length in bytes (0 if widget is invalid)
Parameters
ctx GUI context
widget_id id of the textarea widget
Returns
text length in bytes, or 0 if widget is invalid
Definition at line 3379 of file n_gui.c.
References N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_TEXTAREA, N_GUI_TEXTAREA_DATA::text_len, and N_GUI_WIDGET::type.
n_gui_textarea_scroll_to_bottom()
void n_gui_textarea_scroll_to_bottom (N_GUI_CTX * ctx, int widget_id)
scroll a multiline textarea to the bottom
Parameters
ctx GUI context
widget_id id of the textarea widget
Definition at line 3279 of file n_gui.c.
References _textarea_content_height(), N_GUI_WIDGET::data, N_GUI_CTX::default_font, N_GUI_WIDGET::font, N_GUI_WIDGET::h, N_GUI_TEXTAREA_DATA::multiline, n_gui_get_widget(), N_GUI_TYPE_TEXTAREA, N_GUI_TEXTAREA_DATA::scroll_y, N_GUI_CTX::style, N_GUI_TEXTAREA_DATA::text_len, N_GUI_STYLE::textarea_padding, N_GUI_WIDGET::type, and N_GUI_WIDGET::w.
n_gui_textarea_scroll_to_offset()
void n_gui_textarea_scroll_to_offset (N_GUI_CTX * ctx, int widget_id, size_t byte_offset)
scroll a multiline textarea so that the given byte offset is vertically centered
Parameters
ctx GUI context
widget_id id of the textarea widget
byte_offset byte offset in text to center on screen
Definition at line 3318 of file n_gui.c.
References _text_w(), _textarea_content_height(), _utf8_char_len(), N_GUI_WIDGET::data, N_GUI_CTX::default_font, N_GUI_WIDGET::font, N_GUI_WIDGET::h, N_GUI_TEXTAREA_DATA::multiline, n_gui_get_widget(), N_GUI_TYPE_TEXTAREA, N_GUI_TEXTAREA_DATA::scroll_from_wheel, N_GUI_TEXTAREA_DATA::scroll_y, N_GUI_STYLE::scrollbar_size, N_GUI_CTX::style, N_GUI_TEXTAREA_DATA::text, N_GUI_TEXTAREA_DATA::text_len, N_GUI_STYLE::textarea_padding, N_GUI_WIDGET::type, and N_GUI_WIDGET::w.
n_gui_textarea_set_bitmap()
void n_gui_textarea_set_bitmap (N_GUI_CTX * ctx, int widget_id, ALLEGRO_BITMAP * bg)
set optional background bitmap on a textarea widget.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the widget's lifetime and destroy them after the GUI context is destroyed.
set optional background bitmap on a textarea widget.
Note
Bitmaps are NOT owned by N_GUI.
Definition at line 2922 of file n_gui.c.
References N_GUI_WIDGET::data, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_TEXTAREA, n_log, and N_GUI_WIDGET::type.
Referenced by main().
n_gui_textarea_set_mask_char()
void n_gui_textarea_set_mask_char (N_GUI_CTX * ctx, int widget_id, char mask)
set a mask character for password-style input (e.g.
'*'). Set to '\0' to disable masking. Only affects single-line textareas.
Parameters
ctx the GUI context
widget_id id of the textarea widget
set a mask character for password-style input (e.g.
Parameters
mask The character to display instead of actual text (e.g. '*'). Set to '\0' to disable masking.
Definition at line 2936 of file n_gui.c.
References N_GUI_WIDGET::data, LOG_WARNING, n_gui_get_widget(), N_GUI_TYPE_TEXTAREA, n_log, and N_GUI_WIDGET::type.
n_gui_textarea_set_selection()
void n_gui_textarea_set_selection (N_GUI_CTX * ctx, int widget_id, size_t start, size_t end)
set the text selection range (byte offsets into text content)
Parameters
ctx GUI context
widget_id id of the textarea widget
start selection start byte offset
end selection end byte offset
Definition at line 3301 of file n_gui.c.
References N_GUI_TEXTAREA_DATA::cursor_pos, N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_TEXTAREA, N_GUI_TEXTAREA_DATA::sel_end, N_GUI_TEXTAREA_DATA::sel_start, N_GUI_TEXTAREA_DATA::text_len, and N_GUI_WIDGET::type.
n_gui_textarea_set_text()
void n_gui_textarea_set_text (N_GUI_CTX * ctx, int widget_id, const char * text)
set text area content
set text area content
Parameters
ctx GUI context
widget_id id of the textarea widget
text the text to set, or NULL to clear
Definition at line 2191 of file n_gui.c.
References _normalize_crlf(), N_GUI_TEXTAREA_DATA::char_limit, N_GUI_TEXTAREA_DATA::cursor_pos, N_GUI_WIDGET::data, n_gui_get_widget(), N_GUI_TYPE_TEXTAREA, N_GUI_TEXTAREA_DATA::scroll_x, N_GUI_TEXTAREA_DATA::text, N_GUI_TEXTAREA_DATA::text_len, and N_GUI_WIDGET::type.
Referenced by main(), n_gui_kvtable_add_row(), on_clear_click(), on_completion_select(), and on_send_click().
n_gui_toggle_window()
void n_gui_toggle_window (N_GUI_CTX * ctx, int window_id)
toggle window visibility (show/hide)
toggle window visibility (show/hide)
Definition at line 1129 of file n_gui.c.
References n_gui_get_window(), N_GUI_WIN_OPEN, and N_GUI_WINDOW::state.
Referenced by on_window_toggle_click().
n_gui_tooltip_pending()
int n_gui_tooltip_pending (N_GUI_CTX * ctx)
tooltip phase: 0 = none (or tooltips disabled via style.tooltip_delay <= 0), 1 = arming (hosts with cached GUI renders must keep redrawing so the bubble can appear on time), 2 = shown (static - re-render once on the transition, then stop)
tooltip phase: 0 = none (or tooltips disabled via style.tooltip_delay <= 0), 1 = arming (hosts with cached GUI renders must keep redrawing so the bubble can appear on time), 2 = shown (static - re-render once on the transition, then stop)
Hosts that cache the GUI render must keep invalidating/redrawing while this returns 1 (arming), or the bubble can never appear - it shows only after the pointer STOPS, when no more input events trigger redraws. A steady 2 (shown) needs one re-render on the transition and none after; re-rendering every tick during 2 would burn the cache for nothing.
Parameters
ctx the GUI context
Returns
0 = none/disabled, 1 = arming, 2 = shown
Definition at line 1437 of file n_gui.c.
References N_GUI_CTX::style, N_GUI_CTX::tooltip_armed_at, N_GUI_STYLE::tooltip_delay, and N_GUI_CTX::tooltip_widget_id.
n_gui_tree_add_node()
int n_gui_tree_add_node (N_GUI_TREE * tree, const char * label, int parent_index, void * user_data)
add a node to the tree
Definition at line 9019 of file n_gui.c.
References N_GUI_TREE_NODE::depth, N_GUI_TREE_NODE::expanded, N_GUI_TREE_NODE::has_children, N_GUI_TREE_NODE::label, N_GUI_TREE_MAX, n_gui_tree_rebuild(), N_GUI_TREE::nb_nodes, N_GUI_TREE::nodes, N_GUI_TREE_NODE::parent_index, and N_GUI_TREE_NODE::user_data.
n_gui_tree_clear()
void n_gui_tree_clear (N_GUI_TREE * tree)
remove all nodes and clear the backing listbox; tree object remains valid
Definition at line 9040 of file n_gui.c.
References N_GUI_TREE::ctx, N_GUI_TREE::listbox_id, n_gui_listbox_clear(), N_GUI_TREE::nb_nodes, and N_GUI_TREE::nb_visible.
n_gui_tree_create()
N_GUI_TREE * n_gui_tree_create (N_GUI_CTX * ctx, int window_id, float x, float y, float w, float h, void(*)(int, void *) on_select, void * user_data)
create a tree view in an existing window
Definition at line 8980 of file n_gui.c.
References _n_gui_tree_listbox_selected(), N_GUI_TREE::ctx, N_GUI_TREE::drag_active, N_GUI_TREE::drag_armed_node, N_GUI_TREE::drag_hover_node, N_GUI_TREE::drag_press_x, N_GUI_TREE::drag_press_y, N_GUI_TREE::drag_source_node, N_GUI_TREE::drop_position, N_GUI_TREE::drop_user_data, FreeNoLog, N_GUI_TREE::listbox_id, Malloc, N_GUI_TREE::mouse_b1_prev, n_gui_add_listbox(), N_GUI_DROP_INTO, N_GUI_SELECT_SINGLE, N_GUI_TREE::nb_nodes, N_GUI_TREE::nb_visible, N_GUI_TREE::on_drop, N_GUI_TREE::on_select, N_GUI_TREE::user_data, and N_GUI_TREE::window_id.
n_gui_tree_draw_overlay()
void n_gui_tree_draw_overlay (N_GUI_TREE * tree)
per-frame overlay drawing: draws the active drop-indicator on top of the listbox.
Call after n_gui_draw(). No-op when no drag is in progress.
Definition at line 9369 of file n_gui.c.
References _n_gui_tree_listbox_bounds(), N_GUI_THEME::border_active, N_GUI_TREE::ctx, N_GUI_CTX::default_theme, N_GUI_TREE::drag_active, N_GUI_TREE::drag_hover_node, N_GUI_TREE::drop_position, N_GUI_TREE::listbox_id, N_GUI_DROP_BEFORE, N_GUI_DROP_INTO, n_gui_get_widget(), N_GUI_TREE::nb_visible, N_GUI_WIDGET::theme, and N_GUI_TREE::visible_map.
n_gui_tree_find_by_user_data()
int n_gui_tree_find_by_user_data (const N_GUI_TREE * tree, const void * ptr)
find the first node whose user_data pointer equals ptr, or -1.
Used to re-resolve a node index after a rebuild compacted the array: the caller stashes the stable user_data pointer before the rebuild, then calls this to find the new index.
Definition at line 9138 of file n_gui.c.
References N_GUI_TREE::nb_nodes, N_GUI_TREE::nodes, and N_GUI_TREE_NODE::user_data.
n_gui_tree_free()
void n_gui_tree_free (N_GUI_TREE ** tree)
free a tree view (does not destroy the N_GUI listbox)
Definition at line 9201 of file n_gui.c.
References FreeNoLog.
n_gui_tree_get_selection()
int n_gui_tree_get_selection (N_GUI_TREE * tree)
get the index of the currently selected node, or -1 when nothing is selected or the selection points at a hidden row
Definition at line 9109 of file n_gui.c.
References N_GUI_TREE::ctx, N_GUI_TREE::listbox_id, n_gui_listbox_get_selected(), N_GUI_TREE::nb_visible, and N_GUI_TREE::visible_map.
Referenced by n_gui_tree_rebuild().
n_gui_tree_rebuild()
void n_gui_tree_rebuild (N_GUI_TREE * tree)
rebuild the listbox to reflect current tree state
Definition at line 9153 of file n_gui.c.
References _n_gui_tree_node_visible(), N_GUI_TREE::ctx, N_GUI_TREE_NODE::depth, display, N_GUI_TREE_NODE::expanded, N_GUI_TREE_NODE::has_children, N_GUI_TREE_NODE::label, N_GUI_TREE::listbox_id, n_gui_listbox_add_item(), n_gui_listbox_clear(), n_gui_listbox_get_scroll_offset(), n_gui_listbox_set_scroll_offset(), n_gui_listbox_set_selected(), n_gui_tree_get_selection(), N_GUI_TREE_MAX, N_GUI_TREE::nb_nodes, N_GUI_TREE::nb_visible, N_GUI_TREE::nodes, and N_GUI_TREE::visible_map.
Referenced by n_gui_tree_add_node(), n_gui_tree_remove_node(), n_gui_tree_set_label(), n_gui_tree_set_selection(), and n_gui_tree_toggle_expand().
n_gui_tree_remove_node()
void n_gui_tree_remove_node (N_GUI_TREE * tree, int node_index)
remove a node and its entire subtree; remaining node indices are compacted (callers holding indices across the call must discard or re-resolve them)
Definition at line 9047 of file n_gui.c.
References N_GUI_TREE_NODE::has_children, N_GUI_TREE_MAX, n_gui_tree_rebuild(), N_GUI_TREE::nb_nodes, N_GUI_TREE::nodes, and N_GUI_TREE_NODE::parent_index.
n_gui_tree_set_label()
void n_gui_tree_set_label (N_GUI_TREE * tree, int node_index, const char * new_label)
change the display label of a node
Definition at line 9101 of file n_gui.c.
References N_GUI_TREE_NODE::label, n_gui_tree_rebuild(), N_GUI_TREE::nb_nodes, and N_GUI_TREE::nodes.
n_gui_tree_set_on_drop()
void n_gui_tree_set_on_drop (N_GUI_TREE * tree, n_gui_tree_on_drop_t on_drop, void * user_data)
install (or clear, with NULL) a drag-reorder drop callback.
Drag state is only tracked when on_drop is non-NULL.
Definition at line 9212 of file n_gui.c.
References N_GUI_TREE::drag_active, N_GUI_TREE::drag_armed_node, N_GUI_TREE::drag_hover_node, N_GUI_TREE::drag_source_node, N_GUI_TREE::drop_user_data, and N_GUI_TREE::on_drop.
n_gui_tree_set_selection()
void n_gui_tree_set_selection (N_GUI_TREE * tree, int node_index)
programmatically select a node; ancestors are expanded so the node is visible, and the listbox scrolls to reveal it.
Does not fire the on_select callback. No-op if node_index is out of range.
Definition at line 9116 of file n_gui.c.
References N_GUI_TREE::ctx, N_GUI_TREE_NODE::expanded, N_GUI_TREE::listbox_id, n_gui_listbox_set_scroll_offset(), n_gui_listbox_set_selected(), n_gui_tree_rebuild(), N_GUI_TREE::nb_nodes, N_GUI_TREE::nb_visible, N_GUI_TREE::nodes, N_GUI_TREE_NODE::parent_index, and N_GUI_TREE::visible_map.
n_gui_tree_tick()
void n_gui_tree_tick (N_GUI_TREE * tree)
per-frame poll: reads ctx->mouse_* to track drag state and fires the on_drop callback on release.
Call once per frame while the tree is visible, before n_gui_draw(). No-op when on_drop is NULL.
Definition at line 9307 of file n_gui.c.
References _N_GUI_TREE_DRAG_THRESHOLD_PX, _n_gui_tree_hit_row(), N_GUI_TREE::ctx, N_GUI_TREE::drag_active, N_GUI_TREE::drag_armed_node, N_GUI_TREE::drag_hover_node, N_GUI_TREE::drag_press_x, N_GUI_TREE::drag_press_y, N_GUI_TREE::drag_source_node, N_GUI_TREE::drop_position, N_GUI_TREE::drop_user_data, N_GUI_CTX::mouse_b1, N_GUI_TREE::mouse_b1_prev, N_GUI_CTX::mouse_x, N_GUI_CTX::mouse_y, N_GUI_DROP_INTO, and N_GUI_TREE::on_drop.
n_gui_tree_toggle_expand()
void n_gui_tree_toggle_expand (N_GUI_TREE * tree, int node_index)
toggle expand/collapse of a node
Definition at line 9146 of file n_gui.c.
References N_GUI_TREE_NODE::expanded, N_GUI_TREE_NODE::has_children, n_gui_tree_rebuild(), N_GUI_TREE::nb_nodes, and N_GUI_TREE::nodes.
Referenced by _n_gui_tree_listbox_selected().
n_gui_update_transform()
void n_gui_update_transform (N_GUI_CTX * ctx)
recalculate scale and offset from virtual canvas to display.
Called automatically by n_gui_set_display_size when virtual canvas is set. You should not normally need to call this directly.
recalculate scale and offset from virtual canvas to display.
Uses uniform (aspect-preserving) scaling with centred letterboxing, identical to the approach used by BlockBlaster's update_view_offset(). Called automatically by n_gui_set_display_size() when virtual canvas is set.
Definition at line 5705 of file n_gui.c.
References __n_assert, N_GUI_CTX::display_h, N_GUI_CTX::display_w, N_GUI_CTX::gui_offset_x, N_GUI_CTX::gui_offset_y, N_GUI_CTX::gui_scale, N_GUI_CTX::virtual_h, and N_GUI_CTX::virtual_w.
Referenced by n_gui_set_display_size(), and n_gui_set_virtual_size().
n_gui_wants_mouse()
int n_gui_wants_mouse (N_GUI_CTX * ctx)
check if the mouse is currently over any open GUI window (use to prevent click-through to the game world)
check if the mouse is currently over any open GUI window (use to prevent click-through to the game world)
Use this to prevent mouse clicks from passing through the GUI to the game.
Parameters
ctx the GUI context
Returns
1 if the mouse is over a GUI window, 0 otherwise
Definition at line 8182 of file n_gui.c.
References __n_assert, _point_in_rect(), _win_tbh(), N_GUI_CTX::gui_offset_x, N_GUI_CTX::gui_offset_y, N_GUI_CTX::gui_scale, N_GUI_WINDOW::h, list_foreach, N_GUI_CTX::mouse_x, N_GUI_CTX::mouse_y, N_GUI_WIN_MINIMISED, N_GUI_WIN_OPEN, N_GUI_WINDOW::state, N_GUI_CTX::virtual_h, N_GUI_CTX::virtual_w, N_GUI_WINDOW::w, N_GUI_CTX::windows, N_GUI_WINDOW::x, and N_GUI_WINDOW::y.
Referenced by main().
n_gui_window_apply_autofit()
void n_gui_window_apply_autofit (N_GUI_CTX * ctx, int window_id)
trigger auto-fit recalculation for a window (call after adding/removing/resizing widgets)
Parameters
ctx the GUI context
window_id the window to recalculate
trigger auto-fit recalculation for a window (call after adding/removing/resizing widgets)
Computes content bounding box from visible widgets and adjusts window dimensions based on autofit_flags and autofit_border.
Definition at line 1214 of file n_gui.c.
References __n_assert, _win_tbh(), N_GUI_WINDOW::autofit_border, N_GUI_WINDOW::autofit_flags, N_GUI_WINDOW::autofit_origin_x, N_GUI_WINDOW::autofit_origin_y, N_GUI_WINDOW::content_h, N_GUI_WINDOW::content_w, N_GUI_WIDGET::h, N_GUI_WINDOW::h, list_foreach, N_GUI_WINDOW::min_h, N_GUI_WINDOW::min_w, N_GUI_AUTOFIT_CENTER, N_GUI_AUTOFIT_EXPAND_LEFT, N_GUI_AUTOFIT_EXPAND_UP, N_GUI_AUTOFIT_H, N_GUI_AUTOFIT_W, n_gui_get_window(), N_GUI_WIDGET::visible, N_GUI_WIDGET::w, N_GUI_WINDOW::w, N_GUI_WINDOW::widgets, N_GUI_WIDGET::x, N_GUI_WINDOW::x, N_GUI_WIDGET::y, and N_GUI_WINDOW::y.
Referenced by main(), and n_gui_draw().
n_gui_window_autosize()
void n_gui_window_autosize (N_GUI_CTX * ctx, int window_id)
recompute and apply minimum-fit size for a window based on its current widgets
recompute and apply minimum-fit size for a window based on its current widgets
Adds padding around the furthest widget extents.
Definition at line 1166 of file n_gui.c.
References _win_tbh(), N_GUI_WIDGET::h, N_GUI_WINDOW::h, list_foreach, N_GUI_WINDOW::min_h, N_GUI_WINDOW::min_w, n_gui_get_window(), N_GUI_WIDGET::w, N_GUI_WINDOW::w, N_GUI_WINDOW::widgets, N_GUI_WIDGET::x, and N_GUI_WIDGET::y.
Referenced by main().
n_gui_window_get_flags()
int n_gui_window_get_flags (N_GUI_CTX * ctx, int window_id)
get feature flags of a window
get feature flags of a window
Returns
the flags, or 0
Definition at line 1156 of file n_gui.c.
References N_GUI_WINDOW::flags, and n_gui_get_window().
n_gui_window_get_resize_policy()
int n_gui_window_get_resize_policy (N_GUI_CTX * ctx, int window_id)
get per-window resize policy
get per-window resize policy
Returns
N_GUI_WIN_RESIZE_NONE, _MOVE, or _SCALE
Definition at line 5805 of file n_gui.c.
References __n_assert, n_gui_get_window(), and N_GUI_WINDOW::resize_policy.
n_gui_window_get_zorder()
int n_gui_window_get_zorder (N_GUI_CTX * ctx, int window_id)
get window z-order mode
get window z-order mode
Definition at line 1100 of file n_gui.c.
References __n_assert, n_gui_get_window(), N_GUI_ZORDER_NORMAL, and N_GUI_WINDOW::z_order.
n_gui_window_get_zvalue()
int n_gui_window_get_zvalue (N_GUI_CTX * ctx, int window_id)
get window z-value (for N_GUI_ZORDER_FIXED mode)
get window z-value (for N_GUI_ZORDER_FIXED mode)
Definition at line 1110 of file n_gui.c.
References __n_assert, n_gui_get_window(), and N_GUI_WINDOW::z_value.
n_gui_window_is_maximised()
int n_gui_window_is_maximised (N_GUI_CTX * ctx, int window_id)
check if a window is currently maximised
check if a window is currently maximised
Returns
1 if maximised, 0 if not (or invalid id)
Definition at line 823 of file n_gui.c.
References __n_assert, n_gui_get_window(), N_GUI_WIN_MAXIMISED, and N_GUI_WINDOW::state.
n_gui_window_is_open()
int n_gui_window_is_open (N_GUI_CTX * ctx, int window_id)
check if window is visible
check if window is visible
Returns
1 if open, 0 if closed
Definition at line 1138 of file n_gui.c.
References n_gui_get_window(), N_GUI_WIN_OPEN, and N_GUI_WINDOW::state.
Referenced by on_windows_menu_open().
n_gui_window_set_autofit()
void n_gui_window_set_autofit (N_GUI_CTX * ctx, int window_id, int autofit_flags, float border)
configure auto-fit behavior for a dialog window
Parameters
ctx the GUI context
window_id the window to configure
autofit_flags bitmask of N_GUI_AUTOFIT_W, N_GUI_AUTOFIT_H, N_GUI_AUTOFIT_EXPAND_LEFT, N_GUI_AUTOFIT_EXPAND_UP
border padding in pixels between content bounding box and window edge (on each side)
configure auto-fit behavior for a dialog window
Store the flags and border value in the window struct.
Definition at line 1195 of file n_gui.c.
References __n_assert, N_GUI_WINDOW::autofit_border, N_GUI_WINDOW::autofit_flags, N_GUI_WINDOW::autofit_origin_x, N_GUI_WINDOW::autofit_origin_y, LOG_ERR, n_gui_get_window(), n_log, N_GUI_WINDOW::x, and N_GUI_WINDOW::y.
Referenced by main().
n_gui_window_set_bitmaps()
void n_gui_window_set_bitmaps (N_GUI_CTX * ctx, int window_id, ALLEGRO_BITMAP * bg, ALLEGRO_BITMAP * titlebar, int bg_scale_mode)
set optional bitmap overlays on a window's body and titlebar.
Pass NULL for any bitmap you don't want to set.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the window's lifetime and destroy them after the GUI context is destroyed.
Parameters
ctx the GUI context
window_id id of the target window
bg body background bitmap (NULL = color fill)
titlebar titlebar background bitmap (NULL = color fill)
bg_scale_mode scale mode for bg: N_GUI_IMAGE_FIT, N_GUI_IMAGE_STRETCH, or N_GUI_IMAGE_CENTER
set optional bitmap overlays on a window's body and titlebar.
Note
Bitmaps are NOT owned by N_GUI. The caller must keep them alive for the window's lifetime and destroy them after the GUI context is destroyed.
Definition at line 2856 of file n_gui.c.
References N_GUI_WINDOW::bg_bitmap, N_GUI_WINDOW::bg_scale_mode, LOG_WARNING, n_gui_get_window(), n_log, and N_GUI_WINDOW::titlebar_bitmap.
Referenced by main().
n_gui_window_set_close_callback()
void n_gui_window_set_close_callback (N_GUI_CTX * ctx, int window_id, void(*)(int, void *) on_close, void * user_data)
set the close button callback for a window (NULL = default: hide window)
Parameters
ctx the GUI context
window_id the target window
on_close callback receiving (window_id, user_data). Must call n_gui_close_window() itself if desired.
user_data user data passed to the callback
set the close button callback for a window (NULL = default: hide window)
Definition at line 833 of file n_gui.c.
References __n_assert, n_gui_get_window(), N_GUI_TB_BUTTONS::on_close, N_GUI_TB_BUTTONS::on_close_user_data, and N_GUI_WINDOW::tb_buttons.
n_gui_window_set_content_draw_callback()
void n_gui_window_set_content_draw_callback (N_GUI_CTX * ctx, int window_id, void(*)(int, void *) on_content_draw, void * user_data)
set a content-draw callback for a window, invoked during n_gui_draw right after the window's own content is drawn (at the window's z-order)
Parameters
ctx the GUI context
window_id the target window
on_content_draw callback receiving (window_id, user_data); NULL clears it
user_data user data passed to the callback
set a content-draw callback for a window, invoked during n_gui_draw right after the window's own content is drawn (at the window's z-order)
The callback runs during n_gui_draw immediately after the window's own content is drawn, at the window's z-order, so any custom rendering it performs is occluded by windows that draw on top of this one.
Definition at line 848 of file n_gui.c.
References __n_assert, n_gui_get_window(), N_GUI_WINDOW::on_content_draw, and N_GUI_WINDOW::on_content_draw_data.
n_gui_window_set_flags()
void n_gui_window_set_flags (N_GUI_CTX * ctx, int window_id, int flags)
set feature flags on a window (N_GUI_WIN_AUTO_SCROLLBAR, N_GUI_WIN_RESIZABLE, ...)
Parameters
ctx the GUI context
window_id id of the target window
flags bitmask of N_GUI_WIN_* flags to set
set feature flags on a window (N_GUI_WIN_AUTO_SCROLLBAR, N_GUI_WIN_RESIZABLE, ...)
Definition at line 1147 of file n_gui.c.
References N_GUI_WINDOW::flags, and n_gui_get_window().
Referenced by main(), and main().
n_gui_window_set_maximize_callback()
void n_gui_window_set_maximize_callback (N_GUI_CTX * ctx, int window_id, void(*)(int, void *) on_maximize, void * user_data)
set the maximize button callback for a window (NULL = default: toggle maximised)
Parameters
ctx the GUI context
window_id the target window
on_maximize callback receiving (window_id, user_data)
user_data user data passed to the callback
set the maximize button callback for a window (NULL = default: toggle maximised)
Definition at line 870 of file n_gui.c.
References __n_assert, n_gui_get_window(), N_GUI_TB_BUTTONS::on_maximize, N_GUI_TB_BUTTONS::on_maximize_user_data, and N_GUI_WINDOW::tb_buttons.
n_gui_window_set_minimize_callback()
void n_gui_window_set_minimize_callback (N_GUI_CTX * ctx, int window_id, void(*)(int, void *) on_minimize, void * user_data)
set the minimize button callback for a window (NULL = default: toggle minimised)
Parameters
ctx the GUI context
window_id the target window
on_minimize callback receiving (window_id, user_data)
user_data user data passed to the callback
set the minimize button callback for a window (NULL = default: toggle minimised)
Definition at line 859 of file n_gui.c.
References __n_assert, n_gui_get_window(), N_GUI_TB_BUTTONS::on_minimize, N_GUI_TB_BUTTONS::on_minimize_user_data, and N_GUI_WINDOW::tb_buttons.
n_gui_window_set_resize_policy()
void n_gui_window_set_resize_policy (N_GUI_CTX * ctx, int window_id, int policy)
set per-window resize policy (N_GUI_WIN_RESIZE_NONE / _MOVE / _SCALE).
Automatically captures normalized coordinates from the window's current position/size relative to the current display size.
set per-window resize policy (N_GUI_WIN_RESIZE_NONE / _MOVE / _SCALE).
Automatically captures normalized coordinates from the window's current position/size relative to the current display size.
Definition at line 5792 of file n_gui.c.
References __n_assert, _n_gui_window_capture_normalized(), n_gui_get_window(), and N_GUI_WINDOW::resize_policy.
Referenced by main(), and main().
n_gui_window_set_tb_btn_theme()
void n_gui_window_set_tb_btn_theme (N_GUI_CTX * ctx, int window_id, N_GUI_THEME theme)
set the theme for titlebar minimize/maximize buttons on a specific window
set the theme for titlebar minimize/maximize buttons on a specific window
Definition at line 881 of file n_gui.c.
References __n_assert, N_GUI_TB_BUTTONS::btn_theme, n_gui_get_window(), and N_GUI_WINDOW::tb_buttons.
n_gui_window_set_tb_button_bitmaps()
void n_gui_window_set_tb_button_bitmaps (N_GUI_CTX * ctx, int window_id, int btn_type, ALLEGRO_BITMAP * normal, ALLEGRO_BITMAP * hover, ALLEGRO_BITMAP * active)
set optional bitmap overlays on a titlebar button
Parameters
ctx the GUI context
window_id the target window
btn_type N_GUI_TB_BTN_MINIMIZE, N_GUI_TB_BTN_MAXIMIZE, or N_GUI_TB_BTN_CLOSE
normal bitmap for normal state (NULL = color theme)
hover bitmap for hover state (NULL = fallback to normal)
active bitmap for active/pressed state (NULL = fallback to normal)
set optional bitmap overlays on a titlebar button
Definition at line 901 of file n_gui.c.
References __n_assert, N_GUI_TB_BUTTONS::close_active_bitmap, N_GUI_TB_BUTTONS::close_bitmap, N_GUI_TB_BUTTONS::close_hover_bitmap, N_GUI_TB_BUTTONS::maximize_active_bitmap, N_GUI_TB_BUTTONS::maximize_bitmap, N_GUI_TB_BUTTONS::maximize_hover_bitmap, N_GUI_TB_BUTTONS::minimize_active_bitmap, N_GUI_TB_BUTTONS::minimize_bitmap, N_GUI_TB_BUTTONS::minimize_hover_bitmap, n_gui_get_window(), N_GUI_TB_BTN_CLOSE, N_GUI_TB_BTN_MAXIMIZE, N_GUI_TB_BTN_MINIMIZE, and N_GUI_WINDOW::tb_buttons.
Referenced by main().
n_gui_window_set_tb_close_theme()
void n_gui_window_set_tb_close_theme (N_GUI_CTX * ctx, int window_id, N_GUI_THEME theme)
set the theme for the titlebar close button on a specific window
set the theme for the titlebar close button on a specific window
Definition at line 891 of file n_gui.c.
References __n_assert, N_GUI_TB_BUTTONS::close_theme, n_gui_get_window(), and N_GUI_WINDOW::tb_buttons.
n_gui_window_set_zorder()
void n_gui_window_set_zorder (N_GUI_CTX * ctx, int window_id, int z_mode, int z_value)
set window z-order mode and value
Parameters
ctx the GUI context
window_id the window to configure
z_mode one of N_GUI_ZORDER_NORMAL, N_GUI_ZORDER_ALWAYS_ON_TOP, N_GUI_ZORDER_ALWAYS_BEHIND, N_GUI_ZORDER_FIXED, N_GUI_ZORDER_POPUP
z_value z-value for N_GUI_ZORDER_FIXED mode (lower = behind, higher = on top), ignored for other modes
set window z-order mode and value
Re-sorts the window list after changing.
Definition at line 1082 of file n_gui.c.
References __n_assert, _sort_windows_by_zorder(), LOG_ERR, n_gui_get_window(), N_GUI_ZORDER_ALWAYS_BEHIND, N_GUI_ZORDER_ALWAYS_ON_TOP, N_GUI_ZORDER_FIXED, N_GUI_ZORDER_NORMAL, N_GUI_ZORDER_POPUP, n_log, N_GUI_WINDOW::z_order, and N_GUI_WINDOW::z_value.
n_gui_window_update_normalized()
void n_gui_window_update_normalized (N_GUI_CTX * ctx, int window_id)
recapture normalized coordinates for a window from its current absolute position/size.
Call after programmatically moving/resizing a window if you want the new position to be the adaptive reference point.
recapture normalized coordinates for a window from its current absolute position/size.
Call after programmatically moving/resizing a window if you want the new position to be the adaptive reference point.
Definition at line 5818 of file n_gui.c.
References __n_assert, _n_gui_window_capture_normalized(), N_GUI_CTX::display_h, N_GUI_CTX::display_w, n_gui_get_window(), N_GUI_CTX::ref_display_h, and N_GUI_CTX::ref_display_w.