Nilorea Library: TIMERS: generally used headers, defines, timers, allocators,...
TIMERS: generally used headers, defines, timers, allocators,...
Data Structures
struct N_TIME
Timing Structure.
Functions
time_t get_msec (N_TIME *timer)
Poll any N_TIME HiTimer, returning msec.
time_t get_sec (N_TIME *timer)
Poll any N_TIME HiTimer, returning sec.
time_t get_usec (N_TIME *timer)
Poll any N_TIME HiTimer, returning usec.
void PAUSE (void)
for the 'press a key to continue'
int start_HiTimer (N_TIME *timer)
Init or restart from zero any N_TIME HiTimer.
void u_sleep (unsigned int usec)
sleep for the given number of microseconds
Detailed Description
Data Structure Documentation
N_TIME
struct N_TIME
Timing Structure.
Examples
ex_fluid.c.
Definition at line 48 of file n_time.h.
Data Fields
struct timeval currentTime current time
time_t delta time since last poll
struct timeval startTime start time
Function Documentation
get_msec()
time_t get_msec (N_TIME * timer)
Poll any N_TIME HiTimer, returning msec.
Poll any N_TIME HiTimer, returning msec.
Parameters
timer Any N_TIMER *timer you wanna poll
Returns
The elapsed number of msec for the given N_TIME *timer
Definition at line 127 of file n_time.c.
References __n_assert, currentTime, delta, and startTime.
get_sec()
time_t get_sec (N_TIME * timer)
Poll any N_TIME HiTimer, returning sec.
Poll any N_TIME HiTimer, returning sec.
Parameters
timer Any N_TIMER *timer you wanna poll
Returns
The elapsed number of sec for the given N_TIME *timer
Definition at line 148 of file n_time.c.
References __n_assert, currentTime, delta, and startTime.
get_usec()
time_t get_usec (N_TIME * timer)
Poll any N_TIME HiTimer, returning usec.
Poll any N_TIME HiTimer, returning usec.
Parameters
timer Any N_TIMER *timer you wanna poll
Returns
The elapsed number of usec for the given N_TIME *timer
Definition at line 106 of file n_time.c.
References __n_assert, currentTime, delta, and startTime.
Referenced by _netw_timed_connect(), main(), manage_particle(), n_kafka_polling_thread(), and netw_connect_ex_to().
PAUSE()
void PAUSE (void)
for the 'press a key to continue'
for the 'press a key to continue'
Definition at line 61 of file n_time.c.
References LOG_DEBUG, LOG_ERR, and n_log.
start_HiTimer()
int start_HiTimer (N_TIME * timer)
Init or restart from zero any N_TIME HiTimer.
Init or restart from zero any N_TIME HiTimer.
Parameters
timer Any N_TIMER *timer you wanna start or reset
Returns
TRUE or FALSE
Definition at line 84 of file n_time.c.
References __n_assert, delta, and startTime.
Referenced by _netw_timed_connect(), init_particle_system(), main(), n_kafka_polling_thread(), and netw_connect_ex_to().
u_sleep()
void u_sleep (unsigned int usec)
sleep for the given number of microseconds
sleep for the given number of microseconds
Parameters
usec Number of usec to sleep
Definition at line 53 of file n_time.c.
Referenced by destroy_threaded_pool(), handle_client(), main(), manage_client(), netw_accept_pool_thread_func(), netw_send_func(), netw_wait_msg(), recv_ssl_data(), run_client(), run_server(), and send_ssl_data().