Nilorea Library: KAFKA: generic event producer and consumer functions
KAFKA: generic event producer and consumer functions
Data Structures
struct N_KAFKA
structure of a KAFKA consumer or producer handle
struct N_KAFKA_EVENT
structure of a KAFKA message
Macros
#define N_KAFKA_EVENT_CREATED 5
state of a freshly created event
#define N_KAFKA_EVENT_ERROR 2
state of an errored event
#define N_KAFKA_EVENT_OK 4
state of an OK event
#define N_KAFKA_EVENT_QUEUED 0
state of a queued event
#define N_KAFKA_EVENT_WAITING_ACK 1
state of a sent event waiting for acknowledgement
Functions
int n_kafka_add_header (N_KAFKA_EVENT *event, N_STR *key, N_STR *value)
add a header to an event
int n_kafka_add_header_ex (N_KAFKA_EVENT *event, char *key, size_t key_length, char *value, size_t value_length)
add a header to an event (extended version)
void n_kafka_delete (N_KAFKA *kafka)
delete a kafka handle
int n_kafka_disable_event_consumption (N_KAFKA *kafka)
disable event consumption
int n_kafka_disable_event_production (N_KAFKA *kafka)
disable event production
int n_kafka_dump_unprocessed (N_KAFKA *kafka, char *directory)
dump unprocessed events to a directory
int n_kafka_enable_event_consumption (N_KAFKA *kafka)
enable event consumption
int n_kafka_enable_event_production (N_KAFKA *kafka)
enable event production
int n_kafka_event_destroy (N_KAFKA_EVENT **event)
destroy a kafka event
void n_kafka_event_destroy_ptr (void *event)
destroy a kafka event (void pointer version for list destructor)
N_KAFKA_EVENT * n_kafka_get_event (N_KAFKA *kafka)
get the next received event
int32_t n_kafka_get_schema_from_char (const char *string)
get schema id from a char string
int32_t n_kafka_get_schema_from_nstr (const N_STR *string)
get schema id from an N_STR string
int n_kafka_get_status (N_KAFKA *kafka, size_t *nb_queued, size_t *nb_waiting, size_t *nb_error)
get kafka queue status counters
N_KAFKA * n_kafka_load_config (char *config_file, int mode)
load kafka configuration from file
int n_kafka_load_unprocessed (N_KAFKA *kafka, const char *directory)
load unprocessed events from a directory
N_KAFKA * n_kafka_new (int32_t poll_timeout, int32_t poll_interval, size_t errstr_len)
create a new kafka handle
N_KAFKA_EVENT * n_kafka_new_event (int schema_id)
create a new empty kafka event
N_KAFKA_EVENT * n_kafka_new_event_from_char (const char *string, size_t written, int schema_id)
create a new kafka event from a char string
N_KAFKA_EVENT * n_kafka_new_event_from_file (char *filename, int schema_id)
create a new kafka event from a file
N_KAFKA_EVENT * n_kafka_new_event_from_string (const N_STR *string, int schema_id)
create a new kafka event from an N_STR string
int n_kafka_new_headers (N_KAFKA_EVENT *event, size_t count)
create new headers for an event
int n_kafka_poll (N_KAFKA *kafka)
poll kafka for events
int n_kafka_produce (N_KAFKA *kafka, N_KAFKA_EVENT *event)
produce a kafka event
int n_kafka_put_schema_in_char (char *string, int schema_id)
put schema id in a char string
int n_kafka_put_schema_in_nstr (N_STR *string, int schema_id)
put schema id in an N_STR string
int n_kafka_set_error_timeout (N_KAFKA *kafka, int32_t error_timeout)
set the retry interval (in seconds) for errored events.
int n_kafka_set_sended_dir (N_KAFKA *kafka, const char *tosend_dir, const char *sended_dir)
set the 'to-send' and 'sended' base directories used to move acknowledged event files instead of deleting them
int n_kafka_start_polling_thread (N_KAFKA *kafka)
start the kafka polling thread
int n_kafka_stop_polling_thread (N_KAFKA *kafka)
stop the kafka polling thread
Detailed Description
Data Structure Documentation
N_KAFKA
struct N_KAFKA
structure of a KAFKA consumer or producer handle
Examples
ex_kafka.c.
Definition at line 88 of file n_kafka.h.
Data Fields
char * bootstrap_servers kafka bootstrap servers string
cJSON * configuration kafka json configuration holder
int32_t error_timeout retry interval in seconds for events stuck in N_KAFKA_EVENT_ERROR.
0 (default) disables retries, errored events stay errored until the caller dumps and reloads them.
N_STR * errstr kafka error string holder
char * event_cmd eventual custom event_cmd
int32_t event_consumption_enabled bool flag to suspend or restart event consumption
int32_t event_production_enabled bool flag to suspend or restart event production
LIST * events_to_send list of N_KAFKA_EVENT to send
char * groupid consumer group id
int is_transactional TRUE when a 'transactional.id' is set in the producer config: produces are then wrapped in kafka transactions.
FALSE keeps the legacy fire-and-forget produce path.
int mode kafka handle mode: RD_KAFKA_CONSUMER or RD_KAFKA_PRODUCER
int32_t monitored_directory_interval monitored directory refresh interval in msecs
size_t nb_error number of errored events
size_t nb_queued number of waiting events in the producer waiting list
size_t nb_waiting number of events waiting for an ack in the waiting list
int32_t poll_interval poll interval in msecs
int32_t poll_timeout poll timeout in msecs
pthread_t polling_thread polling thread id
int polling_thread_status polling thread status, 0 => off , 1 => on , 2 => wants to stop, will be turned out to 0 by exiting polling thread
rd_kafka_conf_t * rd_kafka_conf kafka structure handle
rd_kafka_t * rd_kafka_handle kafka handle (producer or consumer)
rd_kafka_topic_t * rd_kafka_topic kafka topic handle
LIST * received_events list of received N_KAFKA_EVENT
pthread_rwlock_t rwlock access lock
int schema_id kafka schema id in network order
char * sended_dir base directory produced event files are moved to once acknowledged ('sended').
When NULL, acknowledged files are deleted (legacy behaviour) instead of being moved.
rd_kafka_topic_partition_list_t * subscription subscribed topics
char * topic kafka topic string
char ** topics list of topics to subscribe to
char * tosend_dir base directory the produced event files are read from ('to-send').
Used together with sended_dir to compute the destination subpath when moving a file on ack. NULL keeps the legacy behaviour.
N_KAFKA_EVENT
struct N_KAFKA_EVENT
structure of a KAFKA message
Examples
ex_kafka.c.
Definition at line 66 of file n_kafka.h.
Data Fields
time_t error_time wall-clock time at which status flipped to N_KAFKA_EVENT_ERROR.
0 when the event has never errored. Used by the retry logic gated by N_KAFKA::error_timeout.
N_STR * event_files_to_delete string containing the original event source file name if it is to be deleted when event is produced.
List separated with ',' else it's NULL
N_STR * event_string string containing the topic id + payload
char * from_topic in case of received event, else NULL
struct N_KAFKA * parent_table access lock
rd_kafka_headers_t * rd_kafka_headers kafka produce event headers structure handle
LIST * received_headers kafka consume event headers structure handle
int schema_id kafka schema_id
unsigned int status state of the event: N_KAFKA_EVENT_CREATED ,N_KAFKA_EVENT_QUEUED , N_KAFKA_EVENT_WAITING_ACK , N_KAFKA_EVENT_ERROR , N_KAFKA_EVENT_OK
Macro Definition Documentation
N_KAFKA_EVENT_CREATED
#define N_KAFKA_EVENT_CREATED 5
state of a freshly created event
Definition at line 63 of file n_kafka.h.
N_KAFKA_EVENT_ERROR
#define N_KAFKA_EVENT_ERROR 2
state of an errored event
Definition at line 59 of file n_kafka.h.
N_KAFKA_EVENT_OK
#define N_KAFKA_EVENT_OK 4
state of an OK event
Definition at line 61 of file n_kafka.h.
N_KAFKA_EVENT_QUEUED
#define N_KAFKA_EVENT_QUEUED 0
state of a queued event
Definition at line 55 of file n_kafka.h.
N_KAFKA_EVENT_WAITING_ACK
#define N_KAFKA_EVENT_WAITING_ACK 1
state of a sent event waiting for acknowledgement
Definition at line 57 of file n_kafka.h.
Function Documentation
n_kafka_add_header()
int n_kafka_add_header (N_KAFKA_EVENT * event, N_STR * key, N_STR * value)
add a header to an event
add a header to an event
headers array must have been allocated before
Parameters
event target event
key N_STR *string of the key
value N_STR *string of the value
Returns
TRUE or FALSE
Definition at line 853 of file n_kafka.c.
References __n_assert, N_STR::data, key, n_kafka_add_header_ex(), and N_STR::written.
n_kafka_add_header_ex()
int n_kafka_add_header_ex (N_KAFKA_EVENT * event, char * key, size_t key_length, char * value, size_t value_length)
add a header to an event (extended version)
add a header to an event (extended version)
headers array must have been allocated before
Parameters
event target event
key string of the key
key_length size of the key string
value string of the value
value_length size of the value string
Returns
TRUE or FALSE
Definition at line 819 of file n_kafka.c.
References __n_assert, key, LOG_ERR, n_kafka_event_fdesc(), n_log, and N_KAFKA_EVENT::rd_kafka_headers.
Referenced by n_kafka_add_header().
n_kafka_delete()
void n_kafka_delete (N_KAFKA * kafka)
delete a kafka handle
delete a kafka handle
Parameters
kafka N_KAFKA handle to delete
Definition at line 343 of file n_kafka.c.
References __n_assert, bootstrap_servers, configuration, errstr, event_cmd, events_to_send, Free, free_nstr, free_split_result(), FreeNoLog, groupid, list_destroy(), LOG_DEBUG, mode, n_kafka_stop_polling_thread(), n_log, poll_timeout, rd_kafka_conf, rd_kafka_handle, rd_kafka_topic, received_events, rw_lock_destroy, rwlock, sended_dir, subscription, topic, topics, and tosend_dir.
Referenced by main(), n_kafka_load_config(), and n_kafka_new().
n_kafka_disable_event_consumption()
int n_kafka_disable_event_consumption (N_KAFKA * kafka)
disable event consumption
Parameters
kafka the N_KAFKA instance
Returns
TRUE or FALSE
Definition at line 1400 of file n_kafka.c.
References __n_assert, event_consumption_enabled, rwlock, unlock, and write_lock.
Referenced by n_kafka_stop_polling_thread().
n_kafka_disable_event_production()
int n_kafka_disable_event_production (N_KAFKA * kafka)
disable event production
Parameters
kafka the N_KAFKA instance
Returns
TRUE or FALSE
Definition at line 1426 of file n_kafka.c.
References __n_assert, event_production_enabled, rwlock, unlock, and write_lock.
n_kafka_dump_unprocessed()
int n_kafka_dump_unprocessed (N_KAFKA * kafka, char * directory)
dump unprocessed events to a directory
dump unprocessed events to a directory
Parameters
kafka kafka handle to use
directory the directory in which to dump the events
Returns
TRUE or FALSE
Definition at line 1440 of file n_kafka.c.
References __n_assert, _nstr, N_STR::data, events_to_send, free_nstr, N_STR::length, list_foreach, LOG_DEBUG, LOG_ERR, Malloc, n_kafka_event_fdesc(), N_KAFKA_EVENT_OK, n_log, nb_error, nb_queued, nb_waiting, nstr_to_file(), nstrprintf, polling_thread_status, read_lock, rwlock, topic, unlock, and N_STR::written.
Referenced by main().
n_kafka_enable_event_consumption()
int n_kafka_enable_event_consumption (N_KAFKA * kafka)
enable event consumption
Parameters
kafka the N_KAFKA instance
Returns
TRUE or FALSE
Definition at line 1387 of file n_kafka.c.
References __n_assert, event_consumption_enabled, rwlock, unlock, and write_lock.
n_kafka_enable_event_production()
int n_kafka_enable_event_production (N_KAFKA * kafka)
enable event production
Parameters
kafka the N_KAFKA instance
Returns
TRUE or FALSE
Definition at line 1413 of file n_kafka.c.
References __n_assert, event_production_enabled, rwlock, unlock, and write_lock.
n_kafka_event_destroy()
int n_kafka_event_destroy (N_KAFKA_EVENT ** event)
destroy a kafka event
destroy a kafka event
Parameters
event event to delete
Returns
TRUE or FALSE
Definition at line 1042 of file n_kafka.c.
References __n_assert, and n_kafka_event_destroy_ptr().
Referenced by main(), and n_kafka_poll().
n_kafka_event_destroy_ptr()
void n_kafka_event_destroy_ptr (void * event_ptr)
destroy a kafka event (void pointer version for list destructor)
destroy a kafka event (void pointer version for list destructor)
Parameters
event_ptr void pointer to target
Definition at line 1014 of file n_kafka.c.
References __n_assert, free_nstr, FreeNoLog, and list_destroy().
Referenced by n_kafka_event_destroy(), n_kafka_poll(), and n_kafka_produce().
n_kafka_get_event()
N_KAFKA_EVENT * n_kafka_get_event (N_KAFKA * kafka)
get the next received event
get the next received event
Parameters
kafka kafka handle to use
Returns
a received event ror NULL
Definition at line 1514 of file n_kafka.c.
References __n_assert, received_events, remove_list_node, rwlock, LIST::start, unlock, and write_lock.
Referenced by main().
n_kafka_get_schema_from_char()
int32_t n_kafka_get_schema_from_char (const char * string)
get schema id from a char string
get schema id from a char string
Parameters
string char *source from where to read schema id
Returns
zero or positive number on success, -1 on error
Definition at line 150 of file n_kafka.c.
References __n_assert.
Referenced by n_kafka_get_schema_from_nstr().
n_kafka_get_schema_from_nstr()
int32_t n_kafka_get_schema_from_nstr (const N_STR * string)
get schema id from an N_STR string
get schema id from an N_STR string
Parameters
string N_STR *source from where to read schema id
Returns
zero or positive number on success, -1 on error
Definition at line 164 of file n_kafka.c.
References __n_assert, N_STR::data, n_kafka_get_schema_from_char(), and N_STR::written.
Referenced by n_kafka_poll().
n_kafka_get_status()
int n_kafka_get_status (N_KAFKA * kafka, size_t * nb_queued, size_t * nb_waiting, size_t * nb_error)
get kafka queue status counters
get kafka queue status counters
Parameters
kafka handler to use
nb_queued pointer to queue number holder
nb_waiting pointer to waiting number holder
nb_error pointer to error number holder
Returns
TRUE or FALSE
Definition at line 205 of file n_kafka.c.
References __n_assert, nb_error, nb_queued, nb_waiting, polling_thread_status, read_lock, rwlock, and unlock.
Referenced by main().
n_kafka_load_config()
N_KAFKA * n_kafka_load_config (char * config_file, int mode)
load kafka configuration from file
load kafka configuration from file
Parameters
config_file path and filename of the config file
mode RD_KAFKA_CONSUMER or RD_KAFKA_PRODUCER
Returns
an allocated and configured N_KAFKA *kafka handle or NULL
Definition at line 462 of file n_kafka.c.
References __n_assert, _nstr, _nstrp, _str, bootstrap_servers, config_file, N_STR::data, errstr, event_cmd, file_to_nstr(), free_nstr, get_computer_name(), groupid, is_transactional, join(), N_STR::length, LOG_DEBUG, LOG_ERR, mode, mode, monitored_directory_interval, n_kafka_delete(), n_kafka_delivery_message_callback(), n_kafka_new(), n_log, new_nstr(), nstrprintf, poll_interval, poll_timeout, rd_kafka_conf, rd_kafka_handle, rd_kafka_topic, schema_id, split(), split_count(), subscription, topic, and topics.
Referenced by main().
n_kafka_load_unprocessed()
int n_kafka_load_unprocessed (N_KAFKA * kafka, const char * directory)
load unprocessed events from a directory
load unprocessed events from a directory
Parameters
kafka kafka handle to use
directory the directory from which to load the events
Returns
TRUE or FALSE
Definition at line 1496 of file n_kafka.c.
References __n_assert, rwlock, unlock, and write_lock.
n_kafka_new()
N_KAFKA * n_kafka_new (int32_t poll_timeout, int32_t poll_interval, size_t errstr_len)
create a new kafka handle
create a new kafka handle
Parameters
poll_interval set polling interval
poll_timeout set polling
errstr_len set the size of the error string buffer
Returns
a new empty N_KAFKA *kafka handle or NULL
Definition at line 406 of file n_kafka.c.
References __n_assert, bootstrap_servers, configuration, error_timeout, errstr, event_cmd, event_consumption_enabled, event_production_enabled, events_to_send, Free, groupid, init_lock, is_transactional, LOG_ERR, Malloc, MAX_LIST_ITEMS, mode, monitored_directory_interval, n_kafka_delete(), n_log, nb_error, nb_queued, nb_waiting, new_generic_list(), new_nstr(), poll_interval, poll_timeout, polling_thread_status, rd_kafka_conf, rd_kafka_handle, received_events, rwlock, schema_id, sended_dir, subscription, topic, topics, and tosend_dir.
Referenced by n_kafka_load_config().
n_kafka_new_event()
N_KAFKA_EVENT * n_kafka_new_event (int schema_id)
create a new empty kafka event
create a new empty kafka event
Parameters
schema_id schema id that the event is using, -1 if not using avro schema_id formatted events
Returns
a new empty N_KAFKA_EVENT *event
Definition at line 770 of file n_kafka.c.
References __n_assert, Malloc, and N_KAFKA_EVENT_CREATED.
Referenced by n_kafka_new_event_from_char().
n_kafka_new_event_from_char()
N_KAFKA_EVENT * n_kafka_new_event_from_char (const char * string, size_t written, int schema_id)
create a new kafka event from a char string
create a new kafka event from a char string
Parameters
string source string
written lenght of the string
schema_id the schema id to use. Pass -1 for non avro formatted events
Returns
a new N_KAFKA *event or NULL
Definition at line 945 of file n_kafka.c.
References __n_assert, Malloc, N_KAFKA_EVENT_QUEUED, n_kafka_new_event(), and n_kafka_put_schema_in_nstr().
Referenced by main(), n_kafka_new_event_from_string(), and n_kafka_poll().
n_kafka_new_event_from_file()
N_KAFKA_EVENT * n_kafka_new_event_from_file (char * filename, int schema_id)
create a new kafka event from a file
create a new kafka event from a file
Parameters
filename source file path and filename
schema_id the schema id to use. Pass -1 for non avro formatted events
Returns
a new N_KAFKA *event or NULL
Definition at line 998 of file n_kafka.c.
References __n_assert, file_to_nstr(), free_nstr, and n_kafka_new_event_from_string().
Referenced by main().
n_kafka_new_event_from_string()
N_KAFKA_EVENT * n_kafka_new_event_from_string (const N_STR * string, int schema_id)
create a new kafka event from an N_STR string
create a new kafka event from an N_STR string
Parameters
string source string
schema_id the schema id to use. Pass -1 for non avro formatted events
Returns
a new N_KAFKA *event or NULL
Definition at line 983 of file n_kafka.c.
References __n_assert, N_STR::data, n_kafka_new_event_from_char(), and N_STR::written.
Referenced by n_kafka_new_event_from_file().
n_kafka_new_headers()
int n_kafka_new_headers (N_KAFKA_EVENT * event, size_t count)
create new headers for an event
create new headers for an event
Parameters
event target event
count size in elements of the created headers array
Returns
TRUE or FALSE
Definition at line 794 of file n_kafka.c.
References __n_assert, LOG_ERR, n_kafka_event_fdesc(), n_log, and N_KAFKA_EVENT::rd_kafka_headers.
n_kafka_poll()
int n_kafka_poll (N_KAFKA * kafka)
poll kafka for events
poll kafka for events
Parameters
kafka kafka handle to use
Returns
TRUE or FALSE
Definition at line 1054 of file n_kafka.c.
References __n_assert, _str, error_timeout, event_consumption_enabled, event_production_enabled, events_to_send, free_nstr_ptr(), is_transactional, list_push(), LOG_DEBUG, LOG_ERR, LOG_INFO, MAX_LIST_ITEMS, mode, n_kafka_event_destroy(), n_kafka_event_destroy_ptr(), N_KAFKA_EVENT_ERROR, n_kafka_event_fdesc(), N_KAFKA_EVENT_OK, N_KAFKA_EVENT_QUEUED, n_kafka_get_schema_from_nstr(), n_kafka_new_event_from_char(), n_kafka_produce_ex(), n_log, nb_error, nb_queued, nb_waiting, new_generic_list(), LIST_NODE::next, nstrprintf, poll_interval, LIST_NODE::ptr, rd_kafka_handle, read_lock, received_events, remove_list_node, rwlock, schema_id, LIST::start, topic, unlock, and write_lock.
Referenced by n_kafka_polling_thread().
n_kafka_produce()
int n_kafka_produce (N_KAFKA * kafka, N_KAFKA_EVENT * event)
produce a kafka event
produce a kafka event
Parameters
kafka the producer N_KAFKA handle to use
event event to send. Will be owned by N_KAFKA *kafka handle once done
Returns
TRUE or FALSE
Definition at line 869 of file n_kafka.c.
References __n_assert, events_to_send, list_push(), LOG_DEBUG, n_kafka_event_destroy_ptr(), n_kafka_event_fdesc(), n_log, nb_queued, rd_kafka_handle, rwlock, topic, unlock, and write_lock.
Referenced by main().
n_kafka_put_schema_in_char()
int n_kafka_put_schema_in_char (char * string, int schema_id)
put schema id in a char string
put schema id in a char string
Parameters
string char *destination where to write schema id
schema_id the schema_id to write
Returns
zero or positive number on success, -1 on error
Definition at line 177 of file n_kafka.c.
References __n_assert.
Referenced by n_kafka_put_schema_in_nstr().
n_kafka_put_schema_in_nstr()
int n_kafka_put_schema_in_nstr (N_STR * string, int schema_id)
put schema id in an N_STR string
put schema id in an N_STR string
Parameters
string N_STR *destination where to write schema id
schema_id the schema_id to write
Returns
zero or positive number on success, -1 on error
Definition at line 190 of file n_kafka.c.
References __n_assert, N_STR::data, n_kafka_put_schema_in_char(), and N_STR::written.
Referenced by n_kafka_new_event_from_char().
n_kafka_set_error_timeout()
int n_kafka_set_error_timeout (N_KAFKA * kafka, int32_t error_timeout)
set the retry interval (in seconds) for errored events.
0 disables retries.
set the retry interval (in seconds) for errored events.
Parameters
kafka handler to configure
error_timeout seconds to wait before re-queuing an errored event; 0 disables retries (default)
Returns
TRUE or FALSE
Definition at line 224 of file n_kafka.c.
References __n_assert, error_timeout, LOG_ERR, n_log, rwlock, unlock, and write_lock.
n_kafka_set_sended_dir()
int n_kafka_set_sended_dir (N_KAFKA * kafka, const char * tosend_dir, const char * sended_dir)
set the 'to-send' and 'sended' base directories used to move acknowledged event files instead of deleting them
set the 'to-send' and 'sended' base directories used to move acknowledged event files instead of deleting them
Parameters
kafka handler to configure
tosend_dir base directory the event files are read from; used to compute the subpath to preserve. Can be NULL (then only the basename is preserved)
sended_dir base directory acknowledged event files are moved into. NULL restores the legacy delete-on-ack behaviour
Returns
TRUE or FALSE
Definition at line 243 of file n_kafka.c.
References __n_assert, FreeNoLog, rwlock, sended_dir, tosend_dir, unlock, and write_lock.
n_kafka_start_polling_thread()
int n_kafka_start_polling_thread (N_KAFKA * kafka)
start the kafka polling thread
start the kafka polling thread
Parameters
kafka kafka handle to use
Returns
TRUE or FALSE
Definition at line 1309 of file n_kafka.c.
References __n_assert, LOG_DEBUG, LOG_ERR, n_kafka_polling_thread(), n_log, polling_thread, polling_thread_status, rd_kafka_handle, read_lock, rwlock, unlock, and write_lock.
Referenced by main().
n_kafka_stop_polling_thread()
int n_kafka_stop_polling_thread (N_KAFKA * kafka)
stop the kafka polling thread
stop the kafka polling thread
Parameters
kafka target kafka handle
Returns
TRUE or FALSE
Definition at line 1341 of file n_kafka.c.
References __n_assert, LOG_DEBUG, LOG_ERR, mode, n_kafka_disable_event_consumption(), n_log, polling_thread, polling_thread_status, rd_kafka_handle, read_lock, rwlock, unlock, and write_lock.
Referenced by n_kafka_delete().