Nilorea Library: ZLIB: shortcuts to easy compress/decompress data
ZLIB: shortcuts to easy compress/decompress data
Functions
size_t CompressData (unsigned char *abSrc, size_t nLenSrc, unsigned char *abDst, size_t nLenDst)
Compress a string to another.
size_t GetMaxCompressedLen (size_t nLenSrc)
Return the maximum compressed size.
size_t UncompressData (unsigned char *abSrc, size_t nLenSrc, unsigned char *abDst, size_t nLenDst)
Uncompress a string to another.
N_STR * unzip_nstr (N_STR *src)
Return an uncompressed version of src.
N_STR * zip_nstr (N_STR *src)
Return a compressed version of src.
Detailed Description
Function Documentation
CompressData()
size_t CompressData (unsigned char * abSrc, size_t nLenSrc, unsigned char * abDst, size_t nLenDst)
Compress a string to another.
Parameters
abSrc source string
nLenSrc size of source string
abDst destination string
nLenDst destination length
Returns
0 or length of output
Definition at line 54 of file n_zlib.c.
References __n_assert, LOG_ERR, and n_log.
Referenced by main(), and zip_nstr().
GetMaxCompressedLen()
size_t GetMaxCompressedLen (size_t nLenSrc)
Return the maximum compressed size.
Parameters
nLenSrc The uncompressed source data length in bytes
Returns
The size in bytes
Definition at line 41 of file n_zlib.c.
Referenced by main(), and zip_nstr().
UncompressData()
size_t UncompressData (unsigned char * abSrc, size_t nLenSrc, unsigned char * abDst, size_t nLenDst)
Uncompress a string to another.
Parameters
abSrc source string
nLenSrc size of source string
abDst destination string
nLenDst destination length
Returns
0 or length of output
Definition at line 111 of file n_zlib.c.
References __n_assert, LOG_ERR, and n_log.
Referenced by main(), and unzip_nstr().
unzip_nstr()
N_STR * unzip_nstr (N_STR * src)
Return an uncompressed version of src.
Return an uncompressed version of src.
Parameters
src The source string
Returns
The uncompressed string or NULL
Definition at line 216 of file n_zlib.c.
References __n_assert, N_STR::data, free_nstr, N_STR::length, LOG_DEBUG, LOG_ERR, n_log, new_nstr(), UncompressData(), and N_STR::written.
Referenced by main(), and netw_recv_func().
zip_nstr()
N_STR * zip_nstr (N_STR * src)
Return a compressed version of src.
Return a compressed version of src.
Parameters
src The source string
Returns
The compressed string or NULL
Definition at line 165 of file n_zlib.c.
References __n_assert, CompressData(), N_STR::data, free_nstr, GetMaxCompressedLen(), N_STR::length, LOG_DEBUG, LOG_ERR, n_log, new_nstr(), and N_STR::written.
Referenced by main(), and netw_send_func().