var searchData=
[
  ['c_20style_20try_20catch_20endtry_20throw_0',['EXCEPTIONS: C++ style try,catch,endtry,throw',['../group___e_x_c_e_p_t_i_o_n_s.html',1,'']]],
  ['catch_20endtry_20throw_1',['EXCEPTIONS: C++ style try,catch,endtry,throw',['../group___e_x_c_e_p_t_i_o_n_s.html',1,'']]],
  ['certificate_20authority_20and_20per_20host_20leaf_20minting_2',['X509: certificate authority and per-host leaf minting',['../group___n___x509.html',1,'']]],
  ['char_20strings_20with_20dynamic_20resizing_20and_20boundary_20checking_3',['STRINGS: replacement to char *strings with dynamic resizing and boundary checking',['../group___n___s_t_r.html',1,'']]],
  ['checking_4',['STRINGS: replacement to char *strings with dynamic resizing and boundary checking',['../group___n___s_t_r.html',1,'']]],
  ['cjson_5',['JSON: a thin public wrapper over cJSON',['../group___n___j_s_o_n.html',1,'']]],
  ['classic_20config_20file_20loading_20saving_6',['CONFIGURATIONS: classic config file loading/saving',['../group___c_o_n_f_i_g_f_i_l_e.html',1,'']]],
  ['classic_20or_20trie_20tree_20hash_5ftables_7',['HASH TABLES: classic or trie tree hash_tables',['../group___h_a_s_h___t_a_b_l_e.html',1,'']]],
  ['clean_20enum_20macro_20set_8',['ENUMERATIONS: quick and clean enum macro set',['../group___e_n_u_m_s.html',1,'']]],
  ['client_20over_20quic_9',['HTTP3: minimal blocking HTTP/3 client over QUIC',['../group___n___h_t_t_p3.html',1,'']]],
  ['client_20server_20clock_20offset_20estimation_10',['CLOCK_SYNC: client/server clock offset estimation',['../group___c_l_o_c_k___s_y_n_c.html',1,'']]],
  ['clock_20offset_20estimation_11',['CLOCK_SYNC: client/server clock offset estimation',['../group___c_l_o_c_k___s_y_n_c.html',1,'']]],
  ['clock_5fsync_3a_20client_20server_20clock_20offset_20estimation_12',['CLOCK_SYNC: client/server clock offset estimation',['../group___c_l_o_c_k___s_y_n_c.html',1,'']]],
  ['combination_20of_20a_20question_20and_20an_20answer_13',['CYPHERS: VIGENERE (encode / decode) a (N_STR / file) with a root key or a combination of a question and an answer',['../group___c_y_p_h_e_r___v_i_g_e_n_e_r_e.html',1,'']]],
  ['commons_3a_20macros_20headers_20defines_20timers_20allocators_14',['COMMONS: macros, headers, defines, timers, allocators,...',['../group___c_o_m_m_o_n_s.html',1,'']]],
  ['communications_15',['NETWORK ENGINE: connect, accept, send and recv wrappers. Network Queue, thread-safe add/get message, ssl/tls secured communications',['../group___n_e_t_w_o_r_k_i_n_g.html',1,'']]],
  ['compress_20decompress_20data_16',['compress decompress data',['../group___l_z4.html',1,'LZ4: shortcuts to easy compress/decompress data'],['../group___z_l_i_b.html',1,'ZLIB: shortcuts to easy compress/decompress data']]],
  ['config_20file_20loading_20saving_17',['CONFIGURATIONS: classic config file loading/saving',['../group___c_o_n_f_i_g_f_i_l_e.html',1,'']]],
  ['configurations_3a_20classic_20config_20file_20loading_20saving_18',['CONFIGURATIONS: classic config file loading/saving',['../group___c_o_n_f_i_g_f_i_l_e.html',1,'']]],
  ['connect_20accept_20send_20and_20recv_20wrappers_20network_20queue_20thread_20safe_20add_20get_20message_20ssl_20tls_20secured_20communications_19',['NETWORK ENGINE: connect, accept, send and recv wrappers. Network Queue, thread-safe add/get message, ssl/tls secured communications',['../group___n_e_t_w_o_r_k_i_n_g.html',1,'']]],
  ['connection_20handling_20',['ACCEPT_POOL: parallel accept pool for high-performance connection handling',['../group___a_c_c_e_p_t___p_o_o_l.html',1,'']]],
  ['console_20to_20file_20to_20syslog_21',['LOGGING NODUP: no duplicate logging to console, to file, to syslog',['../group___l_o_g_n_o_d_u_p.html',1,'']]],
  ['console_20to_20file_20to_20syslog_20to_20event_20log_22',['LOGGING: logging to console, to file, to syslog, to event log',['../group___l_o_g.html',1,'']]],
  ['consumer_20functions_23',['KAFKA: generic event producer and consumer functions',['../group___n___k_a_f_k_a.html',1,'']]],
  ['convergence_20blending_24',['DEAD_RECKONING: latency hiding with extrapolation and convergence blending',['../group___d_e_a_d___r_e_c_k_o_n_i_n_g.html',1,'']]],
  ['conversion_25',['AVRO: binary format encoding/decoding with JSON conversion',['../group___a_v_r_o.html',1,'']]],
  ['cookie_20jar_26',['COOKIES: domain-aware HTTP cookie jar',['../group___n___c_o_o_k_i_e_s.html',1,'']]],
  ['cookies_3a_20domain_20aware_20http_20cookie_20jar_27',['COOKIES: domain-aware HTTP cookie jar',['../group___n___c_o_o_k_i_e_s.html',1,'']]],
  ['create_20and_20manage_20a_20thread_20pool_28',['THREADS: tools to create and manage a thread pool',['../group___t_h_r_e_a_d_s.html',1,'']]],
  ['cryptographically_20secure_20random_20helpers_29',['RANDOM: cryptographically secure random helpers',['../group___n___r_a_n_d_o_m.html',1,'']]],
  ['cubic_20hermite_20spline_20dead_20reckoning_20and_20movement_20simulation_20for_202d_203d_30',['TRAJECTORY: cubic Hermite spline dead reckoning and movement simulation for 2D/3D',['../group___t_r_a_j_e_c_t_o_r_y.html',1,'']]],
  ['cyphers_3a_20base64_20encode_20decode_20from_20to_20a_20n_5fstr_20string_31',['CYPHERS: BASE64 (encode / decode) (from / to) a N_STR *string',['../group___c_y_p_h_e_r___b_a_s_e64.html',1,'']]],
  ['cyphers_3a_20vigenere_20encode_20decode_20a_20n_5fstr_20file_20with_20a_20root_20key_20or_20a_20combination_20of_20a_20question_20and_20an_20answer_32',['CYPHERS: VIGENERE (encode / decode) a (N_STR / file) with a root key or a combination of a question and an answer',['../group___c_y_p_h_e_r___v_i_g_e_n_e_r_e.html',1,'']]]
];
