var searchData=
[
  ['a_20n_5fstr_20file_20with_20a_20root_20key_20or_20a_20combination_20of_20a_20question_20and_20an_20answer_0',['CYPHERS: VIGENERE (encode / decode) a (N_STR / file) with a root key or a combination of a question and an answer',['../group___c_y_p_h_e_r___v_i_g_e_n_e_r_e.html',1,'']]],
  ['a_20n_5fstr_20string_1',['CYPHERS: BASE64 (encode / decode) (from / to) a N_STR *string',['../group___c_y_p_h_e_r___b_a_s_e64.html',1,'']]],
  ['a_20pathfinding_20for_202d_203d_20grids_2',['ASTAR: A* pathfinding for 2D/3D grids',['../group___a_s_t_a_r.html',1,'']]],
  ['a_20record_20response_3',['DNS: minimal query parse and A-record response',['../group___n___d_n_s.html',1,'']]],
  ['a_20single_20n_5fstr_20message_4',['NETWORK MESSAGES: tools to serialize integers, double, N_STR from and back to a single N_STR *message',['../group___n_e_t_w_o_r_k___m_s_g.html',1,'']]],
  ['a_20small_20boolean_20field_20query_20language_5',['QUERY: a small boolean field-query language',['../group___n___q_u_e_r_y.html',1,'']]],
  ['a_20thin_20public_20wrapper_20over_20cjson_6',['JSON: a thin public wrapper over cJSON',['../group___n___j_s_o_n.html',1,'']]],
  ['a_20thread_20pool_7',['THREADS: tools to create and manage a thread pool',['../group___t_h_r_e_a_d_s.html',1,'']]],
  ['aabb3d_3a_20simple_20space_20area_20management_20api_8',['AABB3D: simple space area management API',['../group___a_a_b_b3_d.html',1,'']]],
  ['accept_20pool_20for_20high_20performance_20connection_20handling_9',['ACCEPT_POOL: parallel accept pool for high-performance connection handling',['../group___a_c_c_e_p_t___p_o_o_l.html',1,'']]],
  ['accept_20send_20and_20recv_20wrappers_20network_20queue_20thread_20safe_20add_20get_20message_20ssl_20tls_20secured_20communications_10',['NETWORK ENGINE: connect, accept, send and recv wrappers. Network Queue, thread-safe add/get message, ssl/tls secured communications',['../group___n_e_t_w_o_r_k_i_n_g.html',1,'']]],
  ['accept_5fpool_3a_20parallel_20accept_20pool_20for_20high_20performance_20connection_20handling_11',['ACCEPT_POOL: parallel accept pool for high-performance connection handling',['../group___a_c_c_e_p_t___p_o_o_l.html',1,'']]],
  ['add_20get_20message_20ssl_20tls_20secured_20communications_12',['NETWORK ENGINE: connect, accept, send and recv wrappers. Network Queue, thread-safe add/get message, ssl/tls secured communications',['../group___n_e_t_w_o_r_k_i_n_g.html',1,'']]],
  ['allegro_205_20helpers_20user_20input_13',['ALLEGRO5: allegro 5 helpers (user input,...)',['../group___a_l_l_e_g_r_o5.html',1,'']]],
  ['allegro5_20widget_20system_20with_20pseudo_20windows_14',['GUI: allegro5 widget system with pseudo-windows',['../group___g_u_i.html',1,'']]],
  ['allegro5_3a_20allegro_205_20helpers_20user_20input_15',['ALLEGRO5: allegro 5 helpers (user input,...)',['../group___a_l_l_e_g_r_o5.html',1,'']]],
  ['allocators_16',['allocators',['../group___c_o_m_m_o_n_s.html',1,'COMMONS: macros, headers, defines, timers, allocators,...'],['../group___n___t_i_m_e.html',1,'TIMERS: generally used headers, defines, timers, allocators,...']]],
  ['an_20answer_17',['CYPHERS: VIGENERE (encode / decode) a (N_STR / file) with a root key or a combination of a question and an answer',['../group___c_y_p_h_e_r___v_i_g_e_n_e_r_e.html',1,'']]],
  ['and_20a_20record_20response_18',['DNS: minimal query parse and A-record response',['../group___n___d_n_s.html',1,'']]],
  ['and_20an_20answer_19',['CYPHERS: VIGENERE (encode / decode) a (N_STR / file) with a root key or a combination of a question and an answer',['../group___c_y_p_h_e_r___v_i_g_e_n_e_r_e.html',1,'']]],
  ['and_20back_20to_20a_20single_20n_5fstr_20message_20',['NETWORK MESSAGES: tools to serialize integers, double, N_STR from and back to a single N_STR *message',['../group___n_e_t_w_o_r_k___m_s_g.html',1,'']]],
  ['and_20blit_20funcs_21',['GRAPHICS: animation library, loading structures and blit funcs',['../group___a_n_i_m___l_i_b.html',1,'']]],
  ['and_20boundary_20checking_22',['STRINGS: replacement to char *strings with dynamic resizing and boundary checking',['../group___n___s_t_r.html',1,'']]],
  ['and_20clean_20enum_20macro_20set_23',['ENUMERATIONS: quick and clean enum macro set',['../group___e_n_u_m_s.html',1,'']]],
  ['and_20consumer_20functions_24',['KAFKA: generic event producer and consumer functions',['../group___n___k_a_f_k_a.html',1,'']]],
  ['and_20convergence_20blending_25',['DEAD_RECKONING: latency hiding with extrapolation and convergence blending',['../group___d_e_a_d___r_e_c_k_o_n_i_n_g.html',1,'']]],
  ['and_20decode_26',['HEX: hexadecimal encode and decode',['../group___n___h_e_x.html',1,'']]],
  ['and_20hmac_27',['DIGEST: message digests and HMAC',['../group___n___d_i_g_e_s_t.html',1,'']]],
  ['and_20javascript_20text_20for_20display_28',['PRETTY: reformat JSON, XML/HTML and JavaScript text for display',['../group___n___p_r_e_t_t_y.html',1,'']]],
  ['and_20manage_20a_20thread_20pool_29',['THREADS: tools to create and manage a thread pool',['../group___t_h_r_e_a_d_s.html',1,'']]],
  ['and_20movement_20simulation_20for_202d_203d_30',['TRAJECTORY: cubic Hermite spline dead reckoning and movement simulation for 2D/3D',['../group___t_r_a_j_e_c_t_o_r_y.html',1,'']]],
  ['and_20per_20host_20leaf_20minting_31',['X509: certificate authority and per-host leaf minting',['../group___n___x509.html',1,'']]],
  ['and_20recv_20wrappers_20network_20queue_20thread_20safe_20add_20get_20message_20ssl_20tls_20secured_20communications_32',['NETWORK ENGINE: connect, accept, send and recv wrappers. Network Queue, thread-safe add/get message, ssl/tls secured communications',['../group___n_e_t_w_o_r_k_i_n_g.html',1,'']]],
  ['and_20stack_20printing_33',['SIGNALS: signals handling and stack printing',['../group___s_i_g_n_a_l_s.html',1,'']]],
  ['animation_20library_20loading_20structures_20and_20blit_20funcs_34',['GRAPHICS: animation library, loading structures and blit funcs',['../group___a_n_i_m___l_i_b.html',1,'']]],
  ['answer_35',['CYPHERS: VIGENERE (encode / decode) a (N_STR / file) with a root key or a combination of a question and an answer',['../group___c_y_p_h_e_r___v_i_g_e_n_e_r_e.html',1,'']]],
  ['api_36',['AABB3D: simple space area management API',['../group___a_a_b_b3_d.html',1,'']]],
  ['apps_3a_20game_20environment_20management_20utilities_37',['GAME APPS: game environment management utilities',['../group___g_a_m_e___e_n_v.html',1,'']]],
  ['area_20management_20api_38',['AABB3D: simple space area management API',['../group___a_a_b_b3_d.html',1,'']]],
  ['astar_3a_20a_20pathfinding_20for_202d_203d_20grids_39',['ASTAR: A* pathfinding for 2D/3D grids',['../group___a_s_t_a_r.html',1,'']]],
  ['authority_20and_20per_20host_20leaf_20minting_40',['X509: certificate authority and per-host leaf minting',['../group___n___x509.html',1,'']]],
  ['avro_3a_20binary_20format_20encoding_20decoding_20with_20json_20conversion_41',['AVRO: binary format encoding/decoding with JSON conversion',['../group___a_v_r_o.html',1,'']]],
  ['aware_20http_20cookie_20jar_42',['COOKIES: domain-aware HTTP cookie jar',['../group___n___c_o_o_k_i_e_s.html',1,'']]]
];
