var searchData=
[
  ['tables_3a_20classic_20or_20trie_20tree_20hash_5ftables_0',['HASH TABLES: classic or trie tree hash_tables',['../group___h_a_s_h___t_a_b_l_e.html',1,'']]],
  ['text_20for_20display_1',['PRETTY: reformat JSON, XML/HTML and JavaScript text for display',['../group___n___p_r_e_t_t_y.html',1,'']]],
  ['thin_20public_20wrapper_20over_20cjson_2',['JSON: a thin public wrapper over cJSON',['../group___n___j_s_o_n.html',1,'']]],
  ['thread_20pool_3',['THREADS: tools to create and manage a thread pool',['../group___t_h_r_e_a_d_s.html',1,'']]],
  ['thread_20safe_20add_20get_20message_20ssl_20tls_20secured_20communications_4',['NETWORK ENGINE: connect, accept, send and recv wrappers. Network Queue, thread-safe add/get message, ssl/tls secured communications',['../group___n_e_t_w_o_r_k_i_n_g.html',1,'']]],
  ['threads_3a_20tools_20to_20create_20and_20manage_20a_20thread_20pool_5',['THREADS: tools to create and manage a thread pool',['../group___t_h_r_e_a_d_s.html',1,'']]],
  ['throw_6',['EXCEPTIONS: C++ style try,catch,endtry,throw',['../group___e_x_c_e_p_t_i_o_n_s.html',1,'']]],
  ['tiles_7',['GRAPHICS: isometric engine, maps, tiles, ...',['../group___i_s_o_m_e_t_r_i_c___e_n_g_i_n_e.html',1,'']]],
  ['timers_20allocators_8',['timers allocators',['../group___c_o_m_m_o_n_s.html',1,'COMMONS: macros, headers, defines, timers, allocators,...'],['../group___n___t_i_m_e.html',1,'TIMERS: generally used headers, defines, timers, allocators,...']]],
  ['timers_3a_20generally_20used_20headers_20defines_20timers_20allocators_9',['TIMERS: generally used headers, defines, timers, allocators,...',['../group___n___t_i_m_e.html',1,'']]],
  ['tls_20secured_20communications_10',['NETWORK ENGINE: connect, accept, send and recv wrappers. Network Queue, thread-safe add/get message, ssl/tls secured communications',['../group___n_e_t_w_o_r_k_i_n_g.html',1,'']]],
  ['to_20a_20n_5fstr_20string_11',['CYPHERS: BASE64 (encode / decode) (from / to) a N_STR *string',['../group___c_y_p_h_e_r___b_a_s_e64.html',1,'']]],
  ['to_20char_20strings_20with_20dynamic_20resizing_20and_20boundary_20checking_12',['STRINGS: replacement to char *strings with dynamic resizing and boundary checking',['../group___n___s_t_r.html',1,'']]],
  ['to_20console_20to_20file_20to_20syslog_13',['LOGGING NODUP: no duplicate logging to console, to file, to syslog',['../group___l_o_g_n_o_d_u_p.html',1,'']]],
  ['to_20console_20to_20file_20to_20syslog_20to_20event_20log_14',['LOGGING: logging to console, to file, to syslog, to event log',['../group___l_o_g.html',1,'']]],
  ['to_20create_20and_20manage_20a_20thread_20pool_15',['THREADS: tools to create and manage a thread pool',['../group___t_h_r_e_a_d_s.html',1,'']]],
  ['to_20easy_20compress_20decompress_20data_16',['to easy compress decompress data',['../group___l_z4.html',1,'LZ4: shortcuts to easy compress/decompress data'],['../group___z_l_i_b.html',1,'ZLIB: shortcuts to easy compress/decompress data']]],
  ['to_20serialize_20integers_20double_20n_5fstr_20from_20and_20back_20to_20a_20single_20n_5fstr_20message_17',['NETWORK MESSAGES: tools to serialize integers, double, N_STR from and back to a single N_STR *message',['../group___n_e_t_w_o_r_k___m_s_g.html',1,'']]],
  ['tools_20to_20create_20and_20manage_20a_20thread_20pool_18',['THREADS: tools to create and manage a thread pool',['../group___t_h_r_e_a_d_s.html',1,'']]],
  ['tools_20to_20serialize_20integers_20double_20n_5fstr_20from_20and_20back_20to_20a_20single_20n_5fstr_20message_19',['NETWORK MESSAGES: tools to serialize integers, double, N_STR from and back to a single N_STR *message',['../group___n_e_t_w_o_r_k___m_s_g.html',1,'']]],
  ['trajectory_3a_20cubic_20hermite_20spline_20dead_20reckoning_20and_20movement_20simulation_20for_202d_203d_20',['TRAJECTORY: cubic Hermite spline dead reckoning and movement simulation for 2D/3D',['../group___t_r_a_j_e_c_t_o_r_y.html',1,'']]],
  ['tree_20hash_5ftables_21',['HASH TABLES: classic or trie tree hash_tables',['../group___h_a_s_h___t_a_b_l_e.html',1,'']]],
  ['tree_20with_20generic_20support_22',['TREE: various tree with generic support',['../group___t_r_e_e.html',1,'']]],
  ['tree_3a_20various_20tree_20with_20generic_20support_23',['TREE: various tree with generic support',['../group___t_r_e_e.html',1,'']]],
  ['trie_20tree_20hash_5ftables_24',['HASH TABLES: classic or trie tree hash_tables',['../group___h_a_s_h___t_a_b_l_e.html',1,'']]],
  ['try_20catch_20endtry_20throw_25',['EXCEPTIONS: C++ style try,catch,endtry,throw',['../group___e_x_c_e_p_t_i_o_n_s.html',1,'']]],
  ['type_20list_26',['LISTS: generic type list',['../group___l_i_s_t.html',1,'']]],
  ['type_20stack_27',['STACKS: generic type stack',['../group___s_t_a_c_k.html',1,'']]]
];
