Nilorea Library: lexmenu.c File Reference
lexmenu.c File Reference
#include "nilorea/lexmenu.h"
#include "lexmenu.h"
#include <stdio.h>
#include <strings.h>
Functions
char * lex__createFileName (const char *filename, const char *postfix)
BITMAP * lex__loadStateImage (const char *value, const char *postfix)
SAMPLE * lex__loadStateSample (const char *value, const char *postfix)
LexMenuItem * lexLoadItemFromSection (const char *itemSectionName, int id)
LexMenu * lexLoadMenuFromFile (const char *filename, const char *screenname)
void lexMenu__fireEvent (LexMenuEvent *event)
BITMAP * lexMenu__getImg (LexMenuItem *item)
int lexMenu__getX (LexMenuItem *item)
int lexMenu__getY (LexMenuItem *item)
void lexMenuAddItem (LexMenu *menu, LexMenuItem *item)
LexMenu * lexMenuCreate (BITMAP *bg)
LexMenuItem * lexMenuCreateItem ()
LexMenu * lexMenuDestroy (LexMenu *menu)
BITMAP * lexMenuGetBitmap (LexMenu *menu, int item, int whichone)
int lexMenuRun (LexMenu *menu, BITMAP *dst)
void lexMenuSetCallback (LexMenuItem *item, int callbackID, LexMenuCallback func)
void lexMenuSetImage (LexMenuItem *item, int state, BITMAP *img)
void lexMenuSetSample (LexMenuItem *item, int event, SAMPLE *sample)
Detailed Description
common headers and low-level hugly functions & define
Author:
Castagnier Mickael
Version:
1.0
Date:
24/03/05
Definition in file lexmenu.c.
Function Documentation
char* lex__createFileName (const char * filename, const char * postfix)
Definition at line 520 of file lexmenu.c.
Referenced by lex__loadStateImage(), and lex__loadStateSample().
BITMAP* lex__loadStateImage (const char * value, const char * postfix)
Definition at line 547 of file lexmenu.c.
References lex__createFileName().
Referenced by lexLoadItemFromSection().
SAMPLE* lex__loadStateSample (const char * value, const char * postfix)
Definition at line 559 of file lexmenu.c.
References lex__createFileName().
Referenced by lexLoadItemFromSection().
LexMenuItem* lexLoadItemFromSection (const char * itemSectionName, int id)
Definition at line 571 of file lexmenu.c.
References lex__loadStateImage(), lex__loadStateSample(), lexMenuCreateItem(), lexMenuSetImage(), and lexMenuSetSample().
Referenced by lexLoadMenuFromFile().
LexMenu* lexLoadMenuFromFile (const char * filename, const char * screenname)
Definition at line 634 of file lexmenu.c.
References lexLoadItemFromSection(), lexMenuAddItem(), and lexMenuCreate().
void lexMenu__fireEvent (LexMenuEvent * event)
Definition at line 132 of file lexmenu.c.
Referenced by lexMenuRun().
BITMAP* lexMenu__getImg (LexMenuItem * item)
Definition at line 71 of file lexmenu.c.
Referenced by lexMenu__getX(), lexMenu__getY(), and lexMenuRun().
int lexMenu__getX (LexMenuItem * item)
Definition at line 88 of file lexmenu.c.
References lexMenu__getImg().
Referenced by lexMenuRun().
int lexMenu__getY (LexMenuItem * item)
Definition at line 111 of file lexmenu.c.
References lexMenu__getImg().
Referenced by lexMenuRun().
void lexMenuAddItem (LexMenu * menu, LexMenuItem * item)
Definition at line 144 of file lexmenu.c.
Referenced by lexLoadMenuFromFile().
LexMenu* lexMenuCreate (BITMAP * bg)
Definition at line 17 of file lexmenu.c.
Referenced by lexLoadMenuFromFile().
LexMenuItem* lexMenuCreateItem ()
Definition at line 64 of file lexmenu.c.
Referenced by lexLoadItemFromSection().
LexMenu* lexMenuDestroy (LexMenu * menu)
Definition at line 30 of file lexmenu.c.
BITMAP* lexMenuGetBitmap (LexMenu * menu, int item, int whichone)
Definition at line 698 of file lexmenu.c.
int lexMenuRun (LexMenu * menu, BITMAP * dst)
Definition at line 174 of file lexmenu.c.
References lexMenu__fireEvent(), lexMenu__getImg(), lexMenu__getX(), and lexMenu__getY().
void lexMenuSetCallback (LexMenuItem * item, int callbackID, LexMenuCallback func)
Definition at line 155 of file lexmenu.c.
void lexMenuSetImage (LexMenuItem * item, int state, BITMAP * img)
Definition at line 161 of file lexmenu.c.
Referenced by lexLoadItemFromSection().
void lexMenuSetSample (LexMenuItem * item, int event, SAMPLE * sample)
Definition at line 167 of file lexmenu.c.
Referenced by lexLoadItemFromSection().