Nilorea Library: n_3d.c File Reference
n_3d.c File Reference
#include "nilorea/n_3d.h"
Functions
double distance (VECTOR3D p1, VECTOR3D p2)
compute the distance between two VECTOR3D points
static int same_sign (double a, double b)
Quickly check if two walue are the same sign or not.
int update_physics_position (PHYSICS *object, double delta_t)
Update object position, reversed. Wrapper of update_physics_position_reverse_nb to update each componants.
int update_physics_position_nb (PHYSICS *object, int it, double delta_t)
Update object position componant.
int update_physics_position_reverse (PHYSICS *object, double delta_t)
Update object position, reversed. Wrapper of update_physics_position_reverse_nb to update each componants.
int update_physics_position_reverse_nb (PHYSICS *object, int it, double delta_t)
Update object position componant, reversed.
int vector_intersect (VECTOR3D p1, VECTOR3D p2, VECTOR3D p3, VECTOR3D p4, VECTOR3D *px)
Compute if two vectors are intersecting or not.
Detailed Description
3D helpers, vector and camera
Author:
Castagnier Mickael
Version:
1.0
Date:
30/04/2014
Definition in file n_3d.c.
Function Documentation
double distance (VECTOR3D p1, VECTOR3D p2)
compute the distance between two VECTOR3D points
Parameters:
p1 The first point
p2 The second point
Returns:
The computed distance
Definition at line 18 of file n_3d.c.
int same_sign (double a, double b) [static]
Quickly check if two walue are the same sign or not.
Parameters:
a first value
b second value
Returns:
TRUE or FALSE
Definition at line 110 of file n_3d.c.
Referenced by vector_intersect().
int update_physics_position (PHYSICS * object, double delta_t)
Update object position, reversed. Wrapper of update_physics_position_reverse_nb to update each componants.
Parameters:
object The object physics to update
delta_t Elapsed time since last call for componant update computing
Returns:
TRUE or FALSE
Definition at line 92 of file n_3d.c.
References update_physics_position_nb().
int update_physics_position_nb (PHYSICS * object, int it, double delta_t)
Update object position componant.
Parameters:
object The object physics to update
it Componant of VECTOR3D to update. it values : 0 -> x, 1 -> y , 2 -> z
delta_t Elapsed time since last call for componant update computing
Returns:
TRUE or FALSE
Definition at line 32 of file n_3d.c.
Referenced by update_physics_position(), and update_physics_position_reverse().
int update_physics_position_reverse (PHYSICS * object, double delta_t)
Update object position, reversed. Wrapper of update_physics_position_reverse_nb to update each componants.
Parameters:
object The object physics to update
delta_t Elapsed time since last call for componant update computing
Returns:
TRUE or FALSE
Definition at line 69 of file n_3d.c.
References update_physics_position_nb().
int update_physics_position_reverse_nb (PHYSICS * object, int it, double delta_t)
Update object position componant, reversed.
Parameters:
object The object physics to update
it Componant of VECTOR3D to update. it values : 0 -> x, 1 -> y , 2 -> z
delta_t Elapsed time since last call for componant update computing
Returns:
TRUE or FALSE
Definition at line 51 of file n_3d.c.
int vector_intersect (VECTOR3D p1, VECTOR3D p2, VECTOR3D p3, VECTOR3D p4, VECTOR3D * px)
Compute if two vectors are intersecting or not.
Parameters:
p1 First point of vector 1
p2 Second poinf of vector 1
p3 First point of vector 2
p4 Second point of vector 2
px Storage for the eventual point
Returns:
VECTOR3D_DONT_INTERSECT , VECTOR3D_COLLINEAR or VECTOR3D_DO_INTERSECT
Definition at line 126 of file n_3d.c.
References same_sign().