Nilorea Library: n_config_file.c File Reference
n_config_file.c File Reference
#include "nilorea/n_common.h"
#include "nilorea/n_config_file.h"
Functions
int destroy_config_file (CONFIG_FILE **cfg_file)
Destroy a loaded config file.
void destroy_config_file_section (void *ptr)
Destroy a config file section.
char * get_config_section_value (CONFIG_FILE *cfg_file, char *section_name, int section_position, char *entry, int entry_position)
Function to parse sections and get entries values.
int get_nb_config_file_sections (CONFIG_FILE *cfg_file, char *section_name)
Get the number of config file with section_name.
int get_nb_config_file_sections_entries (CONFIG_FILE *cfg_file, char *section_name, int section_position, char *entry)
Get the number of config file with section_name.
CONFIG_FILE * load_config_file (char *filename, int *errors)
load a config file
Detailed Description
common function
Author:
Castagnier Mickael
Version:
1.0
Date:
24/03/05
Definition in file n_config_file.c.
Function Documentation
int destroy_config_file (CONFIG_FILE ** cfg_file)
Destroy a loaded config file.
Parameters:
cfg_file pointer to a loaded config file to destroy
Returns:
TRUE or FALSE
Definition at line 323 of file n_config_file.c.
References list_destroy().
void destroy_config_file_section (void * ptr)
Destroy a config file section.
Parameters:
ptr A pointer to a config file section
Returns:
void
Definition at line 17 of file n_config_file.c.
References destroy_ht().
Referenced by load_config_file().
char * get_config_section_value (CONFIG_FILE * cfg_file, char * section_name, int section_position, char * entry, int entry_position)
Function to parse sections and get entries values.
Parameters:
cfg_file name of config file
section_name name of section
section_position section number
entry entry name
entry_position entry number
Returns:
the value of the named entry in section[ position ]
Definition at line 273 of file n_config_file.c.
References ht_get_ptr().
int get_nb_config_file_sections (CONFIG_FILE * cfg_file, char * section_name)
Get the number of config file with section_name.
Parameters:
cfg_file Config file to process
section_name name of sections to search
Returns:
The number of named sections or a negative value
Definition at line 196 of file n_config_file.c.
int get_nb_config_file_sections_entries (CONFIG_FILE * cfg_file, char * section_name, int section_position, char * entry)
Get the number of config file with section_name.
Parameters:
cfg_file Config file to process
section_name name of sections to search
section_position position of the section if there are multiples same name sections
entry name of entry to retrieve
Returns:
The number of named sections entries or a negative value
Definition at line 224 of file n_config_file.c.
References ht_get_ptr().
CONFIG_FILE * load_config_file (char * filename, int * errors)
load a config file
Parameters:
filename Filename of the config file
errors pointer to an int which will represent the number of errors encountered when reading config file
Returns:
NULL or a loaded config file
Definition at line 36 of file n_config_file.c.
References destroy_config_file_section(), free_split_result(), ht_get_ptr(), ht_put_ptr(), list_push(), new_generic_list(), new_ht(), skipu(), split(), and trim_nocopy().