Nilorea Library: n_debug_mem.c File Reference
n_debug_mem.c File Reference
#include "nilorea/n_debug_mem.h"
Functions
void * db_malloc (size_t size)
return a new allocated element
void * db_mem_alloc (size_t size, int line, char *file, const char *func)
allocate a new pointer with size and also put it in the debug table
int db_mem_dump_leaked (char *file)
Dump the current debug memory table.
void db_mem_free (void *ptr)
Free a pointer and also remove it from debug table.
void delete_db_mem_item (void *ptr)
delete a debug meme item
int init_debug_mem ()
initialize debug tables
DEBUG_MEM_ITEM * new_db_mem_item (void *ptr, size_t size, int line, char *file, char *func)
allocate a new item in the debug table
Variables
static DEBUG_MEM_TABLE __debug_mem_table
Detailed Description
Helpers for debugging memory
Author:
Castagnier Mickael
Date:
2014-10-10
Definition in file n_debug_mem.c.
Function Documentation
void * db_malloc (size_t size)
return a new allocated element
Parameters:
size the size of the element
Returns:
Allocated delement or NULL
Definition at line 126 of file n_debug_mem.c.
References db_mem_alloc().
void * db_mem_alloc (size_t size, int line, char * file, const char * func)
allocate a new pointer with size and also put it in the debug table
Parameters:
size the size of the allocated data
line line of the allocation
file file of the allocation
func function where the allocation was made
Returns:
A new item or NULL
Definition at line 96 of file n_debug_mem.c.
References __debug_mem_table, delete_db_mem_item(), ht_put_ptr(), and new_db_mem_item().
Referenced by db_malloc().
int db_mem_dump_leaked (char * file)
Dump the current debug memory table.
Parameters:
file The name of the logfile
Returns:
TRUE or FALSE
Definition at line 163 of file n_debug_mem.c.
References __debug_mem_table, and delete_db_mem_item().
void * db_mem_free (void * ptr)
Free a pointer and also remove it from debug table.
Parameters:
ptr Pointer to free
Definition at line 137 of file n_debug_mem.c.
References __debug_mem_table, delete_db_mem_item(), ht_get_ptr(), and ht_remove().
void delete_db_mem_item (void * item)
delete a debug meme item
Parameters:
item the item to destroy
Definition at line 75 of file n_debug_mem.c.
Referenced by db_mem_alloc(), db_mem_dump_leaked(), and db_mem_free().
int init_debug_mem ()
initialize debug tables
Returns:
TRUE or FALSE
Definition at line 17 of file n_debug_mem.c.
References __debug_mem_table, and new_ht().
DEBUG_MEM_ITEM * new_db_mem_item (void * ptr, size_t size, int line, char * file, char * func)
allocate a new item in the debug table
Parameters:
ptr Pointer address to save
size the size of the allocated data
line line of the allocation
file file of the allocation
func function where the allocation was made
Returns:
A new item or NULL
Definition at line 50 of file n_debug_mem.c.
Referenced by db_mem_alloc().
Variable Documentation
DEBUG_MEM_TABLE __debug_mem_table [static]
global table of allocation
Definition at line 10 of file n_debug_mem.c.
Referenced by db_mem_alloc(), db_mem_dump_leaked(), db_mem_free(), and init_debug_mem().