Nilorea Library: n_games.c File Reference
n_games.c File Reference
#include "nilorea/n_games.h"
Functions
void destroy_game_env (GAME_ENV **game)
int init_game_env (GAME_ENV **game)
GAME_ENV * load_game_config (char *config_name)
load a config from file
Detailed Description
Games helpers functions
Author:
Castagnier Mickael
Version:
1.0
Date:
26/06/2015
Definition in file n_games.c.
Function Documentation
void destroy_game_env (GAME_ENV ** game)
Parameters:
game a pointer a to a game structure to destroy
Definition at line 58 of file n_games.c.
Referenced by load_game_config().
init_game_env (GAME_ENV ** game)
Parameters:
game a pointer to a game structure to allocate
Returns:
TRUE or FALSE
Definition at line 15 of file n_games.c.
Referenced by load_game_config().
GAME_ENV * load_game_config (char * config_name)
load a config from file
Parameters:
config_name the name of the game file config
Returns:
Loaded config or NULL
Definition at line 75 of file n_games.c.
References destroy_game_env(), and init_game_env().