Nilorea Library: n_list.c File Reference
n_list.c File Reference
#include "nilorea/n_common.h"
#include <pthread.h>
#include "nilorea/n_log.h"
#include "nilorea/n_list.h"
Functions
int list_destroy (LIST **list)
Empty and Free a list container. Call the destructor each time.
int list_empty (LIST *list)
Empty a LIST list of pointers.
int list_empty_with_f (LIST *list, void(*free_fnct)(void *ptr))
Empty a LIST list of pointers.
void * list_pop_f (LIST *list)
Get a pointer from the end of the list.
int list_push (LIST *list, void *ptr, void(*destructor)(void *ptr))
Add a pointer to the end of the list.
int list_push_sorted (LIST *list, void *ptr, int(*comparator)(const void *a, const void *b), void(*destructor)(void *ptr))
Add a pointer sorted in the list , starting by the end of the list.
void * list_shift_f (LIST *list)
Get a pointer from the start of the list.
int list_unshift (LIST *list, void *ptr, void(*destructor)(void *ptr))
Add a pointer at the start of the list.
int list_unshift_sorted (LIST *list, void *ptr, int(*comparator)(const void *a, const void *b), void(*destructor)(void *ptr))
Add a pointer sorted in the list , starting by the start of the list.
LIST * new_generic_list (int max_items)
Initialiaze a generic list container to max_items pointers.
LIST_NODE * new_list_node (void *ptr, void(*destructor)(void *ptr))
Allocate a new node to link in a list.
void * remove_list_node_f (LIST *list, LIST_NODE *node)
Internal function called each time we need to get a node out of a list.
Detailed Description
Pointer list functions definitions
Author:
Castagnier Mickael
Version:
2.0
Date:
24/04/13
Definition in file n_list.c.
Function Documentation
int list_destroy (LIST ** list)
Empty and Free a list container. Call the destructor each time.
Parameters:
list The list to destroy. An already empty or null list will cause an error and a _log message.
Returns:
TRUE or FALSE. Check error messages in DEBUG mode.
Definition at line 441 of file n_list.c.
References list_empty().
Referenced by delete_msg(), destroy_config_file(), destroy_ht(), destroy_threaded_pool(), and netw_set().
int list_empty (LIST * list)
Empty a LIST list of pointers.
Parameters:
list The list to empty. An already empty or null list will cause an error and a _log message.
Returns:
TRUE or FALSE. Check error messages in DEBUG mode.
Definition at line 385 of file n_list.c.
Referenced by empty_msg(), list_destroy(), and netw_set().
int list_empty_with_f (LIST * list, void(*)(void *ptr) free_fnct)
Empty a LIST list of pointers.
Parameters:
list The list to empty. An already empty or null list will cause an error and a _log message.
free_fnct a function ptr to a void func(void *ptr)
Returns:
TRUE or FALSE. Check error messages in DEBUG mode.
Definition at line 415 of file n_list.c.
void * list_pop_f (LIST * list)
Get a pointer from the end of the list.
Parameters:
list An initilized list container. A null value will cause an error and a _log message.
Returns:
A void *ptr or NULL. Check error messages in DEBUG mode.
Definition at line 314 of file n_list.c.
int list_push (LIST * list, void * ptr, void(*)(void *ptr) destructor)
Add a pointer to the end of the list.
Parameters:
list An initilized list container. A null value will cause an error and a _log message.
ptr The pointer you wan to put in the list. A null value will cause an error and a _log message.
destructor Pointer to the ptr type destructor function. Leave to NULL if there isn't.
Returns:
TRUE or FALSE. Check error messages in DEBUG mode.
Definition at line 121 of file n_list.c.
References new_list_node().
Referenced by add_int_to_msg(), add_nb_to_msg(), add_nstrdup_to_msg(), add_nstrptr_to_msg(), add_strdup_to_msg(), add_threaded_process(), ht_put_double(), ht_put_int(), ht_put_ptr(), ht_put_string(), list_push_sorted(), list_unshift_sorted(), load_config_file(), netw_add_msg(), netw_recv_func(), and scan_dir_ex().
int list_push_sorted (LIST * list, void * ptr, int(*)(const void *a, const void *b) comparator, void(*)(void *ptr) destructor)
Add a pointer sorted in the list , starting by the end of the list.
Parameters:
list An initilized list container. A null value will cause an error and a _log message.
ptr The pointer you wan to put in the list. A null value will cause an error and a _log message.
comparator A pointer to a function which take two void * pointers and return an int.
destructor Pointer to the ptr type destructor function. Leave to NULL if there isn't.
Returns:
TRUE or FALSE. Check error messages in DEBUG mode.
Definition at line 162 of file n_list.c.
References list_push(), list_unshift(), and new_list_node().
void * list_shift_f (LIST * list)
Get a pointer from the start of the list.
Parameters:
list An initilized list container. A null value will cause an error and a _log message.
Returns:
A void *ptr or NULL. Check error messages in DEBUG mode.
Definition at line 349 of file n_list.c.
int list_unshift (LIST * list, void * ptr, void(*)(void *ptr) destructor)
Add a pointer at the start of the list.
Parameters:
list An initilized list container. A null value will cause an error and a _log message.
ptr The pointer you wan to put in the list. A null value will cause an error and a _log message.
destructor Pointer to the ptr type destructor function. Leave to NULL if there isn't.
Returns:
A void *ptr or NULL. Check error messages in DEBUG mode.
Definition at line 219 of file n_list.c.
References new_list_node().
Referenced by list_push_sorted(), and list_unshift_sorted().
int list_unshift_sorted (LIST * list, void * ptr, int(*)(const void *a, const void *b) comparator, void(*)(void *ptr) destructor)
Add a pointer sorted in the list , starting by the start of the list.
Parameters:
list An initilized list container. A null value will cause an error and a _log message.
ptr The pointer you wan to put in the list. A null value will cause an error and a _log message.
comparator A pointer to a function which take two void * pointers and return an int.
destructor Pointer to the ptr type destructor function. Leave to NULL if there isn't.
Returns:
TRUE or FALSE. Check error messages in DEBUG mode.
Definition at line 259 of file n_list.c.
References list_push(), list_unshift(), and new_list_node().
LIST * new_generic_list (int max_items)
Initialiaze a generic list container to max_items pointers.
Parameters:
max_items Specify a max size for the list container, 0 or negative for unlimited lists.
Returns:
a new LIST or NULL
Definition at line 20 of file n_list.c.
Referenced by create_msg(), load_config_file(), netw_new(), new_ht(), new_neural_net(), and new_thread_pool().
LIST_NODE * new_list_node (void * ptr, void(*)(void *ptr) destructor)
Allocate a new node to link in a list.
Parameters:
ptr The pointer you want to put in the node.
destructor Pointer to the ptr type destructor function. Leave to NULL if there isn't.
Returns:
A new node or NULL on error. Check error messages in DEBUG mode.
Definition at line 46 of file n_list.c.
Referenced by list_push(), list_push_sorted(), list_unshift(), and list_unshift_sorted().
void * remove_list_node_f (LIST * list, LIST_NODE * node)
Internal function called each time we need to get a node out of a list.
Parameters:
list The list to pick in
node The node to remove in the list
Returns:
The node or NULL
Definition at line 68 of file n_list.c.