Nilorea Library: n_log.c File Reference
n_log.c File Reference
#include <pthread.h>
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
Data Structures
struct _code
Typedefs
typedef struct _code CODE
Functions
void _n_log (int level, const char *file, const char *func, int line, const char *format,...)
Logging function. log(level , const char *format , ...) is a macro around _log.
int _vscprintf_so (const char *format, va_list pargs)
int asprintf (char *strp[], const char *fmt,...)
int close_safe_logging (TS_LOG *log)
close a thread-safe logging file
void close_sysjrnl (void)
Close syslog connection or clean internals for event log.
FILE * get_log_file (void)
return the current log_file
int get_log_level (void)
Get the global log level value.
int open_safe_logging (TS_LOG **log, char *pathname, char *opt)
Open a thread-safe logging file.
char * open_sysjrnl (char *identity)
Open connection to syslog or create internals for event log.
int set_log_file (char *file)
Set the logging to a file instead of stderr.
void set_log_level (const int log_level)
Set the global log level value (static int LOG_LEVEL)
int vasprintf (char **strp, const char *fmt, va_list ap)
int write_safe_log (TS_LOG *log, char *pat,...)
write to a thread-safe logging file
Variables
static FILE * log_file = NULL
static int LOG_LEVEL = LOG_NULL
static int LOG_TYPE = LOG_STDERR
static CODE prioritynames []
char * proc_name = NULL
Typedef Documentation
typedef struct _code CODE
internal struct to handle log types
Function Documentation
void _n_log (int level, const char * file, const char * func, int line, const char * format, ...)
Logging function. log(level , const char *format , ...) is a macro around _log.
Parameters:
level Logging level
file File containing the emmited log
func Function emmiting the log
line Line of the log
format Format and string of the log, printf style
Definition at line 205 of file n_log.c.
References get_log_level(), log_file, LOG_TYPE, proc_name, and vasprintf().
Referenced by _n_nodup_log(), and _n_nodup_log_indexed().
int _vscprintf_so (const char * format, va_list pargs)
Definition at line 167 of file n_log.c.
Referenced by vasprintf().
int asprintf (char * strp[], const char * fmt, ...)
Definition at line 189 of file n_log.c.
References vasprintf().
close_safe_logging (TS_LOG * log)
close a thread-safe logging file
Parameters:
log A TS_LOG handler
Returns:
TRUE on success, FALSE on error
Definition at line 340 of file n_log.c.
void close_sysjrnl (void)
Close syslog connection or clean internals for event log.
Definition at line 82 of file n_log.c.
References proc_name.
FILE * get_log_file (void)
return the current log_file
Returns:
a valid FILE handle or NULL
Definition at line 159 of file n_log.c.
References log_file.
int get_log_level (void)
Get the global log level value.
Returns:
static int LOG_LEVEL
Definition at line 122 of file n_log.c.
References LOG_LEVEL.
Referenced by _n_log().
open_safe_logging (TS_LOG ** log, char * pathname, char * opt)
Open a thread-safe logging file.
Parameters:
log A TS_LOG handler
pathname The file path (if any) and name
opt Options for opening (please never forget to use "w")
Returns:
TRUE on success , FALSE on error , -1000 if already open
Definition at line 271 of file n_log.c.
open_sysjrnl (char * identity)
Open connection to syslog or create internals for event log.
Parameters:
identity Tag for syslog or NULL to use argv[0]
Returns:
NULL or identity if success
Definition at line 63 of file n_log.c.
References proc_name.
int set_log_file (char * file)
Set the logging to a file instead of stderr.
Parameters:
file The filename where to log
Returns:
TRUE or FALSE
Definition at line 134 of file n_log.c.
References log_file, and set_log_level().
void set_log_level (const int log_level)
Set the global log level value (static int LOG_LEVEL)
Parameters:
log_level Log level value. Supported: JRNLONLY,NOLOG,LOG_NOTICE/INFO/ERR/DEBUG,LOG_FILE/STDERR/SYSJRNL
Definition at line 96 of file n_log.c.
References LOG_LEVEL, and LOG_TYPE.
Referenced by set_log_file().
int vasprintf (char ** strp, const char * fmt, va_list ap)
Definition at line 177 of file n_log.c.
References _vscprintf_so().
Referenced by _n_log(), _n_nodup_log(), _n_nodup_log_indexed(), and asprintf().
write_safe_log (TS_LOG * log, char * pat, ...)
write to a thread-safe logging file
Parameters:
log A TS_LOG handler
pat Pattern for writting (i.e "%d %d %s")
Returns:
TRUE on success, FALSE on error
Definition at line 308 of file n_log.c.
Variable Documentation
FILE* log_file = NULL [static]
static FILE handling if logging to file is enabled
Definition at line 52 of file n_log.c.
Referenced by _n_log(), get_log_file(), and set_log_file().
int LOG_LEVEL = LOG_NULL [static]
static global maximum wanted log level value
Definition at line 46 of file n_log.c.
Referenced by get_log_level(), and set_log_level().
int LOG_TYPE = LOG_STDERR [static]
static global logging type (STDERR, FILE, SYSJRNL)
Definition at line 49 of file n_log.c.
Referenced by _n_log(), and set_log_level().
CODE prioritynames[] [static]
Initial value:
 {
                {               "EMERG",        LOG_EMERG,                      "ERROR" },
                {               "ALERT",        LOG_ALERT,                      "ERROR" },
                {               "CRITICAL",     LOG_CRIT,                       "ERROR" },
                {               "ERROR",        LOG_ERR,                        "ERROR" },
                {               "WARNING",      LOG_WARNING,    "WARNING" },
                {               "NOTICE",       LOG_NOTICE,                     "SUCCESS" },
                {               "INFO",                         LOG_INFO,                       "INFORMATION" },
                {               "DEBUG",        LOG_DEBUG,                      "INFORMATION" },
                {               NULL,                           -1,                                              NULL }
}
array of log levels
Definition at line 32 of file n_log.c.
char* proc_name = NULL
static proc name, for windows event log
Definition at line 55 of file n_log.c.
Referenced by _n_log(), close_sysjrnl(), and open_sysjrnl().