Nilorea Library: n_network_msg.c File Reference
n_network_msg.c File Reference
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_network.h"
#include "nilorea/n_network_msg.h"
Functions
int add_int_to_msg (NETW_MSG *msg, int value)
Add an int to the int list int the message.
int add_nb_to_msg (NETW_MSG *msg, double value)
Add an float to the message.
int add_nstrdup_to_msg (NETW_MSG *msg, N_STR *str)
Add a copy of str to the string list in the message.
int add_nstrptr_to_msg (NETW_MSG *msg, N_STR *str)
Add a string to the string list in the message.
int add_strdup_to_msg (NETW_MSG *msg, char *str)
Add a copy of char *str to the string list in the message.
int create_msg (NETW_MSG **msg)
Create a NETW_MSG *object.
int delete_msg (NETW_MSG **msg)
Delete a NETW_MSG *object.
double double_swap (double value)
Swap bytes endiannes for a double.
int empty_msg (NETW_MSG **msg)
Empty a NETW_MSG *object.
int get_int_from_msg (NETW_MSG *msg, int *value)
Get a number from a message number list.
int get_nb_from_msg (NETW_MSG *msg, double *value)
Get a number from a message number list.
int get_nstr_from_msg (NETW_MSG *msg, N_STR **value)
Get a string from a message string list.
int get_str_from_msg (NETW_MSG *msg, char **value)
Get a string from a message string list.
double htond (double value)
If needed swap bytes for a double.
NETW_MSG * make_msg_from_str (N_STR *str)
Make a single message of the string.
N_STR * make_str_from_msg (NETW_MSG *msg)
Make a single string of the message.
int netw_get_ident (N_STR *msg, int *type, int *ident, N_STR **name, N_STR **passwd)
Retrieves identification from netwmsg.
int netw_get_ping (N_STR *msg, int *type, int *from, int *to, int *time)
Retrieves a ping travel elapsed time.
int netw_get_position (N_STR *msg, int *id, double *X, double *Y, double *vx, double *vy, double *acc_x, double *acc_y, int *time_stamp)
Retrieves position from netwmsg.
int netw_get_string (N_STR *msg, int *id, N_STR **name, N_STR **chan, N_STR **txt, int *color)
Retrieves string from netwmsg.
int netw_msg_get_type (N_STR *msg)
Get the type of message without killing the first number. Use with netw_get_XXX.
int netw_send_ident (NETWORK *netw, int type, int id, N_STR *name, N_STR *passwd)
Add a formatted NETWMSG_IDENT message to the specified network.
int netw_send_ping (NETWORK *netw, int type, int id_from, int id_to, int time)
Add a ping reply to the network.
int netw_send_position (NETWORK *netw, int id, double X, double Y, double vx, double vy, double acc_x, double acc_y, int time_stamp)
Add a formatted NETWMSG_IDENT message to the specified network.
int netw_send_string_to (NETWORK *netw, int id_from, int id_to, char *name, char *txt, int color)
Add a string to the network, aiming a specific user.
int netw_send_string_to_all (NETWORK *netw, int id, char *name, char *chan, char *txt, int color)
Add a string to the network, aiming all server-side users.
double ntohd (double value)
If needed swap bytes for a double.
Detailed Description
network messages function Network Engine
Author:
Castagnier Mickael
Version:
1.0
Date:
10/05/2005
Definition in file n_network_msg.c.
Function Documentation
add_int_to_msg (NETW_MSG * msg, int value)
Add an int to the int list int the message.
Parameters:
msg A NETW_MSG *object to complete with the value
value The value to add to the message
Returns:
TRUE or FALSE
Definition at line 181 of file n_network_msg.c.
References list_push().
Referenced by make_msg_from_str(), netw_send_ident(), netw_send_ping(), netw_send_position(), netw_send_string_to(), and netw_send_string_to_all().
add_nb_to_msg (NETW_MSG * msg, double value)
Add an float to the message.
Parameters:
msg A NETW_MSG *object to complete with the value
value The value to add to the message
Warning:
The floating value will be rounded by the network serialization !
Returns:
TRUE or FALSE
Definition at line 159 of file n_network_msg.c.
References list_push().
Referenced by make_msg_from_str(), and netw_send_position().
add_nstrdup_to_msg (NETW_MSG * msg, N_STR * str)
Add a copy of str to the string list in the message.
Parameters:
msg A NETW_MSG *object to complete with the string
str The string to add to the message
Returns:
TRUE or FALSE
Definition at line 219 of file n_network_msg.c.
References free_nstr_ptr(), list_push(), and nstrdup().
Referenced by netw_send_ident().
add_nstrptr_to_msg (NETW_MSG * msg, N_STR * str)
Add a string to the string list in the message.
Parameters:
msg A NETW_MSG *object to complete with the string
str The string to add to the message
Returns:
TRUE or FALSE
Definition at line 203 of file n_network_msg.c.
References free_nstr_ptr(), and list_push().
Referenced by make_msg_from_str(), netw_send_string_to(), and netw_send_string_to_all().
add_strdup_to_msg (NETW_MSG * msg, char * str)
Add a copy of char *str to the string list in the message.
Parameters:
msg A NETW_MSG *object to complete with the string
str The string to add to the message
Returns:
TRUE or FALSE
Definition at line 237 of file n_network_msg.c.
References char_to_nstr(), free_nstr_ptr(), and list_push().
create_msg (NETW_MSG ** msg)
Create a NETW_MSG *object.
Parameters:
msg A NETW_MSG *object
Returns:
TRUE or FALSE
Definition at line 78 of file n_network_msg.c.
References new_generic_list().
Referenced by make_msg_from_str(), netw_send_ident(), netw_send_ping(), netw_send_position(), netw_send_string_to(), and netw_send_string_to_all().
delete_msg (NETW_MSG ** msg)
Delete a NETW_MSG *object.
Parameters:
msg A NETW_MSG *object to delete
Returns:
TRUE or FALSE
Definition at line 106 of file n_network_msg.c.
References list_destroy().
Referenced by netw_get_ident(), netw_get_ping(), netw_get_position(), netw_get_string(), netw_send_ident(), netw_send_ping(), netw_send_position(), netw_send_string_to(), and netw_send_string_to_all().
static double double_swap (double value)
Swap bytes endiannes for a double.
Parameters:
value The double to swap
Returns:
A swapped double
Definition at line 18 of file n_network_msg.c.
Referenced by htond(), and ntohd().
empty_msg (NETW_MSG ** msg)
Empty a NETW_MSG *object.
Parameters:
msg A NETW_MSG **object
Returns:
TRUE or FALSE
Definition at line 139 of file n_network_msg.c.
References list_empty().
get_int_from_msg (NETW_MSG * msg, int * value)
Get a number from a message number list.
Parameters:
msg A NETW_MSG *object for extracting number
value A int value where you want to store the result
Returns:
A pointer to the N_STR, Do not forget to free it !
Definition at line 281 of file n_network_msg.c.
Referenced by netw_get_ident(), netw_get_ping(), netw_get_position(), and netw_get_string().
int get_nb_from_msg (NETW_MSG * msg, double * value)
Get a number from a message number list.
Parameters:
msg A NETW_MSG *object for extracting number
value A int value where you want to store the result
Returns:
A pointer to the N_STR, Do not forget to free it !
Definition at line 257 of file n_network_msg.c.
Referenced by netw_get_position().
get_nstr_from_msg (NETW_MSG * msg, N_STR ** value)
Get a string from a message string list.
Parameters:
msg The NETW_MSG where you have a str to get
value A pointer to a NULL N_STR for storage
Returns:
TRUE or FALSE
Definition at line 306 of file n_network_msg.c.
Referenced by netw_get_ident(), and netw_get_string().
get_str_from_msg (NETW_MSG * msg, char ** value)
Get a string from a message string list.
Parameters:
msg The NETW_MSG where you have a str to get
value A pointer to a NULL N_STR for storage
Returns:
TRUE or FALSE
Definition at line 333 of file n_network_msg.c.
static double htond (double value)
If needed swap bytes for a double.
Parameters:
value The value to eventually swap
Returns:
The modified value
Definition at line 44 of file n_network_msg.c.
References double_swap().
Referenced by make_str_from_msg().
make_msg_from_str (N_STR * str)
Make a single message of the string.
Parameters:
str A N_STR structure to convert into a NETW_MSG one
Returns:
A pointer to the generated NETW_MSG, do not forget to free it after use !
Definition at line 477 of file n_network_msg.c.
References add_int_to_msg(), add_nb_to_msg(), add_nstrptr_to_msg(), create_msg(), and ntohd().
Referenced by netw_get_ident(), netw_get_ping(), netw_get_position(), and netw_get_string().
make_str_from_msg (NETW_MSG * msg)
Make a single string of the message.
Parameters:
msg A NETW_MSG structure to convert into a N_STR one
Returns:
A pointer to the generated N_STR, do not forget to free it after use !
Definition at line 361 of file n_network_msg.c.
References htond().
Referenced by netw_send_ident(), netw_send_ping(), netw_send_position(), netw_send_string_to(), and netw_send_string_to_all().
int netw_get_ident (N_STR * msg, int * type, int * ident, N_STR ** name, N_STR ** passwd)
Retrieves identification from netwmsg.
Parameters:
msg The source string from which we are going to extract the data
type NETMSG_IDENT_NEW , NETMSG_IDENT_REPLY_OK , NETMSG_IDENT_REPLY_NOK , NETMSG_IDENT_REQUEST
ident ID for the user
name Name of the user
passwd Password of the user
Returns:
TRUE or FALSE
Definition at line 818 of file n_network_msg.c.
References delete_msg(), get_int_from_msg(), get_nstr_from_msg(), and make_msg_from_str().
netw_get_ping (N_STR * msg, int * type, int * from, int * to, int * time)
Retrieves a ping travel elapsed time.
Parameters:
msg The source string from which we are going to extract the data
type NETW_PING_REQUEST or NETW_PING_REPLY
from Identifiant of the sender
to Targetted Identifiant, -1 for server ping
time The time it was when the ping was sended
Returns:
TRUE or FALSE
Definition at line 954 of file n_network_msg.c.
References delete_msg(), get_int_from_msg(), and make_msg_from_str().
int netw_get_position (N_STR * msg, int * id, double * X, double * Y, double * vx, double * vy, double * acc_x, double * acc_y, int * time_stamp)
Retrieves position from netwmsg.
Parameters:
msg The source string from which we are going to extract the data
id
X X position inside a big grid
Y Y position inside a big grid
vx X speed
vy Y speed
acc_x X acceleration
acc_y Y acceleration
time_stamp Current Time when it was sended (for some delta we would want to compute)
Returns:
TRUE or FALSE
Definition at line 861 of file n_network_msg.c.
References delete_msg(), get_int_from_msg(), get_nb_from_msg(), and make_msg_from_str().
netw_get_string (N_STR * msg, int * id, N_STR ** name, N_STR ** chan, N_STR ** txt, int * color)
Retrieves string from netwmsg.
Parameters:
msg The source string from which we are going to extract the data
id The ID of the sending client
name Name of user
chan Target Channel, if any. Pass "ALL" to target the default channel
txt The text to send
color The color of the text
Returns:
TRUE or FALSE
Definition at line 908 of file n_network_msg.c.
References delete_msg(), get_int_from_msg(), get_nstr_from_msg(), and make_msg_from_str().
netw_msg_get_type (N_STR * msg)
Get the type of message without killing the first number. Use with netw_get_XXX.
Parameters:
msg A char *msg_object you want to have type
Returns:
The value corresponding to the type or FALSE
Definition at line 570 of file n_network_msg.c.
int netw_send_ident (NETWORK * netw, int type, int id, N_STR * name, N_STR * passwd)
Add a formatted NETWMSG_IDENT message to the specified network.
Parameters:
netw The aimed NETWORK where we want to add something to send
type type of identification (NETW_IDENT_REQUEST , NETW_IDENT_NEW)
id The ID of the sending client
name Username
passwd Password
Returns:
TRUE or FALSE
Definition at line 599 of file n_network_msg.c.
References add_int_to_msg(), add_nstrdup_to_msg(), create_msg(), delete_msg(), make_str_from_msg(), and netw_add_msg().
netw_send_ping (NETWORK * netw, int id_from, int id_to, int time, int type)
Add a ping reply to the network.
Parameters:
netw The aimed NETWORK where we want to add something to send
id_from Identifiant of the sender
id_to Identifiant of the destination, -1 if the serveur itslef is targetted
time The time it was when the ping was sended
type NETW_PING_REQUEST or NETW_PING_REPLY
Returns:
TRUE or FALSE
Definition at line 782 of file n_network_msg.c.
References add_int_to_msg(), create_msg(), delete_msg(), make_str_from_msg(), and netw_add_msg().
netw_send_position (NETWORK * netw, int id, double X, double Y, double vx, double vy, double acc_x, double acc_y, int time_stamp)
Add a formatted NETWMSG_IDENT message to the specified network.
Parameters:
netw The aimed NETWORK where we want to add something to send
id The ID of the sending client
X X position inside a big grid
Y Y position inside a big grid
vx X speed
vy Y speed
acc_x Y acceleration
acc_y X acceleration
time_stamp Current Time when sending (for some delta we would want to compute)
Returns:
TRUE or FALSE
Definition at line 638 of file n_network_msg.c.
References add_int_to_msg(), add_nb_to_msg(), create_msg(), delete_msg(), make_str_from_msg(), and netw_add_msg().
netw_send_string_to (NETWORK * netw, int id_from, int id_to, char * name, char * txt, int color)
Add a string to the network, aiming a specific user.
Parameters:
netw The aimed NETWORK where we want to add something to send
id_from The ID of the sending client
id_to The ID of the targetted client
name Sender Name
txt Sender text
color Sender text color
Returns:
TRUE or FALSE
Definition at line 733 of file n_network_msg.c.
References add_int_to_msg(), add_nstrptr_to_msg(), char_to_nstr(), create_msg(), delete_msg(), make_str_from_msg(), and netw_add_msg().
netw_send_string_to_all (NETWORK * netw, int id, char * name, char * chan, char * txt, int color)
Add a string to the network, aiming all server-side users.
Parameters:
netw The aimed NETWORK where we want to add something to send
id The ID of the sending client
name Name of user
chan Target Channel, if any. Pass "ALL" to target the default channel
txt The text to send
color The color of the text
Returns:
TRUE or FALSE;
Definition at line 679 of file n_network_msg.c.
References add_int_to_msg(), add_nstrptr_to_msg(), char_to_nstr(), create_msg(), delete_msg(), make_str_from_msg(), and netw_add_msg().
static double ntohd (double value)
If needed swap bytes for a double.
Parameters:
value The value to eventually swap
Returns:
The modified value
Definition at line 61 of file n_network_msg.c.
References double_swap().
Referenced by make_msg_from_str().