Nilorea Library: n_nodup_log.c File Reference
n_nodup_log.c File Reference
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_str.h"
#include "nilorea/n_list.h"
#include "nilorea/n_hash.h"
#include "nilorea/n_nodup_log.h"
Functions
void _n_nodup_log (int LEVEL, const char *file, const char *func, int line, const char *format,...)
Logging function. log(level , const char *format , ...) is a macro around _log.
void _n_nodup_log_indexed (int LEVEL, const char *prefix, const char *file, const char *func, int line, const char *format,...)
Logging function. log(level , const char *format , ...) is a macro around _log.
int check_n_log_dup (const char *log, const char *file, const char *func, int line)
check if a log was already done or not at the given line, func, file
int check_n_log_dup_indexed (const char *log, const char *file, const char *func, int line, const char *prefix)
check if a log was already done or not at the given line, func, file
int close_nodup_log ()
Empty nodup logtable and close the no duplicate logging session.
int dump_nodup_log (char *file)
Dump the duplicate error log hash table in a file.
int empty_nodup_table ()
Empty the nodup internal table.
static char * get_nodup_indexed_key (const char *file, const char *func, const char *prefix, int line)
internal, get a key for an indexed log entry
static char * get_nodup_key (const char *file, const char *func, int line)
internal, get a key for a log entry
int init_nodup_log (int max)
initialize the no duplicate logging system
Variables
static HASH_TABLE * _n_nodup_table = NULL
Function Documentation
void _n_nodup_log (int LEVEL, const char * file, const char * func, int line, const char * format, ...)
Logging function. log(level , const char *format , ...) is a macro around _log.
Parameters:
LEVEL Logging level
file File containing the emmited log
func Function emmiting the log
line Line of the log
format Format and string of the log, printf style
Definition at line 212 of file n_nodup_log.c.
References _n_log(), _n_nodup_table, check_n_log_dup(), get_nodup_key(), ht_get_node(), ht_put_string(), and vasprintf().
void _n_nodup_log_indexed (int LEVEL, const char * prefix, const char * file, const char * func, int line, const char * format, ...)
Logging function. log(level , const char *format , ...) is a macro around _log.
Parameters:
LEVEL Logging level
prefix prefix to subgroup logs
file File containing the emmited log
func Function emmiting the log
line Line of the log
format Format and string of the log, printf style
Definition at line 271 of file n_nodup_log.c.
References _n_log(), _n_nodup_table, check_n_log_dup_indexed(), get_nodup_indexed_key(), ht_get_node(), ht_put_string(), and vasprintf().
check_n_log_dup (const char * log, const char * file, const char * func, int line)
check if a log was already done or not at the given line, func, file
Parameters:
log the line of log
file the file containing the log
func the name of calling func
line the line of the log
Returns:
0 if not existing 1 if existing with the same value , 2 if key exist and value is different
Definition at line 133 of file n_nodup_log.c.
References _n_nodup_table, get_nodup_key(), and ht_get_node().
Referenced by _n_nodup_log().
check_n_log_dup_indexed (const char * log, const char * file, const char * func, int line, const char * prefix)
check if a log was already done or not at the given line, func, file
Parameters:
log the line of log
file the file containing the log
func the name of calling func
line the line of the log
prefix prefix to subgroup logs
Returns:
0 if not existing 1 if existing with the same value , 2 if key exist and value is different
Definition at line 174 of file n_nodup_log.c.
References _n_nodup_table, get_nodup_indexed_key(), and ht_get_node().
Referenced by _n_nodup_log_indexed().
int close_nodup_log ()
Empty nodup logtable and close the no duplicate logging session.
Returns:
TRUE or FALSE
Definition at line 75 of file n_nodup_log.c.
References _n_nodup_table, and destroy_ht().
void dump_nodup_log (char * file)
Dump the duplicate error log hash table in a file.
Parameters:
file The path and filename to the dump file
Returns:
TRUE or FALSE
Definition at line 328 of file n_nodup_log.c.
References _n_nodup_table.
int empty_nodup_table ()
Empty the nodup internal table.
Returns:
TRUE or FALSE
Definition at line 63 of file n_nodup_log.c.
References _n_nodup_table, and empty_ht().
char * get_nodup_indexed_key (const char * file, const char * func, const char * prefix, int line) [static]
internal, get a key for an indexed log entry
Parameters:
file log source file
func log source
line log source
prefix prefix for log entry
Returns:
The key for the the log entry
Definition at line 110 of file n_nodup_log.c.
Referenced by _n_nodup_log_indexed(), and check_n_log_dup_indexed().
char * get_nodup_key (const char * file, const char * func, int line) [static]
internal, get a key for a log entry
Parameters:
file log source file
func log source
line log source
Returns:
The key for the the log entry
Definition at line 89 of file n_nodup_log.c.
Referenced by _n_nodup_log(), and check_n_log_dup().
init_nodup_log (int max)
initialize the no duplicate logging system
Parameters:
max the max size of the internal hash table. Leave it to zero or negative to keep the internal value in use (1024)
Returns:
TRUE or FALSE
Definition at line 32 of file n_nodup_log.c.
References _n_nodup_table, and new_ht().
Variable Documentation
HASH_TABLE* _n_nodup_table = NULL [static]
internal: no dup hash_table log save
Definition at line 25 of file n_nodup_log.c.
Referenced by _n_nodup_log(), _n_nodup_log_indexed(), check_n_log_dup(), check_n_log_dup_indexed(), close_nodup_log(), dump_nodup_log(), empty_nodup_table(), and init_nodup_log().