Nilorea Library: n_str.c File Reference
n_str.c File Reference
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_str.h"
#include <pthread.h>
#include <math.h>
Functions
int _free_nstr (N_STR **ptr)
Free a N_STR structure and set the pointer to NULL.
N_STR * char_to_nstr (char *src)
Convert a char into a N_STR, short version.
int char_to_nstr_ex (char *from, NSTRBYTE nboct, N_STR **to)
Convert a char into a N_STR, extended version.
int empty_nstr (N_STR *nstr)
empty a N_STR string
N_STR * file_to_nstr (char *filename)
Load a whole file into a N_STR. Be aware of the NSTRBYTE addressing limit (2GB commonly)
int free_nstr_nolog (N_STR **ptr)
Free a N_STR structure and set the pointer to NULL.
void free_nstr_ptr (void *ptr)
Free a N_STR pointer structure.
void free_nstr_ptr_nolog (void *ptr)
Free a N_STR pointer structure.
int free_split_result (char ***tab)
Free a split result allocated array.
N_STR * new_nstr (NSTRBYTE size)
create a new N_STR string
char * nfgets (char *buffer, int size, FILE *stream)
try to fgets until new line
int nstr_to_fd (N_STR *str, FILE *out, int lock)
Write a N_STR content into a file.
int nstr_to_file (N_STR *str, char *filename)
Write a N_STR content into a file.
int nstrcat (N_STR *dst, N_STR *src)
Add N_STR *src content to N_STR *dst, resizing it if needed.
int nstrcat_bytes (N_STR *dest, void *data)
Append data into N_STR using internal N_STR size and cursor position. Wrapper to nstrcat_ex, with resize_flag on and a block size one byte higher than size.
int nstrcat_bytes_ex (N_STR *dest, void *data, NSTRBYTE size)
Append data into N_STR using internal N_STR size and cursor position. Wrapper to nstrcat_ex, with resize_flag on and a block size one byte higher than size.
int nstrcat_ex (N_STR *dest, void *src, NSTRBYTE size, NSTRBYTE blk_size, int resize_flag)
Append data into N_STR using internal N_STR size and cursor position.
N_STR * nstrdup (N_STR *str)
Duplicate a N_STR.
int scan_dir (const char *dir, LIST *result, const int recurse)
Scan a list of directory and return a list of char *file.
int scan_dir_ex (const char *dir, const char *pattern, LIST *result, const int recurse, const int mode)
Scan a list of directory and return a list of char *file.
int skipu (char *string, char toskip, NSTRBYTE *iterator, int inc)
skip until 'toskip' occurence is found from 'iterator' to the next 'toskip' value. The new iterator index is automatically stored, returning to it first value if an error append.
int skipw (char *string, char toskip, NSTRBYTE *iterator, int inc)
skip while 'toskip' occurence is found from 'iterator' to the next non 'toskip' position. The new iterator index is automatically stored, returning to it first value if an error append.
char ** split (char *str, const char *delim, int empty)
Split the strings into a an array of char *pointer , ended by a NULL one. Max 256 splitted elements per call.
int split_count (char **split_result)
Count split elements.
char * str_replace (const char *string, const char *substr, const char *replacement)
Replace "substr" by "replacement" inside string taken from http://coding.debuntu.org/c-implementing-str_replace-replace-all-occurrences-substring By Chantra.
int str_sanitize (char *string, const char *mask, const char replacement)
clean a string by replacing evil characteres
int str_sanitize_ex (char *string, const unsigned int string_len, const char *mask, const unsigned int masklen, const char replacement)
clean a string by replacing evil characteres
int str_to_int (const char *s, int *i, const int base)
Helper for string to integer.
int str_to_int_ex (const char *s, NSTRBYTE start, NSTRBYTE end, int *i, const int base)
Helper for string[start to end] to integer. Automatically add /0 for conversion. Leave values untouched if any error occur. Work on a copy of the chunk.
int str_to_int_nolog (const char *s, NSTRBYTE start, NSTRBYTE end, int *i, const int base, N_STR **infos)
Helper for string[start to end] to integer. Automatically add /0 for conversion. Leave values untouched if any error occur. Work on a copy of the chunk.
int str_to_long (const char *s, long int *i, const int base)
Helper for string to integer.
int str_to_long_ex (const char *s, NSTRBYTE start, NSTRBYTE end, long int *i, const int base)
Helper for string[start to end] to integer. Automatically add /0 for conversion. Leave values untouched if any error occur. Work on a copy of the chunk.
int strcpy_u (char *from, char *to, NSTRBYTE to_size, char split, NSTRBYTE *it)
Copy from start to dest until from[ iterator ] == split.
int strlo (char *string, char *dest)
Upper case a string.
int strup (char *string, char *dest)
Upper case a string.
char * trim_nocopy (char *s)
trim and zero end the string, WARNING: keep and original pointer to delete the string correctly
int wildmat (register const char *text, register const char *p)
Written by Rich Salz rsalz at osf.org, refurbished by me. Wildcard pattern matching .
int wildmatcase (register const char *text, register const char *p)
Written by Rich Salz rsalz at osf.org, refurbished by me. Wildcard pattern matching case insensitive.
int write_and_fit (char **dest, NSTRBYTE *size, NSTRBYTE *written, char *src)
Detailed Description
string function Everything you need to use string is here
Author:
Castagnier Mickael
Version:
1.0
Date:
01/04/05
Definition in file n_str.c.
Function Documentation
int _free_nstr (N_STR ** ptr)
Free a N_STR structure and set the pointer to NULL.
Parameters:
ptr A N_STR *object to free
Returns:
TRUE or FALSE
Definition at line 43 of file n_str.c.
N_STR * char_to_nstr (char * src)
Convert a char into a N_STR, short version.
Parameters:
src A char *string to convert
Returns:
A N_STR copy of src or NULL
Definition at line 274 of file n_str.c.
References char_to_nstr_ex().
Referenced by add_strdup_to_msg(), netw_send_string_to(), and netw_send_string_to_all().
char_to_nstr_ex (char * from, NSTRBYTE nboct, N_STR ** to)
Convert a char into a N_STR, extended version.
Parameters:
from A char *string to convert
nboct The size to copy, from 1 octet to nboctet (ustrsizez(from))
to A N_STR pointer who will be Malloced
Returns:
True on success, FALSE on failure (to will be set to NULL)
Definition at line 245 of file n_str.c.
Referenced by char_to_nstr().
int empty_nstr (N_STR * nstr)
empty a N_STR string
Parameters:
nstr the N_STR *str string to empty
Returns:
TRUE or FALSE
Definition at line 197 of file n_str.c.
N_STR * file_to_nstr (char * filename)
Load a whole file into a N_STR. Be aware of the NSTRBYTE addressing limit (2GB commonly)
Parameters:
filename The filename to load inside a N_STR
Returns:
A valid N_STR or NULL
Definition at line 289 of file n_str.c.
References new_nstr().
int free_nstr_nolog (N_STR ** ptr)
Free a N_STR structure and set the pointer to NULL.
Parameters:
ptr A N_STR *object to free
Returns:
TRUE or FALSE
Definition at line 60 of file n_str.c.
void free_nstr_ptr (void * ptr)
Free a N_STR pointer structure.
Parameters:
ptr A N_STR *object to free
Definition at line 26 of file n_str.c.
Referenced by add_nstrdup_to_msg(), add_nstrptr_to_msg(), add_strdup_to_msg(), netw_add_msg(), netw_recv_func(), and scan_dir_ex().
void free_nstr_ptr_nolog (void * ptr)
Free a N_STR pointer structure.
Parameters:
ptr A N_STR *object to free
Definition at line 78 of file n_str.c.
int free_split_result (char *** tab)
Free a split result allocated array.
Parameters:
tab A pointer to a split result to free
Returns:
TRUE
Definition at line 971 of file n_str.c.
Referenced by load_config_file(), and split().
N_STR * new_nstr (NSTRBYTE size)
create a new N_STR string
Parameters:
size Size of the new string. 0 for no allocation.
Returns:
A new allocated N_STR or NULL
Definition at line 213 of file n_str.c.
Referenced by file_to_nstr(), unzip_nstr(), and zip_nstr().
char * nfgets (char * buffer, int size, FILE * stream)
try to fgets until new line
Parameters:
buffer The string where to read the file
size Size of the string
stream The file to read
Returns:
NULL or the captured string
Definition at line 127 of file n_str.c.
int nstr_to_fd (N_STR * str, FILE * out, int lock)
Write a N_STR content into a file.
Parameters:
str The N_STR *content to write down
out An opened FILE *handler
lock a write lock will be put if lock = 1
Returns:
TRUE or FALSE
Definition at line 359 of file n_str.c.
Referenced by nstr_to_file().
int nstr_to_file (N_STR * str, char * filename)
Write a N_STR content into a file.
Parameters:
str The N_STR *content to write down
filename The destination filename
Returns:
TRUE or FALSE
Definition at line 415 of file n_str.c.
References nstr_to_fd().
int nstrcat (N_STR * dst, N_STR * src)
Add N_STR *src content to N_STR *dst, resizing it if needed.
Parameters:
dst The N_STR *destination
src The N_STR *source to concatenate into dst
Returns:
TRUE or FALSE
Definition at line 1049 of file n_str.c.
References nstrcat_ex().
int nstrcat_bytes (N_STR * dest, void * data)
Append data into N_STR using internal N_STR size and cursor position. Wrapper to nstrcat_ex, with resize_flag on and a block size one byte higher than size.
Parameters:
dest The N_STR *destination (accumulator)
data The data to append
Returns:
TRUE or FALSE
Definition at line 1084 of file n_str.c.
References nstrcat_bytes_ex().
int nstrcat_bytes_ex (N_STR * dest, void * data, NSTRBYTE size)
Append data into N_STR using internal N_STR size and cursor position. Wrapper to nstrcat_ex, with resize_flag on and a block size one byte higher than size.
Parameters:
dest The N_STR *destination (accumulator)
data The data to append
size The number of octet of data we want to append in dest
Returns:
TRUE or FALSE
Definition at line 1063 of file n_str.c.
References nstrcat_ex().
Referenced by nstrcat_bytes().
int nstrcat_ex (N_STR * dest, void * src, NSTRBYTE size, NSTRBYTE blk_size, int resize_flag)
Append data into N_STR using internal N_STR size and cursor position.
Parameters:
dest The N_STR *destination (accumulator)
src The data to append
size The number of octet of data we want to append in dest
blk_size In case of resizing, this is the increment which will be used to reach (dest -> written + size)
resize_flag Set it to a positive non zero value to allow resizing, or to zero or negative to forbid resizing
Returns:
TRUE or FALSE
Definition at line 998 of file n_str.c.
Referenced by nstrcat(), and nstrcat_bytes_ex().
N_STR * nstrdup (N_STR * str)
Duplicate a N_STR.
Parameters:
str A N_STR *object to free
Returns:
A valid N_STR or NULL
Definition at line 634 of file n_str.c.
Referenced by add_nstrdup_to_msg().
int scan_dir (const char * dir, LIST * result, const int recurse)
Scan a list of directory and return a list of char *file.
Parameters:
dir The directory to scan
result A pointer to a valid LIST for the results
recurse Recursive search if TRUE, directory only if FALSE
Returns:
TRUE or FALSE
Definition at line 1146 of file n_str.c.
References scan_dir_ex().
int scan_dir_ex (const char * dir, const char * pattern, LIST * result, const int recurse, const int mode)
Scan a list of directory and return a list of char *file.
Parameters:
dir The directory to scan
pattern Pattern that files must follow to figure in the list
result A pointer to a valid LIST for the results
recurse Recursive search if TRUE, directory only if FALSE
mode 0 for a list of char* , 1 for a list of N_STR *
Returns:
TRUE or FALSE
Definition at line 1162 of file n_str.c.
References free_nstr_ptr(), list_push(), and wildmatcase().
Referenced by scan_dir().
skipu (char * string, char toskip, NSTRBYTE * iterator, int inc)
skip until 'toskip' occurence is found from 'iterator' to the next 'toskip' value. The new iterator index is automatically stored, returning to it first value if an error append.
Parameters:
string a char *stri:wqng to search in
toskip skipping while char character 'toskip' isnt found
iterator an int iteraor position on the string
inc an int to specify the step of skipping
Returns:
TRUE if success FALSE or ABORT if not
Definition at line 729 of file n_str.c.
Referenced by load_config_file().
int skipw (char * string, char toskip, NSTRBYTE * iterator, int inc)
skip while 'toskip' occurence is found from 'iterator' to the next non 'toskip' position. The new iterator index is automatically stored, returning to it first value if an error append.
Parameters:
string a char *string to search in
toskip skipping while char character 'toskip' is found
iterator an int iteraor position on the string
inc an int to specify the step of skipping
Returns:
TRUE if success FALSE or ABORT if not
Definition at line 675 of file n_str.c.
char ** split (char * str, const char * delim, int empty)
Split the strings into a an array of char *pointer , ended by a NULL one. Max 256 splitted elements per call.
Parameters:
str The char *str to split
delim The delimiter, one or more characters
empty Empty flag. If 1, then empty delimited areas will be added as NULL entries, else they will be skipped.
Returns:
An array of char *, ended by a NULL entry.
Definition at line 871 of file n_str.c.
References free_split_result().
Referenced by load_config_file().
int split_count (char ** split_result)
Count split elements.
Parameters:
split_result A char **result from a split call
Returns:
The number of elements or -1 if errors
Definition at line 951 of file n_str.c.
char * str_replace (const char * string, const char * substr, const char * replacement)
Replace "substr" by "replacement" inside string taken from http://coding.debuntu.org/c-implementing-str_replace-replace-all-occurrences-substring By Chantra.
Parameters:
string Original string to modify
substr String to search
replacement Substitution string
Returns:
A copy of the sustituted string or NULL
Definition at line 1377 of file n_str.c.
int str_sanitize (char * string, const char * mask, const char replacement)
clean a string by replacing evil characteres
Parameters:
string The string to change
mask The caracters to kill
replacement replacement for mask
Returns:
TRUE or FALSE
Definition at line 1442 of file n_str.c.
References str_sanitize_ex().
int str_sanitize_ex (char * string, const unsigned int string_len, const char * mask, const unsigned int masklen, const char replacement)
clean a string by replacing evil characteres
Parameters:
string The string to change
string_len Size of the data to treat
mask The caracters to kill
masklen size of mask
replacement replacement for mask
Returns:
TRUE or FALSE
Definition at line 1416 of file n_str.c.
Referenced by str_sanitize().
int str_to_int (const char * s, int * i, const int base)
Helper for string to integer.
Parameters:
s String to convert
i A pointer to an integer variable which will receieve the value.
base Base for converting values
Returns:
TRUE or FALSE
Definition at line 546 of file n_str.c.
References str_to_int_ex().
int str_to_int_ex (const char * s, NSTRBYTE start, NSTRBYTE end, int * i, const int base)
Helper for string[start to end] to integer. Automatically add /0 for conversion. Leave values untouched if any error occur. Work on a copy of the chunk.
Parameters:
s String to convert
start Start position of the chunk
end End position of the chunk
i A pointer to an integer variable which will receieve the value.
base Base for converting values
Returns:
TRUE or FALSE
Definition at line 446 of file n_str.c.
Referenced by str_to_int().
int str_to_int_nolog (const char * s, NSTRBYTE start, NSTRBYTE end, int * i, const int base, N_STR ** infos)
Helper for string[start to end] to integer. Automatically add /0 for conversion. Leave values untouched if any error occur. Work on a copy of the chunk.
Parameters:
s String to convert
start Start position of the chunk
end End position of the chunk
i A pointer to an integer variable which will receieve the value.
base Base for converting values
infos If not NULL , contain the errors. remember to free the pointer if returned !!
Returns:
TRUE or FALSE
Definition at line 499 of file n_str.c.
int str_to_long (const char * s, long int * i, const int base)
Helper for string to integer.
Parameters:
s String to convert
i A pointer to an integer variable which will receieve the value.
base Base for converting values
Returns:
TRUE or FALSE
Definition at line 617 of file n_str.c.
References str_to_long_ex().
int str_to_long_ex (const char * s, NSTRBYTE start, NSTRBYTE end, long int * i, const int base)
Helper for string[start to end] to integer. Automatically add /0 for conversion. Leave values untouched if any error occur. Work on a copy of the chunk.
Parameters:
s String to convert
start Start position of the chunk
end End position of the chunk
i A pointer to an integer variable which will receieve the value.
base Base for converting values
Returns:
TRUE or FALSE
Definition at line 569 of file n_str.c.
Referenced by str_to_long().
int strcpy_u (char * from, char * to, NSTRBYTE to_size, char split, NSTRBYTE * it)
Copy from start to dest until from[ iterator ] == split.
Parameters:
from Source string
to Dest string
to_size the maximum size to write
split stopping character
it Save of iterator
Returns:
TRUE or FALSE
Definition at line 830 of file n_str.c.
strlo (char * string, char * dest)
Upper case a string.
Parameters:
string the string to change to lower case
dest the string where storing result
Warning:
string must be same size as dest
Returns:
TRUE or FALSE
Definition at line 805 of file n_str.c.
int strup (char * string, char * dest)
Upper case a string.
Parameters:
string the string to change to upper case
dest the string where storing result
Warning:
string must be same size as dest
Returns:
TRUE or FALSE
Definition at line 782 of file n_str.c.
char * trim_nocopy (char * s)
trim and zero end the string, WARNING: keep and original pointer to delete the string correctly
Parameters:
s The string to trim
Returns:
the trimmed string or NULL
Definition at line 95 of file n_str.c.
Referenced by load_config_file().
int wildmat (register const char * text, register const char * p)
Written by Rich Salz rsalz at osf.org, refurbished by me. Wildcard pattern matching .
Parameters:
text The source text to search
p The text to search, with wildcards
Returns:
return TRUE, FALSE, or WILDMAT_ABORT.
Definition at line 1241 of file n_str.c.
int wildmatcase (register const char * text, register const char * p)
Written by Rich Salz rsalz at osf.org, refurbished by me. Wildcard pattern matching case insensitive.
Parameters:
text The source text to search
p The text to search, with wildcards
Returns:
return TRUE, FALSE, or WILDMAT_ABORT.
Definition at line 1308 of file n_str.c.
Referenced by scan_dir_ex().
int write_and_fit (char ** dest, NSTRBYTE * size, NSTRBYTE * written, char * src)
Parameters:
dest The dest string
size The current size, will be updated if written + strlen(dest) > size
written the number of octet added
src The source string to add
Returns:
TRUE on success or FALSE on a realloc error
Definition at line 1107 of file n_str.c.