Nilorea Library: n_thread_pool.c File Reference
n_thread_pool.c File Reference
#include <unistd.h>
#include <pthread.h>
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_thread_pool.h"
#include "nilorea/n_time.h"
Functions
int add_threaded_process (THREAD_POOL *thread_pool, void *(*func_ptr)(void *param), void *param, int mode)
add a function and params to a thread pool
int destroy_threaded_pool (THREAD_POOL **pool, int delay)
delete a thread_pool, exit the threads and free the structs
THREAD_POOL * new_thread_pool (int nbmaxthr, int nb_max_waiting)
Create a new pool of nbmaxthr threads.
int refresh_thread_pool (THREAD_POOL *thread_pool)
try to add some waiting DIRECT_PROCs on some free thread slots, else do nothing
int start_threaded_pool (THREAD_POOL *thread_pool)
Launch the process waiting for exectution in the thread pool.
void * thread_pool_processing_function (void *param)
Internal thread pool processing function.
int wait_for_threaded_pool (THREAD_POOL *thread_pool, int delay)
Wait for all the launched process in the thread pool to terminate.
Detailed Description
Thread pool functions
Author:
Castagnier Mickael
Version:
1.0
Date:
30/04/2014
Definition in file n_thread_pool.c.
Function Documentation
int add_threaded_process (THREAD_POOL * thread_pool, void *(*)(void *param) func_ptr, void * param, int mode)
add a function and params to a thread pool
Parameters:
thread_pool The target thread pool
func_ptr The function pointer to launch
param Eventual parameter struct to pass to the function
mode SYNCED_PROC: added to pool, but wait for a start call with other waiting procs. DIRECT_PROC: the function actually starts as quick as possible
Returns:
TRUE or FALSE
Definition at line 175 of file n_thread_pool.c.
References list_push().
Referenced by refresh_thread_pool().
int destroy_threaded_pool (THREAD_POOL ** pool, int delay)
delete a thread_pool, exit the threads and free the structs
Parameters:
pool The THREAD_POOL *object to kill
delay The THREAD_POOL *object to kill
Returns:
TRUE or FALSE
Definition at line 338 of file n_thread_pool.c.
References list_destroy(), and u_sleep().
THREAD_POOL * new_thread_pool (int nbmaxthr, int nb_max_waiting)
Create a new pool of nbmaxthr threads.
Parameters:
nbmaxthr number of active threads in the pool
nb_max_waiting max number of waiting procs in the pool
Returns:
NULL or a new trhead pool object
Definition at line 103 of file n_thread_pool.c.
References new_generic_list(), and thread_pool_processing_function().
int refresh_thread_pool (THREAD_POOL * thread_pool)
try to add some waiting DIRECT_PROCs on some free thread slots, else do nothing
Parameters:
thread_pool The thread pool to refresh
Returns:
TRUE or FALSE
Definition at line 405 of file n_thread_pool.c.
References add_threaded_process().
Referenced by wait_for_threaded_pool().
int start_threaded_pool (THREAD_POOL * thread_pool)
Launch the process waiting for exectution in the thread pool.
Parameters:
thread_pool The thread pool to launche
Returns:
TRUE or FALSE
Definition at line 255 of file n_thread_pool.c.
void * thread_pool_processing_function (void * param)
Internal thread pool processing function.
Parameters:
param Teh eventual param of a process
Returns:
NULL when exiting
Definition at line 21 of file n_thread_pool.c.
Referenced by new_thread_pool().
int wait_for_threaded_pool (THREAD_POOL * thread_pool, int delay)
Wait for all the launched process in the thread pool to terminate.
Parameters:
thread_pool The thread pool to wait
delay time between each check
Returns:
TRUE or FALSE
Definition at line 293 of file n_thread_pool.c.
References refresh_thread_pool(), and u_sleep().