Nilorea Library: n_time.c File Reference
n_time.c File Reference
#include <unistd.h>
#include "nilorea/n_time.h"
Functions
time_t get_msec (N_TIME *timer)
Poll any N_TIME HiTimer, returning msec, and moving currentTime to startTime.
time_t get_sec (N_TIME *timer)
Poll any N_TIME HiTimer, returning sec, and moving currentTime to startTime.
time_t get_usec (N_TIME *timer)
Poll any N_TIME HiTimer, returning usec, and moving currentTime to startTime.
void PAUSE (void)
make a pause in a terminal
int start_HiTimer (N_TIME *timer)
Initialize or restart from zero any N_TIME HiTimer.
void u_sleep (unsigned int usec)
wrapper around usleep for API consistency
Detailed Description
common time function
Author:
Castagnier Mickael
Version:
1.0
Date:
24/03/05
Definition in file n_time.c.
Function Documentation
time_t get_msec (N_TIME * timer)
Poll any N_TIME HiTimer, returning msec, and moving currentTime to startTime.
Parameters:
timer Any N_TIMER *timer you wanna poll
Returns:
The elapsed number of msec for the given N_TIME *timer
Definition at line 114 of file n_time.c.
Referenced by manage_particle().
time_t get_sec (N_TIME * timer)
Poll any N_TIME HiTimer, returning sec, and moving currentTime to startTime.
Parameters:
timer Any N_TIMER *timer you wanna poll
Returns:
The elapsed number of sec for the given N_TIME *timer
Definition at line 137 of file n_time.c.
time_t get_usec (N_TIME * timer)
Poll any N_TIME HiTimer, returning usec, and moving currentTime to startTime.
Parameters:
timer Any N_TIMER *timer you wanna poll
Returns:
The elapsed number of usec for the given N_TIME *timer
Definition at line 91 of file n_time.c.
void PAUSE (void)
make a pause in a terminal
Definition at line 46 of file n_time.c.
int start_HiTimer (N_TIME * timer)
Initialize or restart from zero any N_TIME HiTimer.
Parameters:
timer Any N_TIMER *timer you wanna start or reset
Returns:
TRUE or FALSE
Definition at line 66 of file n_time.c.
Referenced by init_particle_system().
void u_sleep (unsigned int usec)
wrapper around usleep for API consistency
Parameters:
usec Number of usec to sleep
Definition at line 35 of file n_time.c.
Referenced by destroy_threaded_pool(), netw_recv_func(), netw_send_func(), netw_wait_msg(), and wait_for_threaded_pool().