Nilorea Library: include/nilorea/n_zlib.h File Reference
include/nilorea/n_zlib.h File Reference
#include <zlib.h>
#include "n_str.h"
Functions
int CompressData (unsigned char *abSrc, int nLenSrc, unsigned char *abDst, int nLenDst)
Compress a string to another.
int GetMaxCompressedLen (int nLenSrc)
Return the maximum compressed size.
int UncompressData (unsigned char *abSrc, int nLenSrc, unsigned char *abDst, int nLenDst)
Uncompress a string to another.
N_STR * unzip_nstr (N_STR *src)
N_STR * zip_nstr (N_STR *src)
Detailed Description
ZLIB compression handler
Author:
Castagnier Mickael
Version:
1.0
Date:
27/06/2017
Definition in file n_zlib.h.
Function Documentation
int CompressData (unsigned char * abSrc, int nLenSrc, unsigned char * abDst, int nLenDst)
Compress a string to another.
Parameters:
abSrc source string
nLenSrc size of source string
abDst destination string
nLenDst destination length
Returns:
-1 or lenght of output
Definition at line 40 of file n_zlib.c.
Referenced by zip_nstr().
int GetMaxCompressedLen (int nLenSrc)
Return the maximum compressed size.
Parameters:
nLenSrc
Returns:
The size in bytes
Definition at line 24 of file n_zlib.c.
Referenced by zip_nstr().
int UncompressData (unsigned char * abSrc, int nLenSrc, unsigned char * abDst, int nLenDst)
Uncompress a string to another.
Parameters:
abSrc source string
nLenSrc size of source string
abDst destination string
nLenDst destination length
Returns:
-1 or lenght of output
Definition at line 70 of file n_zlib.c.
References LOG_ERR, and n_log.
Referenced by unzip_nstr().
N_STR* unzip_nstr (N_STR * src)
Parameters:
src The source string
Returns:
The uncompressed string or NULL
Definition at line 125 of file n_zlib.c.
References LOG_DEBUG, n_log, new_nstr(), and UncompressData().
N_STR* zip_nstr (N_STR * src)
Parameters:
src The source string
Returns:
The compressed string or NULL
Definition at line 103 of file n_zlib.c.
References CompressData(), GetMaxCompressedLen(), LOG_DEBUG, n_log, and new_nstr().