Nilorea Library: examples/ex_configfile.c File Reference
ex_configfile.c File Reference
#include "nilorea/n_config_file.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Examples
ex_configfile.c.
Definition at line 9 of file ex_configfile.c.
References config_endfor, config_foreach, destroy_config_file(), get_config_section_value(), get_nb_config_file_sections(), get_nb_config_file_sections_entries(), key, load_config_file(), LOG_DEBUG, LOG_ERR, LOG_INFO, n_log, and set_log_level().