Nilorea Library: examples/ex_threads.c File Reference
ex_threads.c File Reference
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include "nilorea/n_log.h"
#include "nilorea/n_thread_pool.h"
Functions
int main (int argc, char **argv)
void * occupy_thread (void *rest)
void process_args (int argc, char **argv)
void usage (void)
Variables
static pthread_t netw_thr
Function Documentation
main()
int main (int argc, char ** argv)
Examples
ex_threads.c.
Definition at line 113 of file ex_threads.c.
References add_threaded_process(), destroy_threaded_pool(), DIRECT_PROC, LOG_DEBUG, LOG_ERR, LOG_INFO, n_log, new_thread_pool(), occupy_thread(), process_args(), refresh_thread_pool(), set_log_level(), and wait_for_threaded_pool().
occupy_thread()
void * occupy_thread (void * rest)
Examples
ex_threads.c.
Definition at line 94 of file ex_threads.c.
References __n_assert, LOG_INFO, and n_log.
Referenced by main().
process_args()
void process_args (int argc, char ** argv)
Examples
ex_threads.c.
Definition at line 23 of file ex_threads.c.
References getoptret, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, LOG_NULL, set_log_level(), and usage().
Referenced by main().
usage()
void usage (void)
Examples
ex_threads.c.
Definition at line 16 of file ex_threads.c.
Referenced by process_args().
Variable Documentation
netw_thr
pthread_t netw_thr static
Examples
ex_threads.c.
Definition at line 14 of file ex_threads.c.