Nilorea Library: examples/ex_gui_netserver.c File Reference
ex_gui_netserver.c File Reference
#include "nilorea/n_common.h"
#include "nilorea/n_str.h"
#include "nilorea/n_list.h"
#include "nilorea/n_hash.h"
#include "nilorea/n_network.h"
#include "nilorea/n_network_msg.h"
#include "nilorea/n_user.h"
#include <allegro5/allegro.h>
#include <allegro5/allegro_audio.h>
#include <allegro5/allegro_acodec.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_image.h>
#include <allegro5/allegro_primitives.h>
#include <allegro5/allegro_ttf.h>
Macros
#define HEIGHT 480
#define WIDTH 640
Functions
int main (int argc, char *argv[])
void process_args (int argc, char **argv, char **bind_addr, char **port, int *ip_version)
int process_clients (NETWORK_POOL *netw_pool, N_USERLIST *userlist)
void usage (void)
Macro Definition Documentation
HEIGHT
#define HEIGHT 480
Examples
ex_gui_netserver.c.
Definition at line 8 of file ex_gui_netserver.c.
WIDTH
#define WIDTH 640
Examples
ex_gui_netserver.c.
Definition at line 7 of file ex_gui_netserver.c.
Function Documentation
main()
int main (int argc, char * argv[])
Examples
ex_gui_netserver.c.
Definition at line 256 of file ex_gui_netserver.c.
References __n_assert, _nstr, _str, active_object, display, DONE, fps_timer, free_nstr, getoptret, HEIGHT, ip_version, key, KEY_CTRL, KEY_DOWN, KEY_ESC, KEY_LEFT, KEY_RIGHT, KEY_SPACE, KEY_UP, list_destroy(), LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, logic_timer, n_abort(), n_log, netw, netw_accept_from_ex(), netw_make_listening(), netw_new_pool(), netw_pool_add(), netw_pool_nbclients(), netw_set_user_id(), netw_sigchld_handler(), netw_start_thr_engine(), NETWORK_IPALL, new_generic_list(), nstrprintf, process_args(), process_clients(), scr_buf, server, set_log_level(), userlist_add_user(), userlist_new(), userlist_send_waiting_msgs(), and WIDTH.
process_args()
void process_args (int argc, char ** argv, char ** bind_addr, char ** port, int * ip_version)
Examples
ex_gui_netserver.c.
Definition at line 38 of file ex_gui_netserver.c.
References getoptret, LOG_DEBUG, LOG_ERR, LOG_INFO, log_level, LOG_NOTICE, LOG_NULL, n_log, NETWORK_IPV4, NETWORK_IPV6, set_log_level(), and usage().
Referenced by main().
process_clients()
int process_clients (NETWORK_POOL * netw_pool, N_USERLIST * userlist)
Examples
ex_gui_netserver.c.
Definition at line 154 of file ex_gui_netserver.c.
References __n_assert, free_nstr, hash_val, ht_foreach, list_destroy(), list_push(), LOG_DEBUG, LOG_ERR, LOG_INFO, LOG_NOTICE, n_log, NETMSG_GET_BOX, NETMSG_IDENT_REPLY_OK, NETMSG_IDENT_REQUEST, netmsg_make_ping(), NETMSG_PING_REPLY, NETMSG_PING_REQUEST, NETMSG_POSITION, NETMSG_QUIT, NETMSG_STRING, netw, netw_close(), netw_get_ident(), netw_get_msg(), netw_get_ping(), netw_get_state(), netw_msg_get_type(), netw_pool_broadcast(), netw_send_ident(), netw_send_ping(), netw_send_quit(), new_generic_list(), read_lock, unlock, userlist_add_msg_to(), userlist_add_msg_to_all(), and userlist_del_user().
Referenced by main().
usage()
void usage (void)
Examples
ex_gui_netserver.c.
Definition at line 26 of file ex_gui_netserver.c.
Referenced by process_args().