Nilorea Library: examples/ex_monolith.c File Reference
ex_monolith.c File Reference
#include "nilorea.h"
Functions
int main (void)
Function Documentation
main()
int main (void)
Examples
ex_monolith.c.
Definition at line 9 of file ex_monolith.c.
References _nstr, free_nstr, LOG_DEBUG, new_nstr(), nstrcat(), nstrdup(), nstrprintf, nstrprintf_cat, and set_log_level().