Nilorea Library: examples/ex_signals.c File Reference
ex_signals.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <signal.h>
#include <assert.h>
#include "nilorea/n_signals.h"
#include "nilorea/n_log.h"
#include <libgen.h>
Functions
void cause_calamity (void)
void cause_segfault (void)
int divide_by_zero (void)
void illegal_instruction (void)
void infinite_loop (void)
int main (int argc, char *argv[])
void stack_overflow (void)
Variables
char * progname = NULL
Function Documentation
cause_calamity()
void cause_calamity (void)
Examples
ex_signals.c.
Definition at line 51 of file ex_signals.c.
References cause_segfault(), divide_by_zero(), illegal_instruction(), infinite_loop(), and stack_overflow().
Referenced by main().
cause_segfault()
void cause_segfault (void)
Examples
ex_signals.c.
Definition at line 72 of file ex_signals.c.
Referenced by cause_calamity().
divide_by_zero()
int divide_by_zero (void)
Examples
ex_signals.c.
Definition at line 65 of file ex_signals.c.
Referenced by cause_calamity().
illegal_instruction()
void illegal_instruction (void)
Examples
ex_signals.c.
Definition at line 99 of file ex_signals.c.
Referenced by cause_calamity().
infinite_loop()
void infinite_loop (void)
Examples
ex_signals.c.
Definition at line 86 of file ex_signals.c.
Referenced by cause_calamity().
main()
int main (int argc, char * argv[])
Examples
ex_signals.c.
Definition at line 32 of file ex_signals.c.
References cause_calamity(), LOG_DEBUG, LOG_STDERR, n_log, progname, set_log_level(), and set_signal_handler().
stack_overflow()
void stack_overflow (void)
Examples
ex_signals.c.
Definition at line 78 of file ex_signals.c.
References stack_overflow().
Referenced by cause_calamity(), and stack_overflow().
Variable Documentation
progname
char* progname = NULL
Examples
ex_signals.c.
Definition at line 30 of file ex_signals.c.
Referenced by main(), and set_signal_handler().