Nilorea Library: PHYSICS: simple 3D movement simulation
PHYSICS: simple 3D movement simulation
Data Structures
struct PHYSICS
structure of the physics of an object
Macros
#define copy_point(__src_, __dst_) memcpy(__dst_ , __src_ , sizeof(VECTOR3D));
VECTOR3D copy wrapper.
#define MOVE_INTER 1
PHYSICS object state for move interpolated between two position.
#define MOVE_SIMU 2
PHYSICS object state for move simulated from latest update.
#define MOVE_STOPPED 0
PHYSICS object state for STOPPED.
#define VECTOR3D_COLLINEAR -1
value when the two VECTOR3D are collinear
#define VECTOR3D_DO_INTERSECT 0
value when the two VECTOR3D are intersecting
#define VECTOR3D_DONT_INTERSECT -2
value when the two VECTOR3D are not connected
#define VECTOR3D_SET(VECTOR, X, Y, Z)
helper to set a VECTOR3D position
Typedefs
typedef double VECTOR3D[3]
struct of a point
Functions
double distance (VECTOR3D *p1, VECTOR3D *p2)
compute the distance between two VECTOR3D points
int update_physics_position (PHYSICS *object, double delta_t)
Update object position, reversed.
int update_physics_position_nb (PHYSICS *object, int it, double delta_t)
Update object position componant.
int update_physics_position_reverse (PHYSICS *object, double delta_t)
Update object position, reversed.
int update_physics_position_reverse_nb (PHYSICS *object, int it, double delta_t)
Update object position componant, reversed.
double vector_angle_between (VECTOR3D *vec1, VECTOR3D *vec2)
Compute angle beteen two VECTOR3D.
double vector_dot_product (VECTOR3D *vec1, VECTOR3D *vec2)
Compute the dot product of two VECTOR3D.
int vector_intersect (VECTOR3D *p0, VECTOR3D *p1, VECTOR3D *p2, VECTOR3D *p3, VECTOR3D *px)
Compute if two vectors are intersecting or not.
double vector_normalize (VECTOR3D *vec)
Return the normalized value of vec.
Detailed Description
Data Structure Documentation
PHYSICS
struct PHYSICS
structure of the physics of an object
Examples
ex_gui_dictionary.c, and ex_gui_particles.c.
Definition at line 49 of file n_3d.h.
Data Fields
VECTOR3D acceleration ax,ay,az actual acceleration
VECTOR3D angular_acceleration rax,ray,raz actual angular acceleration
VECTOR3D angular_speed rvx,rvy,rvz actual angular speed
int can_jump ability
time_t delta_t last delta_t used
VECTOR3D gravity gx , gy , gz gravity
VECTOR3D orientation ax,ay,az actual rotation position
VECTOR3D position x,y,z actual position
VECTOR3D speed vx,vy,vz actual speed
int sz size
int type optionnal type id
Macro Definition Documentation
copy_point
#define copy_point (__src_, __dst_) memcpy(__dst_ , __src_ , sizeof(VECTOR3D));
#include <include/nilorea/n_3d.h>
VECTOR3D copy wrapper.
Definition at line 95 of file n_3d.h.
MOVE_INTER
#define MOVE_INTER 1
#include <include/nilorea/n_3d.h>
PHYSICS object state for move interpolated between two position.
Definition at line 27 of file n_3d.h.
MOVE_SIMU
#define MOVE_SIMU 2
#include <include/nilorea/n_3d.h>
PHYSICS object state for move simulated from latest update.
Definition at line 29 of file n_3d.h.
MOVE_STOPPED
#define MOVE_STOPPED 0
#include <include/nilorea/n_3d.h>
PHYSICS object state for STOPPED.
Definition at line 25 of file n_3d.h.
VECTOR3D_COLLINEAR
#define VECTOR3D_COLLINEAR -1
#include <include/nilorea/n_3d.h>
value when the two VECTOR3D are collinear
Definition at line 34 of file n_3d.h.
VECTOR3D_DO_INTERSECT
#define VECTOR3D_DO_INTERSECT 0
#include <include/nilorea/n_3d.h>
value when the two VECTOR3D are intersecting
Definition at line 36 of file n_3d.h.
VECTOR3D_DONT_INTERSECT
#define VECTOR3D_DONT_INTERSECT -2
#include <include/nilorea/n_3d.h>
value when the two VECTOR3D are not connected
Definition at line 32 of file n_3d.h.
VECTOR3D_SET
#define VECTOR3D_SET (VECTOR, X, Y, Z)
#include <include/nilorea/n_3d.h>
Value:
   VECTOR[ 0 ] = (X) ; \
   VECTOR[ 1 ] = (Y) ; \
   VECTOR[ 2 ] = (Z) ;
helper to set a VECTOR3D position
Examples
ex_gui_dictionary.c, and ex_gui_particles.c.
Definition at line 43 of file n_3d.h.
Typedef Documentation
VECTOR3D
typedef double VECTOR3D[3]
#include <include/nilorea/n_3d.h>
struct of a point
Definition at line 39 of file n_3d.h.
Function Documentation
distance()
double distance (VECTOR3D * p1, VECTOR3D * p2)
#include <include/nilorea/n_3d.h>
compute the distance between two VECTOR3D points
Parameters
p1 The first point
p2 The second point
Returns
The computed distance
Definition at line 18 of file n_3d.c.
update_physics_position()
int update_physics_position (PHYSICS * object, double delta_t)
#include <include/nilorea/n_3d.h>
Update object position, reversed.
Wrapper of update_physics_position_reverse_nb to update each componants.
Parameters
object The object physics to update
delta_t Elapsed time since last call for componant update computing
Returns
TRUE or FALSE
Definition at line 98 of file n_3d.c.
References update_physics_position_nb().
Referenced by manage_particle_ex().
update_physics_position_nb()
int update_physics_position_nb (PHYSICS * object, int it, double delta_t)
#include <include/nilorea/n_3d.h>
Update object position componant.
Parameters
object The object physics to update
it Componant of VECTOR3D to update. it values : 0 -> x, 1 -> y , 2 -> z
delta_t Elapsed time since last call for componant update computing
Returns
TRUE or FALSE
Definition at line 34 of file n_3d.c.
References __n_assert.
Referenced by update_physics_position(), and update_physics_position_reverse().
update_physics_position_reverse()
int update_physics_position_reverse (PHYSICS * object, double delta_t)
#include <include/nilorea/n_3d.h>
Update object position, reversed.
Wrapper of update_physics_position_reverse_nb to update each componants.
Parameters
object The object physics to update
delta_t Elapsed time since last call for componant update computing
Returns
TRUE or FALSE
Definition at line 73 of file n_3d.c.
References update_physics_position_nb().
update_physics_position_reverse_nb()
int update_physics_position_reverse_nb (PHYSICS * object, int it, double delta_t)
#include <include/nilorea/n_3d.h>
Update object position componant, reversed.
Parameters
object The object physics to update
it Componant of VECTOR3D to update. it values : 0 -> x, 1 -> y , 2 -> z
delta_t Elapsed time since last call for componant update computing
Returns
TRUE or FALSE
Definition at line 55 of file n_3d.c.
References __n_assert.
vector_angle_between()
double vector_angle_between (VECTOR3D * vec1, VECTOR3D * vec2)
#include <include/nilorea/n_3d.h>
Compute angle beteen two VECTOR3D.
Parameters
vec1 first VECTOR3D
vec2 second VECTOR3D
Returns
angle between vectors in rad (todeg = returnval * 180/PI_2)
Definition at line 254 of file n_3d.c.
References vector_dot_product(), and vector_normalize().
vector_dot_product()
double vector_dot_product (VECTOR3D * vec1, VECTOR3D * vec2)
#include <include/nilorea/n_3d.h>
Compute the dot product of two VECTOR3D.
Parameters
vec1 first VECTOR3D
vec2 second VECTOR3D
Returns
dot product value
Definition at line 224 of file n_3d.c.
Referenced by vector_angle_between().
vector_intersect()
int vector_intersect (VECTOR3D * p1, VECTOR3D * p2, VECTOR3D * p3, VECTOR3D * p4, VECTOR3D * px)
#include <include/nilorea/n_3d.h>
Compute if two vectors are intersecting or not.
Parameters
p1 First point of vector 1
p2 Second poinf of vector 1
p3 First point of vector 2
p4 Second point of vector 2
px Storage for the eventual point
Returns
VECTOR3D_DONT_INTERSECT , VECTOR3D_COLLINEAR or VECTOR3D_DO_INTERSECT
Definition at line 132 of file n_3d.c.
References same_sign(), VECTOR3D_COLLINEAR, VECTOR3D_DO_INTERSECT, and VECTOR3D_DONT_INTERSECT.
vector_normalize()
double vector_normalize (VECTOR3D * vec)
#include <include/nilorea/n_3d.h>
Return the normalized value of vec.
Parameters
vec VECTOR3D to normalize
Returns
normalized value of vec
Definition at line 236 of file n_3d.c.
Referenced by vector_angle_between().