Nilorea Library: GAMES: game utilities
GAMES: game utilities
Data Structures
struct GAME_ENV
Game Environment structure.
struct PARTICLE
Structure of a single particle.
struct PARTICLE_SYSTEM
Structure of a particle system.
Macros
#define BITMAP_PART 8
bitmap particle
#define CIRCLE_PART 6
circle particle
#define CPU_USE_FULL -1
full use of CPU
#define CPU_USE_LESS 10
wait more
#define CPU_USE_NICE 0
let the other process have some times
#define FIRE_PART 4
fire particle
#define NORMAL_PART 0
classic moving particle
#define PIXEL_PART 7
pixel particle
#define SINUS_PART 1
sinus based moving particle
#define SNOW_PART 3
snow particle
#define STAR_PART 5
star particle
#define TEXT_PART 9
bitmap particle
#define TRANS_PART 2
transparent particle
Typedefs
typedef struct GAME_ENV GAME_ENV
Game Environment structure.
typedef struct PARTICLE PARTICLE
Structure of a single particle.
typedef struct PARTICLE_SYSTEM PARTICLE_SYSTEM
Structure of a particle system.
Functions
int add_particle (PARTICLE_SYSTEM *psys, int spr, int mode, int lifetime, int size, ALLEGRO_COLOR color, PHYSICS object)
int add_particle_ex (PARTICLE_SYSTEM *psys, int spr, int mode, int off_x, int off_y, int lifetime, int size, ALLEGRO_COLOR color, double vx, double vy, double vz, double ax, double ay, double az)
void destroy_game_env (GAME_ENV **game)
int draw_particle (PARTICLE_SYSTEM *psys, double xpos, double ypos, int w, int h, double range)
int free_particle_system (PARTICLE_SYSTEM **psys)
int init_game_env (GAME_ENV **game)
int init_particle_system (PARTICLE_SYSTEM **psys, int max, double x, double y, double z, int max_sprites)
GAME_ENV * load_game_config (char *config_name)
load a config from file
int manage_particle (PARTICLE_SYSTEM *psys)
int move_particles (PARTICLE_SYSTEM *psys, double vx, double vy, double vz)
Detailed Description
Function Documentation
void destroy_game_env (GAME_ENV ** game)
Parameters
game a pointer a to a game structure to destroy
Definition at line 58 of file n_games.c.
References Free.
Referenced by load_game_config().
int init_game_env (GAME_ENV ** game)
Parameters
game a pointer to a game structure to allocate
Returns
TRUE or FALSE
Definition at line 15 of file n_games.c.
References CPU_USE_FULL, LOG_ERR, Malloc, and n_log.
Referenced by load_game_config().
GAME_ENV* load_game_config (char * config_name)
load a config from file
Parameters
config_name the name of the game file config
Returns
Loaded config or NULL
Definition at line 75 of file n_games.c.
References CPU_USE_FULL, CPU_USE_LESS, CPU_USE_NICE, destroy_game_env(), init_game_env(), LOG_ERR, LOG_NOTICE, and n_log.