Nilorea Library: NETWORK MESSAGES: tools to serialize integers, double, N_STR from and back to a single N_STR *message
NETWORK MESSAGES: tools to serialize integers, double, N_STR from and back to a single N_STR *message
Data Structures
struct NETW_MSG
network message, array of char and int
Macros
#define NETMSG_BOX 8
Network Message is box retrieving reply: (int x , int y , int z , N_STR *data)
#define NETMSG_GET_BOX 7
Network Message is box retrieve: int x , int y , int z.
#define NETMSG_IDENT_REPLY_NOK 2
Network Message is identification reply NON OK: (int)type , (int)id , (N_STR *)name , (N_STR *)password.
#define NETMSG_IDENT_REPLY_OK 1
Network Message is identification reply OK : (int)type , (int)id , (N_STR *)name , (N_STR *)password.
#define NETMSG_IDENT_REQUEST 0
Network Message is identification request: (int)type , (int)id , (N_STR *)name , (N_STR *)password.
#define NETMSG_PING_REPLY 6
Network Message is ping reply: (int)type , (int)id_from , (int)id_to.
#define NETMSG_PING_REQUEST 5
Network Message is ping request: (int)type , (int)id_from , (int)id_to.
#define NETMSG_POSITION 4
Network Message position: (int)type , (int)id , (int)X , (int)Y , (int)x_shift , (int)y_shift ,(int)vx ,(int)vy , (int)speed , (int)acceleration , (int)time_stamp.
#define NETMSG_QUIT 9
Network asking for exit.
#define NETMSG_STRING 3
Network Message is string: (int)type , (int)id , (N_STR *)name , (N_STR *)chan , (N_STR *)text , (int)color.
Functions
int add_int_to_msg (NETW_MSG *msg, int value)
Add an int to the int list int the message.
int add_nb_to_msg (NETW_MSG *msg, double value)
Add an float to the message.
int add_nstrdup_to_msg (NETW_MSG *msg, N_STR *str)
Add a copy of str to the string list in the message.
int add_nstrptr_to_msg (NETW_MSG *msg, N_STR *str)
Add a string to the string list in the message.
int add_strdup_to_msg (NETW_MSG *msg, const char *str)
Add a copy of char *str to the string list in the message.
int create_msg (NETW_MSG **msg)
Create a NETW_MSG *object.
int delete_msg (NETW_MSG **msg)
Delete a NETW_MSG *object.
double double_swap (double value)
Swap bytes endiannes for a double.
int empty_msg (NETW_MSG **msg)
Empty a NETW_MSG *object.
int get_int_from_msg (NETW_MSG *msg, int *value)
Get a number from a message number list.
int get_nb_from_msg (NETW_MSG *msg, double *value)
Get a number from a message number list.
int get_nstr_from_msg (NETW_MSG *msg, N_STR **str)
Get a string from a message string list.
int get_str_from_msg (NETW_MSG *msg, char **str)
Get a string from a message string list.
double htond (double value)
If needed swap bytes for a double.
NETW_MSG * make_msg_from_str (N_STR *str)
Make a single message of the string.
N_STR * make_str_from_msg (NETW_MSG *msg)
Make a single string of the message.
N_STR * netmsg_make_ident (int type, int id, N_STR *name, N_STR *passwd)
Add a formatted NETWMSG_IDENT message to the specified network.
N_STR * netmsg_make_ping (int type, int id_from, int id_to, int time)
Make a ping message to send to a network.
N_STR * netmsg_make_position_msg (int id, double X, double Y, double vx, double vy, double acc_x, double acc_y, int time_stamp)
make a network NETMSG_POSITION message with given parameters
N_STR * netmsg_make_quit_msg (void)
make a generic network NETMSG_QUIT message
N_STR * netmsg_make_string_msg (int id_from, int id_to, N_STR *name, N_STR *chan, N_STR *txt, int color)
make a network NETMSG_STRING message with given parameters
int netw_get_ident (N_STR *msg, int *type, int *ident, N_STR **name, N_STR **passwd)
Retrieves identification from netwmsg.
int netw_get_ping (N_STR *msg, int *type, int *from, int *to, int *time)
Retrieves a ping travel elapsed time.
int netw_get_position (N_STR *msg, int *id, double *X, double *Y, double *vx, double *vy, double *acc_x, double *acc_y, int *time_stamp)
Retrieves position from netwmsg.
int netw_get_quit (N_STR *msg)
get a formatted NETWMSG_QUIT message from the specified network
int netw_get_string (N_STR *msg, int *id, N_STR **name, N_STR **chan, N_STR **txt, int *color)
Retrieves string from netwmsg.
int netw_msg_get_type (N_STR *msg)
Get the type of message without killing the first number. Use with netw_get_XXX.
double ntohd (double value)
If needed swap bytes for a double.
Detailed Description
Data Structure Documentation
NETW_MSG
struct NETW_MSG
network message, array of char and int
Definition at line 48 of file n_network_msg.h.
Data Fields
LIST * tabflt array of casted double value
LIST * tabint array of int
LIST * tabstr array of N_STR
Macro Definition Documentation
NETMSG_BOX
#define NETMSG_BOX 8
#include <include/nilorea/n_network_msg.h>
Network Message is box retrieving reply: (int x , int y , int z , N_STR *data)
Examples
ex_gui_netclient.c.
Definition at line 43 of file n_network_msg.h.
NETMSG_GET_BOX
#define NETMSG_GET_BOX 7
#include <include/nilorea/n_network_msg.h>
Network Message is box retrieve: int x , int y , int z.
Examples
ex_gui_netclient.c, and ex_gui_netserver.c.
Definition at line 41 of file n_network_msg.h.
NETMSG_IDENT_REPLY_NOK
#define NETMSG_IDENT_REPLY_NOK 2
#include <include/nilorea/n_network_msg.h>
Network Message is identification reply NON OK: (int)type , (int)id , (N_STR *)name , (N_STR *)password.
Examples
ex_gui_netclient.c.
Definition at line 31 of file n_network_msg.h.
NETMSG_IDENT_REPLY_OK
#define NETMSG_IDENT_REPLY_OK 1
#include <include/nilorea/n_network_msg.h>
Network Message is identification reply OK : (int)type , (int)id , (N_STR *)name , (N_STR *)password.
Examples
ex_gui_netclient.c, and ex_gui_netserver.c.
Definition at line 29 of file n_network_msg.h.
NETMSG_IDENT_REQUEST
#define NETMSG_IDENT_REQUEST 0
#include <include/nilorea/n_network_msg.h>
Network Message is identification request: (int)type , (int)id , (N_STR *)name , (N_STR *)password.
Examples
ex_gui_netclient.c, and ex_gui_netserver.c.
Definition at line 27 of file n_network_msg.h.
NETMSG_PING_REPLY
#define NETMSG_PING_REPLY 6
#include <include/nilorea/n_network_msg.h>
Network Message is ping reply: (int)type , (int)id_from , (int)id_to.
Examples
ex_gui_netclient.c, and ex_gui_netserver.c.
Definition at line 39 of file n_network_msg.h.
NETMSG_PING_REQUEST
#define NETMSG_PING_REQUEST 5
#include <include/nilorea/n_network_msg.h>
Network Message is ping request: (int)type , (int)id_from , (int)id_to.
Examples
ex_gui_netclient.c, and ex_gui_netserver.c.
Definition at line 37 of file n_network_msg.h.
NETMSG_POSITION
#define NETMSG_POSITION 4
#include <include/nilorea/n_network_msg.h>
Network Message position: (int)type , (int)id , (int)X , (int)Y , (int)x_shift , (int)y_shift ,(int)vx ,(int)vy , (int)speed , (int)acceleration , (int)time_stamp.
Examples
ex_gui_netclient.c, and ex_gui_netserver.c.
Definition at line 35 of file n_network_msg.h.
NETMSG_QUIT
#define NETMSG_QUIT 9
#include <include/nilorea/n_network_msg.h>
Network asking for exit.
Examples
ex_gui_netclient.c, and ex_gui_netserver.c.
Definition at line 45 of file n_network_msg.h.
NETMSG_STRING
#define NETMSG_STRING 3
#include <include/nilorea/n_network_msg.h>
Network Message is string: (int)type , (int)id , (N_STR *)name , (N_STR *)chan , (N_STR *)text , (int)color.
Examples
ex_gui_netclient.c, and ex_gui_netserver.c.
Definition at line 33 of file n_network_msg.h.
Function Documentation
add_int_to_msg()
int add_int_to_msg (NETW_MSG * msg, int value)
#include <include/nilorea/n_network_msg.h>
Add an int to the int list int the message.
Parameters
msg A NETW_MSG *object to complete with the value
value The value to add to the message
Returns
TRUE or FALSE
Definition at line 181 of file n_network_msg.c.
References __n_assert, list_push(), and Malloc.
Referenced by make_msg_from_str(), netmsg_make_ident(), netmsg_make_ping(), netmsg_make_position_msg(), netmsg_make_quit_msg(), netmsg_make_string_msg(), and send_net_datas().
add_nb_to_msg()
int add_nb_to_msg (NETW_MSG * msg, double value)
#include <include/nilorea/n_network_msg.h>
Add an float to the message.
Parameters
msg A NETW_MSG *object to complete with the value
value The value to add to the message
Warning
The floating value will be rounded by the network serialization !
Returns
TRUE or FALSE
Definition at line 159 of file n_network_msg.c.
References __n_assert, list_push(), and Malloc.
Referenced by make_msg_from_str(), and netmsg_make_position_msg().
add_nstrdup_to_msg()
int add_nstrdup_to_msg (NETW_MSG * msg, N_STR * str)
#include <include/nilorea/n_network_msg.h>
Add a copy of str to the string list in the message.
Parameters
msg A NETW_MSG *object to complete with the string
str The string to add to the message
Returns
TRUE or FALSE
Definition at line 219 of file n_network_msg.c.
References __n_assert, free_nstr_ptr(), list_push(), and nstrdup().
Referenced by netmsg_make_ident(), netmsg_make_string_msg(), and send_net_datas().
add_nstrptr_to_msg()
int add_nstrptr_to_msg (NETW_MSG * msg, N_STR * str)
#include <include/nilorea/n_network_msg.h>
Add a string to the string list in the message.
Parameters
msg A NETW_MSG *object to complete with the string
str The string to add to the message
Returns
TRUE or FALSE
Definition at line 203 of file n_network_msg.c.
References __n_assert, free_nstr_ptr(), and list_push().
Referenced by make_msg_from_str(), and send_net_datas().
add_strdup_to_msg()
int add_strdup_to_msg (NETW_MSG * msg, const char * str)
#include <include/nilorea/n_network_msg.h>
Add a copy of char *str to the string list in the message.
Parameters
msg A NETW_MSG *object to complete with the string
str The string to add to the message
Returns
TRUE or FALSE
Definition at line 237 of file n_network_msg.c.
References __n_assert, char_to_nstr(), free_nstr_ptr(), and list_push().
create_msg()
int create_msg (NETW_MSG ** msg)
#include <include/nilorea/n_network_msg.h>
Create a NETW_MSG *object.
Parameters
msg A NETW_MSG *object
Returns
TRUE or FALSE
Definition at line 78 of file n_network_msg.c.
References __n_assert, LOG_ERR, Malloc, n_log, and new_generic_list().
Referenced by make_msg_from_str(), netmsg_make_ident(), netmsg_make_ping(), netmsg_make_position_msg(), netmsg_make_quit_msg(), netmsg_make_string_msg(), and send_net_datas().
delete_msg()
int delete_msg (NETW_MSG ** msg)
#include <include/nilorea/n_network_msg.h>
Delete a NETW_MSG *object.
Parameters
msg A NETW_MSG *object to delete
Returns
TRUE or FALSE
Definition at line 106 of file n_network_msg.c.
References Free, list_destroy(), LOG_ERR, and n_log.
Referenced by get_net_datas(), netmsg_make_ident(), netmsg_make_ping(), netmsg_make_position_msg(), netmsg_make_quit_msg(), netmsg_make_string_msg(), netw_get_ident(), netw_get_ping(), netw_get_position(), netw_get_quit(), netw_get_string(), and send_net_datas().
double_swap()
double double_swap (double value)
#include <include/nilorea/n_network_msg.h>
Swap bytes endiannes for a double.
Parameters
value The double to swap
Returns
A swapped double
Definition at line 18 of file n_network_msg.c.
Referenced by htond(), and ntohd().
empty_msg()
int empty_msg (NETW_MSG ** msg)
#include <include/nilorea/n_network_msg.h>
Empty a NETW_MSG *object.
Parameters
msg A NETW_MSG **object
Returns
TRUE or FALSE
Definition at line 139 of file n_network_msg.c.
References __n_assert, and list_empty().
get_int_from_msg()
int get_int_from_msg (NETW_MSG * msg, int * value)
#include <include/nilorea/n_network_msg.h>
Get a number from a message number list.
Parameters
msg A NETW_MSG *object for extracting number
value A int value where you want to store the result
Returns
A pointer to the N_STR, Do not forget to free it !
Definition at line 281 of file n_network_msg.c.
References __n_assert, Free, and list_shift.
Referenced by get_net_datas(), netw_get_ident(), netw_get_ping(), netw_get_position(), netw_get_quit(), and netw_get_string().
get_nb_from_msg()
int get_nb_from_msg (NETW_MSG * msg, double * value)
#include <include/nilorea/n_network_msg.h>
Get a number from a message number list.
Parameters
msg A NETW_MSG *object for extracting number
value A int value where you want to store the result
Returns
A pointer to the N_STR, Do not forget to free it !
Definition at line 257 of file n_network_msg.c.
References __n_assert, Free, and list_shift.
Referenced by netw_get_position().
get_nstr_from_msg()
int get_nstr_from_msg (NETW_MSG * msg, N_STR ** value)
#include <include/nilorea/n_network_msg.h>
Get a string from a message string list.
Parameters
msg The NETW_MSG where you have a str to get
value A pointer to a NULL N_STR for storage
Returns
TRUE or FALSE
Definition at line 306 of file n_network_msg.c.
References __n_assert, list_shift, LOG_ERR, and n_log.
Referenced by get_net_datas(), netw_get_ident(), and netw_get_string().
get_str_from_msg()
int get_str_from_msg (NETW_MSG * msg, char ** value)
#include <include/nilorea/n_network_msg.h>
Get a string from a message string list.
Parameters
msg The NETW_MSG where you have a str to get
value A pointer to a NULL N_STR for storage
Returns
TRUE or FALSE
Definition at line 333 of file n_network_msg.c.
References __n_assert, Free, list_shift, LOG_ERR, and n_log.
htond()
double htond (double value)
#include <include/nilorea/n_network_msg.h>
If needed swap bytes for a double.
Parameters
value The value to eventually swap
Returns
The modified value
Definition at line 44 of file n_network_msg.c.
References double_swap().
Referenced by make_str_from_msg().
make_msg_from_str()
NETW_MSG * make_msg_from_str (N_STR * str)
#include <include/nilorea/n_network_msg.h>
Make a single message of the string.
Parameters
str A N_STR structure to convert into a NETW_MSG one
Returns
A pointer to the generated NETW_MSG, do not forget to free it after use !
Definition at line 477 of file n_network_msg.c.
References __n_assert, add_int_to_msg(), add_nb_to_msg(), add_nstrptr_to_msg(), create_msg(), Malloc, and ntohd().
Referenced by get_net_datas(), netw_get_ident(), netw_get_ping(), netw_get_position(), netw_get_quit(), and netw_get_string().
make_str_from_msg()
N_STR * make_str_from_msg (NETW_MSG * msg)
#include <include/nilorea/n_network_msg.h>
Make a single string of the message.
Parameters
msg A NETW_MSG structure to convert into a N_STR one
Returns
A pointer to the generated N_STR, do not forget to free it after use !
Definition at line 361 of file n_network_msg.c.
References __n_assert, htond(), and Malloc.
Referenced by netmsg_make_ident(), netmsg_make_ping(), netmsg_make_position_msg(), netmsg_make_quit_msg(), netmsg_make_string_msg(), and send_net_datas().
netmsg_make_ident()
N_STR * netmsg_make_ident (int type, int id, N_STR * name, N_STR * passwd)
#include <include/nilorea/n_network_msg.h>
Add a formatted NETWMSG_IDENT message to the specified network.
Parameters
type type of identification (NETW_IDENT_REQUEST , NETW_IDENT_NEW)
id The ID of the sending client
name Username
passwd Password
Returns
N_STR *netmsg or NULL
Definition at line 622 of file n_network_msg.c.
References __n_assert, add_int_to_msg(), add_nstrdup_to_msg(), create_msg(), delete_msg(), and make_str_from_msg().
Referenced by netw_send_ident().
netmsg_make_ping()
N_STR * netmsg_make_ping (int type, int id_from, int id_to, int time)
#include <include/nilorea/n_network_msg.h>
Make a ping message to send to a network.
Parameters
type NETW_PING_REQUEST or NETW_PING_REPLY
id_from Identifiant of the sender
id_to Identifiant of the destination, -1 if the serveur itslef is targetted
time The time it was when the ping was sended
Returns
A N_STR *message or NULL
Definition at line 575 of file n_network_msg.c.
References __n_assert, add_int_to_msg(), create_msg(), delete_msg(), and make_str_from_msg().
Referenced by netw_send_ping().
netmsg_make_position_msg()
N_STR * netmsg_make_position_msg (int id, double X, double Y, double vx, double vy, double acc_x, double acc_y, int time_stamp)
#include <include/nilorea/n_network_msg.h>
make a network NETMSG_POSITION message with given parameters
Parameters
id The ID of the sending client
X x position
Y y position
vx x speed
vy y speed
acc_x x acceleration
acc_y y acceleration
time_stamp time when the position were copier
Returns
N_STR *netmsg or NULL
Definition at line 672 of file n_network_msg.c.
References __n_assert, add_int_to_msg(), add_nb_to_msg(), create_msg(), delete_msg(), make_str_from_msg(), and NETMSG_POSITION.
Referenced by netw_send_position().
netmsg_make_quit_msg()
N_STR * netmsg_make_quit_msg (void)
#include <include/nilorea/n_network_msg.h>
make a generic network NETMSG_QUIT message
Returns
N_STR *netmsg or NULL
Definition at line 744 of file n_network_msg.c.
References __n_assert, add_int_to_msg(), create_msg(), delete_msg(), make_str_from_msg(), and NETMSG_QUIT.
Referenced by netw_send_quit().
netmsg_make_string_msg()
N_STR * netmsg_make_string_msg (int id_from, int id_to, N_STR * name, N_STR * chan, N_STR * txt, int color)
#include <include/nilorea/n_network_msg.h>
make a network NETMSG_STRING message with given parameters
Parameters
id_from The ID of the sending client
id_to id of the destination
name name of the user
chan targeted channel
txt text to send
color color of the text
Returns
N_STR *netmsg or NULL
Definition at line 710 of file n_network_msg.c.
References __n_assert, add_int_to_msg(), add_nstrdup_to_msg(), create_msg(), delete_msg(), make_str_from_msg(), NETMSG_STRING, and nstrdup().
Referenced by netw_send_string_to(), and netw_send_string_to_all().
netw_get_ident()
int netw_get_ident (N_STR * msg, int * type, int * ident, N_STR ** name, N_STR ** passwd)
#include <include/nilorea/n_network_msg.h>
Retrieves identification from netwmsg.
Parameters
msg The source string from which we are going to extract the data
type NETMSG_IDENT_NEW , NETMSG_IDENT_REPLY_OK , NETMSG_IDENT_REPLY_NOK , NETMSG_IDENT_REQUEST
ident ID for the user
name Name of the user
passwd Password of the user
Returns
TRUE or FALSE
Definition at line 796 of file n_network_msg.c.
References __n_assert, delete_msg(), get_int_from_msg(), get_nstr_from_msg(), LOG_ERR, make_msg_from_str(), n_log, NETMSG_IDENT_REPLY_NOK, NETMSG_IDENT_REPLY_OK, and NETMSG_IDENT_REQUEST.
netw_get_ping()
int netw_get_ping (N_STR * msg, int * type, int * from, int * to, int * time)
#include <include/nilorea/n_network_msg.h>
Retrieves a ping travel elapsed time.
Parameters
msg The source string from which we are going to extract the data
type NETW_PING_REQUEST or NETW_PING_REPLY
from Identifiant of the sender
to Targetted Identifiant, -1 for server ping
time The time it was when the ping was sended
Returns
TRUE or FALSE
Definition at line 930 of file n_network_msg.c.
References __n_assert, delete_msg(), get_int_from_msg(), make_msg_from_str(), NETMSG_PING_REPLY, and NETMSG_PING_REQUEST.
netw_get_position()
int netw_get_position (N_STR * msg, int * id, double * X, double * Y, double * vx, double * vy, double * acc_x, double * acc_y, int * time_stamp)
#include <include/nilorea/n_network_msg.h>
Retrieves position from netwmsg.
Parameters
msg The source string from which we are going to extract the data
id
X X position inside a big grid
Y Y position inside a big grid
vx X speed
vy Y speed
acc_x X acceleration
acc_y Y acceleration
time_stamp Current Time when it was sended (for some delta we would want to compute)
Returns
TRUE or FALSE
Definition at line 839 of file n_network_msg.c.
References __n_assert, delete_msg(), get_int_from_msg(), get_nb_from_msg(), make_msg_from_str(), and NETMSG_POSITION.
netw_get_quit()
int netw_get_quit (N_STR * msg)
#include <include/nilorea/n_network_msg.h>
get a formatted NETWMSG_QUIT message from the specified network
Parameters
msg The source string from which we are going to extract the data
Returns
TRUE or FALSE
Definition at line 965 of file n_network_msg.c.
References __n_assert, delete_msg(), get_int_from_msg(), make_msg_from_str(), and NETMSG_QUIT.
netw_get_string()
int netw_get_string (N_STR * msg, int * id, N_STR ** name, N_STR ** chan, N_STR ** txt, int * color)
#include <include/nilorea/n_network_msg.h>
Retrieves string from netwmsg.
Parameters
msg The source string from which we are going to extract the data
id The ID of the sending client
name Name of user
chan Target Channel, if any. Pass "ALL" to target the default channel
txt The text to send
color The color of the text
Returns
TRUE or FALSE
Definition at line 886 of file n_network_msg.c.
References __n_assert, delete_msg(), get_int_from_msg(), get_nstr_from_msg(), make_msg_from_str(), and NETMSG_STRING.
netw_msg_get_type()
int netw_msg_get_type (N_STR * msg)
#include <include/nilorea/n_network_msg.h>
Get the type of message without killing the first number. Use with netw_get_XXX.
Parameters
msg A char *msg_object you want to have type
Returns
The value corresponding to the type or FALSE
Definition at line 767 of file n_network_msg.c.
References __n_assert.
Referenced by manage_client().
ntohd()
double ntohd (double value)
#include <include/nilorea/n_network_msg.h>
If needed swap bytes for a double.
Parameters
value The value to eventually swap
Returns
The modified value
Definition at line 61 of file n_network_msg.c.
References double_swap().
Referenced by make_msg_from_str().