Nilorea Library: MEMORY DEBUG: leaked memory checker core files
MEMORY DEBUG: leaked memory checker core files
Classes
struct DEBUG_MEM_ITEM
structure of a debug unit
struct DEBUG_MEM_TABLE
structure of a table of DEBUG_MEM_ITEM
Macros
#define DEBUG_MEM_DUMP_MAX_LEN 256
max memory dumped by leaked unit
Functions
void * db_mem_alloc (size_t size, int line, char *file, const char *func)
allocate a new pointer with size and also put it in the debug table
int db_mem_dump_leaked (char *file)
Dump the current debug memory table.
void db_mem_free (void *ptr, int line, char *file, const char *func)
void delete_db_mem_item (void *ptr)
delete a debug mem item
int init_debug_mem ()
initialize debug tables
DEBUG_MEM_ITEM * new_db_mem_item (void *ptr, size_t size, int line, char *file, char *func)
allocate a new item in the debug table
Variables
DEBUG_MEM_TABLE * debug_mem_table
external table for tracking by file usage
Detailed Description
Macro Definition Documentation
DEBUG_MEM_DUMP_MAX_LEN
#define DEBUG_MEM_DUMP_MAX_LEN 256
#include <n_debug_mem.h>
max memory dumped by leaked unit
Definition at line 26 of file n_debug_mem.h.
Function Documentation
db_mem_alloc()
void * db_mem_alloc (size_t size, int line, char * file, const char * func)
#include <n_debug_mem.h>
allocate a new pointer with size and also put it in the debug table
Parameters
size the size of the allocated data
line line of the allocation
file file of the allocation
func function where the allocation was made
Returns
A new item or NULL
Definition at line 101 of file n_debug_mem.c.
References __debug_mem_table, _n_log(), delete_db_mem_item(), DEBUG_MEM_ITEM::file, DEBUG_MEM_ITEM::func, ht_put_ptr(), DEBUG_MEM_ITEM::line, DEBUG_MEM_TABLE::nb_malloc, DEBUG_MEM_ITEM::ptr, DEBUG_MEM_ITEM::size, and DEBUG_MEM_TABLE::table.
db_mem_dump_leaked()
int db_mem_dump_leaked (char * file)
#include <n_debug_mem.h>
Dump the current debug memory table.
Parameters
file The name of the logfile
Returns
TRUE or FALSE
Definition at line 159 of file n_debug_mem.c.
References __debug_mem_table, _n_log(), HASH_NODE::data, delete_db_mem_item(), HASH_TABLE::hash_table, LIST_NODE::next, HASH_VALUE::ptr, LIST_NODE::ptr, DEBUG_MEM_ITEM::size, HASH_TABLE::size, LIST::start, and DEBUG_MEM_TABLE::table.
db_mem_free()
void db_mem_free (void * ptr, int line, char * file, const char * func)
#include <n_debug_mem.h>
Definition at line 133 of file n_debug_mem.c.
References __debug_mem_table, _n_log(), delete_db_mem_item(), DEBUG_MEM_ITEM::file, DEBUG_MEM_ITEM::func, ht_get_ptr(), ht_remove(), DEBUG_MEM_ITEM::line, DEBUG_MEM_TABLE::nb_free, DEBUG_MEM_ITEM::ptr, DEBUG_MEM_ITEM::size, and DEBUG_MEM_TABLE::table.
delete_db_mem_item()
void delete_db_mem_item (void * ptr)
#include <n_debug_mem.h>
delete a debug mem item
Parameters
ptr the item to destroy
Definition at line 80 of file n_debug_mem.c.
Referenced by db_mem_alloc(), db_mem_dump_leaked(), and db_mem_free().
init_debug_mem()
int init_debug_mem ()
#include <n_debug_mem.h>
initialize debug tables
Returns
TRUE or FALSE
Definition at line 22 of file n_debug_mem.c.
References __debug_mem_table, DEBUG_MEM_TABLE::nb_free, DEBUG_MEM_TABLE::nb_malloc, new_ht(), and DEBUG_MEM_TABLE::table.
new_db_mem_item()
DEBUG_MEM_ITEM * new_db_mem_item (void * ptr, size_t size, int line, char * file, char * func)
#include <n_debug_mem.h>
allocate a new item in the debug table
Parameters
ptr Pointer address to save
size the size of the allocated data
line line of the allocation
file file of the allocation
func function where the allocation was made
Returns
A new item or NULL
Definition at line 55 of file n_debug_mem.c.
References DEBUG_MEM_ITEM::file, DEBUG_MEM_ITEM::func, DEBUG_MEM_ITEM::line, DEBUG_MEM_ITEM::ptr, and DEBUG_MEM_ITEM::size.
Variable Documentation
debug_mem_table
DEBUG_MEM_TABLE* debug_mem_table extern
#include <n_debug_mem.h>
external table for tracking by file usage