Nilorea Library: n_debug_locks.c File Reference
n_debug_locks.c File Reference
Helpers for debugging thread locks, on an idea of Aurelian Melinte (see https://linuxgazette.net/150/melinte.html)
#include "nilorea/n_debug_mem.h"
#include "nilorea/n_common.h"
#include "nilorea/n_log.h"
#include "nilorea/n_hash.h"
Data Structures
struct N_MUTEX_INFO
Debuglock mutexes informations.
struct N_PTHREAD_INFO
Debuglock thread informations.
Macros
#define N_DEBUGLOCK_INVALID_IDX (-1)
#define N_DEBUGLOCK_INVALID_MUTEX ((pthread_mutex_t*)0)
#define N_DEBUGLOCK_INVALID_THREAD ((pthread_t)0)
Typedefs
typedef struct N_MUTEX_INFO N_MUTEX_INFO
Debuglock mutexes informations.
typedef struct N_PTHREAD_INFO N_PTHREAD_INFO
Debuglock thread informations.
Functions
void lp_lock_precheck_diagnose (const pthread_mutex_t *mutex)
void lp_unlock_precheck_diagnose (const pthread_mutex_t *mutex)
int n_pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr)
int n_pthread_mutex_lock (pthread_mutex_t *mutex)
int n_pthread_mutex_trylock (pthread_mutex_t *mutex)
int n_pthread_mutex_unlock (pthread_mutex_t *mutex)
int n_pthread_rwlock_rdlock (pthread_rwlock_t *rwlock)
int n_pthread_rwlock_tryrdlock (pthread_rwlock_t *rwlock)
int n_pthread_rwlock_wrlock (pthread_rwlock_t *wrlock)
int pthread_mutex_destroy (pthread_mutex_t *mutex)
int pthread_mutex_lock (pthread_mutex_t *mutex)
int pthread_mutex_trylock (pthread_mutex_t *mutex)
int pthread_rwlock_trywrlock (pthread_rwlock_t *wrlock)
Variables
static int DEBUG_LOCKS = 0
static int DEBUG_LOCKS_INITIALIZED = 0
pthread_mutex_t debuglock_lock
LIST * n_mutex_list = NULL
LIST * n_thread_list = NULL
Detailed Description
Helpers for debugging thread locks, on an idea of Aurelian Melinte (see https://linuxgazette.net/150/melinte.html)
Author
Castagnier Mickael
Date
2014-10-10
Definition in file n_debug_locks.c.
Macro Definition Documentation
N_DEBUGLOCK_INVALID_IDX
#define N_DEBUGLOCK_INVALID_IDX (-1)
Definition at line 12 of file n_debug_locks.c.
N_DEBUGLOCK_INVALID_MUTEX
#define N_DEBUGLOCK_INVALID_MUTEX ((pthread_mutex_t*)0)
Definition at line 14 of file n_debug_locks.c.
N_DEBUGLOCK_INVALID_THREAD
#define N_DEBUGLOCK_INVALID_THREAD ((pthread_t)0)
Definition at line 13 of file n_debug_locks.c.
Typedef Documentation
N_MUTEX_INFO
typedef struct N_MUTEX_INFO N_MUTEX_INFO
Debuglock mutexes informations.
N_PTHREAD_INFO
typedef struct N_PTHREAD_INFO N_PTHREAD_INFO
Debuglock thread informations.
Function Documentation
lp_lock_precheck_diagnose()
void lp_lock_precheck_diagnose (const pthread_mutex_t * mutex)
Definition at line 110 of file n_debug_locks.c.
lp_unlock_precheck_diagnose()
void lp_unlock_precheck_diagnose (const pthread_mutex_t * mutex)
Definition at line 160 of file n_debug_locks.c.
n_pthread_mutex_init()
int n_pthread_mutex_init (pthread_mutex_t * mutex, const pthread_mutexattr_t * mutexattr)
Definition at line 55 of file n_debug_locks.c.
n_pthread_mutex_lock()
int n_pthread_mutex_lock (pthread_mutex_t * mutex)
Definition at line 61 of file n_debug_locks.c.
References pthread_mutex_lock().
n_pthread_mutex_trylock()
int n_pthread_mutex_trylock (pthread_mutex_t * mutex)
Definition at line 66 of file n_debug_locks.c.
References pthread_mutex_trylock().
n_pthread_mutex_unlock()
int n_pthread_mutex_unlock (pthread_mutex_t * mutex)
n_pthread_rwlock_rdlock()
int n_pthread_rwlock_rdlock (pthread_rwlock_t * rwlock)
n_pthread_rwlock_tryrdlock()
int n_pthread_rwlock_tryrdlock (pthread_rwlock_t * rwlock)
Definition at line 80 of file n_debug_locks.c.
n_pthread_rwlock_wrlock()
int n_pthread_rwlock_wrlock (pthread_rwlock_t * wrlock)
Definition at line 85 of file n_debug_locks.c.
pthread_mutex_destroy()
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Definition at line 95 of file n_debug_locks.c.
References pthread_mutex_destroy().
Referenced by close_safe_logging(), destroy_threaded_pool(), netw_close(), netw_new(), and pthread_mutex_destroy().
pthread_mutex_lock()
int pthread_mutex_lock (pthread_mutex_t * mutex)
Definition at line 185 of file n_debug_locks.c.
Referenced by add_threaded_process(), close_safe_logging(), destroy_threaded_pool(), n_pthread_mutex_lock(), netw_add_msg(), netw_add_msg_ex(), netw_get_msg(), netw_get_queue_status(), netw_get_state(), netw_recv_func(), netw_send_func(), netw_set(), netw_start_thr_engine(), netw_wait_close_timed(), refresh_thread_pool(), start_threaded_pool(), thread_pool_processing_function(), wait_for_threaded_pool(), and write_safe_log().
pthread_mutex_trylock()
int pthread_mutex_trylock (pthread_mutex_t * mutex)
Definition at line 206 of file n_debug_locks.c.
Referenced by n_pthread_mutex_trylock().
pthread_rwlock_trywrlock()
int pthread_rwlock_trywrlock (pthread_rwlock_t * wrlock)
Definition at line 90 of file n_debug_locks.c.
References pthread_rwlock_trywrlock().
Referenced by pthread_rwlock_trywrlock().
Variable Documentation
DEBUG_LOCKS
int DEBUG_LOCKS = 0 static
:flag for enabling or disabling debugging on locks
Definition at line 17 of file n_debug_locks.c.
DEBUG_LOCKS_INITIALIZED
int DEBUG_LOCKS_INITIALIZED = 0 static
:flag for to check initialisation status
Definition at line 19 of file n_debug_locks.c.
debuglock_lock
pthread_mutex_t debuglock_lock
: mutex to lock debuglock infos
Definition at line 21 of file n_debug_locks.c.
n_mutex_list
LIST* n_mutex_list = NULL
Definition at line 53 of file n_debug_locks.c.
n_thread_list
LIST* n_thread_list = NULL
Definition at line 52 of file n_debug_locks.c.