Nilorea Library: HASH_TABLE Struct Reference
HASH_TABLE Struct Reference
HASH TABLE: classic or trie tree hash_tables
#include "n_hash.h"
Data Fields
unsigned int alphabet_length
unsigned int alphabet_offset
int(* destroy_ht)(struct HASH_TABLE **table)
int(* empty_ht)(struct HASH_TABLE *table)
LIST ** hash_table
int(* ht_get_double)(struct HASH_TABLE *table, char *key, double *val)
int(* ht_get_int)(struct HASH_TABLE *table, char *key, int *val)
HASH_NODE *(* ht_get_node)(struct HASH_TABLE *table, char *key)
int(* ht_get_ptr)(struct HASH_TABLE *table, char *key, void **val)
int(* ht_get_string)(struct HASH_TABLE *table, char *key, char **val)
void(* ht_print)(struct HASH_TABLE *table)
int(* ht_put_double)(struct HASH_TABLE *table, char *key, double val)
int(* ht_put_int)(struct HASH_TABLE *table, char *key, int val)
int(* ht_put_ptr)(struct HASH_TABLE *table, char *key, void *ptr, void(*destructor)(void *ptr))
int(* ht_put_string)(struct HASH_TABLE *table, char *key, char *val)
int(* ht_put_string_ptr)(struct HASH_TABLE *table, char *key, char *val)
int(* ht_remove)(struct HASH_TABLE *table, char *key)
LIST *(* ht_search)(struct HASH_TABLE *table, int(*node_is_matching)(HASH_NODE *node))
unsigned int mode
unsigned long int nb_keys
HASH_NODE * root
uint32_t seed
unsigned long int size
Detailed Description
Examples
ex_gui_netclient.c, and ex_hash.c.
Definition at line 108 of file n_hash.h.
Field Documentation
alphabet_length
unsigned int HASH_TABLE::alphabet_length
HASH_TRIE mode: size of the alphabet.
Definition at line 121 of file n_hash.h.
alphabet_offset
unsigned int HASH_TABLE::alphabet_offset
HASH_TRIE mode: offset to deduce to individual key digits.
Definition at line 123 of file n_hash.h.
destroy_ht
int(* HASH_TABLE::destroy_ht) (struct HASH_TABLE **table)
destroy a hash table
Definition at line 153 of file n_hash.h.
empty_ht
int(* HASH_TABLE::empty_ht) (struct HASH_TABLE *table)
empty a hash table.
char *strings are also freed
Definition at line 151 of file n_hash.h.
hash_table
LIST** HASH_TABLE::hash_table
HASH_CLASSIC mode: preallocated hash table.
Definition at line 117 of file n_hash.h.
ht_get_double
int(* HASH_TABLE::ht_get_double) (struct HASH_TABLE *table, char *key, double *val)
get a double from a key's node
Definition at line 141 of file n_hash.h.
Referenced by ht_get_double().
ht_get_int
int(* HASH_TABLE::ht_get_int) (struct HASH_TABLE *table, char *key, int *val)
get an int from a key's node
Definition at line 139 of file n_hash.h.
Referenced by ht_get_int().
ht_get_node
HASH_NODE *(* HASH_TABLE::ht_get_node) (struct HASH_TABLE *table, char *key)
get HASH_NODE at 'key' from table
Definition at line 127 of file n_hash.h.
Referenced by ht_get_node().
ht_get_ptr
int(* HASH_TABLE::ht_get_ptr) (struct HASH_TABLE *table, char *key, void **val)
get a pointer from a key's node
Definition at line 143 of file n_hash.h.
ht_get_string
int(* HASH_TABLE::ht_get_string) (struct HASH_TABLE *table, char *key, char **val)
get a char *string from a key's node
Definition at line 145 of file n_hash.h.
Referenced by ht_get_string().
ht_print
void(* HASH_TABLE::ht_print) (struct HASH_TABLE *table)
print table
Definition at line 155 of file n_hash.h.
Referenced by ht_print().
ht_put_double
int(* HASH_TABLE::ht_put_double) (struct HASH_TABLE *table, char *key, double val)
put a double
Definition at line 131 of file n_hash.h.
Referenced by ht_put_double().
ht_put_int
int(* HASH_TABLE::ht_put_int) (struct HASH_TABLE *table, char *key, int val)
put an integer
Definition at line 129 of file n_hash.h.
Referenced by ht_put_int().
ht_put_ptr
int(* HASH_TABLE::ht_put_ptr) (struct HASH_TABLE *table, char *key, void *ptr, void(*destructor)(void *ptr))
put a a pointer
Definition at line 133 of file n_hash.h.
Referenced by ht_put_ptr().
ht_put_string
int(* HASH_TABLE::ht_put_string) (struct HASH_TABLE *table, char *key, char *val)
put an char *string
Definition at line 135 of file n_hash.h.
Referenced by ht_put_string().
ht_put_string_ptr
int(* HASH_TABLE::ht_put_string_ptr) (struct HASH_TABLE *table, char *key, char *val)
put an char *string pointer
Definition at line 137 of file n_hash.h.
Referenced by ht_put_string_ptr().
ht_remove
int(* HASH_TABLE::ht_remove) (struct HASH_TABLE *table, char *key)
remove given's key node from the table
Definition at line 147 of file n_hash.h.
Referenced by ht_remove().
ht_search
LIST *(* HASH_TABLE::ht_search) (struct HASH_TABLE *table, int(*node_is_matching)(HASH_NODE *node))
search elements given an expression
Definition at line 149 of file n_hash.h.
mode
unsigned int HASH_TABLE::mode
hashing mode, murmurhash and classic HASH_MURMUR, or HASH_TRIE
Definition at line 125 of file n_hash.h.
nb_keys
unsigned long int HASH_TABLE::nb_keys
total number of used keys in the table
Definition at line 113 of file n_hash.h.
root
HASH_NODE* HASH_TABLE::root
HASH_TRIE mode: Start of tree.
Definition at line 119 of file n_hash.h.
seed
uint32_t HASH_TABLE::seed
table's seed
Definition at line 115 of file n_hash.h.
size
unsigned long int HASH_TABLE::size
size of the hash table
Definition at line 111 of file n_hash.h.
Referenced by _ht_get_node(), and _ht_remove().
The documentation for this struct was generated from the following file:
include/nilorea/n_hash.h